### ISSUE TITLE
Vídeo de abertura

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#10]

**Comment by cmdiasbr** [comment]
https://user-images.githubusercontent.com/45003095/128784814-5b96a745-dd6e-4f5f-91b6-557c45a509e6.mp4

**Comment by cmdiasbr** [comment]
Link no Drive https://drive.google.com/file/d/1jSI6qedbeL3tosmnbAYTXp7ESL2ZWqaC/view?usp=sharing

**Comment by cmdiasbr** [comment]
update do video (aumentado a logo no final): 
https://drive.google.com/file/d/1eRylThE5x2LiThJSLLaEHQ7WjUGspqZ5/view?usp=sharing


https://user-images.githubusercontent.com/45003095/129998647-64e76e77-551c-4be4-ad38-860ea973460d.mp4

**Comment by alynnefs** [comment]
Podemos marcar como concluído?
