### ISSUE TITLE
Hosts para as palestras

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#11]
Precismos convidar pessoas para apresentar e interagir com palestrantes e keynotes

**Comment by cecivieira** [comment]
https://docs.google.com/spreadsheets/d/1tVzdZsIb8vB5tqE_JMcwIIMfvlwqswhnkPA-FSfRMNI/edit#gid=0

Planilha com anfitriãs e infraestrutura
