### ISSUE TITLE
Nos siga nas redes sociais

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#112]
### Campanha
Lançamento do evento
  
### Peça/publicidade solicitada
- Cartão para twitter pedindo para seguir no instagram
- Cartão para Instagram pedindo para seguir no twitter
- Cartão genérico "nos siga nas nossas redes sociais" para divulgar nos grupos de telegram e discord

### Detalhamento do uso
Essa postagem tem o objetivo que trazer a audiência do Twitter para o Instagram, além de incentivar inscrição de pessoas que ainda não nos seguem.

### Data prevista para uso da arte
06 jul. 2021

### Quais informações devem aparecer na arte
- Cartão para twitter pedindo para seguir no instagram: **logo da Instagram**
- Cartão para Instagram pedindo para seguir no twitter: **logo da twitter**
- Cartão genérico "nos siga nas nossas redes sociais" para divulgar nos grupos de telegram e discord: **logos da twitter e instagram**

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
https://www.canva.com/design/DAEjXjv6y9E/share/preview?token=WyBhi2rVa41qP8rqI4T76g&role=EDITOR&utm_content=DAEjXjv6y9E&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by anadulce** [comment]
A #PyBR2021 está chegando!
Te esperamos de 11 a 17 de outubro no maior evento da América Latina <3
Nos siga nas redes sociais para mais informações: link

**Comment by deboraazevedo** [comment]
Sugestão de texto

VEM AÍ!

Nos dias 11 a 17 de Outubro estaremos juntos no maior e mais pythônico evento da América Latina.

Não quer perder nenhuma novidade? Siga-nos nas redes sociais!

**Comment by deboraazevedo** [comment]
Link do post na Instagram: https://www.instagram.com/p/CQ_W_N-nxAz/
Liink do post na Twitter: https://twitter.com/pythonbrasil/status/1412426303580606470

No Telegram e no Discord também foi postado, mas não consigo puxar um link dessas publicações.
