### ISSUE TITLE
Divulgação da data

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#114]
### Campanha
Lançamento do evento
  
### Peça/publicidade solicitada
- Cartão para divulgação da data do evento

### Detalhamento do uso
A arte será usada para divulgar amplamente a data que ocorrerá o evento. Ela deverá ser traduzida paea espanhol, então, por favor, compartilha o link editável.

### Data prevista para uso da arte
09 jul. 2021

### Quais informações devem aparecer na arte
Data do evento: 11 a 17 out. 2021

### Quais formatos necessários
- [x] Quadrado
- [x] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
![divulgacao](https://user-images.githubusercontent.com/45003095/125214919-fa271c80-e28f-11eb-9ffa-8cf1bc44d17a.png)

**Comment by cecivieira** [comment]
@martinsvanessa Ficou massa!!! Obrigada!! Deixa a issue aberta, por favor, pra @deboraazevedo programar a publicação e registrar o link do post aqui também

**Comment by deboraazevedo** [comment]
Já posso programar essa postagem?

Pensei num texto tipo assim:

Depois de um fim de semana incrível com a @pythonnordeste online, mandamos o lembrete: de 11 a 17 de outubro, teremos também a Python Brasil online!

Não perde tempo e já marca essa data na sua agenda! Nos vemos em Outubro, cada um de sua casa :))))

**Comment by cecivieira** [comment]
Sim

**Comment by deboraazevedo** [comment]
postagem agendada para hoje 7pm

**Comment by deboraazevedo** [comment]
https://twitter.com/pythonbrasil/status/1417242899197186050
https://www.instagram.com/p/CRhn5aaDNL7/
