### ISSUE TITLE
Novidade: Trilha em espanhol

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#115]
### Campanha
Lançamento do evento
  
### Peça/publicidade solicitada
- Cartão para divulgação da trilha em espanhol

### Detalhamento do uso
Divulgar que esse ano teremos pela primeira vez uma trilha em espanhol com foco na divulgação de trabalhos de pessoas moradoras nos demais países da América Latina.
Essa arte será traduzida para espanhol, por favor, compartilha o link da arte editável.

### Data prevista para uso da arte
13 jul. 2021

### Quais informações devem aparecer na arte
Sugestão/Pitaco: "novidade: trilha em espanhol - América Latina"

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

**Comment by cecivieira** [comment]
@cmdiasbr ficou linda!!!!
Alynne vai comprar hoje o pacote de imagens, então a gente poderia substituir metade das imagens masculinas por mulheres?

**Comment by deboraazevedo** [comment]
afffff ta lindo mesmooooooo

**Comment by cmdiasbr** [comment]
**Postado**

**Comment by martinsvanessa** [comment]
![Cards (1)](https://user-images.githubusercontent.com/18190437/125213727-e8db1180-e289-11eb-8b37-50d96e8950dd.png)

**Comment by cecivieira** [comment]
pt-br

https://www.instagram.com/p/CRG9-eMr5TK/
https://twitter.com/pythonbrasil/status/1413497202983456770

Post em espanhol agendado para 13 jun às 11h55
