### ISSUE TITLE
Padrão para newsletter

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#117]
### Campanha
Não definida
  
### Peça/publicidade solicitada
Artes para estrutura da newsletter

### Detalhamento do uso
As imagens serão usadas para na estrutura da newsletter quinzenal

### Data prevista para uso da arte
início 15 jun. 2021

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [x] Outro: header (1200x500px)
- [x] Outro: footer (1200x162px)
- [ ] Sugestão de fonte + cor de fonte + cor para substituir as partes em vinho (ver imagem abaixo)

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

Vamos usar esse template no MailChimp. Nas imagens das notícias usaremos os cartões das redes sociais.
![image](https://user-images.githubusercontent.com/30605862/124198581-55def200-daa7-11eb-99a2-ad3b1e5b90b3.png)

**Comment by cmdiasbr** [comment]
O que é para escrever no banner do header e do footer? @cecivieira

**Comment by cecivieira** [comment]
O que tu quiser, não temos preferência

**Comment by cmdiasbr** [comment]
@martinsvanessa

**Comment by paulohenriquedsgn** [comment]
@cecivieira @martinsvanessa @deboraazevedo @cmdiasbr meninas ainda é interessante manter a proposta da newsletter?

**Comment by cecivieira** [comment]
@paulohenriquedsgn Não sei. Temos 73 inscritos na newsletter (achei pouco)
Comunicação acha que vale a pena dedicar energia para mais esse veículo de comunicação?

**Comment by cecivieira** [comment]
Atividade descontinuada
