### ISSUE TITLE
Assine nossa newsletter

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#118]
### Campanha
Lançamento do evento
  
### Peça/publicidade solicitada
Cartão para redes sociais

### Detalhamento do uso
Incentivar que as pessoas assine a newsletter do evento.

### Data prevista para uso da arte
11 jun. 2021

### Quais informações devem aparecer na arte
Sugestão: "Assine nossa newsletter"

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
Link para adicionar na legenda:
http://eepurl.com/hCzL0L

**Comment by cmdiasbr** [comment]
![Inscrição para newsletter](https://user-images.githubusercontent.com/45003095/124386471-fe13d700-dcb0-11eb-8ccf-79f83e220382.png)

Eu só alinhei a logo da pybr da imagem que estava no Canva

**Comment by cecivieira** [comment]
@cmdiasbr obrigada! vou atualizar o cabeçalho.

Peguei os mesmos elementos e fiz um card pras redes sociais. Vê se tá de boa

https://www.canva.com/design/DAEjPWNunB0/share/preview?token=iHxtxgtxfLnVmOwj8hToDg&role=EDITOR&utm_content=DAEjPWNunB0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by cmdiasbr** [comment]
Atualizei no Canva
![assine_newsletter_instagram](https://user-images.githubusercontent.com/45003095/124520782-dd887180-ddc3-11eb-8c3d-5e32a2bc386b.png)

**Comment by anadulce** [comment]
Você quer saber sobre as novidades e atividades da Python Brasil 2021?
Nós podemos te mandar as notícias em primeira mão :) Só colocar seu e-mail nesse forms:

PS: não se preocupe, não vamos compartilhar seu e-mail com ninguém.
