### ISSUE TITLE
Definir como os certificados serão gerados

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#119]
### Descrição
Precisamos de um processo automatizado para geração dos certificados de participação no evento. A ferramenta de inscrição que usamos em 2020, EventBrite, parou de oferecer essa funcionalidade.

Seria interessante que os próprios participantes pudessem gerar seus próprios certificados e que a ferramenta fosse facilmente adaptada para outros eventos da comunidade. Dessa forma, diminuiríamos o trabalho da organização.

### Requisitos para a atividade ser considerada como concluída
- Processo, ferramentas, fluxos relacionados a geração de certificado de participação definidos
- Lista de tarefas associadas criadas no Github.

**Comment by JacksonOsvaldo** [comment]
Opa, @rougeth. Tudo certo? Meu caro, o ideal seria desenvolvermos algo do zero ou podemos utilizar uma solução Open Source? Encontrei algo bem interessante aqui no GitHub e acho que podemos utilizar: https://github.com/vinigracindo/sgce

**Comment by GabrielRF** [comment]
@JacksonOsvaldo Penso que criar do zero ou usar algo open seja indiferente.
Eu ia tocar essa issue por já ter o código pronto, que uso em uma outra solução. Tava esperando mesmo a arte do certificado para dar continuidade a issue.
Fique a vontade para colaborar da forma que achar melhor!

**Comment by JacksonOsvaldo** [comment]
Opa, @GabrielRF. Tudo certo? Obrigado pelo retorno. E, oh, posso te ajudar com o que você já tem, então? Se existir algo que eu possa fazer, só mandar que estou à disposição.

Sobre a questão de começar do zero ou open, é só porque não queria reinventar a roda, sabe? Mas, ainda tô me acostumando com a metodologia de trabalho por aqui.

Novamente, estou a disposição.

**Comment by cecivieira** [comment]
@GabrielRF pelo que entendi tu já concluiu essa atividade, correto?
Se sim, posta aqui o link para o repositório e fecha a issue, por favor.

**Comment by GabrielRF** [comment]
@cecivieira Pensei em forkar o repositório da arte dos palestrantes. 
A arte já está pronta? Se estiver, posso concluir isso em poucos dias :)

**Comment by alynnefs** [comment]
@GabrielRF acho que se tiver a arte pronta ela tá no drive e em alguma issue
