### ISSUE TITLE
Orçar pacote de imagens 3D

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#120]
### Descrição
Orçar pacote de imagens 3D que tenha figuras que represente melhor a diversidade de gênero, cor, corpos, pessoas com necessidades especiais, etc.

### Requisitos para a atividade ser considerada como concluída
- Buscar pacote de imagens;
- Escolher qual será adquirido;
- Inserir preço e contatos na lista de fornecedores (https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing)

**Comment by cmdiasbr** [comment]
https://ui8.net/rakata/products/worked-3d-illustrations

https://ui8.net/blendit/products/outer-space-character-3d

Recomendo esse site (ui8.net)

**Comment by deboraazevedo** [comment]
Fica aqui os meus 10 centavos desse repositório que encontrei.. essas 3d custam 49 dólares

https://www.blackillustrations.com/illustration-category/3d

**Comment by cecivieira** [comment]
@cmdiasbr Qual ou quais a gente deve comprar? 
Responde e fecha a issue, por favor. Vamos comprar o(s) que tu responder.

**Comment by cmdiasbr** [comment]
@cecivieira se for possível, eu prefiro uma votação dos demais para escolher qual pacote usar, por mim qualquer um desses estaria ótimo:

https://ui8.net/rakata/products/worked-3d-illustrations
https://ui8.net/blendit/products/outer-space-character-3d
https://superscene.pro/
https://3ddd.casa/?ref=landingfolio

No caso tem alguns que tem o pacote (objetos + chars). Os objetos não precisa, isso já temos vários packs gratuitos.

**Comment by alynnefs** [comment]
achei fofo o que a @deboraazevedo mandou, pq quase nunca os cachos tão bem desenhadinhos assim. Dá pra mudar cor quando compra ou vem só o png também?

**Comment by cmdiasbr** [comment]
> achei fofo o que a @deboraazevedo mandou, pq quase nunca os cachos tão bem desenhadinhos assim. Dá pra mudar cor quando compra ou vem só o png também?

os que tem a opção Figma e AI dá para mudar a cor.

**Comment by cecivieira** [comment]
@cmdiasbr postei a enquete no Discord. Vota la'também. Tenho um preferido hehehehehehehehe

**Comment by cecivieira** [comment]
O pacote mais votado foi https://superscene.pro/

@alynnefs tu poderia comprar e preencher nessa planilha (https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit#gid=0)?

**Comment by alynnefs** [comment]
@cecivieira e @cmdiasbr, salvem a noob: se não precisa de objeto, é pra comprar a opção "characters", de $48, certo?

**Comment by cecivieira** [comment]
Acho que sim porque dá para trocar de cor das bonecas e tem mais umas coisas, mas acho melhor esperar Camila responder

```
    240 hero components
    in three skin tones
    + special characters
    png, blender sources
    figma & sketch

```

**Comment by cmdiasbr** [comment]
> Acho que sim porque dá para trocar de cor das bonecas e tem mais umas coisas, mas acho melhor esperar Camila responder
> 
> ```
>     240 hero components
>     in three skin tones
>     + special characters
>     png, blender sources
>     figma & sketch
> ```

Sim, é esse de $48 @alynnefs @cecivieira

**Comment by alynnefs** [comment]
Imagens compradas \o/

ticket do comprovante: https://pythonbrasil.freshdesk.com/a/tickets/7018

pasta no drive: https://drive.google.com/drive/folders/1pUSEw-PmEvtfQa7S4kKk-xswwZVsqASc?usp=sharing
