### ISSUE TITLE
Parceria com Jooble

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#122]
### Descrição
Recebida proposta de parceria da Jooble (ver comentários)

### Requisitos para a atividade ser considerada como concluída

- Perguntar a empresa: alcance da página, média de conversão (cliques) no banner, se a visualização do banner é regional ou internacional;
- Comentar na issue informações dadas pela empresa;
- Decidir se vai firmar ou não a parceria.

**Comment by cecivieira** [comment]
@tiidadavena

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/124534694-2b64a000-ddeb-11eb-9d1a-fa4d9455be12.png)
![image](https://user-images.githubusercontent.com/30605862/124534758-48996e80-ddeb-11eb-8159-21b5ec9f5b31.png)

**Comment by tiidadavena** [comment]
A resposta da Jooble acerca dos questionamentos das taxas de acessos e de conversões:

"Não consigo dizer o volume de páginas no Jooble. Colocamos o banner em palavras-chave, portanto, fornecer um valor para todo o Jooble será uma história um tanto irrelevante.
Quanto às conversões, nada podemos garantir, pois tudo depende do tipo de serviço anunciado, do nicho e do próprio banner. Podemos garantir a quantidade de visualização. Além disso, os banners são uma forma de aumentar a fidelidade à marca e aumentar o conhecimento da mesma.
Sempre poderão escolher as palavras chaves relevantes para voces, e também poderemos propor um google banner em vez do banner rotativo."

**Comment by alynnefs** [comment]
Vocês acham válido fazer a parceria mesmo sem os dados?

**Comment by cecivieira** [comment]
Acho que não, pois sabemos que o impacto positivo para a empresa é alto, no entanto não temos dados para saber se o impacto será correspondente para nós.

**Comment by alynnefs** [comment]
Então seria bom agradecer a empresa e avisar, eles devem estar esperando resposta. @tiidadavena que tava em contato, né?

**Comment by cecivieira** [comment]
@tiidadavena quando tu responder, pode fechar a issue.

**Comment by tiidadavena** [comment]
Me perdi nas issues.

Isso, não passaram valores exatos.  Irei respondê-los baseados na falta de informações e no real impacto para o evento.
