### ISSUE TITLE
Assinar Hootsuite

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#123]
### Descrição
Efetivar assinatura do hootsuite (plataforma de gestão de mídia social)
Planilha orçamento: https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing

### Requisitos para a atividade ser considerada como concluída
- Assinar plataforma hootsuite

**Comment by deboraazevedo** [comment]
como fica essa issue? assinamos 30 dias premium de graça e depois teremos que assinar e pagar mesmo, né?

**Comment by cecivieira** [comment]
É sim, após 30 dias o valor será debitado. Quando isso acontecer, fecho-a e solicito reembolso.

**Comment by gabubellon** [comment]
@cecivieira  deu 30 dias ontem (08/08). Não esqueça de pedir o reembolso

**Comment by alynnefs** [comment]
> @cecivieira deu 30 dias ontem (08/08). Não esqueça de pedir o reembolso

vim aqui pra dizer isso 😋

**Comment by alynnefs** [comment]
Ressarcido
