### ISSUE TITLE
Patrocínio da LuizaLabs

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#124]
### Descrição
Issue para registro do patrocínio da LuizaLabs  - ticket #7003 no Freshdesk

Exemplo de como pode ser feito: #40

**Comment by tiidadavena** [comment]
O representante da Luizalabs (Renan) retornou pedindo para agendar uma reunião às 11h na sexta-feira (16/07). Para mim esse horário tá tranquilo, pois será feriado municipal em Recife. 

@apast @cecivieira pelo menos de um vocês poderia participar da reunião nesta data/horário?

**Comment by cecivieira** [comment]
@tiidadavena se não estou enganada, durante a reunião de segunda Pastore falou que poderia participar. Qualquer coisa me fala que a gente se ajeita.

**Comment by tiidadavena** [comment]
Sim, Ana, Pastore confirmou participação na reunião de amanhã às 11h.

Vou cobrar o link da reunião para Renan.

**Comment by tiidadavena** [comment]
Cássio Botaro - Luizalabs

Renan - Arquitetura de Software

Contrato do patrocínio ASAP - (foi enviado email solicitando os dados da empresa, ainda sem retorno, mas acredito que sejam os mesmos do patrocínio que rolou em 2015/16)

Reiteraram o interesse na cota Ouro e solicitaram a lista de assets necessários do time de Comunicação

**Comment by cecivieira** [comment]
@tiidadavena Não entendi a solicitação feita à equipe de Comunicação. Querem a lista de imagens que vai ser divulgada? Entendi não.

@deboraazevedo

**Comment by tiidadavena** [comment]
> @tiidadavena Não entendi a solicitação feita à equipe de Comunicação. Querem a lista de imagens que vai ser divulgada? Entendi não.
> 
> @deboraazevedo

Oi, Ana!

O que eles pediram seria uma espécie de checklist com os assets de que o time de Comunicação da PYBR vai precisar para montar as vinhetas, os posts...

**Comment by tiidadavena** [comment]
> @tiidadavena Não entendi a solicitação feita à equipe de Comunicação. Querem a lista de imagens que vai ser divulgada? Entendi não.
> 
> @deboraazevedo

Mas eles pediram para ter uma noção, vocês podem ver esses itens com calma. ;)

**Comment by cecivieira** [comment]
Ainda não entendi completamente a demanda. Qual dessas é a pergunta:

1 - Qual o plano de comunicação da PyBR?
ou
2 - Qual o material gráfico que a patrocinadora deverá enviar para a PyBR para sua divulgação?
ou
3 - Quais as divulgações da marca da patrocinadora  está comprometida na cota ouro?

**Comment by tiidadavena** [comment]
> Ainda não entendi completamente a demanda. Qual dessas é a pergunta:
> 
> 1 - Qual o plano de comunicação da PyBR?
> ou
> 2 - Qual o material gráfico que a patrocinadora deverá enviar para a PyBR para sua divulgação?
> ou
> 3 - Quais as divulgações da marca da patrocinadora está comprometida na cota ouro?

Seria a pergunta 2

**Comment by alynnefs** [comment]
@tiidadavena tem alguma coisa pendente aqui que eu possa ajudar?

**Comment by tiidadavena** [comment]
Update: pediram o modelo da minuta de contrato. Doc enviado para apreciação pela empresa.

**Comment by cecivieira** [comment]
@tiidadavena coloca aqui o link para a minuta do contrato da LuizaLabs

**Comment by tiidadavena** [comment]
> @tiidadavena coloca aqui o link para a minuta do contrato da LuizaLabs

O doc enviado foi no formato PDF. 

Segue link do doc editável: https://drive.google.com/file/d/1jyi98l66zt3UkEEqIymyC8kcJaUpbSnM/view?usp=sharing

**Comment by gabubellon** [comment]
#182

**Comment by tiidadavena** [comment]
Eles devem retomar sobre o contrato ainda hoje: "(...) estou aguardando uma aprovação que deve vir na próxima terça-feira (10/08)."

**Comment by tiidadavena** [comment]
Resposta sobre o email sobre o retorno do contrato: “Até agora, tudo certo e vamos providenciar as informações. Enquanto isso, você pode me tirar uma dúvida: No contrato e no material para o patrocínio, não são mencionadas entradas para os patrocinadores. Como funciona isso? Como patrocinadores, teremos acesso a ingressos para nossos colaboradores?”

**Comment by tiidadavena** [comment]
> Resposta sobre o email sobre o retorno do contrato: “Até agora, tudo certo e vamos providenciar as informações. Enquanto isso, você pode me tirar uma dúvida: No contrato e no material para o patrocínio, não são mencionadas entradas para os patrocinadores. Como funciona isso? Como patrocinadores, teremos acesso a ingressos para nossos colaboradores?”
@alynnefs

**Comment by cecivieira** [comment]
Acho que não é necessário criar nenhum tipo de ingresso para patrocinadoras. Apenas comunicar que é um evento gratuito.
Essa mesma pergunta foi feita pelo Mercado Livre e respondemos isso.

**Comment by tiidadavena** [comment]
No dia 12/08 enviamos email questionando se haviam dúvidas sobre o contrato e sobre o processo, no qual responderam que não haviam dúvidas, e na semana passada não recebemos nenhum retorno sobre o processo. 

Será enviado um email hoje (25/08) para questionar o andar da carruagem.

**Comment by tiidadavena** [comment]
Na segunda (30/08) enviaram o seguinte email:

"Me desculpe a demora, mas ainda temos pendências aqui do nosso lado. Qual é o nosso prazo para o envio do tema do tutorial?"

**Comment by tiidadavena** [comment]
Já foi enviado o email com a devolutiva com a data para 10/09.

**Comment by tiidadavena** [comment]
@gabubellon @alynnefs pensando em formas de pedir o status do andamento de forma não "abrasiva".

**Comment by tiidadavena** [comment]
Recebido email da Luizalabs com alterações na documentação. Na devolutiva a eles, foi enviado outro email com as alterações inclusas.

Nova versão:
[20210728 - Patrocinio APYB.docx.pdf](https://github.com/pythonbrasil/pybr2021-org/files/7117557/20210728.-.Patrocinio.APYB.docx.pdf)

**Comment by tiidadavena** [comment]
Recebemos o email do Jurídico da empresa pedindo os dados do representante legal e da testemunha e os respectivos emails para assinar a documentação.

Os dados enviados para resposta para eles (no caso, o nome completo e o email) foram os da representante legal (Alynne) e da testemunha (eu)

**Comment by alynnefs** [comment]
Contrato assinado, esperando a assinatura deles para gerar a nota fiscal

**Comment by tiidadavena** [comment]
Eles enviaram uma nova versão do contrato para assinatura, @alynnefs e eu já assinamos, aguardando as outras partes da Luizalabs para terminar o processo de assinatura
![image](https://user-images.githubusercontent.com/12106738/133092140-aa91ae93-1ef9-4404-83a5-7c468f00f06d.png)

**Comment by tiidadavena** [comment]
Documento do Patrocínio da APyB e Luizalabs assinado:

![image](https://user-images.githubusercontent.com/12106738/133283908-6e930613-7950-4352-b8ea-f435fbd2eb77.png)

**Comment by alynnefs** [comment]
Pedi informações para a nota fiscal e solicitei o preenchimento do formulário até sexta, 17/09

**Comment by tiidadavena** [comment]
Durante a emissão da NF, foi verificado que os dados fiscais da empresa divergiam aos do contrato. Foi enviado email questionando para qual CNPJ deveria ser finalizado o processo (Magalu ou Luizalabs?).

**Comment by alynnefs** [comment]
geração de nota fiscal solicitada

**Comment by cecivieira** [comment]
@tiidadavena @alynnefs a LuizaLabs enviou um vídeo de 3'20", então não é possível publicar no twitter, pois tem o limite de 2 minutos. Consegui agendar para as outras redes, mas no Twitter não é possível.

Seria interessante informar à patrocinadora para que saiba que essa contrapartida não será cumprida completamente porque ela não enviou o material conforme solicitado (vídeo de até 2 min)

**Comment by alynnefs** [comment]
@cecivieira não acha que vale pedir uma versão menor?

**Comment by cecivieira** [comment]
Acho que podemos tentar, mas o formulário está bem explícito

![Screenshot_2021-09-17-21-02-42-552_com.android.chrome.jpg](https://user-images.githubusercontent.com/30605862/133864873-93cf1d2d-65ab-41d6-9192-71853f45c230.jpg)

**Comment by alynnefs** [comment]
solicitei

**Comment by alynnefs** [comment]
[Nota fiscal](https://drive.google.com/file/d/1SRXgR-rsvKl7QgM_LcfA4cSUf_FwVLJO/view?usp=sharing) enviada, aguardando pagamento.

Resposta do Renan sobre o vídeo:
> Realmente eu não encontrei um video institucional com menos de 2 minutos. Eu vi que foi feita a comunicação no twitter e ficou muito bom. Nós queremos fazer uma comunicação nas nossas redes sociais também. Vocês tem uma página com os materiais e logotipos?


Já enviei as logos e as artes

**Comment by alynnefs** [comment]
Resposta da Rubia sobre o pagamento:

> O pagamento será efetuado no dia 08/10
