### ISSUE TITLE
Criar formulário para Confirmação de atividade

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#125]
### Descrição
Criar formulário para confirmar participação da proponente selecionada no evento. 

### Requisitos para a atividade ser considerada como concluída
- Concluir formulário ([link](https://docs.google.com/forms/d/16W4KHu6U_XSaFBg5jCJZoABc4qOkaGspWy0tnFOHaKA/edit?usp=sharing))
- Traduzir para espanhol

**Comment by cecivieira** [comment]
@belaaiza @anadulce a revisão desse formulário foi concluída?

**Comment by cecivieira** [comment]
@anadulce No corpo do e-mail que você vai enviar para as facilitadoras, informa qual a atividade que foi aprovada?
Imagino que uma mesma pessoa possa ter submetido várias palestras ou outras atividades.

**Comment by cecivieira** [comment]
Formulário revisado.
Link para ser enviado para facilitadoras de sprint, palestra, keynote e tutorial:
https://forms.gle/z8Qd2f6h6pitErBK6

**Comment by anadulce** [comment]
Olá, @cecivieira <3
No corpo do e-mail eu mando até o título da atividade aprovada, por motivos de tem pessoas com mais de uma submissão, então sim, pode ficar tranquila sobre isso, esse problema a gente resolve no texto do e-mail.
