### ISSUE TITLE
Incentivo a submissão de palestra - Principais temas

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#127]
### Campanha
Chamada para atividades
  
### Peça/publicidade solicitada
Cartão para redes sociais com sugestões de temas para palestra

### Detalhamento do uso
As peças serão usadas estimular a submissão de atividades e para dar ideia sobre temas que podem ser. Exemplos de temas recorrentes nos anos anteriores: educação, carreira, comunidade e técnico).
Por favor, compartilha o link editável, pois vamos traduzir essa peça.

### Data prevista para uso da arte
13 jul. 2021

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
Inspiração:

You don't have to teach. Tell us your Python-related story. How you discover it, secrets you've unravel, shortcuts you use, or even community you create! Because in PyCon APAC, we talk about everything under the moon. CFP is now open! Submit your talk at: https://www.papercall.io/pyconapac Looking forward to your story!

file:///home/cecivieira/Downloads/tell_us_your_story-twitter.png

**Comment by deboraazevedo** [comment]
Vamos fazer uma chamada geral que nem essa ou vamos fazer uma chamada para cada tema?

**Comment by cecivieira** [comment]
Acho que seria interessante fazer uma chamada mais geral, assim não limitaríamos aos temas que já estamos acostumadas.
Podemos escrever na legenda umas sugestões, mas não limitar ao ponto de fazer uma chamada pra cada tema específico.

**Comment by cmdiasbr** [comment]
![Cards](https://user-images.githubusercontent.com/45003095/125218147-b1279600-e298-11eb-909b-fdab4d835861.png)

**Comment by cecivieira** [comment]
@martinsvanessa Ficou massa!!! Obrigada!! Deixa a issue aberta, por favor, pra @deboraazevedo programar a publicação e registrar o link do post aqui também

**Comment by cecivieira** [comment]
https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

![image](https://user-images.githubusercontent.com/30605862/125311129-8f1a2c00-e309-11eb-842a-1f861cc8b9f7.png)

**Comment by deboraazevedo** [comment]
O maior evento de Python da América Latina está com chamada para atividades abertas!

Temos algumas temáticas que são sempre recorrentes no nosso evento: palestras sobre comunidade, educação, carreira e técnica.

Tem algum dúvida? Fala com a gente!

#PyBR2021

sugestão de texto.. querendo agendar pra quinta-feira dessa semana esse post

**Comment by deboraazevedo** [comment]
https://twitter.com/pythonbrasil/status/1417242899197186050
https://www.instagram.com/p/CRhn5aaDNL7/

**Comment by deboraazevedo** [comment]
https://www.instagram.com/p/CRpTvh2r0KB/
https://twitter.com/pythonbrasil/status/1418330141181218816
