### ISSUE TITLE
Incentivo a submissão de palestra - Níveis técnico

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#128]
### Campanha
Chamada para atividades
  
### Peça/publicidade solicitada
Cartão para incentivar a submissão de palestra

### Detalhamento do uso
A peça será utilizada para incentivar a submissão de palestras em diferentes níveis técnicos. Dialoga com a #127 , mas será postada em dia diferente.
Por favor, compartilha o link editável para tradução.

### Data prevista para uso da arte
15 jun. 2021

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by deboraazevedo** [comment]
Sugestão de texto

Tá em dúvida se o conteúdo que tu quer compartilhar não serve pra Python Brasil? Nem tenha! Na Python Brasil incentivamos palestras de todos os níveis de conhecimento.

O que você sabe com certeza vai ajudar alguém, submete sua atividade!

**Comment by cecivieira** [comment]
@deboraazevedo Sugiro que em todas você coloque o link para o formulário (https://forms.gle/aSxwwGekZpTs9k9K6) e data limite (12 agosto) 

Você faz legendas boas. Acho que tu pode agendar diretamente os posts, sem precisar postar as legendas aqui para aprovação.

**Comment by cmdiasbr** [comment]
![Cards](https://user-images.githubusercontent.com/45003095/126547799-3651f8ca-8106-4e1c-8108-677f542e63a7.png)

https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

**Comment by paulohenriquedsgn** [comment]
@deboraazevedo sobre a arte que você tinha comentado

**Comment by paulohenriquedsgn** [comment]
Link das postagens publicadas:

Linkedin: https://www.linkedin.com/posts/apyb_as-submiss%C3%B5es-de-atividades-para-a-python-activity-6828657020678234112-NHcp
Instagram: https://www.instagram.com/p/CSJ7qzMMVtK/?utm_source=ig_web_copy_link
Twitter: https://twitter.com/pythonbrasil/status/1422891331060477959?s=20
Facebook: https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fpythonbrasil%2Fphotos%2Fa.582882565067606%2F4522493481106475%2F&show_text=true&width=500
