### ISSUE TITLE
Relembrar período para submissão de atividades

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#129]
### Campanha
Chamada para atividades
  
### Peça/publicidade solicitada
Cartão para relembrar período de submissões de atividades

### Detalhamento do uso
Cartão genérico para ser postado durante o mês lembrando que estão abertas as submissões de atividades

### Data prevista para uso da arte
20 jul. 2021

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
https://www.canva.com/design/DAEjeGESl4Q/share/preview?token=w1kEvpcUAXyn_dPtUVGKsw&role=EDITOR&utm_content=DAEjeGESl4Q&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by cmdiasbr** [comment]
https://user-images.githubusercontent.com/45003095/125213566-15daf480-e289-11eb-87db-0f367bd3399d.mp4

**Comment by cecivieira** [comment]
@martinsvanessa Ficou massa!!! Obrigada!! Deixa a issue aberta, por favor, pra @deboraazevedo programar a publicação e registrar o link do post aqui também

**Comment by deboraazevedo** [comment]
Sugestão de texto:
As submissões de atividades para a Python Brasil estão abertas (mas não pra sempre haha)
Conta pra gente a sua história com Python: algo que tu descobriu, um atalho que tu aprendeu que facilita a sua vida, fala sobre como a sua comunidade funciona.
Queremos ouvir a sua história!

queria fazer essa postagem na semana que vem

**Comment by anadulce** [comment]
Sugestões: Sempre manter a data do evento nas imagens, e já está na hora de começar a vincular a data de encerramento das submissões nos textos ou imagens (para fazer pressão aos proponentes).
Sugestão de texto:
"As submissões de atividades para a Python Brasil estão abertas até 12 de agosto. Já submeteu a sua?
A Python Brasil possui participantes de diversos níveis de conhecimento e áreas, portanto aquele conteúdo que você queria muito apresentar tem espaço aqui <3
"

**Comment by paulohenriquedsgn** [comment]
![Cards](https://user-images.githubusercontent.com/64554724/127746509-e2a403d5-407d-43d7-9c0c-1d2e0667afa8.png)

@deboraazevedo já temos a arte para relembrar das submissões das palestras e o texto sugerido por você e Ana Dulce
"As submissões de atividades para a Python Brasil estão abertas até 12 de agosto. Já submeteu a sua?
A Python Brasil possui participantes de diversos níveis de conhecimento e áreas, portanto aquele conteúdo que você queria muito apresentar tem espaço aqui <3

Estou sugerindo agendar essa postagem para:
Twitter - 05/08 às 09:00hs
Linkedin - 05/08 às 09:00hs
Facebook - 04/08 às 10:00hs
Instagram - 05/08 às 10:00hs

Aguardo teu retorno para seguir

**Comment by paulohenriquedsgn** [comment]
@cecivieira deixa tua opinião também

**Comment by deboraazevedo** [comment]
Acho ótimo o texto! Por mim pode agendar o post :))

**Comment by paulohenriquedsgn** [comment]
@deboraazevedo vou agendar todos então :)

**Comment by cecivieira** [comment]
@paulohenriquedsgn dentro do link do canva tem essas outras imagens pra agendar.

Eu sou ruim de criar legendas. Se tu for também, posta a imagem lá no canal do Discord #geral-voluntariado e pede ajuda.

![image](https://user-images.githubusercontent.com/30605862/127918879-8742207b-8c26-497d-8095-2ee4078f8932.png)
![image](https://user-images.githubusercontent.com/30605862/127919067-b209fe9e-42bf-4d12-81bd-b9ac6ad7a06d.png)

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/127919097-275795a5-d630-4a5f-a073-958deafcb475.png)
![image](https://user-images.githubusercontent.com/30605862/127919109-0c0d61e4-19b8-4900-81b7-9211fdf4373d.png)

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/127919437-03ed683e-d376-4ef0-82b8-e9d5712ea1de.png)
![image](https://user-images.githubusercontent.com/30605862/127919465-68e213fd-0c3a-4701-9ec7-34b5684d799b.png)

**Comment by paulohenriquedsgn** [comment]
Link das postagens publicadas:

- Linkedin: https://www.linkedin.com/posts/apyb_as-submiss%C3%B5es-de-atividades-para-a-python-activity-6828657020678234112-NHcp
- Instagram: https://www.instagram.com/p/CSJ7qzMMVtK/?utm_source=ig_web_copy_link
- Twitter: https://twitter.com/pythonbrasil/status/1422891331060477959?s=20
- Facebook: https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fpythonbrasil%2Fphotos%2Fa.582882565067606%2F4522493481106475%2F&show_text=true&width=500
