### ISSUE TITLE
Abra seu e-mail

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#130]
### Campanha
Chamada para atividades
  
### Peça/publicidade solicitada
Cartão genérico pedindo para as facilitadoras de atividades abram seus e-mails

### Detalhamento do uso
Essa divulgação servirá para que as facilitadoras de atividades saibam que foi enviado e-mail com o resultado da avaliação. Elas tem um prazo de 3 dias para respondê-lo. Compartilha a arte editável para tradução, por favor

### Data prevista para uso da arte
02 set. 2021

### Quais informações devem aparecer na arte
Data limite para responder 05 set. (essa data deve ser editável, pois haverão outras rodadas de contato)

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

**Comment by cecivieira** [comment]
https://www.canva.com/design/DAEji0NpsRo/lOXkNhge5jMMU2pcBxVYEQ/view?utm_content=DAEji0NpsRo&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Arte para ser traduzida para espanhol

**Comment by deboraazevedo** [comment]
instagram https://www.instagram.com/p/CS-N1PwMb9B/
Twitter https://twitter.com/pythonbrasil/status/1430287619511013376
Facebook https://www.facebook.com/pythonbrasil/posts/4585385591483930

**Comment by cecivieira** [comment]
essa issue é para abrir o e-mail relacionado a APROVAÇÃO da atividade

**Comment by cmdiasbr** [comment]
Card para tradução: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

![Cards Gerais](https://user-images.githubusercontent.com/45003095/132238574-fc34ca1a-387f-412d-8ba4-a9148edfece8.png)

**Comment by cecivieira** [comment]
Versão em espanhol:
https://www.canva.com/design/DAEj_l16BnQ/-WdVZh1HIRQEhFVycpKDLA/edit

**Comment by alynnefs** [comment]
Vou fechar a issue (:
