### ISSUE TITLE
Venha participar da organização

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#131]
### Campanha
Lançamento do evento
  
### Peça/publicidade solicitada
Cartão para redes sociais

### Detalhamento do uso
Fazer chamada (meio desesperada) para pessoas que estejam interessadas em participar da organização da Python Brasil 2021 . Compartilha o link editpavel para tradução, por favor

### Data prevista para uso da arte
19 jul. 2021

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

**Comment by cecivieira** [comment]
@cmdiasbr ficou linda!!!!
Alynne vai comprar hoje o pacote de imagens, então a gente poderia substituir metade das imagens masculinas por mulheres?

**Comment by cmdiasbr** [comment]
> @cmdiasbr ficou linda!!!!
> Alynne vai comprar hoje o pacote de imagens, então a gente poderia substituir metade das imagens masculinas por mulheres?

Sim, vocês podem adicionar ou mudar algo lá também.

**Comment by martinsvanessa** [comment]
![Cards](https://user-images.githubusercontent.com/18190437/125213304-3f475080-e288-11eb-8a16-9db72c4545d4.png)

**Comment by martinsvanessa** [comment]
@cecivieira se tiver tudo ok vamos encerrar essa issue.

**Comment by cecivieira** [comment]
@martinsvanessa Ficou massa!!! Obrigada!! Deixa a issue aberta pra @deboraazevedo programar a publicação e registrar o link do post aqui também

**Comment by deboraazevedo** [comment]
Vem pra organização a Python Brasil!

Temos espaço para mais mãos para poder fazer o melhor evento para a melhor comunidade <3

Não tem pre-requisito para participar: basta ter boa vontade pra aprender e tempo livre pra se dedicar.

Se interessou? Entra em contato com a gente! 

sugestão de texto, to querendo agendar pra sábado :)

**Comment by paulohenriquedsgn** [comment]
Links das postagens publicadas:

Português:
Facebook - https://www.facebook.com/328258703863328/posts/4490649044290919
Instagram - https://www.instagram.com/p/CRuB4NnpGsQ/
Twitter - https://twitter.com/62984618/status/1418994545669419008

Espanhol:
Facebook - https://www.facebook.com/328258703863328/posts/4490522850970205
Instagram - https://twitter.com/62984618/status/1418979475866460167
Twitter - https://www.instagram.com/p/CRt7BqVr8mT/
