### ISSUE TITLE
Criar formulário para voluntariado de Comunicação

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#132]
### Descrição
Criar formulário para cadastro de voluntarias para colaborar com a Comunicação do evento. Ele deve ter uma breve explicação sobre o plano de comunicação e o que se espera da pessoa.

### Requisitos para a atividade ser considerada como concluída

- Criar formulário.

**Comment by alynnefs** [comment]
@cecivieira, @deboraazevedo, @paulohenriquedsgn, podemos fechar essa issue?

**Comment by cecivieira** [comment]
Atividade descontinuada
