### ISSUE TITLE
Criar canal e role para time de resposta no Discord

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#133]
### Descrição
O time de resposta precisa de um canal no Discord para discussões internas e um role próprio para que as pessoas possam mencionar o time a parti de qualquer canal.

### Requisitos para a atividade ser considerada como concluída

- Role `cdc` criado
- Categoria `Código de Conduta` criada (ter a categoria ajuda na separação de contextos)
- Categoria definida como privada, com permissões de leitura/escrita a apenas ao papel `cdc`
- Canal de texto `Discussões` criado (ou nome semelhante)

**Comment by gabubellon** [comment]
Isso já foi feito não ?

**Comment by gabubellon** [comment]
#182

**Comment by rougeth** [comment]
Sim, valeu @gabubellon
