### ISSUE TITLE
Convidar pessoas para o CDC

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#135]
### Descrição
Convidar pessoas de fora da organização que possam atuar como time de resposta do Código  de Conduta.

### Requisitos para a atividade ser considerada como concluída

- Pessoas convidadas verbalmente
- Pessoas no servidor do discord
- Pessoas com permissão de CDC no discord

**Comment by alynnefs** [comment]
issue associada: #133

**Comment by gabubellon** [comment]
#182
