### ISSUE TITLE
Convidar pessoas para ficarem responsáveis por cada trilha

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#136]
### Descrição

Convidar pessoas para ficarem responsáveis por cada trilha, bem como pela comunicação com palestrantes e voluntários

### Requisitos para a atividade ser considerada como concluída

- Pessoas convidadas verbalmente
- Pessoas no servidor do discord
- Pessoas com permissão de voluntário no discord

**Comment by cecivieira** [comment]
@anadulce isso será necessário?

**Comment by anadulce** [comment]
Se a maior parte das informações forem solicitadas via forms, acho que minimiza bastante a comunicação e o trabalho. Acho que não é mandatório.

**Comment by cecivieira** [comment]
@anadulce acredito que essa issue pode ser fechada
