### ISSUE TITLE
Registrar custos que já tivemos na planilha Financeiro

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#137]
### Descrição
Atualizar a [planilha](https://docs.google.com/spreadsheets/d/1ddYFSfrkOsH0LbP7O1a13IuZImvUXEGnfvpQiv3aISM/edit#gid=899647314) com os gastos já efetuados

### Requisitos para a atividade ser considerada como concluída

- Planilha atualizada

**Comment by alynnefs** [comment]
@cecivieira: colocar o Hootsuite
eu: colocar o pacote de imagens

**Comment by gabubellon** [comment]
não tenho escrita na leitura

**Comment by alynnefs** [comment]
> não tenho escrita na leitura
> 

@gabubellon não entendi
