### ISSUE TITLE
Atualizar o status dos patrocinadores

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#139]
### Descrição
Atualizar [planilha](https://docs.google.com/spreadsheets/d/1ddYFSfrkOsH0LbP7O1a13IuZImvUXEGnfvpQiv3aISM/edit#gid=899647314) com os status dos patrocinadores

### Requisitos para a atividade ser considerada como concluída

- planilha atualizada

**Comment by alynnefs** [comment]
[planilha onde deve ser atualizado](https://docs.google.com/spreadsheets/d/1ddYFSfrkOsH0LbP7O1a13IuZImvUXEGnfvpQiv3aISM/edit?usp=sharing)

@apast, acho que não tá com permissão de edição, você pode ver isso depois?

**Comment by gabubellon** [comment]
#182

**Comment by tiidadavena** [comment]
Gente, segue planilha atualizada com os status das patrocinadoras: https://docs.google.com/spreadsheets/d/1pz619Ma2K9mv6N2vdn1CdzzmHZ7yePuHN85CxKFZ0H0/edit?usp=sharing

Mais info sobre as empresas patrocinadoras podem ser encontradas aqui: https://drive.google.com/drive/u/2/folders/1-joru_hoJd2KoLLYUeiTY5UPjyS9aLzX

**Comment by tiidadavena** [comment]
> Gente, segue planilha atualizada com os status das patrocinadoras: https://docs.google.com/spreadsheets/d/1pz619Ma2K9mv6N2vdn1CdzzmHZ7yePuHN85CxKFZ0H0/edit?usp=sharing
> 
> Mais info sobre as empresas patrocinadoras podem ser encontradas aqui: https://drive.google.com/drive/u/2/folders/1-joru_hoJd2KoLLYUeiTY5UPjyS9aLzX

@alynnefs @anadulce @gabubellon @cecivieira

**Comment by alynnefs** [comment]
@tiidadavena VanHack tá fechado?

**Comment by alynnefs** [comment]
atualizei de acordo com o status de hoje (22/09)

**Comment by alynnefs** [comment]
atualizado de acordo com o status de hoje (23/11)

**Comment by cecivieira** [comment]
Incluída aba "Fluxo de Caixa", onde é possível verificar patrocínios e despesas previstas e efetivadas.
Última atualização em 23/11

**Comment by cecivieira** [comment]
Todos os patrocínios recebidos, conforme relatado no fluxo de caixa do evento:

https://docs.google.com/spreadsheets/d/1pz619Ma2K9mv6N2vdn1CdzzmHZ7yePuHN85CxKFZ0H0/edit#gid=228361764

* O fluxo de caixa em breve poderá ser encontrado no site do evento
