### ISSUE TITLE
Criar formulário para submissão de atividades

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#14]

**Comment by rougeth** [comment]
Em relação ao título da palestra, em 2020 tivemos problema com o limite de caracteres (100) no nome do vídeo no YouTube. O padrão que usamos foi:
```
[PyBR2020] Título - Nome Sobrenome
# Exemplo: [PyBR2020] Desmistificando o git rebase - André Girol
```
Escrevendo esse comentário, vi que poderíamos ter tirado o `[]` 😅. Mesmo assim, precisamos considerar isso no formulário.

Já em relação ao nome da pessoa palestrante, **muitas** pessoas mandaram o nome completo, o que adicionou um passo a mais na hora da edição. Talvez deixar mais claro no formulário para enviarem apenas o primeiro nome e o último sobrenome.

**Comment by cecivieira** [comment]
Pensando na ideia de enviar brinde para palestrantes. Nesse formulário deve ter os campos número do sapato, tamanho de camisa, endereço completo... e outros campos que podemos imaginar que precisemos para os brindes.

Também deve ser solicitada foto e nome para ser usada nas peças publicitárias, @ do twitter (caso deseje ser marcada nas postagens).

Coletar todas as informações de uma só vez pode economizar muito tempo da organização.

**Comment by cecivieira** [comment]
@alynnefs se já existir algum formulário que devemos usar como base, coloca o link aqui, por favor

**Comment by alynnefs** [comment]
Tem [esse](https://docs.google.com/forms/d/1f-A2C7ujiC9Zuzmcr0cuROIyVRssYX2lZbSNhFlp1GQ/edit?usp=sharing), mas podem modificar como acharem melhor.
Só não sei se é interessante pegar as informações antes de aprovar as palestras, porque tem gente que submete mais de uma atividade

**Comment by cecivieira** [comment]
Qual seria o problema de pegar informações duplicadas nesse caso?

**Comment by cecivieira** [comment]
O que precisa ser feito:

- [ ] Rever gênero do texto. Deixar gênero neuro ou que concorde com "pessoa"
- [ ] Inserir cláusula dando ciência sobre uso dos dados em conformidade com a LGPD

**Comment by cecivieira** [comment]
Inseri a seguinte cláusula. O que vocês acham?

- No dia XX de XX as submetedoras das atividades selecionadas receberão e-mail de confirmação e deverão OBRIGATORIAMENTE respondê-lo até dia XXXXXXXXXX. Caso isso não ocorra a organização entenderá que houve desistencia por parte da submetedora

**Comment by anadulce** [comment]
@cecivieira ano passado pretendíamos colocar informações complementares de divulgação, mas o formulário já é terrivelmente extenso sem essas informações. Além disso, se fosse para pedir dados de divulgação, o ponto mais importante seria pedir uma foto, e nesse caso o @rougeth identificou ano passado que limitaríamos o formulário a pessoas que utilizassem G-Mail.
Acho que a experiência do usuário já é bem exaustiva com esse forms, e acho que temos que tomar cuidado pra não ser desmotivadora.

**Comment by anadulce** [comment]
Além disso, eu não me comprometeria a enviar brindes porque ainda não temos certeza se realmente faremos isso.

**Comment by cecivieira** [comment]
Inserido Termo de Consentimento para Tratamento de Dados Pessoais:

"
Conforme artigo 5º, inciso X, da Lei Geral de Proteção de Dados Pessoais (nº 13.709/2018), entende-se por "tratamento" a coleta, produção, recepção, classificação, utilização, acesso, reprodução, transmissão, distribuição, processamento, arquivamento, armazenamento, eliminação, avaliação ou controle da informação, modificação, comunicação, transferência, difusão ou extração.

Em atendimento ao artigo 8º, parágrafo 4º, este termo guarda finalidade determinada, sendo esta:

    • Cadastro de submissão de atividade para PyBR2021.

Após o encerramento da Python Brasil 2021, os dados pessoais constantes nas submissões serão eliminados.
"


Não tenho mais nenhuma alteração para o formulário

**Comment by anadulce** [comment]
@cecivieira acho uma boa tirar mesmo.
Nos anos anteriores, o comunicado acontecia somente por e-mail, e como fazíamos a divulgação nas redes sociais de "Proponentes, chequem seus e-mails", a maioria responde sem problemas.
O e-mail vinha com um aviso de "Esperaremos pela sua resposta até dia X", e também mandávamos outro e-mail lembrando essa data tipo um dia antes dela terminar, então não é feita essa comunicação por outros meios mesmo.
Esse outro contato costuma ser mais útil quando a pessoa confirma a palestra e some, num momento que é menos custoso pra organização ir atrás dela do que chamar outro palestrante (depois de já termos divulgado a atividade), mas nem todas as pessoas respondem esse campo corretamente, tenho vários exemplos do ano passado onde a pessoa colocou outro e-mail e não viu o e-mail no outro e-mail também, que escreveu "Twitter" ou "Telegram" e não colocou @.
Eu acho útil termos um outro meio de comunicação rápida (tipo um Telegram) pra algum caso muito específico, mas não precisamos pedir nesse momento não, pode ser naquele forms de informação adicionais para pessoas aprovadas :)

**Comment by cecivieira** [comment]
@anadulce fiz o ajuste no formulário de inscrição e inseri a pergunta no formulário que iremos usar para confirmar a atividade.

Tu tem mais algum ajuste a fazer nesse formulário de inscrição? Se não tiver, podemos dar essa atividade como concluída.

**Comment by cecivieira** [comment]
Mentira... hehehehe
Precisa traduzir pra espanhol... faço isso durante a semana.

@anadulce só olha pra vê se dá de boa a versão em português, assim já pego a versão final para traduzir

**Comment by cecivieira** [comment]
O grupo de voluntárias da América Latina concluiu a tradução e revisão do formulário.

@anadulce @belaaiza o que vocês acham dessas datas? As principais estarão explicitadas no formulário:

12 jul. - abertura das submissões
12 ago. - encerramento das submissões
19 ago - envio para avaliadoras de propostas anonimizadas
26 ago - limite para recebimento das avaliações
02 set. - envio de e-mail para pessoas cujas atividades foram selecionadas
05 set. - limite para responder ao e-mail de contato
06 set. - envio de e-mail para segunda leva de pessoas cujas atividades foram selecionadas (cobrir vagas abertas)
09 set. - data limite para responder ao e-mail de contato
16 set. - publicação de programação

**Comment by anadulce** [comment]
Não acha que três dias é muito pouco tempo para responder ao e-mail? E normalmente organizamos para que esses dias coincidam com o fim de semana para dar mais tempo para as pessoas se organizarem e responderem, porque enviamos aquele forms de colher informações para divulgação junto, então isso demanda um certo esforço da parte das pessoas proponentes.
Eu colocaria:
02 set. - envio de e-mail para pessoas cujas atividades foram selecionadas
07 set. - limite para responder ao e-mail de contato
----- acho bom darmos um dia para nos organizarmos aqui. Não é só chamar as próximas palestras, também é necessário dar alguma atenção ao balanceamento de temas também em relação às palestras confirmadas. Eu deixaria um dia livre aqui para debates internos da organização.
09 set. - envio de e-mail para segunda leva de pessoas cujas atividades foram selecionadas (cobrir vagas abertas)
13 set. - data limite para responder ao e-mail de contato
19 set. - publicação de programação

Eu acho que não necessariamente precisamos esperar ter ambos fechados para começar a divulgar a programação.
Uma coisa é divulgar o conteúdo, e outra coisa é divulgar os horários.
Podemos começar postando quais são as palestras aprovadas (porque esse trabalho de postagens e criação das artes para cada palestrante vai ser cansativo), e depois fechar a distribuição.

Fechar a distribuição das palestras é sempre um trabalho imenso, porque demanda gerenciar as indisponibilidades de N palestrantes em X trilhas. Normalmente leva alguns dias para conseguirmos terminar e revisar, porque esse acaba sendo um processo totalmente manual (e, até onde me consta, escalonamento de horários assim é NP-Completo, então vai ser meio complicado criar um script para automatizar porque é um cálculo pesado, mas posso pesquisar já que é uma área do meu interesse e ficaria bem feliz em ter isso automatizado também).

Também acho bom termos consciência de que não preencheremos todos os slots de palestras com duas chamadas, e que vamos fechar a nossa grade com espaços vazios e que haverão alterações depois desse momento. Esperamos que não drásticas, mas haverão.

**Comment by rougeth** [comment]
+1 para dar mais tempo para as pessoas responderem os emails. Talvez até mandar um segundo email como lembrete faltando um dia para o prazo?

**Comment by anadulce** [comment]
Ah sim, sou super a favor de mandar lembretes também e já pretendia fazer, achei que não estava documentado para não poluir o cronograma mesmo.

**Comment by cecivieira** [comment]
Tinha pensado em deixar a divulgação da programação pro final por conta dessa complexidade que tu relatou @anadulce . Teríamos 12 dias para definir quem, em que data, a que horário e em que trilha. Mas acho que nada impede que divulguemos antes do prazo.

O calendário ficaria assim?

12 jul. - abertura das submissões
12 ago. - encerramento das submissões
19 ago - envio para avaliadoras de propostas anonimizadas
26 ago - limite para recebimento das avaliações
02 set. - envio de e-mail para pessoas cujas atividades foram selecionadas
06 set. - reenvio de e-mail para pessoas cujas atividades foram selecionadas
07 set. - limite para responder ao e-mail de contato
----- acho bom darmos um dia para nos organizarmos aqui. Não é só chamar as próximas palestras, também é necessário dar alguma atenção ao balanceamento de temas também em relação às palestras confirmadas. Eu deixaria um dia livre aqui para debates internos da organização.
09 set. - envio de e-mail para segunda leva de pessoas cujas atividades foram selecionadas (cobrir vagas abertas)
13 set. - data limite para responder ao e-mail de contato
19 set. - publicação de programação

**Comment by cecivieira** [comment]
Foram inseridas as datas do comentário anterior no formulário com a mensagem "(previsão)".
