### ISSUE TITLE
Deixar o site com a linguagem mais neutra possível

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#140]
### Descrição

Atualizar textos do site, deixando a linguagem neutra

### Requisitos para a atividade ser considerada como concluída

- site atualizado

**Comment by cecivieira** [comment]
Atualização realizada.
https://github.com/pythonbrasil/pybr2021-site/commit/03ebd12fbf897f1d4f221f7736de43f2097fd8d0
