### ISSUE TITLE
Cabeçalho para Twitter

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#144]
### Campanha
--
  
### Peça/publicidade solicitada
Cabeçalho para perfil do Twitter

### Detalhamento do uso
Atualizar perfil do Twitter

### Data prevista para uso da arte
Imediata

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [x] Outro *(cabeçalho do Twitter)*

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
https://drive.google.com/file/d/1_LParut6wAVSaqqZxVqTe68kVuhQT05l/view?usp=sharing

**Comment by cmdiasbr** [comment]
Tanto para Twitter quanto Facebook os banners estão aqui https://drive.google.com/drive/u/0/folders/1vijbP6a3Af0xOZrqsnIOLDAjUQ3guA0U

**Comment by cecivieira** [comment]
Cabeçalhos atualizados
