### ISSUE TITLE
Avaliação da plataforma Euleer

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#145]
### Descrição
Avaliar a plataforma Euleer como possível substituta para StreamYard+Youtube.

### Requisitos para a atividade ser considerada como concluída

- Assistir apresentação da plataforma;
- Testar plataforma.

**Comment by cecivieira** [comment]
Boa taardeee!!
Na conversa com Diana, ela  apresentou de forma geral a plataforma Eulerr e ofereceu pra gente usar. Anotei algumas funcionalidades:

- Filtro para xingamentos nos comentários da audiência (pt, es, en);
- Formação de thread nos comentários da audiência;
- Suporte para tradução simultânea. A assistente pode escolher o idioma que ouvirá a palestra;
- Suporte para intérprete de Libras;
- Identifica as pessoas online na sala da palestra;
- Possibilidade de gamificação com interação da plataforma (isso pode servir para distribuição de brindes por parte das patrocinadoras);
- Breakout rooms.

Pensei que poderíamos assistir uma apresentação da plataforma para saber se facilitará nossa vida e temos interesse. O que vocês acham?

**Comment by alynnefs** [comment]
Como faz pra ver?

**Comment by cecivieira** [comment]
@alynnefs ver a plataforma? Não tenho senha para teste. Caso a gente tenha interesse em explorar a possibilidade de mudança de plataforma, marco uma próxima reunião para que expliquem a plataforma melhor e nos dê um acesso para testes.

**Comment by alynnefs** [comment]
Descobrir se é possível adicionar pessoas depois do início do evento

**Comment by anadulce** [comment]
* Simultâneo no Youtube?
* Cadastro de usuários: como isso é feito? Como é gerenciado?

**Comment by alynnefs** [comment]
Marcar reunião para ver a possibilidade de usar nos tutoriais

**Comment by cecivieira** [comment]
@gabubellon tu poderia colocar aqui tuas anotações feitas durante a reunião com a Euleer?

**Comment by gabubellon** [comment]
Itens anotador com a conversa co a Euleer
* Ambiente segmentado por roles
* Possui integração com aviso por email e countdown com timezone
* Permite ter close caption em tempo real  com multiplos canais (precisa ser pessoa fazendo input das legendas em tempo real)
* Moderação com soft e hard ban
* Permite promover pessoas as outras roles podendo ter hosts, palestrantes, apresentadores e participantes bem segmentados
* Q/A bem elaborado com vote up de perguntas
* Permite banner clicaveis apenas no ambiente interno deles
* Multiplas salas de transmissão
* Vinculo com transmissão para o youtube
* Permite gravar, podendo ligar e desligar a gravação (stream ao vivo não para) com limite de 8hs por arquivo
* Permite backstage com chat entre moderadores e pessoas no backstage
* Permite adicionar pessoas durante o evento
* Permite inserir pessoas em bulk
* Não tem API
* Downloads apenas manuais

Em um contexto geral é uma excelente ferramenta
Podemos utilizar a mesma para os tutorias
Estamos abertos para ter um trial com a empresa  e testar mais próximo ao evento, uma vez que os tutoriais não precisam ser transmitidos
