### ISSUE TITLE
Definir formas para recebimento de doação

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#146]
### Descrição
Foi definido que a organização do evento fará arrecadação finaceira através de doação para beniciar instituições com trabalhos sociais. Nesse momento precisamos definir como viabilizar essa ação.

### Requisitos para a atividade ser considerada como concluída

- Definir faixas de valores a serem doados;
- Plataforma para arrecadação.

**Comment by cecivieira** [comment]
Pensei que poderíamos definir faixas de valores para doação, que seriam disponibilizados em forma de ingresso na plataforma de inscrição. Além disso, poderíamos programar postagens de incentivo à doação (discord durante o evento e redes sociais) com link para esses ingressos e Qrcode nos vídeos de intervalo.

Pensei também em divulgar uma chave PIX, mas acho que dificultaria um pouco saber o montante arrecadado para esse fim, tendo em vista que dividimos a conta bancária com outros eventos/atividades.

**Comment by cecivieira** [comment]
Faixas de valores sugeridas:
R$5
R$15
R$30
R$70
R$100
R$150

Pensando que a pessoa pode comprar quantos ingressos desejar em cada faixa de valor. Definiri várias seria apenas para facilitar a doação da usuária.

**Comment by alynnefs** [comment]
Ter vários ingressos pra uma só pessoa não vai fazer com que tenha mais inscritos do que realmente tenha? Exemplo, se eu pego o ingresso de 5 e o de 15, a plataforma conta como um ou dois inscritos?

**Comment by cecivieira** [comment]
Não sei.
Precisamos  testar isso no Eventbrite.

**Comment by cecivieira** [comment]
@gabubellon Verificar com Apyb possibilidade de recebimento via pix

**Comment by cecivieira** [comment]
@alynnefs verificar restrição de compra apenas de 1 ingresso

**Comment by alynnefs** [comment]
O eventbrite permite que a pessoa escolha o valor que quer doar

![Screenshot from 2021-07-26 21-39-58](https://user-images.githubusercontent.com/17454743/127076877-6fcf1fe4-f0d1-42a0-bfc9-e62401dcf3f5.png)

**Comment by cecivieira** [comment]
Achei essa solução massa.
Acho que podemos usar ela e a do pix (se rolar)

**Comment by alynnefs** [comment]
sim sim, não precisamos descartar o pix, mas ter o valor definido pela pessoa ajuda muito

**Comment by cecivieira** [comment]
@gabubellon tu conseguiu ver como viabilizar doação via pix com a Apyb?

**Comment by gabubellon** [comment]
Alinhado com @mazulo , vai ser vinculado uma chave pix ao email de eventos e um QR code gerado pela APyB 
![image](https://user-images.githubusercontent.com/7385097/127866668-cbf6f3fd-8708-4e3b-8635-83d2d6b70a0d.png)
O mesmo está responsável por informar a org dos valores do evento irá acompanhar as doações e fazer o repasse após evento

**Comment by alynnefs** [comment]
decidido: inscrição no modo doação + pix durante o evento
