### ISSUE TITLE
Fazer roteiro para anfitriã de palestras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#147]
### Descrição
Como no ano pasado, as voluntárias que serão afitriãs nas palesttras receberão um roteiro com orientações e perfil da pessoa palestrante. É necessário revisar o do ano anterior e fazer as adequações necessárias.

### Requisitos para a atividade ser considerada como concluída

- Revisar roteiro do ano anterior;
- Incluir mensagem de incentivo a doação

**Comment by cecivieira** [comment]
@alynnefs @GabrielRF vocês poderiam compartilhar o documento usado no ano passado?
Se der para criar uma cópia na pasta desse ano e compartilhar esse versão, seria melhor, assim já iríamos modificando.

**Comment by alynnefs** [comment]
modelo: https://docs.google.com/document/d/1LToU5UL1siCDeUbRLQEMtLMhAHx1TJ6wpDdM-EuCfrA/edit?usp=sharing

@cecivieira, alguma dica de onde colocar no drive desse ano? faço uma pasta nova?

**Comment by cecivieira** [comment]
Dentro de Trilhas: https://drive.google.com/drive/u/0/folders/1tzgQ1J7HlV3DAWpNa8qig_lCzCCTTocf

**Comment by alynnefs** [comment]
feito: https://docs.google.com/document/d/1Wm1YHy7uCBe61Gwf60rtag5hXvfhp5AJPWxMH9E28g0/edit?usp=sharing

vou atualizar o guia que o @gabubellon fez pra usar na python nordeste, mas a gente vai seguir esse modelo aí

**Comment by belaaiza** [comment]
@alynnefs não consegui abrir o doc, na pasta "Trilhas" só aparece pra mim outra pasta: "América Latina" e dentro dela uma planilha de voluntárias, será se tô sem acesso?

**Comment by alynnefs** [comment]
@belaaiza, eu não tinha movido o arquivo. Agora tá na pasta "Trilhas" (:

**Comment by dandaramcsousa** [comment]
doing: https://docs.google.com/document/d/1RgLJU9mm1XEyMLlX87YNvQS0dAdAo3Dh5VMu_bwLGm8/edit?usp=sharing

**Comment by cecivieira** [comment]
Deixei os pitacos no documento.

Acho um pouco grosseiro informar na apresentação da palestra que a pessoa tem "x minutos", pois ela já foi muito avisada em todo o processo desde a submissão.

**Comment by joaomaia7** [comment]
eu gostaria de auxiliar nessa issue.

**Comment by cecivieira** [comment]
O roteiro foi colocado neste repositório, ou seja, toda a atualização deve ser realizada através de PR. Caso precise de ajuda, comenta aqui e me marca que fazemos juntas.

https://github.com/pythonbrasil/pybr2021-org/blob/main/roteiros/palestra-transmissao-ao-vivo.md

**Comment by cecivieira** [comment]
@joaomaia7 dá uma olhada na versão atual. Fica a vontade para modificar e mandar Pull request. Caso precise se ajuda para fazer isso, comenta aqui =D

https://github.com/pythonbrasil/pybr2021-org/blob/main/roteiros/palestra-transmissao-ao-vivo.md

**Comment by joaomaia7** [comment]
@cecivieira realizei algumas mudanças de ordem gramatical e de apresentação do documento, apenas. mandei Pull Request. fique à vontade para sugerir modificações.

**Comment by cecivieira** [comment]
@joaomaia7 Ficou massa! Deixei um comentário lá se tu quiser fazer também.
Dá uma olhada lá #189

**Comment by cecivieira** [comment]
Roteiro concluído:

https://github.com/pythonbrasil/pybr2021-org/blob/main/roteiros/palestra-transmissao-ao-vivo.md
