### ISSUE TITLE
Patrocínio com a Carta

### ISSUE THREAD

**Issue by tiidadavena** [pythonbrasil/pybr2021-org#148]
Descrição
Issue para registro do patrocínio com a Carta na pessoa de Gustavo Morada.

Ticket #7024 no Freshdesk.

Exemplo de como pode ser feito: #40

**Comment by tiidadavena** [comment]
Interesse na cota Gold.

Reunião agendada para amanhã às 16h.

Aguardando o link da reunião.

**Comment by tiidadavena** [comment]
1. Vão precisar do Plano de Patrocínio em inglês com valores em Real

2.  "Vão precisar traduzir o contrato para inglês, pois o setor Jurídico é EUA, mas o valor será pago pela filial brasileira"

3. A maioria dos colaboradores são anglófonos, são dos EUA e CAN (dependendo da quantidade de palestrantes, a Carta pode ajudar a conseguir um tradutor / intérprete

4. O tutorial será feito em PT-BR

5. CTO (Jerry Talton) poderia ser um palestrante ou um candidato do Keynote (larga XP em python e com atuação em empresas como Slack e atuação em Stanford)

**Comment by tiidadavena** [comment]
Pessoal da Carta enviou email cobrando sobre a possbilidade de tradução simultânea para as palestras em inglês:

"(...) poderemos ter tradução simultânea ou não de Inglês para Português.
Ahh e os exemplos de videos e materiais que temos que enviar para material de divulgação."

@cecivieira @deboraazevedo @alynnefs podemos enviar materiais dos posts da PYBR deste ano e do ano passado como exemplo?

**Comment by cecivieira** [comment]
Conversamos sobre ter palestras em inglês e acredito que concluímos que o evento é para dar visibilidade para o que está sendo produzido na comunidade local em português. Seria ter um evento de grande porte que oportunizasse as pessoas que não tem um segundo idioma.

A ideia da trilha em espanhol foi a pouca popularidade de produtoras de conteúdo latino americana em nosso país, então teremos tradução simultânea espanhol-português, mas não ao contrário. Pelo motivo de o foco ser a comunidade brasileira.

**Comment by cecivieira** [comment]
> @cecivieira @deboraazevedo @alynnefs podemos enviar materiais dos posts da PYBR deste ano e do ano passado como exemplo?

Entendi que a empresa precisa saber qual material gráfico enviar. Solicitaremos assim que o contrato for fechado. 

O material dos anos anteriores pode ser visualizados nas nossas redes socias:
https://twitter.com/pythonbrasil
https://www.instagram.com/pythonbrasil/

**Comment by cecivieira** [comment]
> CTO (Jerry Talton) poderia ser um palestrante ou um candidato do Keynote (larga XP em python e com atuação em empresas como Slack e atuação em Stanford)

Acho complicadíssimo a empresa patrocinadora sugerir keynote um dos seus diretores.

> A maioria dos colaboradores são anglófonos, são dos EUA e CAN (dependendo da quantidade de palestrantes, a Carta pode ajudar a conseguir um tradutor / intérprete

Nós não estamos aceitando palestra em inglês

**Comment by tiidadavena** [comment]
> 

> > CTO (Jerry Talton) poderia ser um palestrante ou um candidato do Keynote (larga XP em python e com atuação em empresas como Slack e atuação em Stanford)
> 
> Acho complicadíssimo a empresa patrocinadora sugerir keynote um dos seus diretores.
> 
> > A maioria dos colaboradores são anglófonos, são dos EUA e CAN (dependendo da quantidade de palestrantes, a Carta pode ajudar a conseguir um tradutor / intérprete
> 
> Nós não estamos aceitando atividades em inglês

Massa, Ana!
No caso, posso sugerir a eles para estimular que o time (apenas) do BR envie palestras e atividades?

**Comment by tiidadavena** [comment]
> > 
> 
> > > CTO (Jerry Talton) poderia ser um palestrante ou um candidato do Keynote (larga XP em python e com atuação em empresas como Slack e atuação em Stanford)
> > 
> > 
> > Acho complicadíssimo a empresa patrocinadora sugerir keynote um dos seus diretores.
> > > A maioria dos colaboradores são anglófonos, são dos EUA e CAN (dependendo da quantidade de palestrantes, a Carta pode ajudar a conseguir um tradutor / intérprete
> > > Eles pensaram para ele tentar submeter um tutorial ou sprint, o que vocês acham?
> > 
> > Nós não estamos aceitando atividades em inglês
> 
> Massa, Ana!
> No caso, posso sugerir a eles para estimular que o time (apenas) do BR envie palestras e atividades?

**Comment by tiidadavena** [comment]
> > CTO (Jerry Talton) poderia ser um palestrante ou um candidato do Keynote (larga XP em python e com atuação em empresas como Slack e atuação em Stanford)
> 
> Acho complicadíssimo a empresa patrocinadora sugerir keynote um dos seus diretores.
> 
> > A maioria dos colaboradores são anglófonos, são dos EUA e CAN (dependendo da quantidade de palestrantes, a Carta pode ajudar a conseguir um tradutor / intérprete
> 
> Nós não estamos aceitando atividades em inglês

Sobre o CTO, no caso, rolaria dele submeter uma atividade prática?

**Comment by alynnefs** [comment]
Acho que não tem problema submeterem atividade, mas keynotes são escolhas da organização.

Os materiais de divulgação devem ser os vídeos institucionais, não lembro de ter visto, só a divulgação que a gente montou pra aparecer nos intervalos

**Comment by cecivieira** [comment]
> No caso, posso sugerir a eles para estimular que o time (apenas) do BR envie palestras e atividades?

Seria massa empolgar a equipe da empresa a participar do evento.

> Sobre o CTO, no caso, rolaria dele submeter uma atividade prática?

A cota ouro prevê que a empresa faça uma atividade prática entre 3h e 6h : "Slot para tutorial, uma atividade prática de 3 ou 6 horas, que pode ser relacionada ou não ao contexto da empresa". Que deve ser enviada com 30 dias de antecedência para a organização ( vou abrir uma issue pra fazer esse formulário)

Fora disso, seria ótimo ele submeter atividade, mas como todas as outras será avaliada de forma anonimizada.

**Comment by alynnefs** [comment]
falta só a revisão da tradução (#149) pra enviar o contrato pra eles?

**Comment by tiidadavena** [comment]
Resposta do último email da Carta:

“
+ Exposição da marca na abertura das palestras na edição final publicada no YouTube
+ Exposição da marca durante todas palestras (logo na margem)
+ Divulgação de vídeo institucional em mídias sociais (2 minutos)
+ Apresentação de vídeo institucional na abertura de Keynotes (1 minuto)
+ Exposição da marca em todos e-mails institucionais

Podem me passar as especificações de cada um desses pontos para eu começar a providenciar internamente? 
Especialmente os vídeos institucionais de 2 minutos para divulgação em mídias sociais e de 1 minuto para abertura de Keynotes que ainda não estão claros para mim como vão funcionar. Além disso, possivelmente terei que produzir os vídeos a tempo do evento.

Fico no aguardo das especificações e do contrato.

Obrigado”

**Comment by tiidadavena** [comment]
No caso, Gustavo está pedindo a especificação técnica dos materiais de divulgação, acho que ele se refere às especificações técnicas de formato de arquivo.

**Comment by cecivieira** [comment]
@tiidadavena responde que estamos definindo internamente e enviaremos nos próximos dias.

@martinsvanessa @cmdiasbr 
Vocês lembram das especificações do formato do vídeo com as marcas que vocês fizeram no ano passado (tipo de arquivo e resolução)?

**Comment by cmdiasbr** [comment]
Arquivo .mp4
Resolução 1080x720

**Comment by tiidadavena** [comment]
@alynnefs @cecivieira o que vocês acham desta devolutiva para a Carta?

"Olá, Gustavo!

Estamos definindo internamente o formato dos arquivos e retornaremos em breve.

Sobre o vídeo institucional, é material gerado pela empresa patrocinadora, que exibiremos nos intervalos e aberturas das palestras e trilhas. Mas não existe modelo definido, no caso da pandemia, algumas empresas tem preferido o formato estático, com animações e ilustrações. No caso da Carta, pode ser o vídeo da sede legendado em pt-BR, ou algum vídeo demo do funcionamento da solução da empresa, por exemplo.

Seguem materiais que podem ajudar o time de marketing de vocês a criar o vídeo institucional: 

https://www.youtube.com/watch?v=eDQGJRDUd-Y
https://rockcontent.com/br/blog/video-marketing/

Sobre as vinhetas do evento com os patrocinadores, que são produzidas pela nossa equipe de Comunicação, vamos precisar da logo em formato a ser detalhado no formulário, mas adiantamos que o formato o vídeo é em MP4 com resolução de 1080x720p.

Estamos à disposição para quaisquer esclarecimentos,"

**Comment by tiidadavena** [comment]
(Tentei encontrar uma vinheta dos patrocinadores em alguns vídeos e no insta, mas não encontrei pra mostrar de exemplo pro Gustavo)

**Comment by cecivieira** [comment]
Sugestão de alterações:

"Olá, Gustavo!

Estamos definindo internamente o formato dos arquivos e retornaremos em breve.

Sobre o vídeo institucional, é material gerado pela empresa patrocinadora, que exibiremos nos intervalos e aberturas das palestras e trilhas. Mas não existe modelo definido, no caso da pandemia, algumas empresas tem preferido o formato estático, com animações e ilustrações. No caso da Carta, pode ser o vídeo da sede legendado em pt-BR, ou algum vídeo demo do funcionamento da solução da empresa, por exemplo. **Talvez teu setor de marketing possa dar umas ideias legais sobre como comunicar a marca de vocês em um vídeo** Seguem materiais que podem ajudar:

https://www.youtube.com/watch?v=eDQGJRDUd-Y
https://rockcontent.com/br/blog/video-marketing/

Estamos à disposição para quaisquer esclarecimentos,"

-
Pelo que entendi do plano de patrocínio, não existe vinheta com logo das patrocinadoras. Isso só ocorrerá se a gente tiver disposição para fazer com as que não envie o vídeo institucional, mas não é um compromisso contratual. Por isso retirei a informação sobre isso

**Comment by cecivieira** [comment]
@alynnefs vê o que tu acha dessa última versão do e-mail

Acredito que "no caso da carta" faz referência a não ser uma empresa nacional, então o vídeo já pode existir em outro idioma

**Comment by tiidadavena** [comment]
> Sugestão de alterações:
> 
> "Olá, Gustavo!
> 
> Estamos definindo internamente o formato dos arquivos e retornaremos em breve.
> 
> Sobre o vídeo institucional, é material gerado pela empresa patrocinadora, que exibiremos nos intervalos e aberturas das palestras e trilhas. Mas não existe modelo definido, no caso da pandemia, algumas empresas tem preferido o formato estático, com animações e ilustrações. No caso da Carta, pode ser o vídeo da sede legendado em pt-BR, ou algum vídeo demo do funcionamento da solução da empresa, por exemplo. **Talvez teu setor de marketing possa dar umas ideias legais sobre como comunicar a marca de vocês em um vídeo** Seguem materiais que podem ajudar:
> 
> https://www.youtube.com/watch?v=eDQGJRDUd-Y
> https://rockcontent.com/br/blog/video-marketing/
> 
> Estamos à disposição para quaisquer esclarecimentos,"
> 
> 
> Pelo que entendi do plano de patrocínio, não existe vinheta com logo das patrocinadoras. Isso só ocorrerá se a gente tiver disposição para fazer com as que não envie o vídeo institucional, mas não é um compromisso contratual. Por isso retirei a informação sobre isso

Entendi, Ana! Perfeito!

**Comment by alynnefs** [comment]
o que foi conversado na reunião #156: contadora precisa de mais tempo para ver questões burocráticas

**Comment by tiidadavena** [comment]
Corpo do email enviado:

> Olá, Gustavo!

O contrato está em análise final pelo Comitê, mas sobre as outras dúvidas, seguem esclarecimentos a seguir:

Sobre o vídeo institucional, é material gerado pela empresa patrocinadora, que exibiremos nos intervalos e aberturas das palestras e trilhas. Mas não existe modelo definido, no caso da pandemia, algumas empresas tem preferido o formato estático, com animações e ilustrações. No caso da Carta, pode ser o vídeo da sede legendado em pt-BR, ou algum vídeo demo do funcionamento da solução da empresa, por exemplo.

Seguem materiais que podem ajudar o time de marketing de vocês a criar o vídeo institucional, caso não tenha: 

https://www.youtube.com/watch?v=eDQGJRDUd-Y
https://rockcontent.com/br/blog/video-marketing/

Sobre a logo e materiais de divulgação, podem ser exportados no formato PNG. Já os vídeos podem ser exportados em MP4. Para anexar os arquivos, enviaremos um form após a assinatura do contrato (segundo fluxo interno da organização).

Atenciosamente,
Juliana Barros Lima
Python Brasil 2021
>

**Comment by gabubellon** [comment]
#182

**Comment by alynnefs** [comment]
@tiidadavena, pode enviar o contrato traduzido (:

**Comment by alynnefs** [comment]
Cadastrei a apyb no graphite, que é uma plataforma que eles usam para avaliar patrocínios. Também enviamos o formulário que lista os benefícios, pois quem está em contato conosco entrou de férias e queria adiantar o que desse.

**Comment by cecivieira** [comment]
@tiidadavena esse contrato está assinado?

**Comment by alynnefs** [comment]
@cecivieira, já submeti o evento na plataforma de patrocínio que eles usam, estamos aguardando resposta. O nosso contato lá dentro tirou férias, mas adiantamos o que deu

**Comment by tiidadavena** [comment]
Enviado email de cobrança do status de patrocínio para a Carta com prazo para resposta definido na Reunião Geral para o dia 10/09.

**Comment by tiidadavena** [comment]
Carta enviou um email pedindo a versão do contrato em Word para eles adicionarem os dados.

@alynnefs posso enviar em .doc? Eu me comprometo conferir a versão que eles enviarem de volta.

**Comment by cecivieira** [comment]
@tiidadavena envia a versão no Google Docs, assim dá para verificar facilmente se houve alguma alteração

**Comment by tiidadavena** [comment]
> @tiidadavena envia a versão no Google Docs, assim dá para verificar facilmente se houve alguma alteração

Boa ideia, Ana! Obgggggg

**Comment by alynnefs** [comment]
> @tiidadavena envia a versão no Google Docs, assim dá para verificar facilmente se houve alguma alteração

Cheguei tarde, mas ia sugerir isso. @tiidadavena, só muda a permissão do link pra que consigam editar

**Comment by tiidadavena** [comment]
Beleza!

Link com permissões enviado para Gustavo Morada.

**Comment by tiidadavena** [comment]
Enviado email com cobrança da data de prazo para assinatura, pois a empresa já tinha pedido o contrato para preencher com os dados da dela desde sexta-feira.

**Comment by tiidadavena** [comment]
Gustavo Morada enviou agora o contrato assinado pelas partes da Carta. 
@alynnefs falta agora adicionar as nossas assinaturas.

**Comment by tiidadavena** [comment]
[contrato_assinado_parte1_carta.pdf](https://github.com/pythonbrasil/pybr2021-org/files/7205141/contrato_assinado_parte1_carta.pdf)
Documento da carta

**Comment by alynnefs** [comment]
[contrato com as duas assinaturas](https://drive.google.com/file/d/1jxo1cFiOweHzIpso2XRrR-lPIgj3S7Iw/view?usp=sharing)

**Comment by alynnefs** [comment]
Nota fiscal solicitada

**Comment by tiidadavena** [comment]
@alynnefs a Carta perguntou se o tutorial deles no dia 17/10 está confirmado

**Comment by tiidadavena** [comment]
@alynnefs @mazulo Morada avisando do pagamento para a equipe da Carta
![427DF451-A3BC-458D-A47C-9387C155F6A6](https://user-images.githubusercontent.com/12106738/137234551-4026945f-58ff-4009-b170-26892a3cf6b9.jpeg)

**Comment by cecivieira** [comment]
@alynnefs @tiidadavena tem alguma pendência de documentação e pagamento com esse patrocinadora?

**Comment by alynnefs** [comment]
@cecivieira precisa ver se o pagamento já foi feito. Pelo que entendi, só passaram pra área responsável

**Comment by cecivieira** [comment]
@mazulo o pagamento foi recebido?

**Comment by cecivieira** [comment]
@mazulo @alynnefs vocês poderiam atualizar o status desse patrocínio?

**Comment by cecivieira** [comment]
Acho que não fui explícita na mensagem anterior, então refaço:

Vocês poderiam informar aqui na issue como está o andamento do recebimento desse patrocínio? Em que etapa está? Qual a pendencia?

**Comment by alynnefs** [comment]
@cecivieira não achei o pagamento no extrato, mas a NF já foi enviada. Tem como conferir pra ver se deixei passar?

**Comment by cecivieira** [comment]
@alynnefs a entrada de dinehiro não consta no extrato.

@tiidadavena tu poderia fazer contato com a empresa para saber como está o processo?

**Comment by cecivieira** [comment]
Patrocínio recebido em 02 dez 2021
