### ISSUE TITLE
Tradução do Contrato de Patrocínio em Inglês - Carta

### ISSUE THREAD

**Issue by tiidadavena** [pythonbrasil/pybr2021-org#149]
Gustavo nos informou na reunião que como o Jurídico da Carta é no exterior, eles irão precisar do Plano de Patrocínio em inglês para fechar o contrato. 

Modelo de Contrato para tradução: https://docs.google.com/document/d/12zFiaFaSJ7s3CXSty91kdIhGuoF2iVUq/edit?rtpof=true

**Comment by tiidadavena** [comment]
@apast @alynnefs @cecivieira  (por favor, fiquem à vontade para marcar quem mais pode ajudar a revisar)

Segue primeira versão do Contrato (para a carta) com duas colunas e bilíngue: https://docs.google.com/document/u/1/d/1oefJKOADEd2YYTj2XkTNQiTi52-tOzJk/edit#

**Comment by alynnefs** [comment]
Revisei, mas como tem muitas palavras de fora do meu vocabulário, seria bom que outras pessoas também revisassem

**Comment by cecivieira** [comment]
@rougeth tu poderia dá uma olhada na versão em inglês desse contrato?

**Comment by cecivieira** [comment]
@alynnefs tu acha que essa versão do contrato já pode ser enviada para a empresa?

**Comment by gabubellon** [comment]
#182
