### ISSUE TITLE
Patrocínio com a Olist

### ISSUE THREAD

**Issue by tiidadavena** [pythonbrasil/pybr2021-org#150]
Resumo da reunião no dia 16/07:

- Estão com interesse na cota Prata

- Eles disponibilizam o time de mkt para as artes - agendar reuniões com o time de Comunicação

- Métricas de alcance do YouTube para mensurar com mais detalhes

**Comment by tiidadavena** [comment]
A Olist, na pessoa de Pryscila, enviou os dados da empresa para a gente montar uma pré-contrato.

Durante a reunião ficou claro para os participantes sobre o esforço da empresa para mudar a imagem nos últimos meses e agora busca apoiar mais intensamente a comunidade.

**Comment by tiidadavena** [comment]
Link do pré-contrato para revisão: https://drive.google.com/file/d/12zFiaFaSJ7s3CXSty91kdIhGuoF2iVUq/view?usp=sharing

**Comment by alynnefs** [comment]
@tiidadavena posso enviar o contrato para que analisem?

**Comment by tiidadavena** [comment]
Na última segunda (26/07) enviaram email cobrando sobre o status do contrato para apreciação e revisão.

Adicionei uma anotação no Freshdesk com a possível resposta ao email. Para enviar a resposta, aguardo retorno sobre a Organização e a APyB sobre os embaraços enfrentados com a empresa em patrocínios anteriores.

**Comment by gabubellon** [comment]
#182
