### ISSUE TITLE
Definir material gráfico a ser pedido à patrocinadoras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#151]
### Descrição
Conferir compromissos de divulgação da marca das patrocinadoras em cada cota e definir material a ser pedido a essas empresas

### Requisitos para a atividade ser considerada como concluída
- Verificar compromissos da organização nas cotas de patrocínio relacionados a Publicidade da marca;
- Listar material gráfico a ser pedido às empresas

**Comment by cecivieira** [comment]
@rougeth @gabubellon @cmdiasbr pensando nas divulgações das marcas realizadas no ano passado, quais foram os materiais gráficos necessários?

**Comment by rougeth** [comment]
Eu só lembro das logos.

**Comment by paulohenriquedsgn** [comment]
Poderia ser interessante, além das logos,  colocar ou demonstrar alguma informação de como o patrocinador trabalha com python hoje (tamanho da equipe e etc). No evento da Observe eles fizeram algo parecido https://www.instagram.com/p/CFiXvphHkeJ/?utm_medium=copy_link

**Comment by cecivieira** [comment]
@paulohenriquedsgn Boa ideia pedir isso de uma vez só.
Podemos fazer um pequeno formulário para coletar as informações que precisaremos das empresas patrocinadoras.
Daí coloca a seção ouro, prata e bronze, pois precisaremos de informações diferentes para cada uma.

Precisa dá uma olhadinha no plano de patrocínio (https://2021.pythonbrasil.org.br/) . De cabeça só lembro da cota ouro que pode fazer uma atividade prática e o planejamento dela deverá ser enviado para a organização com 30dias de antecedência (idealmente)

**Comment by cecivieira** [comment]
criei um formulário para a coleta das informações que sugeri no comentário anterior

https://docs.google.com/forms/d/1uRG7yt7D8PgwMvTP3wjCSRPRTFn0idvu0sGCCRetdOA/edit?usp=sharing
