### ISSUE TITLE
Configurar botecobot

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#152]
### Descrição
Adicionar [botecobot](https://github.com/rougeth/botecobot) no servidor do Discord do evento.

### Requisitos para a atividade ser considerada como concluída
- Canal `peça uma mesa` criado
- Qualquer usuário com permissão de executar o comando `!mesa <nome-da-mesa>`
- Configurações de permissões criadas do robô [pybr2021-discord-bot](https://github.com/rougeth/pybr2021-discord-bot/)

**Comment by rougeth** [comment]
O robô encontra-se desligado (pós Python Nordeste) por motivos de: acabou os créditos grátis no Heroku. Vou mudar o servidor para algo mais barato, já 7 dólares do Heroku faz do boteco um barzinho.

**Comment by exageraldo** [comment]
@rougeth eu tenho um servidor onde consigo hospedar o bot. acha que rola?

**Comment by rougeth** [comment]
@exageraldo valeu! Eu tenho onde hospedar, preciso migrar só.

**Comment by rougeth** [comment]
Boteco está rodando no Heroku. Vou deixar lá mesmo, depois da Python Brasil vejo o que fazer com ele.
