### ISSUE TITLE
Configurar integração do zapier com google sheets

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#154]
### Descrição
Formulário de submissão de palestras não envia confirmação de submissão. Uma forma de resolver isso seria integrando a planilha de submissões com um serviço de email.

### Requisitos para a atividade ser considerada como concluída
- Criar conta no Zapier para organização
- Configurar Zapier para enviar um email toda vez que tiver uma linha na planilha de submissão

**Comment by anadulce** [comment]
A ferramenta funciona bem (tem um delay de um ou dois minutos), tem uma interface simples de configurar, oferece opções de inserir colunas da planilha original em vários campos do e-mail.
Únicos pontos são: precisa logar com o e-mail do evento se quiser que os e-mails sejam enviados por ele, porque ele faz autenticação direta lá no Google. Tem umas permissões meio assustadoras (ler, editar e apagar tudo no Drive), mas dá pra desconectar facilmente da plataforma também (quando terminarem as submissões).
Eu criei uma conta e vou passar as credenciais para o Gustavo Carvalho.

**Comment by cecivieira** [comment]
@anadulce tu conseguiu fazer login direto pelo e-mail eventos@python.org.br?
Quando tentei ler o e-mail do Zapier abriu essa tela :
![image](https://user-images.githubusercontent.com/30605862/126650822-0c050dc8-0b31-4539-873d-4a2ec4807e29.png)

**Comment by anadulce** [comment]
Eu não tenho acesso ao e-mail, tanto que não conseguimos testar com o e-mail da PyBR por isso.
Só criei uma conta mesmo. Te passo o acesso via lastpass.
Esse teste que tá rodando tá na conta do @Gabrieltggv.

**Comment by cecivieira** [comment]
Será que @gtsalles pode conectar?
Pra gente fazer os testes usando o e-mail do evento.

**Comment by gtsalles** [comment]
Oi gente. Pra confirmar, alguém de vocês precisa do acesso ao email eventos@python.org.br?

**Comment by cecivieira** [comment]
@anadulce recebeu as credenciais para acesso direto ao e-mail eventos@

**Comment by cecivieira** [comment]
Configurado. Falta testar @Gabrieltggv

**Comment by cecivieira** [comment]
Configuração concluída com sucesso.
A partir de hoje todas as submissões recebem uma mensagem de confirmaçaõ com o seguinte modelo:

Olá,

Estamos muito alegres por você ter submetido uma atividade para a Python Brasil 2021 \o
Na segunda quinzena de agosto você receberá algumas atividades para avaliar. Fica de olho por aqui.
----------
Informações da atividade submetida:

Título:  "{{128699980__COL$X}}{{128699980__COL$AG}}{{128699980__COL$AO}}"
Público alvo: " {{128699980__COL$AB}}{{128699980__COL$AH}}{{128699980__COL$AR}}"
Pré-requisitos: "{{128699980__COL$AC}}{{128699980__COL$AI}}{{128699980__COL$AS}}"
Caso você tenha submetido uma palestra, a duração é de 45 minutos (incluindo tempo para perguntas). Caso tenha sido um tutorial, o tempo que você escolheu foi de "{{128699980__COL$AM}}".
Caso sua submissão foi relativa a Sprint de um projeto de código aberto, o(s) horário(s) selecionado(s) por você foi:  "{{128699980__COL$AW}}"

Conteúdo da atividade:
"{{128699980__COL$AD}}{{128699980__COL$AJ}}{{128699980__COL$AT}}"
Conhecimentos e informações você gostaria de transmitir:
"{{128699980__COL$AE}}{{128699980__COL$AI}}{{128699980__COL$AU}}"
Palavras-chave: "{{128699980__COL$AF}}{{128699980__COL$AL}}{{128699980__COL$AV}}"
