### ISSUE TITLE
Integração de novas voluntárias na organização

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#155]
### Descrição
Integrar novas voluntária sna equipe da organização.

### Requisitos para a atividade ser considerada como concluída

- Escrever roteiro para reunião;
- Agendar reunião.

**Comment by cecivieira** [comment]
Roteiro escrito por mim e @anadulce 

https://docs.google.com/document/d/1tbib42s2jKwA5NjHGxJYoIZJW1X9-1mWgJJg8ndaRj0/edit?usp=sharing

**Comment by gabubellon** [comment]
@cecivieira @anadulce  isso já está ok não ?

**Comment by cecivieira** [comment]
Está sim.
