### ISSUE TITLE
Divulgação do plano de patrocínio

### ISSUE THREAD

**Issue by deboraazevedo** [pythonbrasil/pybr2021-org#158]
### Campanha
Divulgação de patrocínio
  
### Peça/publicidade solicitada
Cartão para divulgar o plano de patrocínio

### Detalhamento do uso
Cartão de chamada para empresas patrocinarem a PyBR

### Data prevista para uso da arte
05 ago 2021

### Quais informações devem aparecer na arte
Vem conhecer nosso plano de patrocínio

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Está duplicado (issue #116) @cecivieira @deboraazevedo

**Comment by cecivieira** [comment]
Fechei a anterior

**Comment by cmdiasbr** [comment]
![Cards](https://user-images.githubusercontent.com/45003095/127706056-d26d3e4b-44f9-4f93-aa2e-5bb6b7e14a5c.png)


https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

**Comment by cecivieira** [comment]
Postado

https://www.instagram.com/p/CSFcJGttHUA/
https://twitter.com/pythonbrasil/status/1422289749075705857
https://www.linkedin.com/feed/update/urn:li:activity:6828054952540176384
