### ISSUE TITLE
Enfatizar diversidade das atividades (níveis técnico, público alvo)

### ISSUE THREAD

**Issue by deboraazevedo** [pythonbrasil/pybr2021-org#159]
### Campanha
 Inscrições para evento 

### Peça/publicidade solicitada
Cartão incentivando a submissão de atividades diversas (em temáticas e níveis de conhecimento)

### Detalhamento do uso
Arte usada para o incentivo para a submissão de atividades diversas

### Data prevista para uso da arte
07 ago 2021

### Quais informações devem aparecer na arte
Temos espaço para a sua atividade na PyBR!

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
![Cards (1)](https://user-images.githubusercontent.com/45003095/127585788-ad6f1b3d-fa18-4586-bcb6-7e233ece5e33.png)


Para tradução: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

**Comment by cecivieira** [comment]
Versão em espanhol
https://www.canva.com/design/DAEloufMqdM/share/preview?token=OrE09zDsOky8usKp-wFSCA&role=EDITOR&utm_content=DAEloufMqdM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by alynnefs** [comment]
Submissões encerradas

**Comment by alynnefs** [comment]
Mudar o texto de submissão para inscrição

**Comment by cecivieira** [comment]
@deboraazevedo @paulohenriquedsgn troquei a mensagem da arte para ser usada na abertura das inscrições
