### ISSUE TITLE
Abertura das inscrições para a Python Brasil

### ISSUE THREAD

**Issue by deboraazevedo** [pythonbrasil/pybr2021-org#161]
### Campanha
Inscrições para evento
  
### Peça/publicidade solicitada
Cartão para divulgar a abertura das inscrições

### Detalhamento do uso
Cartão para divulgar que as incrições da PyBR2021 estão abertas

### Data prevista para uso da arte
ago 2021

### Quais informações devem aparecer na arte
Inscrições abertas

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
![Cards](https://user-images.githubusercontent.com/45003095/127242769-469c4086-b13b-4207-863a-939bc26c7181.png)

**Comment by cmdiasbr** [comment]
Tem uma issue #63, verificar isso

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/128344325-fab88a08-e020-4827-a4f8-42e9d4a9062c.png)

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/131517567-9313f75f-3f44-472a-b085-143de467bfd3.png)

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/131517595-77634c09-c7be-41b2-ac66-ce4386e57e70.png)

**Comment by cecivieira** [comment]
Link para formulário de inscrição:
https://www.eventbrite.com.br/e/python-brasil-2021-registration-169078058023

Artes em português: 
https://www.canva.com/design/DAEjPWNunB0/share/preview?token=iHxtxgtxfLnVmOwj8hToDg&role=EDITOR&utm_content=DAEjPWNunB0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Artes em espanhol:
https://www.canva.com/design/DAEloufMqdM/share/preview?token=OrE09zDsOky8usKp-wFSCA&role=EDITOR&utm_content=DAEloufMqdM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by cecivieira** [comment]
Primeira postagem agendada para amanhã (09/09) às 17h05.

**Comment by cecivieira** [comment]
Seria interessante agendar as demais chamadas para as semanas subsequentes

**Comment by cecivieira** [comment]
Agendada todas as postagens relacionadas a inscrições no evento
