### ISSUE TITLE
Arte para o Código de conduta

### ISSUE THREAD

**Issue by paulohenriquedsgn** [pythonbrasil/pybr2021-org#162]
### Campanha
*Código de conduta*
  
### Peça/publicidade solicitada
*Cartões para divulgação de 4 posts sobre o código de conduta do evento*

### Detalhamento do uso
Artes serão utilizadas para:
 - Divulgar código de conduta do evento
 - Principais pontos do código de conduta
 - Como reportar violação do código
 - Punições do código de conduta

### Data prevista para uso da arte
*Informe a data ou período previsto para uso da arte*

### Quais informações devem aparecer na arte
*Informe as informações que você imagina que deva conter na arte*

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
![código de conduta - PYBR2021](https://user-images.githubusercontent.com/45003095/127584336-c232b0a3-b9cd-448e-ba95-e4d975a982ec.png)


As 4 páginas estão aqui: https://www.canva.com/design/DAEloILxFtA/zz-Di8P8OO7ut5aAFxb8xA/edit

**Comment by paulohenriquedsgn** [comment]
@cecivieira as voluntárias poderiam providenciar a tradução, por favor.

**Comment by cecivieira** [comment]
Feito
![image](https://user-images.githubusercontent.com/30605862/128511039-9324a53c-c28d-4da5-bcc5-e8f62c18c9b1.png)

**Comment by cecivieira** [comment]
Link  direto para o Código:

https://python.org.br/cdc/

--------
PS: estou sentidno falta de ter link nas postagens, por exemplo: na postagem para lembrar que o prazo está acabando, não tem link para o formulário de submissões.

Talvez seja importante toda postagem ter link direto para o que está tratando ou para o nosso site. https://2021.pythonbrasil.org.br

**Comment by cmdiasbr** [comment]
> Feito
> ![image](https://user-images.githubusercontent.com/30605862/128511039-9324a53c-c28d-4da5-bcc5-e8f62c18c9b1.png)

Lembrando que são 4 posts. Mas aí não sei como vocês irão postar isso. E os demais posts dá pra copiar o código de conduta em espanhol que tem no site, né?

**Comment by cmdiasbr** [comment]
@cecivieira @deboraazevedo @paulohenriquedsgn

**Comment by alynnefs** [comment]
@cmdiasbr fica muito poluído colocar em alguma das imagens o e-mail que vai ser usado para possíveis denúncias? no documento tem o cdc@.., o contato@.. e também vai ter o meu, mas talvez seja legal ter um e-mail de fácil acesso

**Comment by cecivieira** [comment]
Por ser um conjunto de imagens, acredito que nesse caso deveríamos ter 2 carrosseis no Instagram: 1 em português e outro em espanhol.

---------------



![image](https://user-images.githubusercontent.com/30605862/129355501-37dff28b-678f-4b65-b7c7-b97d1fcc7200.png)
![image](https://user-images.githubusercontent.com/30605862/129355514-069dfea3-549b-44f1-a431-b197d02a1824.png)
![image](https://user-images.githubusercontent.com/30605862/129355521-015d1349-caf4-4a1a-8099-e3b43dcc679e.png)
![image](https://user-images.githubusercontent.com/30605862/129355530-32b57f05-dfa5-41be-bdd8-2812aa37b832.png)

**Comment by alynnefs** [comment]
instagram
pt - https://www.instagram.com/p/CTPa7eYgUcj/
es - https://www.instagram.com/p/CTPhN9Zganz/

twitter
pt - https://twitter.com/pythonbrasil/status/1432689847853010967

linkedin
pt - https://www.linkedin.com/feed/update/urn:li:activity:6838455544164978688/

**Comment by deboraazevedo** [comment]
Facebook
pt https://www.facebook.com/pythonbrasil/posts/4605822326106923
es https://www.facebook.com/pythonbrasil/posts/4605965316092624

**Comment by alynnefs** [comment]
tinha mais algum lugar ou podemos fechar essa issue?

**Comment by cecivieira** [comment]
Pode fechar
