### ISSUE TITLE
Divulgação das atividades (Roda de Diálogo)

### ISSUE THREAD

**Issue by paulohenriquedsgn** [pythonbrasil/pybr2021-org#163]
### Campanha
*Divulgação das atividades (sprint; palestras; tutoriais e keynotes) - Roda de Diálogo*
  
### Peça/publicidade solicitada
*Cartão para divulgar a roda de diálogo*

### Detalhamento do uso
Conjunto de 5 cartões para divulgação da roda de diálogo:
- 1 roda de diálogo
- 2 roda de diálogo
- 3 roda de diálogo
- 4 roda de diálogo
- 5 roda de diálogo

### Data prevista para uso da arte
*Informe a data ou período previsto para uso da arte*

### Quais informações devem aparecer na arte
*Informe as informações que você imagina que deva conter na arte*

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Os 5 cards estão aqui: https://www.canva.com/design/DAEpGpsUBSY/NQOtQoOWLheqcyAhmnF3Dg/edit

É esperado que seja feito otimização nessas artes.

**Comment by deboraazevedo** [comment]
aveeeeee estao lindas demais!

**Comment by deboraazevedo** [comment]
![IMG_20210130_141455](https://user-images.githubusercontent.com/5026063/136447569-0d46720b-646b-48a9-ab0f-e36a82db03c3.jpg)
![photo5091689150112967033](https://user-images.githubusercontent.com/5026063/136447591-b9225b73-3a6f-4fc5-b43b-6a527aff953f.jpg)
![Christiane02](https://user-images.gi
![kardec](https://user-images.githubusercontent.com/5026063/136447830-e9275b17-b2e7-4215-ad59-cf8ebc488d7f.png)
thubusercontent.com/5026063/136447601-1030711f-e123-465c-a3cb-35e50ef5dd34.jpg)

**Comment by anadulce** [comment]
Para a mesa da APyB, eu divulgaria só a logo da associação, e no máximo a imagem do presidente. Assim não temos questões com convidados não confirmados.

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/136667969-ef714559-73df-4041-aea0-373b5d507686.png)

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/136668217-63f716a6-5253-424e-b6ff-035a20ebfe72.png)
![image](https://user-images.githubusercontent.com/30605862/136668225-5adb36d2-18b1-4fbb-952c-9e3b39b0e507.png)
![image](https://user-images.githubusercontent.com/30605862/136668230-2bcf9e7a-5ce0-41d3-8482-1749d1a79a8a.png)

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/136668726-d1311b99-d21e-42c1-b878-ee39de4fb109.png)
A importância da associação/associados e a comunidade na pandemia
![image](https://user-images.githubusercontent.com/30605862/136668754-5697a04e-b555-47fb-acde-bbe98a1f3ed9.png)

@deboraazevedo @dandaramcsousa agenda essas postagens das rodas de dados abertos e apyb, por favor

**Comment by Flaviasv** [comment]
@deboraazevedo  resumo da roda de conversa sobre dados abertos:

Vamos falar sobre a importância dos dados abertos e como eles podem influenciar na sociedade e na comunicação, promovendo o empoderamento e controle social através da  transparência. Além disso, nossos convidados vão abordar os impactos de inovações cívicas e da cultura de dados no contexto atual e seus possíveis desdobramentos.
