### ISSUE TITLE
Divulgação das atividades (Programação das trilhas)

### ISSUE THREAD

**Issue by paulohenriquedsgn** [pythonbrasil/pybr2021-org#164]
### Campanha
Divulgação das atividades (Divulgação da programação da trilha)
  
### Peça/publicidade solicitada
Cartões para divulgação da programação das trilhas

### Detalhamento do uso
Conjunto de 5 cartões para divulgação da programação das trilhas:
- Trilha 1
- Trilha 2
- Trilha 3
- Trilha 4
- Trilha 5

### Data prevista para uso da arte
*Informe a data ou período previsto para uso da arte*

### Quais informações devem aparecer na arte
*Informe as informações que você imagina que deva conter na arte*

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Gostaria de mais detalhes para realizar essa arte.
Qual é a diferença entre essa issue e a issue #163?

Quais informações devem aparecer na arte?

@cecivieira @paulohenriquedsgn @deboraazevedo

**Comment by cecivieira** [comment]
@cmdiasbr a virada issue refere-se as rodas de conversas, que ocorre nas manhãs de segunda a sexta.

Essa isso daqui são para divulgar as trilhas, que ocorrem a tarde e simultaneamente. 

Vou dá uma olhada nas artes que já existem e volto aqui pra dar pitaco.

**Comment by cecivieira** [comment]
O que eu imagino nessa arte é algo como:

Hoje na trilha Xxxx:

Quadro da programação


Deixa sair a programação que a gente reavalia se teremos braços para fazer 20 cartões desse, cada 1 referente a cada dia em cada trilha

**Comment by cmdiasbr** [comment]
Vou deixar como bloqueado por enquanto então.

**Comment by deboraazevedo** [comment]
de acordo com o que rolou no ano anterior, tem foto do palestrante e o título da palestra

**Comment by cecivieira** [comment]
@deboraazevedo são duas issues diferentes. A das facilitadoras é a issue #86
