### ISSUE TITLE
Relembrar que as inscrições estão abertas

### ISSUE THREAD

**Issue by deboraazevedo** [pythonbrasil/pybr2021-org#165]
### Campanha
Inscrições para evento
  
### Peça/publicidade solicitada
Relembrar que as inscrições estão abertas

### Detalhamento do uso
Cartão para relembrar que as inscrições estão abertas e incentivando pra se inscrever

### Data prevista para uso da arte
set 2021

### Quais informações devem aparecer na arte
Já se inscreveu para a Python Brasil?

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
https://user-images.githubusercontent.com/45003095/127586190-efbdcea7-0235-4337-9a29-50873d5c6648.mp4

Para tradução: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit
Formato da postagem: .mp4

**Comment by cecivieira** [comment]
QUE AMOOOORRRRRRRR!!!! <3 <3

**Comment by cecivieira** [comment]
versão em espanhol
https://www.canva.com/design/DAEloufMqdM/share/preview?token=OrE09zDsOky8usKp-wFSCA&role=EDITOR&utm_content=DAEloufMqdM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/128344375-a3b16e0d-2bc1-42d7-9adc-f30f6e5eef27.png)

**Comment by cecivieira** [comment]
Link para formulário de inscrição:
https://www.eventbrite.com.br/e/python-brasil-2021-registration-169078058023

Artes em português: 
https://www.canva.com/design/DAEjPWNunB0/share/preview?token=iHxtxgtxfLnVmOwj8hToDg&role=EDITOR&utm_content=DAEjPWNunB0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Artes em espanhol:
https://www.canva.com/design/DAEloufMqdM/share/preview?token=OrE09zDsOky8usKp-wFSCA&role=EDITOR&utm_content=DAEloufMqdM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by cecivieira** [comment]
Agendada todas as postagens relacionadas a inscrições no evento
