### ISSUE TITLE
Decidir brindes para organização e facilitadoras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#166]
### Descrição
Foi acordado que as pessoas da organização e facilitadoras receberão brindes. Será contratada uma empresa para fazer os brindes e realizar o envio. Tendo em vista que os envios serão dentro e fora do país, precisamos pensar em brindes úteis e de pequeno volume.

Essa empresa tem um bom catálogo. Acredito que poderemos nos basear nele para a escolha do brinde (o que não impede que hajam outras sugestões fora desse catálogo):
https://personalbrindesrecife.com.br/novo/product-category/mais-brindes/

### Requisitos para a atividade ser considerada como concluída

- Reunir sugestões de brindes;
- Definir kit/brinde a ser adquirido

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/127084178-0c6f32d4-6e96-4aac-8c7a-6b13a1cf02d1.png)
https://personalbrindesrecife.com.br/novo/product/bloco-de-anotacoes-com-autoadesivos-coloridos-e-caneta/

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/127084202-326f2bde-c03c-4d39-9552-296be1083d6f.png)
https://personalbrindesrecife.com.br/novo/product/caneta-marca-texto-em-formato-de-estrela/

**Comment by leocesar1** [comment]
Olá, gostaria de dar uma sugestão. O que acha do fone para brinde? São 39gramas, talvez o frete não fique caro. 
![image](https://user-images.githubusercontent.com/55844598/127584855-3da00a77-2d5f-46db-8ae4-ad941ef41708.png)
[https://personalbrindesrecife.com.br/novo/product/fone-de-ouvido-bluetooth-com-case-carregador/](https://personalbrindesrecife.com.br/novo/product/fone-de-ouvido-bluetooth-com-case-carregador/)

**Comment by melkibalbino** [comment]
Olá, tudo bem?

Queria deixa minha opinião

Como será um evento focado em python, me pareceu uma boa ideia.

Seria interessante colocar uma arte do evento.

![image](https://user-images.githubusercontent.com/20757437/127718176-1fb39fb8-472c-4a6e-9b88-75e50fbb4a3f.png)



Caneca metálica em inox com detalhes em plástico (Não é térmica).

Capacidade: 400 ml
Personalização: A Laser (Monocromática)
Embalagem: Caixa em papelão
Dimensões: 6,5 cm x 11,5 cm x 8 cm

**Comment by cecivieira** [comment]
Conforme decidido na reunião #201 , será solicitado orçamento para 2 tipos de brindes:
- Caneca de cerâmica com impressão de imagem customizada do evento
- Caderno tamanho A6 com espiral, capa dura e customizada com imagem do evento

**Comment by cecivieira** [comment]
Quantidade: 
250 brindes

**Comment by cecivieira** [comment]
Foi decidido realizar cotação de 2 tipos de brindes: canecas (independe do tipo) e cadernos tamanho A6.
