### ISSUE TITLE
Criar evento "Python Brasil 2021" no Linkedin da Apyb 

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#168]
### Descrição
Criar evento da Python Brasil 2021 no perfil do Linkedin da Apyb (https://www.linkedin.com/company/apyb/).
Obs.: Ainda não temos link para inscrições, então pode ser um ... "inscrições em breve"

### Requisitos para a atividade ser considerada como concluída

- Criação de evento ([orientações](https://www.linkedin.com/help/linkedin/answer/98192/create-or-manage-a-linkedin-event?lang=en))

**Comment by cecivieira** [comment]
@cmdiasbr @martinsvanessa @paulohenriquedsgn 
Vocês poderiam criar a arte para o cabeçalho do evento e postar aqui? O tamanho é 1776 x 444 px

**Comment by cmdiasbr** [comment]
![linkedin-banner](https://user-images.githubusercontent.com/45003095/127232393-6cb6ff4a-11b9-4166-8e49-ddf52792bc85.png)

**Comment by cecivieira** [comment]
Evento criado:
https://www.linkedin.com/events/6826149916117614592/
