### ISSUE TITLE
Coletar informações da JusBrasil

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#169]
### Descrição
Solicita o preenchimento desse formulário para a JusBrasil. Seria interessante o preenchimento até 10 setembro.
https://forms.gle/6Qgf5CSn2WMZt7ZY6

### Requisitos para a atividade ser considerada como concluída
- Formulário preenchido

**Comment by alynnefs** [comment]
@tiidadavena como eu que estava em contato com eles antes, quer que eu envie ou prefere enviar?

**Comment by tiidadavena** [comment]
> @tiidadavena como eu que estava em contato com eles antes, quer que eu envie ou prefere enviar?

Oi, Alynne! Posso enviar sim, só não enviei antes porque estava revisando o Form. Vou enviá-lo amanhã.

**Comment by tiidadavena** [comment]
> > @tiidadavena como eu que estava em contato com eles antes, quer que eu envie ou prefere enviar?
> 
> Oi, Alynne! Posso enviar sim, só não enviei antes porque estava revisando o Form. Vou enviá-lo amanhã.

Form enviado!

**Comment by gabubellon** [comment]
Isso já não está ok ? (já recebemos o patrocínio não)

**Comment by alynnefs** [comment]
@gabubellon, isso é sobre o formulário pra coletar informações, tipo logos, atividades práticas, etc. Eles ainda não responderam, mas como a atividade prática pode ser enviada até um mês antes do evento e eles já receberam o formulário, vou fechar a issue.
