### ISSUE TITLE
Sistema de Avaliação de Atividades

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#17]
Usar o sistema automatizado para distribuição entre os próprios proponentes das submissões para que as atividades sejam avaliadas.

**Comment by cecivieira** [comment]
Seria interessante que o sistema seja em português e espanhol.

Tenho visto a plataforma https://www.papercall.io/ ser usada para submissões e avaliações. A gente já conhece ela e resolvemos criar um sistema próprio?

**Comment by belaaiza** [comment]
O principal motivo de termos feito um sistema próprio no último ano foi pela forma de avaliação que escolhemos (toda pessoa que fez uma submissão avaliou outras três submissões anonimizadas, no final rankeamos as avaliações para escolher as talks). Se formos seguir esse método de novo, acho que podemos usar qualquer plataforma, desde que gere um banco, csv ou  algo do tipo, para que possamos gerar os formulários de avaliação depois (ou uma plataforma que já suporte isso). 

Eu tô na zona rural, mas assim que eu voltar e estiver com uma internet melhor vou dar uma olhada se a plataforma que tu mandou suportaria isso (mas se vcs manjarem, podem dizer aí também haha)

Também podemos usar outro método de avaliação, podemos discutir isso.

Dúvida: essa issue seria uma duplicidade da #75 ou seriam coisas diferentes?

**Comment by belaaiza** [comment]
@cecivieira dado que planejamos a abertura das submissões pra segunda, tô na dúvida se daria tempo de discutir isso, podemos ver na reunião segunda se vale a pena a gente abrir mais tarde pra fazer essa análise, o que tu acha?

**Comment by cecivieira** [comment]
Acredito que é uma duplicidade de issue essa #75 

Esse sistema que falei abre para que as pessoas possam votar nas palestras , então não ficaria restrito as submetedoras. Acho que por conta do nosso tempo, podemos seguir o plano de usar o mesmo sistema do ano passado.

**Comment by belaaiza** [comment]
Tu sabe se dá pra anonimizar as palestras pros votos? Pq ano passado uma coisa que nos levou a não usar votos é que a galera que tem mais popularidade muitas vezes acaba ganhando mais votos por isso. O formulário nos trás mais informações para a avaliação, permitindo uma seleção mais rica, vou deixá-lo aqui, veja se consegue ver: https://docs.google.com/forms/u/1/d/1fjvGxHKR0RWG43kx0GwiIhEpuBpbz3_8B7BqusF9Tu8/edit?usp=drive_web mas com certeza trás uma complexidade junto haha

vou marcar a @anadulce caso ela queira deixar a opinião dela tb sobre isso, como ela contribuiu muito pra criação desse processo de avaliação

**Comment by cecivieira** [comment]
Dá par anonimizar, mas não sei se tem como inserir um formulário de avaliação. Teria que testar a plataforma.

Ana Dulce vai ficar off por uns dias por motivos pessoais. 

Essa imagem é um exemplo de como tá sendo feita a votação na PyLatam:
![image](https://user-images.githubusercontent.com/30605862/125196287-b997b680-e22f-11eb-845a-145c19af97a9.png)

**Comment by cecivieira** [comment]
Issue duplicada. Ver continuação da discussão na #75
