### ISSUE TITLE
Patrocínio com a Buser

### ISSUE THREAD

**Issue by tiidadavena** [pythonbrasil/pybr2021-org#171]
Na última sexta (23/07) recebemos o email de Abraão Buser, sócio de uma empresa chamada "Buser".

Ticket #7038 no Freshdesk

Enviamos a resposta padrão pedindo para agendar uma reunião.

**Comment by tiidadavena** [comment]
Reunião realizada hoje (04/08) com Abraao Barros:

- Esclarecimentos gerais acerca da cota interessada
- Interesse na cota Prata
- Mais de 40 vagas abertas
- Sugestão de grupo no Whatsapp para compartilhar informações com o mkt (mas reforçamos que a comunicação se dará via email)
- Email de retorno com as informações para montar o pré-contrato

**Comment by alynnefs** [comment]
Contrato assinado. Solicitei mais informações para gerar a nota fiscal.

**Comment by alynnefs** [comment]
Vou solicitar a nota fiscal amanhã

**Comment by alynnefs** [comment]
Nota fiscal enviada

**Comment by alynnefs** [comment]
Pagamento recebido
