### ISSUE TITLE
Solicitar as blogueiras para divulgar as Chamadas para Atividades

### ISSUE THREAD

**Issue by paulohenriquedsgn** [pythonbrasil/pybr2021-org#172]
### Descrição
Entrar em contato com blogueiras ou influenciadoras digitais da área de tecnologia e afins para divulgar a chamada de atividades da Python Brasil 2021. Como objetivo de tornar o evento o mais diverso possível, entrar em contato primeiramente com os perfis abaixo.

- Blogueiras ou Influenciadoras Digitais:
- Pessoas da comunidade negra;
- Pessoas da comunidade LGBTQIA+;
- Pessoas da comunidade surda;

Obs.: Esses perfis não são obrigatórios, mas seria interessante buscar primeiro por eles.

### Requisitos para a atividade ser considerada como concluída
- Entrar em contato com as influenciadoras digitais
- Solicitar ou sugerir data para divulgação
- Verificar e registrar data da postagem

### Lista de Influenciadoras (entrar em contato)
- [x]  https://twitter.com/jesstemporal
- [x] https://twitter.com/ananoterminal
- [x]  https://twitter.com/dunossauro
- [x]  https://twitter.com/cuducos
- [x] https://twitter.com/milalaranjeira
- [x]  https://twitter.com/turicas
- [x]  https://twitter.com/juditecypreste
- [x]  https://twitter.com/NaomiCeder
- [x]  https://twitter.com/yaso
- [x]  https://twitter.com/ramalhoorg
- [x]  https://twitter.com/fmasanori
- [x]  https://twitter.com/aterceiro
- [x]  https://twitter.com/LoyanneC

### Lista de Influenciadoras (que postaram)
- [x]  https://twitter.com/jesstemporal
- [x]  https://twitter.com/ananoterminal
- [x]  https://twitter.com/dunossauro
- [x]  https://twitter.com/cuducos
- [ ]  https://twitter.com/milalaranjeira
- [x]  https://twitter.com/turicas
- [x]  https://twitter.com/juditecypreste
- [x]  https://twitter.com/NaomiCeder
- [ ]  https://twitter.com/yaso
- [x]  https://twitter.com/ramalhoorg
- [x]  https://twitter.com/fmasanori
- [x]  https://twitter.com/aterceiro
- [x]  https://twitter.com/LoyanneC

**Comment by cecivieira** [comment]
@paulohenriquedsgn Jéssica Temporal já compartilhou e por esses dias deve tá gravando um vídeo para as nossas redes.

@deboraazevedo abrir issue sobre pedido de vídeo para as influencers

**Comment by carvsmc** [comment]
Já postou até 30/07:
https://twitter.com/jesstemporal
https://twitter.com/cuducos
https://twitter.com/turicas

https://twitter.com/ananoterminal - deu RT
https://twitter.com/NaomiCeder - deu RT
https://twitter.com/ramalhoorg - deu RT
https://twitter.com/fmasanori - deu RT
https://twitter.com/aterceiro - deu RT

**Comment by alynnefs** [comment]
https://twitter.com/juditecypreste 02/08

**Comment by paulohenriquedsgn** [comment]
As blogueiras realizaram a divulgação conforme combinado
