### ISSUE TITLE
Entrar em contato com comunidades da Améria Latina (espanhol)

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#173]
### Descrição
Entrar em contato com "influencers de medias sociais" e comunidades dos países da América Latica que tem como idioma original espanhol.

Mensagem padrão:
```
Hola!

Este año en PyCon Brasil tendremos una sección en español.
Podrías ayudarnos con la difusión para el call to papers? La ideia es que tengamos diversidad en la agenda.

https://twitter.com/pythonbrasil/status/1414630892786552836
https://instagram.com/p/CRPBeQrLjXj/

El evento del último año tuvo alrededor de 45mil asistentes en Youtube. Además, es gratis!
```

### Requisitos para a atividade ser considerada como concluída
- Chegar a 50 submissões em espanhol

**Comment by cecivieira** [comment]
Mensagem padrão:

**Hola!

Este año en PyCon Brasil tendremos una sección en español.
Podrías ayudarnos con la difusión para el call to papers? La ideia es que tengamos diversidad en la agenda.

https://twitter.com/pythonbrasil/status/1414630892786552836
https://instagram.com/p/CRPBeQrLjXj/

El evento del último año tuvo alrededor de 45mil asistentes en Youtube. Además, es gratis!**

**Comment by cecivieira** [comment]
**TWITTER** Flavinha PyLadies Campina Grande

Data science Argentina
Ruta N
Python Bogotá
Pioneras
WWCode Bogotá
Chicas poderosas
Chicas poderosas Argentina
Ada
CoDeAr
Women who choose Buenos Aires
Chicas programando
Chicas en tecnología
Python Colombia
Pyladies Cochabamba
Chicas poderosas Colombia
Media chicas
Pycon Colombia
DjangoGirls Colombia
Python Chile
Pycon Bolivia
Technolatinas oficial
TemachTIani
Women who code cdmx
Girls in tech Ecuador
Ekoparty
Bug bounty space
Latam Dev
Devops uruguay

**Comment by cecivieira** [comment]
En Ecuador, he enviado el mensaje a: @anaranjo494
django girls uio
Rladies Galápagos
 PythonQuito
 RLadies Guayaquil
 RLadies Quito
Women in Data Science Guayaquil 
Red Ecuatoriana de Datos Abiertos y Metadatos
Open Lab Ec
Datalat
Observatorio de la Transformación Digital Ecuador
Pyladies Ecuador
Red Ecuatoriana De Mujeres Cientificas
Python Ecuador
Medialab CIESPAL

**Comment by cecivieira** [comment]
Voy a compartir en las redes que manejo: Karolbot
PyLadies Colombia 
Women in data Science Bogotá 
Python Colombia
Slack Python colombia y Discord de PyLadies Colombia

**Comment by cecivieira** [comment]
Mi lista: Flávia Cardoso (PyLadies Uruguay)
PyLadies Uruguay
Testing UY
Mujeres IT (Uruguay)
R-Ladies Montevideo
Open Web Uruguay
Montevideo Applied Data Science, AI and Big Data
Data Science Buenos Aires
BA Machine Learning
The Montevideo MySQL Meetup Group
The Montevideo Python Meetup Group
R-Ladies Talca
PyMX

**Comment by cecivieira** [comment]
Cris (Python Chile)
enviaré a python en español, python Chile y python España

**Comment by cecivieira** [comment]
Pedido a Lorena (PyLadies Chicago) e Diana (Cotufa / Keynote da PyBr2020)

**Comment by carvsmc** [comment]
Tem uma galera das Geotecnologias que trabalha com Python
Compartilhou nos stories do insta
@geocienciaschile

DM enviada também pra:
GeoLatinas
Pyladies Med - Pyladies en Medellin
