### ISSUE TITLE
Press Release do Evento

### ISSUE THREAD

**Issue by rafpyprog** [pythonbrasil/pybr2021-org#174]
### Campanha
Divulgação da Python Brasil 2021 em portais, blogs, jornais e revistas que realizam cobertura de tecnologia. 
  
### Peça/publicidade solicitada
Criar um texto no formato de Press release (comunicado de imprensa) para divulgação da Python Brasil 2021 em portais e blogs que realizam cobertura de tecnologia.

### Detalhamento do uso
Texto será enviado para publicações que abordem tecnologia/desenvolvimento.

### Data prevista para uso da arte
Durante todo o período pré-evento

### Quais informações devem aparecer na arte
- Dados básicos do evento:  Quem?  O quê?  Onde?  Quando?  Como?  Por quê?
- Tudo que amamos nesse evento: comunidade, ambiente seguro, diversidade, CDC, conteúdo, networking...
- Chamada para submissão de atividades 

### Quais formatos necessários
- [ ] Texto

### Locais para divulgação
- [ ] Blogs
- [ ] Portais de tecnologia/programação
- [ ] Jornais e revistas de alta circulação que possuam sessões sobre tecnologia;

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
@paulohenriquedsgn @deboraazevedo tô marcando para vocês acompanharem , porque são de Comunicação

**Comment by cmdiasbr** [comment]
@cecivieira o que eu tenho que fazer?

**Comment by rafpyprog** [comment]
@cecivieira , @cmdiasbr, @martinsvanessa, @deboraazevedo fiz esse "MVP" do release, para podermos ter um ponto de início discussão e sugestões.  Nunca tinha feito um release então conto com vcs nas sugestões!

# Participe da Python Brasil 2021, a maior conferência de Python da América Latina

***BRASÍLIA, 29 de Julho - Python Brasil 2021, a maior conferência de Python da América Latina, acontecerá entre os dias 11 e 17 de outubro, reunindo desenvolvedoras, cientistas de dados e entusiastas da tecnologia.***


A Python Brasil 2021, evento promovido pela comunidade brasileira de Python, traz nesta edição uma agenda imperdível para quem quer mergulhar em uma das linguagens de programação mais utilizadas na atualidade.

Uma das principais novidades deste ano é a trilha de atividades em espanhol, que vai trazer ao evento participantes de toda a América Latina, criando um ambiente de muita diversidade onde as comunidades Python de língua latina vão poder se conectar e trocar experiências.

Em sua 17 edição, o evento será realizado de forma online, gratuito e aberto para qualquer pessoa de 11 a 17 de outubro. É esperado um público de mais de 10 mil participantes de todas as partes do Brasil e do mundo.

Nos seis dias de imersão, os participantes poderão contribuir para projetos de software livre, participar de treinamentos e adquirir novos conhecimentos com outras pessoas da comunidade.

E que tal falar sobre aquele projeto inovador, dar dicas sobre carreira ou mostrar formas de usar a tecnologia para causar impacto social, tudo isso em um ambiente inclusivo, seguro e acolhedor ? Até o dia 12 de agosto você poderá submeter sua proposta para apresentação de palestras e tutoriais na maior conferência Python da América Latina.

Você poderá acompanhar a Python Brasil pelo YouTube em tempo real e também participar de atividades e interagir com toda a comunidade pelo servidor criado especialmente para o evento no Discord.

 Não deixe de seguir a página do evento no Instagram para ficar por dentro das últimas novidades!

**Comment by cecivieira** [comment]
@cmdiasbr não precisa de arte. Foi atribuido a tu porque tava por padrão, mas ajeitei a atribuição mais cedo.
Se der, dá uma revisada no release do comentáro acima e dá pitaco.

**Comment by cecivieira** [comment]
Fonte dos dados enviado para @rafpyprog :
https://github.com/pythonbrasil/dados

**Comment by cecivieira** [comment]
@rafpyprog Sugestões de alteração:

# Participe da Python Brasil 2021, a maior conferência de Python da América Latina

***BRASÍLIA, 29 de Julho - Python Brasil 2021, a maior conferência de Python da América Latina, acontecerá entre os dias 11 e 17 de outubro, reunindo _pessoas_ desenvolvedoras, cientistas de dados e entusiastas da tecnologia.***


A Python Brasil 2021, evento promovido pela comunidade brasileira de Python, traz nesta edição uma agenda imperdível para quem quer mergulhar _no universo_ em uma das linguagens de programação mais utilizadas na atualidade.

Uma das principais novidades deste ano é a trilha de atividades em espanhol, que vai trazer ao evento _palestras_ de toda a América Latina, criando um ambiente de muita diversidade onde as comunidades Python de língua _espanhola_ vão poder se conectar e trocar experiências.

Em sua 17 edição, o evento será realizado de forma online, gratuito e aberto para qualquer pessoa de 11 a 17 de outubro. É esperado um público de mais de 10 mil participantes de todas as partes do Brasil e do mundo.

Nos _sete_ dias de imersão, os participantes poderão contribuir para projetos de software livre, participar de treinamentos e adquirir novos conhecimentos com outras pessoas da comunidade.

E que tal falar sobre aquele projeto inovador, dar dicas sobre carreira ou mostrar formas de usar a tecnologia para causar impacto social, tudo isso em um ambiente inclusivo, seguro e acolhedor?! Até o dia 12 de agosto você poderá [submeter sua proposta](https://docs.google.com/forms/d/e/1FAIpQLSfXA7KGJbmoE6BHRgWAtK8LlBTEULv8QTS8ffHLIKUgeiLkZA/viewform) para apresentação de palestras e tutoriais na maior conferência Python da América Latina.

Você poderá acompanhar a Python Brasil pelo YouTube em tempo real e também participar de atividades e interagir com toda a comunidade pelo servidor _do Discord_ criado especialmente para o evento.

 Não deixe de seguir o [perfil do evento no Instagram](https://instagram.com/pythonbrasil?utm_medium=copy_link) ou [Twitter](https://twitter.com/pythonbrasil) para ficar por dentro das últimas novidades!

**Comment by cecivieira** [comment]
@deboraazevedo @paulohenriquedsgn algum acréscimo/modificação?

A ideia é começar o contato com os blogs amanhã (31)

**Comment by deboraazevedo** [comment]
Achei massa!

**Comment by cecivieira** [comment]
@rafpyprog fica a vontade para seguir com a atividade.

De normal não precisa de autorização de ninguém para fazer. Eu costumo pedir pitaco para que outras pessoas possam contribuir, daí sugiro o mesmo para todo mundo.

**Comment by rafpyprog** [comment]
> @rafpyprog fica a vontade para seguir com a atividade.
> 
> De normal não precisa de autorização de ninguém para fazer. Eu costumo pedir pitaco para que outras pessoas possam contribuir, daí sugiro o mesmo para todo mundo.

Blz! É sempre bom ouvir mais opiniões  para garantir aderência à proposta do evento e da comunidade.

**Comment by rafpyprog** [comment]
# Lista dos veículos de comunicação contactados

|Data             | Nome                                                            |
|-----------------|-----------------------------------------------------------|
| 2020-08-02 | [Tecmundo](https://www.tecmundo.com.br)  |
