### ISSUE TITLE
Definir área social a ser beneficiada pela arrecadação realizada via doação

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#176]
### Descrição
Na issue #69 ficou decidido que o evento arrecadá doações em dinheiro que serão completamente revertidas para instituição(ões) sem fins lucrativos que desenvolva trabalho social. Agora, é necessário definir qual a área que será beneficiária.

### Requisitos para a atividade ser considerada como concluída
- Coletar sugestão de áreas;
- Definir área a ser beneficiáda

**Comment by cecivieira** [comment]
**Segurança alimentar (fome)**

A razão de indicar esse tema é devido ao nosso país ter voltado para o mapa da fome e temos em torno de 50% da população em algum nível de insegurança alimentar, sendo 9% estando em completa escacez de alimento. 
Sendo alimentação uma necessidade primária e um tema de sobrevivência, acredito que deveríamos direcionar a arrecadação para ONGs que trabalhe nesse sentido.

Esse episódio traz um bom panorama atual:
https://open.spotify.com/episode/7bJBIzJ4R1VTLrMo6wkWMw?si=9d73370dfa23470e

Links citados durante o episódio e para as pessoas entrevistas:
https://www.nexojornal.com.br/podcast/2021/07/29/Como-efetivamente-ajudar-quem-tem-fome

**Comment by alynnefs** [comment]
Segurança alimentar escolhida
