### ISSUE TITLE
Atualizar script que gera a alocação de palestras e avaliadores

### ISSUE THREAD

**Issue by belaaiza** [pythonbrasil/pybr2021-org#177]
### Descrição
É necessário atualizar o script do ano passado que foi utilizado para alocar cada palestra a três pessoas avaliadoras. No ano passado, para cada submissão que a pessoa fazia, ela deveria avalir três submissões de outras pessoas, dessa forma, o script funciona de modo que nenhuma avalie a mesma palestra e também não avalie palestras repetidas.

Para esse ano, precisamos adaptar no script:
- A limpeza da planilha de acordo com o formato utilizado esse ano
- O incremento utilizado para garantir um autor nunca corrija a própria palestra

### Requisitos para a atividade ser considerada como concluída

- Código disponível para execução e testado com dados no formato da planilha de respostas desse ano

**Comment by rougeth** [comment]
Adicionando um requisito:
- Documentar como script funciona e como usá-lo

**Comment by belaaiza** [comment]
Scripts no repositório do projeto com documentação sobre como usar no README https://github.com/pythonbrasil/pybr2021-org/tree/main/scripts
