### ISSUE TITLE
Atualizar script de ranqueamento das submissões com base nas avaliações

### ISSUE THREAD

**Issue by belaaiza** [pythonbrasil/pybr2021-org#178]
### Descrição
Após termos todas as avaliações das palestras, precisamos ranqueá-las com base nessas avaliações e nos pesos que definimos para selecioná-las.

Ano passado foi utilizado um script feito pela @anadulce, precisamos analisar se precisaremos modificar este script e se sim, levantar as modificações necessárias.

### Requisitos para a atividade ser considerada como concluída

- Código do script pronto para ser executado

**Comment by rougeth** [comment]
Adicionando um requisito:
- Documentar como script funciona e como usá-lo

**Comment by cecivieira** [comment]
Considerar que as pessoas que avaliem as atividades a contento terá pontuação extra 

![image](https://user-images.githubusercontent.com/30605862/127896405-1bb69ae5-2697-4b83-aa7a-901be44e62c2.png)

**Comment by exageraldo** [comment]
Gostaria de ajudar nessa automação.

**Comment by cecivieira** [comment]
@belaaiza como tá o desenvolvimento dessa atividade?
Se estiver concluída, por favor, coloca o link para o repositório do script aqui e fecha a issue

**Comment by belaaiza** [comment]
@cecivieira eu não tenho esse script :( ano passado foi a @anadulce que fez

@anadulce tu sabe como tá? vamos reaproveitar ou fazer outro?

**Comment by anadulce** [comment]
@belaaiza e @cecivieira vai ter que fazer outro, porque mudamos os objetivos que foram definidos ano passado.

**Comment by cecivieira** [comment]
@anadulce o script será publicado no github?
Se sim, poderia colocar o link aqui e fechar a issue?

**Comment by alynnefs** [comment]
@belaaiza o script foi publicado? tem como anexar o link aqui?

**Comment by alynnefs** [comment]
@anadulce o script foi publicado? tem como anexar o link aqui?

**Comment by cecivieira** [comment]
@alynnefs dado que não temos resposta nessa issue (@anadulce ) desde outubro, acredito que ela pode ser fechada e dada como não concluída.

**Comment by cecivieira** [comment]
Esse script não foi localizado. Devido s isso essa issue não tem resolução e será fechada.
