### ISSUE TITLE
Atualizar script para consolidação das avaliações das submissões

### ISSUE THREAD

**Issue by belaaiza** [pythonbrasil/pybr2021-org#179]
### Descrição
Como os formulários das avaliações são anonimizados, nas planilhas de respostas não temos a quem pertence a submissão, dessa forma, no ano passado usamos um script que obtia o nome e e-mail da pessoa dona da submissão através do título da palestra, cruzando com as informações da planilha de submissões.

Este script também foi utilizado para unificar todas as respostas, uma vez que foi gerada uma planilha pra cada formulário de avaliação.

Além disso, o script também fecha o formulário para que ele não possa receber mais respostas.

### Requisitos para a atividade ser considerada como concluída

- Código disponível para execução e testado com dados no formato desse ano
- Documentar como script funciona e como usá-lo

**Comment by belaaiza** [comment]
Atualizei o script que gera os forms para já submeter as respostas para uma planilha unificada. Posso criar um trigger para fechar os formulários após a data que fecham as submissões, o que acham?

Se fizermos isso, não precisaremos do script de consolidação, uma vez que só restaria o cruzamento das informações que dá pra fazer pelo próprio Google Sheets com o QUERY (que é o que o script faz no fim das contas)

**Comment by cecivieira** [comment]
@belaaiza essa atividade está concluída?
Se sim, por favor, posta o link pro repositório e fecha a issue.

**Comment by belaaiza** [comment]
não, ainda preciso terminar a documentação de como usar os scripts

**Comment by cecivieira** [comment]
@belaaiza o script será publicado no github?
Se sim, poderia colocar o link aqui e fechar a issue?

**Comment by alynnefs** [comment]
@belaaiza colocou o script em algum repositório? pode enviar aqui?

**Comment by cecivieira** [comment]
@alynnefs dado que não temos resposta nessa issue (@belaaiza ) desde outubro, acredito que ela pode ser fechada e dada como não concluída.
