### ISSUE TITLE
Definir rodas de conversa

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#18]
### Descrição
Decidir rodas de conversa e seus participantes. Para isso, é necessário que as sugestões estejam escritas [nesta planilha](https://docs.google.com/spreadsheets/d/1UB_HR0z9oZ-_Il1AMhmpJPT0cUYH1epnmWnpV4T_xoM/edit?usp=sharing)

### Requisitos para a atividade ser considerada como concluída

- Temas e pessoas escolhidos
- Pessoas convidadas

**Comment by alynnefs** [comment]
@cecivieira, tem alguma sugestão de pessoas ou organizações pra falar de dados abertos?

**Comment by cecivieira** [comment]
Convidei @anicelysantos para me ajudar a construir essa mesa.

**Comment by cecivieira** [comment]
Foi inicada a organização da roda de diálogo sobre Dados Abertos na issue #202

**Comment by cecivieira** [comment]
@gabubellon https://docs.google.com/spreadsheets/d/1UB_HR0z9oZ-_Il1AMhmpJPT0cUYH1epnmWnpV4T_xoM/edit#gid=0
Planilha das rodas

**Comment by cecivieira** [comment]
Convidar todo mundo da roda até dia 11 setembro

**Comment by gabubellon** [comment]
Convites para mesa de Educação não fomal enviados e 90% respondidos

**Comment by alynnefs** [comment]
@gabubellon, acha melhor a roda de educação não formal ser na quinta (14) ou sexta (15)?
