### ISSUE TITLE
Parceria com a Todas as Letras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#180]
### Descrição
Decidir sobre parceria com a ONG "Todas as Letras" para que eles entrem como apoiadores da Python Brasil e em consequência divulguem o evento. Todas as Letras é um ONG que trabalha inserindo pessoas LGBTI+ na área de tecnologia.
https://www.todasasletras.org/

### Requisitos para a atividade ser considerada como concluída

- Decidir sobre parceria

**Comment by cecivieira** [comment]
Verificar possibilidade de parceria para divulgação de peças do evento em contrapartida a empresa ter sua logo no site do evento na área "empresas parceiras"

**Comment by tiidadavena** [comment]
Vocês poderiam inserir aqui o texto da sugestão de parceria?

**Comment by paulohenriquedsgn** [comment]
Entrei em contato com o Vitor, responsável pela comunicação e a parceria foi fechada, abaixo tem a resposta do instagram com o material para ser enviado: 

"Geralmente os eventos mandam o material que divulgamos
E também mandamos nossos logos para sair nas artes e site como apoio"

O material e a formalização da parceria será realizada por e-mail para o endereço lgbtiintech@gmail.com

**Comment by cecivieira** [comment]
@paulohenriquedsgn @anadulce 
A gente tem escrito os e-mails nas issues antes de mandar, assim as pessoas podem pitacar.
Podemos fazer o mesmo sobre essa parceria.

**Comment by eloabe** [comment]
Posso escrever o e-mail, só preciso de uma orientação sobre o que precisa ter nele. 

Existe algum modelo? Procurei, mas não encontrei.

**Comment by cecivieira** [comment]
@eloabe tu não precisa escrever o e-mail. Te marquei aqui porque soubemos que tas mais próximo da ONG, então pode dá uma ajuda na revisão do texto. =D

**Comment by paulohenriquedsgn** [comment]
Modelo de e-mail (aguardo revisão) para fechamento da parceria e solicitação de material gráfico:


Olá pessoal do Todas as Letras, tudo bem? 

Em primeiro lugar, gostaríamos de agradecer ao Todas as Letras por apoiar o Python Brasil 2021!

Recentemente nossa equipe de comunicação entrou em contato com vocês via instagram sobre a proposta de apoio ao nosso evento por parte do Todas as Letras. Como um dos objetivos do nosso evento é torná-lo o mais diverso possível, achamos interessante propor essa parceria com o Todas as Letras até como forma de fortalecer a comunidade.

O Lucas, Diretor de Comunicação, nos informou o processo de parceria e nos deu uma resposta positiva para prosseguimos com com o mesmo. Conforme combinado via instagram ficamos de formalizar a parceria através de e-mail. Foi definido até o momento que as ambas as organizações teriam essas responsabilidades:

Python Brasil
- Inserir a Todas as Letras como apoiadora em nosso site;

Todas as Letras
- Divulgação do evento Python Brasil 2021;

Com isso definimos essas responsabilidades, mas sintam-se à vontade para alguma alteração ou sugestão com relação a nossa parceria. Aproveito também para solicitar o material gráfico (logo) para que possamos inserir em nosso site. Caso haja mais alguma dúvida ou sugestão não hesitem em nos procurar.

A Python Brasil 2021 agradece mais uma vez a disponibilidade como também o apoio para divulgação do nosso evento.

**Comment by paulohenriquedsgn** [comment]
@tiidadavena @cecivieira @osantana @eloabe pessoal segue o texto da parceria, se puderem dar uma olhada por favor, fiquem livres para editar ou dar sugestões

**Comment by cecivieira** [comment]
@paulohenriquedsgn Quais os canais que a ONG fará a divulgação?
Se já tiver sido acordado, seria interessante explicitar. Caso contrário, cabe perguntar detalhes sobre como será feita a divulgação por parte da ONG.

**Comment by gabubellon** [comment]
#182

**Comment by paulohenriquedsgn** [comment]
@cecivieira entrei em contato com o pessoal hoje e eles responderam que a divulgação será realizada nas redes sociais do Todas as Letras e também nos grupos privados que eles fazem parte. A Todas as Letras possui perfis no Twitter, Instagram, Facebook, Linkedin. Telegram.

**Comment by cecivieira** [comment]
Sugestão de redação:

"
Olá pessoal do Todas as Letras, tudo bem?

Em primeiro lugar, gostaríamos de agradecer ao Todas as Letras por apoiar o Python Brasil 2021!

Recentemente nossa equipe de comunicação entrou em contato com vocês via instagram sobre a proposta de apoio ao nosso evento por parte do Todas as Letras. Como um dos objetivos do nosso evento é torná-lo o mais diverso possível, achamos interessante propor essa parceria com o Todas as Letras até como forma de fortalecer a comunidade.

O Lucas, Diretor de Comunicação, nos informou o processo de parceria e nos deu uma resposta positiva para prosseguimos com com o mesmo. Conforme combinado via instagram ficamos de formalizar a parceria através de e-mail. Foi definido até o momento que as ambas as organizações teriam essas responsabilidades:

Python Brasil

    Inserir a Todas as Letras como apoiadora em nosso site;

Todas as Letras

    Divulgação do evento Python Brasil 2021 nas suas redes sociais (Twitter, Instagram, Facebook, Linkedin) e grupos privados (Telegram);

Com isso definimos essas responsabilidades, mas sintam-se à vontade para alguma alteração ou sugestão com relação a nossa parceria. Aproveito também para solicitar o material gráfico (logo) para que possamos inserir em nosso site. Caso haja mais alguma dúvida ou sugestão não hesitem em nos procurar.

A Python Brasil 2021 agradece mais uma vez a disponibilidade como também o apoio para divulgação do nosso evento.
"

**Comment by paulohenriquedsgn** [comment]
Creio que ficou bem amarrado agora @gabubellon @tiidadavena @eloabe vocês tem alguma sugestão? Ou podemos seguir com esse texto?

**Comment by paulohenriquedsgn** [comment]
Realizado o envio do e-mail e aberto o ticket 7134 no freshdesk, estamos aguardando a resposta.

**Comment by alynnefs** [comment]
Logos enviadas
