### ISSUE TITLE
Pedir para as empresas patrocinadoras incentivarem seus funcionários a submeterem palestras

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#181]
### Descrição

Pedir ajuda às empresas patrocinadoras para que seus funcionários submetam palestras, com o conteúdo não focado na empresa e sim em alguma tecnologia usada ou simplesmente outro conteúdo relacionado.

### Requisitos para a atividade ser considerada como concluída

- E-mail enviado às empresas

**Comment by tiidadavena** [comment]
Segue modelo de texto a ser enviado:

`Bom dia!

As submissões para palestras e atividades para a Python Brasil se encerram no próximo dia 12/08 :D

Apoiamos a diversidade de conteúdos e que as empresas patrocinadoras e apioadoras.

Se tiver aquela ideia engavetada, estudo de caso, uma nova biblioteca, e palestras não técnicas com tópicos sobre carreira e crescimento!

Seguem links dos posts para divulgação entre seus colaboradores e demais funcionários:

https://www.instagram.com/p/CRXcNzYjOmt/
https://twitter.com/pythonbrasil/status/1414599195307257856
`

**Comment by cecivieira** [comment]
Sugestão:

_Bom dia!

As submissões para palestras e atividades para a Python Brasil se encerram no próximo dia 12/08 :D

Gostaríamos do apoio das empresas patrocinadoras no sentido de divulgar junto às suas equipes a chamada para as submissões de atividades.

Se tiver aquela ideia engavetada, estudo de caso, uma nova biblioteca, e palestras técnicas e não técnicas, com tópicos sobre carreira e crescimento. Vem submeter uma proposta!

Seguem links dos posts para divulgação entre as equipes:

https://www.instagram.com/p/CRXcNzYjOmt/
https://twitter.com/pythonbrasil/status/1414599195307257856_

**Comment by tiidadavena** [comment]
Email disparado para as empresas patrocinadoras.
