### ISSUE TITLE
Definir participação no podcast Hipster

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#183]
Autor: @rafpyprog
### Descrição
Mandei mensagem pro Paulo (CEO da Alura) pedindo pra fazer um episódio no Hipsters sobre a PyBr e ele topou. [Precisamos definir tema para o episódio e pessoas a serem entrevistadas].

### Requisitos para a atividade ser considerada como concluída
- Definir tema;
- Convidar pessoas para serem entrevistadas

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/128054986-0b919c74-f914-432e-9439-6448b2c2cbdb.png)

**Comment by cecivieira** [comment]
Sobre o tema do hipsters acho que um bom assunto séria algo como "Vida de Dev Python no Brasil", poderíamos falar sobre a comunidade, mercado de trabalho, diversidade e claro sobre a PyBr

Poderíamos escalar alguém das antigas (#soufãdatania) e alguém das Pyladies... história, inovação, liderança e inclusão... pacote completo !
O que acham ?

**Comment by cecivieira** [comment]
@alynnefs @anadulce

**Comment by rafpyprog** [comment]
Minhas sugestões, depende claro das pessoas toparem...

- Luciano Ramalho
- Tânia Andrea
- Débora Azevedo

**Comment by gabubellon** [comment]
Acho que tem bastante gente da comunidade tem uma carreira bem consolidada, acho que a ideia de "Vida de Python" é uma boa. Da pra puxar a parte de comunidade com educação (Massanori, Ramalho, Dussauro). Da pra mostrar o trabalho cívico que vai e volta  dentro da comunidade  (Turicas, Mario, Cuducos). Da pra mostrar o caminho da PyLadies (tem várias fellow da PSF e gente no Board né :D)

**Comment by gabubellon** [comment]
Um ponto legal, talvez seja um bom conteudo pro Hipster On the Road que é um podcast mais focado em comunidade

**Comment by alynnefs** [comment]
Sei que ele pediu pra não focar no evento, mas se a ideia era chamar gente, talvez seja bom pelo menos deixar isso alinhado com as pessoas. Ou até mesmo convidar pessoas de organizações passadas

**Comment by cecivieira** [comment]
Resumindo o que entendi:

Episódio de Hipster On the Road
Data: setembro
Tema: "Vida de Dev Python no Brasil"
Convidadas: 

| pilar |  pessoa a ser convidada| 
| -- | -- | 
| mercado de trabalho | | 
| educacao | | 
| tecnologia civica| | 

Acho que se for 2 mulheres e 1 cara fica equilibrado o episódio, já que as hosts são homens.

Sugestões de preenchimento dessa tabela?

**Comment by anadulce** [comment]
Pedimos para participar do podcast para fins de divulgar o evento e não acho muito certo legar a responsabilidade de fazer essa contextualização para pessoas de fora da organização. Por mais que a gente tenha uma comunidade maravilhosa, acho problemático onerar sempre as mesmas pessoas (porque são sempre as mesma pessoas que contatamos).
Se for pra fazer, sugiro principalmente focar em gente da organização que tenha interesse e disposição.
Uma pessoa que eu acho que arrasaria nesse podcast seria o @GabrielRF :)

**Comment by cecivieira** [comment]
Pensando que não será um episódio sobre o evento, mas sobre Python nesses 3 piolares. Acho tranquilo mesclar pessoas de dentro e fora da organização. Além disso, concordo demais que precisamos colocar em foco outras pessoas mais da comunidade.

Sugiro @ArianeCamilo para falar sobre tecnologias cívicas

Alguém com sugestão de mulher que trabalha com Educação/produção de conteúdo python?

------------

Resumo

Episódio de Hipster On the Road
Data: setembro
Tema: "Vida de Dev Python no Brasil"
Convidadas: 

| pilar |  pessoa a ser convidada| 
| -- | -- | 
| mercado de trabalho |@GabrielRF | 
| educacao | | 
| tecnologia civica|@ArianeCamilo | 

Acho que se for 2 mulheres e 1 cara fica equilibrado o episódio, já que as hosts são homens.

**Comment by gabubellon** [comment]
@cecivieira  desculpa a duvida , mas seguindo o comentário a @anadulce , a @ArianeCamilo está na organização ?

**Comment by cecivieira** [comment]
@gabubellon ela não está na organização. Indiquei no sentido de combinar gente de dentro e fora da organização:
"Acho tranquilo mesclar pessoas de dentro e fora da organização.¨

**Comment by gabubellon** [comment]
Vou lançar a minha então:

-----------

Resumo

Episódio de Hipster On the Road
Data: setembro
Tema: "Vida de Dev Python no Brasil"
Convidadas: 

| pilar |  pessoa a ser convidada| 
| -- | -- | 
| mercado de trabalho |@GabrielRF | 
| educacao | @deboraazevedo  | 
| tecnologia civica|@ArianeCamilo |

**Comment by cecivieira** [comment]
@gabubellon Tu foi mais rápido do que eu.. heheheh
Ia dar o pitaco de Thais Viana para falar de educação.

Fica como mais uma sugestão

**Comment by gabubellon** [comment]
> @gabubellon Tu foi mais rápido do que eu.. heheheh
> Ia dar o pitaco de Thais Viana para falar de educação.
> 
> Fica como mais uma sugestão

Acho que podemos criar várias versões de cast pra termos opções (e nada impede de ser 3 só :D)

**Comment by rougeth** [comment]
Estou com uma dúvida, o episódio será focado no evento ou não?

**Comment by rafpyprog** [comment]
Galera a ideia é divulgar o evento. Contudo, como o Paulo disse, um episódio sobre um evento específico chama pouca atenção, muita gente não vai ouvir. A ideia é falar sobre a Python em geral e em falarmos sobre o evento no final por exemplo.

**Comment by rougeth** [comment]
@cecivieira Entendi, "eme vento" me confundiu. Então não tem necessidade de limitar apenas para pessoas da org.

> Tipo: Sabe o que é Python -> Python é massa -> O mercado tá bombando -> Nossa Comunidade é top -> Participe da PyBR !

Parece o melhor caminho mesmo, mas não entendi como os três temas dos pilares se encaixariam nisso. Minha impressão é que focar educação ou tecnologia cívica deveria gerar um episódio apenas para esses temas, enquanto falar sobre mercado de trabalho cabe em um episódio mais genérico sobre Python (sem foco em uma área específica).

**Comment by deboraazevedo** [comment]
eu iria pela Thais VIana como educação mesmo, já que não sou Dev Python e minhas questões que envolvem tecnologia em educação é com um viés em outra linguagem.. no caso, se quisessem falar sobre a eleição da PSF e internacionalização das coisas, ai acho que eu poderia ser um bom fit

**Comment by cecivieira** [comment]
> Tipo: Sabe o que é Python -> Python é massa -> O mercado tá bombando -> Nossa Comunidade é top -> Participe da PyBR !

Esse caminho ficou massa.

O que vocês acham da dupla @gabubellon e @lidymonteiro para desenvolver esse caminho?

**Comment by gabubellon** [comment]
@cecivieira  quando você diz desenvolver é achar pessoas para participar e ajudar a roterizar o podcast ?

**Comment by cecivieira** [comment]
@gabubellon quero dizer "pessoas para conversarem e desenvolver esse tema proposto¨

**Comment by rafpyprog** [comment]
Penso que quem for participar precisa saber levar uma conversa sobre dados/fatos do mercado dev python, sobre o uso de Python, tendências, fatos interessantes e experiências pessoais para a conversa ser legal... É importante tb saber falar da PyBR, estrutura do evento, um pouco do histórico, etc...

Acho que a comunidade pode ajudar compilando essas informações para apoiar quem for participar e seria itnteressante ter no grupo alguém com mais tempo de estrada tb

**Comment by gabubellon** [comment]
Da minha parte ok,

**Comment by GabrielRF** [comment]
@anadulce @cecivieira 
> Uma pessoa que eu acho que arrasaria nesse podcast seria o @GabrielRF :)

Me sinto honrado pela lembrança e acho que deve ser muito legal participar de um podcast!

Mas fiquei me questionando...
Mercado de trabalho? Eu? 
Nunca tive emprego como dev. Como dev só fui reprovado para vagas.. kkkkk

**Comment by rafpyprog** [comment]
@lidymonteiro ?

**Comment by lidymonteiro** [comment]
Oie, pessoal. Não estava visualizando o tópico. Fico agradecida pela indicação e a disposição. Desculpem a demora em responder

**Comment by cecivieira** [comment]
@rafpyprog tu pode dar andamento a essa atividade?

**Comment by cecivieira** [comment]
Não estou conseguindo seguir o contato com @rafpyprog . Por isso, essa issue foi fechada.
