### ISSUE TITLE
Patrocínio com o Mercado Livre - 🇦🇷

### ISSUE THREAD

**Issue by tiidadavena** [pythonbrasil/pybr2021-org#184]
Leandro Viña é funcionário da Mercado Livre (sede argentina) e é participante ativo da comunidade argentina de devs Python.

Ele copiou 2 funcionários na sede da ML em São Paulo.

Link do ticket: https://pythonbrasil.freshdesk.com/a/tickets/7118

Segue email traduzido para PT-BR:

> Meu nome é Leandro E. Colombo Viña (também conhecido como LeCoVi) e atualmente estou trabalhando no Mercado Libre. Também participei há alguns anos na comunidade Python Argentina. Estou pressionando internamente pela participação dos membros da MELI em diferentes conferências python. Eu entre em contato com eles porque queremos explorar a possibilidade de ter algum nível de patrocínio no Python Brasil 2021 e também queremos saber se eles precisam de colaboradores na organização.
Temos uma grande comunidade de desenvolvedores com muito interesse no Python e sempre encontramos voluntários que querem contribuir de alguma forma. Como podemos ajudar nesse sentido? 

Na cópia estão Pam e Gio, 2 líderes da minha equipe que estão no site de São Paulo.

**Comment by apast** [comment]
Oi! 

Excelente! Vamos conversar.

Aqui em Florianópolis, temos relações com diversas pessoas internas, também participaram da evolução da comunidade!

Quando podemos conversar?

Na terça-feira, é muito para frente?

Obrigado!

**Comment by tiidadavena** [comment]
Outro ponto a ser levado para a reunião #182 :

Caso a ML opte pelo patrocínio na Cota Ouro, como se dará este processo já que as cotas ouro BR já são esgotadas?

A gente abriria mais uma cota nacional ou uma das internacionais (dólar argentino)?

**Comment by cecivieira** [comment]
Terça-feira fica bom pra mim. Queria conversar antes com vocês, caso a reunião seja em espanhol e precise que eu vá dá uma forcinha.

@tiidadavena acho que não cabe modificarmos a cota de patrocínio. Não temos mais cota ouro para oferecer.

**Comment by cecivieira** [comment]
Precisamos de voluntário na organização para fazer divulgação da trilha em espanhol nas comunidades de TI dos países hispanófonos.

**Comment by tiidadavena** [comment]
> Terça-feira fica bom pra mim. Queria conversar antes com vocês, caso a reunião seja em espanhol e precise que eu vá dá uma forcinha.
> 
> @tiidadavena acho que não cabe modificarmos a cota de patrocínio. Não temos mais cota ouro para oferecer.

Acredito que a opção seria uma cota Ouro para empresas estrangeiras (em dólar estadunidense) como na [planilha](https://docs.google.com/spreadsheets/d/1ddYFSfrkOsH0LbP7O1a13IuZImvUXEGnfvpQiv3aISM/edit#gid=510557133).

Porém, como ele marcou 2 pessoas da filial de SP da empresa, vamos partir do pressuposto que o patrocínio será via BR, começando via Prata.

**Comment by tiidadavena** [comment]
Segue modelo de devolutiva em esp:

"¡Hola, Leandro!

En primer lugar, nos gustaría darle las gracias por su interés en patrocinar Python Brasil 2021!

En cuanto a las cuotas, todavía tenemos cuotas Plata disponibles sí!

Estamos disponibles para hacer preguntas sobre el evento, beneficios, plan de patrocinio o cualquier otra pregunta relacionada con el tema. ¿Prefiere hacerlo a través de una reunión o por escrito?

Solemos celebrar una reunión para alinear expectativas y responder dudas. Una vez resueltos estos términos, continuamos con el progreso del contrato.

La información sobre los beneficios de las cuotas y cómo funciona el evento se puede encontrar en nuestro Plan de Patrocinio (ver portugués - enlace). Pero pronto enviaremos la versión en español del :D 


PS: Sobre la hora de una reunión, estamos disponibles el martes por la tarde.
"

**Comment by tiidadavena** [comment]
> La información sobre los beneficios de las cuotas y cómo funciona el evento se puede encontrar en nuestro Plan de Patrocinio (ver portugués - enlace). Pero pronto enviaremos la versión en español del :D

Não sei se seria o caso de ter o plano de patrocínio em espanhol, mas posso providenciar

**Comment by tiidadavena** [comment]
> > La información sobre los beneficios de las cuotas y cómo funciona el evento se puede encontrar en nuestro Plan de Patrocinio (ver portugués - enlace). Pero pronto enviaremos la versión en español del :D
> 
> Não sei se seria o caso de ter o plano de patrocínio em espanhol, mas posso providenciar

Pronto, traduzi por desencargo, mas necessita de revisão: https://docs.google.com/presentation/d/1a4v_KnfpcOPVnNxhB0ixpEzCwO2zZ8DV/edit?usp=sharing&ouid=105194890272054172164&rtpof=true&sd=true

**Comment by cecivieira** [comment]
Se a gente for usar a versão em espanhol, faço ou peço revisão das voluntárias da trilha América Latina.

**Comment by tiidadavena** [comment]
Em reunião cojunta com @cecivieira e @apast enviamos email de devolutiva agendando reunião para quarta-feira (11/08) às 10h :D

**Comment by tiidadavena** [comment]
> Em reunião cojunta com @cecivieira e @apast enviamos email de devolutiva agendando reunião para quarta-feira (11/08) às 10h :D

A reunião foi muito produtiva! Eles nos informaram que a filial brasileira é quem será a patrocinadora, se interessaram pela cota Prata e convidamos Leonardo Via para para ajudar na organização Latam

**Comment by tiidadavena** [comment]
Foi enviado agora o email com PDF do Plano de Patrocínio em Português e foram solicitados dados fiscais para montar o contrato (razão social, CNPJ etc.).

**Comment by alynnefs** [comment]
Responderam que podem passar os dados para continuar com o processo

**Comment by tiidadavena** [comment]
@alynnefs @mazulo, Pamela (ela é BR), a responsável pela área de Financeiro, mandou msg no pv no Telegram cobrando a documentação. 

Ela precisa de um comprovante bancário que contenha o CNPJ e os dados bancários da APyBR.

**Comment by alynnefs** [comment]
@tiidadavena tem [esse extrato](https://drive.google.com/drive/folders/0B_CQOAVUY5bRQ2pjbzVocjZMX1E?resourcekey=0-ZJQnlDnbLrHj98yBqr96yg) na pasta que o mazulo enviou. Vou te mandar minhas informações pelo discord. CNPJ e dados da conta tem no contrato, mas posso enviar também. Mas sobre "sociedade", não sei em qual a APyB se encaixa

**Comment by tiidadavena** [comment]
Gente, Pamela mandou a devolutiva dos documentos enviados (comprovante de extrato, e o pagamento do Streamyard) e ela disse que as documentações precisam ter CNPJ e dados bancários. 

@alynnefs @mazulo vocês sabem de alguma outro comprovante bancário que pessa nos ajudar?

**Comment by alynnefs** [comment]
Com CNPJ e dados bancários eu não sei :(
Vou adicionar o @sergiomario aqui também

**Comment by mazulo** [comment]
> Gente, Pamela mandou a devolutiva dos documentos enviados (comprovante de extrato, e o pagamento do Streamyard) e ela disse que as documentações precisam ter CNPJ e dados bancários. 
> 
> @alynnefs @mazulo vocês sabem de alguma outro comprovante bancário que pessa nos ajudar?

Eu tava aqui agora dando uma fuçada na conta bancária pra ver se algum outro tipo de extrato incluiria o CNPJ, mas sem sucesso. Talvez no informe de rendimentos ou em algum comprovante da declaração do imposto de renda possa ter. Mas para o informe não encontrei essa opção no sistema. Sobre a declaração, vou conversar com a nossa contadora.

**Comment by tiidadavena** [comment]
Gente, a Pamela (a pessoa do financeiro da MELI BR) perguntou se a gente consegue enviar esse comprovante bancário ainda hoje.

**Comment by tiidadavena** [comment]
> > Gente, Pamela mandou a devolutiva dos documentos enviados (comprovante de extrato, e o pagamento do Streamyard) e ela disse que as documentações precisam ter CNPJ e dados bancários.
> > @alynnefs @mazulo vocês sabem de alguma outro comprovante bancário que p�essa nos ajudar?
> 
> Eu tava aqui agora dando uma fuçada na conta bancária pra ver se algum outro tipo de extrato incluiria o CNPJ, mas sem sucesso. Talvez no informe de rendimentos ou em algum comprovante da declaração do imposto de renda possa ter. Mas para o informe não encontrei essa opção no sistema. Sobre a declaração, vou conversar com a nossa contadora.

A APyB tem algum comprovante de pix ou algum cupom fiscal de pagamento? Abri o app do BB e vi que em "2ª Via do Comprovante" tem as informações de  CPF + agência e CC. Acredito que deve ser demonstrativo análogo para conta PJ.

**Comment by tiidadavena** [comment]
Pamela enviou mais emails e pediu mais algumas infos:

![6BEA7590-E777-4F20-A019-8BB1F418D7D5](https://user-images.githubusercontent.com/12106738/131878900-3d2156a8-78b4-41a0-aab8-a20e2f37bd5f.jpeg)

**Comment by tiidadavena** [comment]
> Pamela enviou mais emails e pediu mais algumas infos:
> 
> ![6BEA7590-E777-4F20-A019-8BB1F418D7D5](https://user-images.githubusercontent.com/12106738/131878900-3d2156a8-78b4-41a0-aab8-a20e2f37bd5f.jpeg)
 @alynnefs @mazulo 
Eu acho que o nome fantasia corresponde aos dados, mas tem algumas informações que acho que só a secretaria da APyB tem.

**Comment by tiidadavena** [comment]
> Pamela enviou mais emails e pediu mais algumas infos:
> 
> ![6BEA7590-E777-4F20-A019-8BB1F418D7D5](https://user-images.githubusercontent.com/12106738/131878900-3d2156a8-78b4-41a0-aab8-a20e2f37bd5f.jpeg)

Planilha com os dados a serem inseridos: #
[FICHA CADASTRO MELI_pythonbr2.xlsx](https://github.com/pythonbrasil/pybr2021-org/files/7100311/FICHA.CADASTRO.MELI_pythonbr2.xlsx)

**Comment by alynnefs** [comment]
@tiidadavena 

- Inscrição Municipal: 100.369
- nome fantasia está em branco nas notas fiscais
- data de constituição: no site diz abril de 2007, mas a conta foi aberta em 08/02/2010
-  endereço pra faturamento deve ser o mesmo

as outras informações da tabela eu não sei

**Comment by tiidadavena** [comment]
> @tiidadavena
> 
> * Inscrição Municipal: 100.369
> * nome fantasia está em branco nas notas fiscais
> * data de constituição: no site diz abril de 2007, mas a conta foi aberta em 08/02/2010
> * endereço pra faturamento deve ser o mesmo
> 
> as outras informações da tabela eu não sei

Perguntei à Pamela qual das datas é melhor para eles

**Comment by tiidadavena** [comment]
> > Pamela enviou mais emails e pediu mais algumas infos:
> > ![6BEA7590-E777-4F20-A019-8BB1F418D7D5](https://user-images.githubusercontent.com/12106738/131878900-3d2156a8-78b4-41a0-aab8-a20e2f37bd5f.jpeg)
> 
> Planilha com os dados a serem inseridos: #
> [FICHA CADASTRO MELI_pythonbr2.xlsx](https://github.com/pythonbrasil/pybr2021-org/files/7100311/FICHA.CADASTRO.MELI_pythonbr2.xlsx)

@mazulo @alynnefs a gente conseguiu mais informações para preencher a planilha?

**Comment by alynnefs** [comment]
@tiidadavena as únicas informações que eu tenho são as do último comentário :/

**Comment by tiidadavena** [comment]
> @tiidadavena as únicas informações que eu tenho são as do último comentário :/

Tô vendo se consigo as infos do INSSQN e de alguma outra coisa

**Comment by tiidadavena** [comment]
Baixei os documentos comprobatórios em posse do CNPJ (e vamos ficar na torcida para que sirvam)

[FICHA.CADASTRO.MELI_pythonbr2-2.xlsx](https://github.com/pythonbrasil/pybr2021-org/files/7117550/FICHA.CADASTRO.MELI_pythonbr2-2.xlsx)
[Certidao-09344485000105-2.pdf](https://github.com/pythonbrasil/pybr2021-org/files/7117551/Certidao-09344485000105-2.pdf)
[ConsultaOptantes.pdf](https://github.com/pythonbrasil/pybr2021-org/files/7117552/ConsultaOptantes.pdf)

**Comment by tiidadavena** [comment]
Recebido email de confirmação do patrocínio da MELI :D

**Comment by tiidadavena** [comment]
Pamela informou via Telegram que o setor de Compras tem até 2 dias para dar o aval sobre os documentos enviados.

**Comment by tiidadavena** [comment]
Pâmela (setor Financeiro - BR) informou que as documentações da APyB foram aceitas e já iniciaram o processo da Ordem de Compra. Agora eles estão aguardando a aprovação da mesma para avançar para a próxima etapa.

**Comment by tiidadavena** [comment]
> Pâmela (setor Financeiro - BR) informou que as documentações da APyB foram aceitas e já iniciaram o processo da Ordem de Compra. Agora eles estão aguardando a aprovação da mesma para avançar para a próxima etapa.

Resposta de Pamela sobre o parecer de avaliação da OC:
"até 3 dias, até a quarta deveríamos ter já a resposta"

**Comment by tiidadavena** [comment]
Última msg de Pamela:

“ estao me pedindo o código de serviço e a descrição do serviço que irá na nota fiscal quando vcs a emitirem, poderia me passar por favor”

**Comment by tiidadavena** [comment]
Enviado contato para Pamela via Telegram questionando o andamento do processo da OC e do patrocínio.

**Comment by tiidadavena** [comment]
Resposta do setor de Compras: “ Boa tarde Ju, 
a Ordem de Compra teve um problema e precisei ajusta-la ontem, eu estou acompanhando essa ordem, amanha eu te falo se temos novidades, o prazo da área de compras após desse ajuste que fiz é até máximo a 2da.”

**Comment by tiidadavena** [comment]
Ordem de Compra aceita e gerada pela MELI
[4500257527.pdf](https://github.com/pythonbrasil/pybr2021-org/files/7181643/4500257527.pdf)
. 

Enviar email confirmando a assinatura do contrato.

**Comment by alynnefs** [comment]
@tiidadavena depois vc pode conferir o contrato? é pra enviar pra Pâmela mesmo?

**Comment by tiidadavena** [comment]
O sistema de compras da MELI (ARIBA) solicitou para a APyB conferir os dados no sistema para validar a OC. Operação já realizada.

**Comment by tiidadavena** [comment]
> @tiidadavena depois vc pode conferir o contrato? é pra enviar pra Pâmela mesmo?
Vou enviar email marcando-a e também Leandro Viña.

**Comment by tiidadavena** [comment]
Enviado email de cobrança de dados para montagem do contrato:
"
Sobre el proceso de contrato, ¿debe estar escrito en portugués, español o ambos? Y ¿a quién debemos enviar el contrato?

Para armar el contrato, necesitaremos los siguientes datos ASAP:

- Nombre completo de la empresa (nombre de la empresa) / Razão social
 - CNPJ (número de registro nacional de la empresa) / Cadastro Nacional de Pessoa Jurídica 
- Dirección completa / Endereço completo 
- Cuota de intereses y moneda de pago (pesos argentinos, reales brasileños, dólares...) / Cota de interesse e moeda de pagamento˜

**Comment by alynnefs** [comment]
contrato enviado para assinatura 🎉

**Comment by tiidadavena** [comment]
Foi informado pôr Pamela via Telegram de que o modelo de contratos da MELI é o que deve ser utilizado para o contrato.
Solicitei o modelo para ser enviado ASAP para analisarmos e inserirmos os dados da APyB.

**Comment by tiidadavena** [comment]
Segue modelo de contrato para patrocínio da Mercado Livre: https://docs.google.com/document/d/14i1-wqYfj7IIza61-GY_PRx7yY0gGZBT/edit?usp=sharing&ouid=105194890272054172164&rtpof=true&sd=true

**Comment by tiidadavena** [comment]
Pamela questionou sobre a obrigatoriedade do contrato, mas explicamos que é um processo default a ser seguido na Organização. Respondemos que sim, que serve como um elemento de garantia das entregas a serem realizadas pela APyB.  Fomos questionados sobre o andamento da análise do contrato, mas afirmamos que seguimos em andamento.

**Comment by tiidadavena** [comment]
Pamela enviou o questionamento via Whats sobre o idioma a ser usado no tutorial, se temos preferência entre português e espanhol.

**Comment by tiidadavena** [comment]
Contrato (minuta da MELI) em fase final de avaliação.

**Comment by tiidadavena** [comment]
Contrato final revisado enviado para a MELI
[Contrato_Patrocínio_Eventos_de_Terceiros - PYTHON BRASIL 2021.docx.pdf](https://github.com/pythonbrasil/pybr2021-org/files/7259801/Contrato_Patrocinio_Eventos_de_Terceiros.-.PYTHON.BRASIL.2021.docx.pdf)
.

**Comment by tiidadavena** [comment]
Reunião marcada 11h30 de hoje para esclarecer dúvidas sobre a Job Fair.

@alynnefs @anadulce onde consigo mais infos detalhadas sobre a Feira de Empregos? E a empresa pode escolher a duração e o melhor horário, confere?

**Comment by alynnefs** [comment]
@tiidadavena são naqueles horários que te passei. Como vai ficar dentro da programação do evento, tem horários específicos

**Comment by tiidadavena** [comment]
> Reunião marcada 11h30 de hoje para esclarecer dúvidas sobre a Job Fair.
> 
> @alynnefs @anadulce onde consigo mais infos detalhadas sobre a Feira de Empregos? E a empresa pode escolher a duração e o melhor horário, confere?

Reunião remarcada para amanhã (05/10) às 17:30

**Comment by tiidadavena** [comment]
Contrato assinado pela MELI e APyB: 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/12106738/135914148-490632e1-6ca6-409d-a6c3-fe2f7dd5f260.png">

**Comment by tiidadavena** [comment]
Enviado Form (traduzido para espanhol) para a MELI: https://forms.gle/ZNk2n3jCdMBxs6KG8

**Comment by tiidadavena** [comment]
Pamela enviou o Plano de Patrocínio para assinatura: 
![image](https://user-images.githubusercontent.com/12106738/135914570-48e55bb9-8fa5-4f55-a4af-829b7643daca.png)

**Comment by alynnefs** [comment]
nota fiscal enviada, depois edito com o link

**Comment by cecivieira** [comment]
@alynnefs qual a previsão para recebimento do dinehiro? Tem alguma pendencia de documentação?

**Comment by cecivieira** [comment]
@alynnefs @tiidadavena quando farão os 60 dias de prazo para a empresa realizar o pagamento do patrocínio?

**Comment by tiidadavena** [comment]
> @alynnefs @tiidadavena quando farão os 60 dias de prazo para a empresa realizar o pagamento do patrocínio?

Solicitei confirmação da data com a MELI mas era até 60 dias depois da assinatura do contrato.

**Comment by tiidadavena** [comment]
> @alynnefs @tiidadavena quando farão os 60 dias de prazo para a empresa realizar o pagamento do patrocínio?

Era a Ordem de Compra, mas enviamos assim que foi gerada no final de setembro.

**Comment by tiidadavena** [comment]
> @alynnefs @tiidadavena quando farão os 60 dias de prazo para a empresa realizar o pagamento do patrocínio?

O pagamento será entre os dias 9 e 14/12.

“ El pago se estará realizando entre los días 9 y 14/12” - devolutiva da MELI hoje.

**Comment by alynnefs** [comment]
patrocínio recebido em 09/12/2021
