### ISSUE TITLE
Documentar protocolo sobre orientações sobre leitura e pré-análise das propostas

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#195]
### Descrição
Documentar todo o processo de avaliação da submissão. Sendo esta issue referente a redação do protocolo com orientações sobre leitura e pré-análise das propostas de atividades, baseada no que será passado por @anadulce em reunião a ser marcada com voluntárias da organização.

### Requisitos para a atividade ser considerada como concluída

- Participar da reunião com orientações sobre leitura e pré-análise das propostas de atividades prokmovida por @anadulce 
- Documentar protocolo com as referidas orientações
- Subir documento para este repositório (/protocolos)

**Comment by alynnefs** [comment]
@anadulce e @belaaiza já analisaram
