### ISSUE TITLE
Traduzir formulário de avaliação das atividades para espanhol

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#196]
### Descrição
Traduzir formulário de avaliação das atividades (https://docs.google.com/forms/d/1hQ_aQeFN-VxX3ThLX12adPOVl1vXSkIaJVymmY10Cw8/edit)

### Requisitos para a atividade ser considerada como concluída

- Formulário traduzido

**Comment by alynnefs** [comment]
Talvez não seja necessário traduzir por causa da pequena quantidade de submissões
