### ISSUE TITLE
Definir data do evento

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#2]
A depender do formato estipulado, quantos dias serão abrangidos, definir uma data para o evento.

**Comment by alynnefs** [comment]
Como a @cecivieira disse, essa issue está relacionada a #30, também sendo bloqueada por ela

**Comment by alynnefs** [comment]
Ao que tudo indica, não tem nenhum evento marcado para ambas as datas.

Minha sugestão: fazer em outubro, assim a gente incentiva a participação nas sprints por causa da hacktoberfest

**Comment by rougeth** [comment]
Boa! Sprints com Hacktoberfest são sempre um sucesso :)

**Comment by cecivieira** [comment]
Damos como decidida a escolha do período entre 11 a 17 de outubro? (Por mim sim)

Se não, quando a gente dá por decida?

**Comment by cecivieira** [comment]
Como já foi feito o levantamento sobre datas de grandes eventos na issue #30 , estou desbloqueando essa.

**Comment by cecivieira** [comment]
Damos como decidida a escolha do período entre 11 a 17 de outubro? (Por mim sim)

Se não, quando a gente dá por decida?

**Comment by alynnefs** [comment]
> Damos como decidida a escolha do período entre 11 a 17 de outubro? (Por mim sim)
> 
> Se não, quando a gente dá por decida?

A gente pode oficializar hoje, mas pra mim faz mais sentido em outubro

**Comment by alynnefs** [comment]
Acontecerá entre 11 e 17 de outubro
