### ISSUE TITLE
Patrocínio com a AmbevTech

### ISSUE THREAD

**Issue by tiidadavena** [pythonbrasil/pybr2021-org#203]
### Descrição
*Iniciar processo de patrocínio com a AmbevTech.*

### Requisitos para a atividade ser considerada como concluída

"Contrato assinado e pagamento recebido do patrocínio + Form recebido com o tutorial"*

Ticket #7212 - AmbevTech representada na pessoa de Carla Uller

**Comment by tiidadavena** [comment]
Carla pediu para agendar uma reunião para dia 09/09. Porém como fica muito em cima para o processo burocrático e faltando 2 dias para submissão do form de tutorial, enviamos uma devolutiva pedindo para reagendar uma reunião com uma data para esta ou para a próxima semana.

**Comment by tiidadavena** [comment]
> > Reunião agendada para o dia 27/07 (sexta-feira) das 10 às 10h30.
> 
> @tiidadavena precisa de alguma coisa? Eu vou me vacinar nesse dia, não sei se consigo acompanhar 🙁

A reunião foi bem tranquila, foram dúvidas pontuais sobre os canais no Discord. Seguem tópicos discutidos:

- Quais as diferenças entre os patrocínios Prata e Ouro?
- Esclarecimentos sobre os canais no Discord
- A AmbevTech está buscando a parceria com ZéDelivery para compartilhar o patrocínio (ambas entrariam com o valor do patrocínio, mas a empresa presente no contrato seria a AmbevTech)

**Comment by tiidadavena** [comment]
Foi enviado email hoje solicitando os dados fiscais da AmbevTech e questionando acerca da confirmação de co-patrocínio com a Zé Delivery

**Comment by alynnefs** [comment]
@tiidadavena acho que seria bom esperar pelo menos o contrato assinado

**Comment by tiidadavena** [comment]
> @tiidadavena acho que seria bom esperar pelo menos o contrato assinado

Beleza! De acordo, e sem falar como é Bronze, não vai precisar de submeter form.

**Comment by tiidadavena** [comment]
@alynnefs 

'Nós temos um contrato padrão de patrocínio. Poderiam nos enviar os dados abaixo para anexarmos ao contrato e devolvo o mesmo para sua análise com nossos dados cadastrais?
Razão social 
Cota de interesse (Ouro, Prata ou Bronze)
CNPJ
Endereço Completo
Inscrição estadual e/ou municipal (se aplicável)"

Tipo, acho que neste caso não faz mt sentido porque o patrocínio é para um evento específico, ou achas melhor pedir para ver a minuta para avaliarmos

**Comment by tiidadavena** [comment]
A devolutiva do email da AmbevTech:

"Para fins de desencargo, poderias enviar o modelo do contrato para encaminhar para análise com o Comitê Organizador? 
​
Anexado a este email segue o nosso modelo de contrato para avaliação."

**Comment by tiidadavena** [comment]
Foi enviado email hoje para a AmbevTech pedindo retorno sobre a minuta do contrato da APyB e foi enviado o link do perfil demográfico dos participantes (https://pybr2020opendata.herokuapp.com).

**Comment by tiidadavena** [comment]
Devolutiva da AmbevTech com a revisão da minuta de contrato dela e elas solicitaram os dados bancários da APyB:

" 
Segue minuta contratual para análise.
 
Gentileza informar os dados cadastrais e dados bancários para transferência."
[HBSIS x Python Brasil 2021 - Contrato de Patrocinio [revisado jurídico].docx]
(https://github.com/pythonbrasil/pybr2021-org/files/7170124/HBSIS.x.Python.Brasil.2021.-.Contrato.de.Patrocinio.revisado.juridico.docx)

**Comment by alynnefs** [comment]
ainda vou ler direito, mas isso não parece o debate que a gente teve um tempo atrás?

> Salvo previsão legal em contrário, os tributos que, direta ou indiretamente, forem devidos em decorrência do presente contrato, ou de sua execução, constituem ônus de exclusiva responsabilidade da PATROCINADA, compreendendo-se os ônus fiscais, trabalhistas, securitários e previdenciários.

**Comment by tiidadavena** [comment]
Enviado email de resposta informando que a APyB prioriza o modelo desta para o contrato e enviei novamente o modelo da PYBR para conferência.

**Comment by alynnefs** [comment]
ainda sobre o contrato deles:
> O presente contrato inicia sua vigência na data de assinatura deste instrumento, assim permanecendo até o término do evento a ser operacionalizado pela PATROCINADA, que será realizado de 11/10/2021 a 17/10/2021.

a gente tinha colocado uma semana a mais por ter um post programado para depois do evento

> 5.8 A PATROCINADORA autoriza a PATROCINADA a divulgar sua logomarca estritamente e exclusivamente durante a realização do EVENTO e em comunicações publicitárias relacionadas com ele, devendo a PATROCINADA manter os padrões visuais repassados pela PATROCINADORA.

algum problema com a divulgação no plano de patrocínio nos anos seguintes?

> 7.5 Nas hipóteses em que ocorra o tratamento de dados pessoais em decorrência do apoio pela PATROCINADORA ao evento, a PATROCINADA observará as seguintes condições:
I – A PATROCINADA se compromete a observar plenamente os princípios e requisitos para tratamento de dados pessoais previstos na Lei 13.709/2018 (Lei Geral de Proteção de Dados), além de eventuais ordenamentos que venham a substituí-los ou complementá-los.
II – A PATROCINADA se compromete a estabelecer boas práticas de segurança de dados em relação às informações tratadas.
III – A PATROCINADA informará prontamente à PATROCINADORA, quando for classificado assim sua necessidade, sobre eventual incidente de segurança que possa acarretar risco ou dano relevante aos titulares dos dados pessoais. 
IV – A PATROCINADA reparará integralmente a PATROCINADORA por eventual penalidade sofrida em decorrência do tratamento indevido dos dados dos titulares, bem como descumprimento à legislação correlata.
V – A PATROCINADA se obriga a colher o consentimento expresso e inequívoco dos titulares de dados, sempre nos limites da necessidade. 

não podemos esquecer de anonimizar os dados pessoais, mas isso não vai ser um problema

> 7.9 As Partes expressamente declaram e concordam que o presente Contrato poderá ser celebrado por meio físico ou eletrônico, a critério destas, reconhecendo como válida qualquer forma de comprovação de anuência aos termos ora acordados, ainda que sem a utilização de certificado digital emitido no padrão ICP-Brasil, nos termos do art. 10, §2º, da Medida Provisória nº 2.200-2. A formalização das avenças na forma aqui acordada será suficiente para a comprovação de validade e integral vinculação das partes ao Contrato, representando a integralidade dos termos entre elas acordados. As partes declaram e garantem, ainda, que têm poderes para assinar eletronicamente o presente Contrato, sob pena de responsabilidades civil e criminal, sendo a ferramenta por elas escolhida reconhecida como adequada para dar validade à celebração deste Contrato.

já seguimos isso, mas talvez seja bom adicionar algo assim nos contratos de 2022

**Comment by tiidadavena** [comment]
Enviado contrato no modelo da Ambevtech com as ressalvas apresentadas por @alynnefs

**Comment by tiidadavena** [comment]
Enviado email de cobrança de andamento de atividades para Luana Gilli (Compras) e Carla Uller (MKT). Ainda não obtivemos as respostas do contrato preenchido com os dados da APyB.

**Comment by alynnefs** [comment]
meus dados foram passados para que eles enviem o contrato para assinar

**Comment by alynnefs** [comment]
[contrato assinado](https://drive.google.com/file/d/1hIb5cEuG6Vf2q4lLg_TpBBsMASFq3DT_/view?usp=sharing)
aguardando dados para gerar a nota fiscal

**Comment by alynnefs** [comment]
Ainda não responderam sobre os dados da NF

**Comment by cecivieira** [comment]
Patrocínio recebido em 17/11
