### ISSUE TITLE
Adicionar imagens de divulgação na capa das redes sociais

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#205]
### Descrição
Adicionar as [imagens de divulgação](https://2021.pythonbrasil.org.br/#recursos) do evento nas redes sociais pessoais dos organizadores

### Requisitos para a atividade ser considerada como concluída

- redes sociais atualizadas

Não vejo como obrigatório, já que é algo pessoal. Mas surgiu como ideia para divulgar ainda mais o evento dentro das nossas bolhas.

**Comment by rougeth** [comment]
Atualizei [meu twitter](https://twitter.com/marcorougeth) :D

**Comment by alynnefs** [comment]
Demorei, mas adicionei no twitter e linkedin :D

**Comment by alynnefs** [comment]
Divulgado pela @dandaramcsousa, vou fechar a issue
