### ISSUE TITLE
Divulgação da campanha de doação

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#207]
### Campanha
Incentivar doação
  
### Peça/publicidade solicitada
3 Cartões - (1 para lançar antes das incrições e outras 2 para relembrar até o fim do evento)

### Detalhamento do uso
Divulgação informativa sobre campanha de arrecadação financeira para beneficiar ONG que trabalha no combate a fome

### Data prevista para uso da arte
01 set. 2021

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Alguém poderia ajudar a fazer o teste para incentivar? 

**Quais informações devem aparecer na arte?**

**Comment by cmdiasbr** [comment]
@alynnefs @cecivieira

**Comment by cecivieira** [comment]
Siimm.. que tipo de teste?

**Comment by cmdiasbr** [comment]
> Siimm.. que tipo de teste?

texto*, eu tava pensando em teste quando escrevi 👎

**Comment by Flaviasv** [comment]
> Alguém poderia ajudar a fazer o teste para incentivar?
> 
> **Quais informações devem aparecer na arte?**

Que tal ajudar a combater a fome no Brasil? Participe da nossa campanha de arrecadação financeira que vai contribuir com ONGs que trabalham no combate à fome no país.

**Comment by cecivieira** [comment]
Achei ótimo. @Flaviasv quando tiver arte, tu poderia traduzir e postar o carrossel?
Pode ser hoje já.

**Comment by cmdiasbr** [comment]
Card 15, salvar como .mp4
https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit


https://user-images.githubusercontent.com/45003095/132109753-1f81a8de-38fb-4a69-91a5-cef795629662.mp4

**Comment by cmdiasbr** [comment]
@Flaviasv @cecivieira

**Comment by cecivieira** [comment]
@Flaviasv traduzir para espanhol e postar:
https://www.canva.com/design/DAEloufMqdM/L83sZgaygyEXRMPg4LCdYw/edit

**Comment by cecivieira** [comment]
Atualizei o texto da imagem anterior, mas não sei postar aqui como mp4. Então, antes de postar, precisa descarregar lá do Canva

**Comment by deboraazevedo** [comment]
fui clicar no link da versao pra traduzir e diz que nao tenho acesso a esse design, mesmo estando no time python brasil :thinking: se quiserem que poste em portugues apenas ja posso fazer pra hoje à  noite

**Comment by cmdiasbr** [comment]
@deboraazevedo tenta aqui: https://www.canva.com/design/DAEjPWNunB0/share/preview?token=iHxtxgtxfLnVmOwj8hToDg&role=EDITOR&utm_content=DAEjPWNunB0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

É a card 15

**Comment by cecivieira** [comment]
A arte á está traduzida.

Versão em espanhol: https://www.canva.com/design/DAEloufMqdM/share/preview?token=OrE09zDsOky8usKp-wFSCA&role=EDITOR&utm_content=DAEloufMqdM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Versão em português: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

Deverá ser postada as artes em .mp4, conforme orientação de Camila

**Comment by cecivieira** [comment]
@deboraazevedo essa arte já pode ser postada.
Sugiro agendamento para amanhã, pois hoje já foi feita uma postagem

**Comment by paulohenriquedsgn** [comment]
> @deboraazevedo essa arte já pode ser postada.
> Sugiro agendamento para amanhã, pois hoje já foi feita uma postagem

@cecivieira postagens agendas para 10:00hs da manhã (Português) e 11:00hs (Espanhol)

**Comment by paulohenriquedsgn** [comment]
Links da postagens

Twitter: 
Português - https://twitter.com/pythonbrasil/status/1435226485569249281?s=20
Espanhol - https://twitter.com/pythonbrasil/status/1435241539307986948?s=20

Instagram:
Português - https://www.instagram.com/p/CThXW10tigI/?utm_source=ig_web_copy_link
Espanhol - https://www.instagram.com/p/CTheMySrkni/?utm_source=ig_web_copy_link

Facebook:
Português - https://fb.watch/7V9mWOT2Sg/
Espanhol - https://fb.watch/7V9oyspXLE/

Linkedin:
Português - https://www.linkedin.com/posts/apyb_pybr2021-activity-6840992160150507520-W2m
Espanhol - https://www.linkedin.com/posts/apyb_qu%C3%A9-te-parece-si-adem%C3%A1s-de-inscribirte-en-activity-6841007153495465984-l-g7
