### ISSUE TITLE
Refazer orçamento de intérprete de libras

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#208]
### Descrição
Refazer orçamento de intérprete de libras, pois os valores podem ter mudado desde o último contato

### Requisitos para a atividade ser considerada como concluída

- Orçamentos feitos

Issue relacionada: #33

**Comment by cecivieira** [comment]
@gabubellon checa essa descrição do serviço, por favor. Vou pedir para refazer o orçamento baseado nela:

Programação diária:
- 2h - Roda de conversa
- 1h30 - Palestra principal
- 16h - Palestras distribuídas em trilhas (ou seja, são 4 trilhas acontecendo simultaneamente e cada uma tem 4h de duração)

Tema/conteúdo:
Tecnologia, com foco em programação.

Horários previstos:
- Roda de conversa: 10h às 12h

- Trilhas:
15:00 às 15:45
15:50 às 16:35
16:40 às 17:25
18:20 às 19:05
19:10 às 19:55

- Palestra principal: 20:00 às 21:30

**Comment by gabubellon** [comment]
Obrigado @cecivieira iria pedir isso mesmo pra fazer isso no almoço

**Comment by gabubellon** [comment]
@cecivieira nesse detalhes a trilha de espanhol não está cotada certo ? Se formos considerar ela considerar  +4h (20h de 5 trilhas)

**Comment by cecivieira** [comment]
@gabubellon A tradução simultânea será dentro de uma sala no discord. Pensando que há um delay importante entre o que está sendo transmitido no youtube em relação ao streamyard, não sei como se daria essa tradução para Libras.

**Comment by gabubellon** [comment]
https://docs.google.com/spreadsheets/d/109qCkLIoCNBFkgZMdfdKkkbBFByxz_HH6bOqRut6U-Q/edit#gid=0
Centralizando Orçamentos na planilha e detalhes na pasta da mesma

**Comment by tiidadavena** [comment]
Tinha feito mais algumas cotações (mas foi há cerca de 1 mês), no caso, só a Liliana respondeu, mas tbm acho que vale a pena falar com a Yone: https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit#gid=0

**Comment by alynnefs** [comment]
Intérprete escolhida: Hands Interpretacio
issue do contrato: #239
