### ISSUE TITLE
Criar o rascunho do evento no Eventbrite

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#209]
### Descrição
Criar o rascunho do evento no Eventbrite para ser vericado pelo time.

### Requisitos para a atividade ser considerada como concluída

- Arte de doação
- Rascunho verificado pelo time
- Evento postado

**Comment by cecivieira** [comment]
Concluídos os formulários para inscrição em português e espanhol.

Aguardando divulgação da arte de doação #207

**Comment by cecivieira** [comment]
espanhol - https://www.eventbrite.com.br/myevent?eid=169085861363
português - https://www.eventbrite.com.br/myevent?eid=169078058023

**Comment by cecivieira** [comment]
Ficou decidido na #212 que será apenas 1 formulário, sendo bilingue.
https://www.eventbrite.com.br/questions?eid=169078058023

As inscrições iniciarão dia 08 set.
