### ISSUE TITLE
Programação

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#21]
### Descrição
Definir a grade do evento

### Requisitos para a atividade ser considerada como concluída

- Grade definida

**Comment by alynnefs** [comment]
adicionar horário do job fair

**Comment by cecivieira** [comment]
@alynnefs tu poderia abrir uma planilha e colocar o link aqui? Ou a programação é feita de forma automatizada?


Como posso inserir a trilha em espanhol?

**Comment by cecivieira** [comment]
programação concluída e disponível no link https://docs.google.com/spreadsheets/d/1t9bBxMSWduKfCb3r9GBFk8TYEDw48nKHQ252SAHFBEs/edit#gid=1398050694
