### ISSUE TITLE
Ler submissões de sprints

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#210]
### Descrição
Ler submissões de sprints para ver se tem alguma fora do tema.

### Requisitos para a atividade ser considerada como concluída

- Ler as submissões
- Mandar o convite para as pessoas

OBS: não consegui adicionar o @eloabe como responsável

**Comment by cecivieira** [comment]
Foi verificado que a plataforma usada no ano passado, EventBrite, atende as necessidades desse ano. Então, para simplificar a criação do formulário de inscrição desse ano, foi mantida a plataforma.

Os eventos estão sendo criados usando a issue #209

**Comment by eloabe** [comment]
🙋‍♂️

**Comment by cecivieira** [comment]
@anadulce tu poderia dar acesso ao material que @eloabe precisa avaliar? E também as orientações?

**Comment by anadulce** [comment]
Feito, @cecivieira :)

**Comment by cecivieira** [comment]
@eloabe você tá precisando de ajuda nessa atividade? Como está o andamento?

**Comment by eloabe** [comment]
Todas as submissões estão ok. Escrevendo o texto dos e-mails, até hoje a noite consigo mandar aqui.

**Comment by cecivieira** [comment]
@eloabe no e-mail, pede para preencher esse formulário até 13 set., por favor
https://forms.gle/xGJqAXtEvNh2j7zx5

Esse formulário coleta informações para divulgação da atividade.

**Comment by cecivieira** [comment]
Isso se tu enviar o email hoje, senão, conta 5 dias a partir da data de envio.

Quando tu fizer isso, manda mensagem aqui e fecha a issue, por favor.

**Comment by eloabe** [comment]
E-mails enviados. Não consigo fechar a issue
