### ISSUE TITLE
Divulgação de patrocinadores - Jusbrasil

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#211]
### Campanha
Divulgação da Jusbrasil, que é patrocinador ouro.
  
### Peça/publicidade solicitada
3 Cartões - 1 para lançar antes do evento, 1 durante e 1 depois (agradecimento)

### Detalhamento do uso
Arte para divulgação dos patrocinadores, acredito que um modelo só resolva para as 3 cotas

### Data prevista para uso da arte
15 de setembro de 2021
entre 11 e 17 de outubro de 2021
até 24 de outubro de 2021

### Quais informações devem aparecer na arte
Cota de patrocínio: ouro

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by alynnefs** [comment]
@anadulce @rougeth deixei passar alguma coisa? a gente vai colocar no telegram também?

**Comment by rougeth** [comment]
Acho que no Telegram não porque os grupos não são canais de comunicação oficiais.

**Comment by rougeth** [comment]
Vamos adiantar a primeira postagem? Pensando no lado da empresa patrocinadora, quando mais cedo divulgarmos melhor, e para gente, não faz "diferença". @cmdiasbr @martinsvanessa @paulohenriquedsgn seria irado se vocês conseguissem priorizar as artes para o primeiro anúncio (marquei vcs pq n sei quem está fazendo as artes :P).

**Comment by cmdiasbr** [comment]
> Vamos adiantar a primeira postagem? Pensando no lado da empresa patrocinadora, quando mais cedo divulgarmos melhor, e para gente, não faz "diferença". @cmdiasbr @martinsvanessa @paulohenriquedsgn seria irado se vocês conseguissem priorizar as artes para o primeiro anúncio (marquei vcs pq n sei quem está fazendo as artes :P).

Eu que estou fazendo as artes Marco, mas a maioria estou fazendo no Canva para que vocês possam modificar se necessário.
As artes de patrocinadores ainda não fiz nenhum, mas irei fazer durante essa semana.

**Comment by alynnefs** [comment]
@cmdiasbr, se fizer um modelo pra ouro, prata e bronze, eu consigo alterar o patrocinador depois. Mas criar do zero eu não sei

**Comment by cmdiasbr** [comment]
Os 3 cards estão aqui: https://www.canva.com/design/DAEpEvgaWm8/Hs6qN0WC8gUduY5hrnj0bQ/edit

![Patrocinadores - Cards](https://user-images.githubusercontent.com/45003095/132105654-9c540abb-06e4-452c-9320-2ba7859ce932.png)

**Comment by cecivieira** [comment]
Antes de agendar poste, verificar informações da arte com as enviadas pela empresa patrocinadora:
https://docs.google.com/forms/d/1uRG7yt7D8PgwMvTP3wjCSRPRTFn0idvu0sGCCRetdOA/edit?usp=sharing

**Comment by rougeth** [comment]
- [x] Logo ok
- [x] O texto no formulário é:

> Somos uma empresa de tecnologia resolvendo velhos problemas com novas soluções. Conectando pessoas à justiça através de advogados e informação jurídica

Estamos indo com apenas a segunda parte. Não vejo problema.

@cecivieira podemos seguir com o envio nas redes sociais. Minha sugestão é enviarmos assim que possível (próxima data que não tenha conflitos com posts já agendados).

**Comment by cecivieira** [comment]
Links para o primeiro post. Os demais estão agendados:

https://www.instagram.com/p/CTe2KHegvX7/
https://twitter.com/pythonbrasil/status/1434872298046214144
https://www.facebook.com/pythonbrasil/photos/a.582882565067606/4624438190912003/
https://www.linkedin.com/company/33193243/

**Comment by alynnefs** [comment]
Só uma pergunta, usaremos a mesma arte para a divulgação durante o evento e após? Caso sim, vou criar issues e linkar com essa

**Comment by cecivieira** [comment]
@alynnefs não, existem 3 artes diferentes. Estão todas no link do Canva que Camila postou
https://www.canva.com/design/DAEpEvgaWm8/Hs6qN0WC8gUduY5hrnj0bQ/edit

Todas as artes e vídeo já foram agendados

**Comment by alynnefs** [comment]
@cecivieira eu tinha apagado o comentário porque entrei no link depois, mas obrigada por responder (:

**Comment by tiidadavena** [comment]
Kim (um funcionário novo no setor de eventos da empresa) questionou sobre alguns detalhes da divulgação dos dados. Mas @alynnefs já respondeu a eles (segue devolutiva a seguir):

"
CONTRAPARTIDAS PATROCÍNIO
Agradecimentos no início do dia de evento (De que maneira? Qual a dinâmica?)
Verbalmente, antes das rodas de conversa, que acontecerão às 10 da manhã
Divulgação nas redes sociais (Quais redes? Qual frequência? Quantidade de posts?)
São 3 posts, um antes do evento*, um durante e um após, sendo cada um deles postado no LinkedIn, Instagram, Twitter e Facebook
Participação na grade exclusiva para Job Fair (Qual plataforma? De que maneira? Qual a dinâmica?) 
Será pelo Discord, a mesma plataforma onde ocorrerá o evento. Iremos alocar um horário na programação oficial do evento, para incentivar a participação das pessoas.
DEFINIR FORMATO DO ARQUIVO (dimensão / tipo de arquivo / 
 
Exposição da marca na edição publicada no YouTube
será adicionada uma vinheta com as logos na edição final
Exposição da marca durante todas palestras
terá uma logo na margem da tela
Exposição da marca em todos e-mails institucionais
citação de patrocinador nos e-mails enviados
Exposição da marca durante os intervalos das palestras
aparecerá na tela durante os intervalos
Exposição da marca no site do evento (Site não apresenta os logos dos patrocinadores, quando está programada essa atualização?) 
Hoje pela manhã foi inserido no site a sessão de patrocínio
Sobre o formato do arquivo, estamos usando esse mesmo. 

* Já foi divulgada a primeira postagem sobre a JusBrasil, seguem os links:
- ​LinkedIn​​​
- Instagram
- Twitter
- Facebook
As demais estão com sua publicação agendada para 22/09, 11/10 e 18/10
O vídeo institucional será nesta primeira data

Para mais informações, temos o Plano de Patrocínio e, caso tenha mais alguma dúvida, pode nos perguntar."
