### ISSUE TITLE
Patrocínio com a Cornershop

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#213]
### Descrição

Iniciar processo de patrocínio com a "Cornershop by Uber".

### Requisitos para a atividade ser considerada como concluída

"Contrato assinado e pagamento recebido do patrocínio + Form recebido com o tutorial (caso haja)"*

Ticket #7233 - Cornershop representada por Daniela María Hoyos Pastor

**Comment by tiidadavena** [comment]
Recebemos esta devolutiva:
"Hello Juliana! i scheduled a meeting for this Thursday 17.30 GMT-3
I invited @Alessandra Leone Tech HR Leader in BR
@Tiago Framesqui Engineering Director in BR
and @Daniela María Hoyos Pastor Tech HR Manager

Will send them the links you sent me so we are all prepared for the meeting, please let me know if that time is good for you and feel free to invite whomever you see fit!"

Confirmamos a reunião agendada que está para esta quinta às 17:30.

Muito provavelmente será em inglês (enviei email questionando sobre, mas aguardando retorno).

Para quem se interessar, segue link da call: https://meet.google.com/qty-chtd-imr

**Comment by alynnefs** [comment]
@tiidadavena é no meet ou no zoom?

**Comment by tiidadavena** [comment]
> @tiidadavena é no meet ou no zoom?

Será no Zoom: https://cornershopapp.zoom.us/j/99919695387?pwd=UTJueUVnRkpmYmpvMXFvSjJMSnc1QT09

**Comment by tiidadavena** [comment]
Recebido este email na sexta-feira (no final do dia):

"Hello everyone! I keep my promise to get back to you before Monday. And I'm happy to inform you that we as a Company want to sponsor Python 2021 BR, we really hope to contribute to the Python community, and we are sure that you are a key ally in that mission :) 
We would love to go with Gold sponsorship in the case you can give us 1 spot, if not (no worries) we would love to go with the Silver

In the meantime, @Tiago Framesqui will be working with other Python lovers in Cornershop to come up with a great presentation for the keynotes section
Please let us know what would be the duration of a presentation, and any other info that may be important regarding that :D

I'll await for your confirmation on this email so we can start seeing billing"

**Comment by tiidadavena** [comment]
Enviado este email de devolutiva, confirmando em que idioma e região o contrato deverá ser redigido:

"Thanks again for your interest to sponsor Python Brasil 2021! The meeting was really enthusiastic and we hope to have answered your questions. <3

About the contract, it will be written in English w/ US dollar prices? Or it'll be based on the Brazilian's company branch? Wondering just in case to start preparing the document.

​And in order to continue the sponsorship process, we'll need the following informations about the company:

​Full legal name (Razão Social)
Full address (Endereço completo)
Company register number (CNPJ)
State or city register company (Inscrição estadual e/ou municipal)"

**Comment by tiidadavena** [comment]
Contrato bilíngue enviado hoje com os valores para a cota Prata.

**Comment by tiidadavena** [comment]
Enviado email de cobrança de andamento para a empresa. A devolutiva deles foi bem ágil e perguntaram se poderiam realizar  a assinatura via DocSign e afins.

Enviaram também este[ Google Forms](https://docs.google.com/forms/d/e/1FAIpQLScdoGBr-Z2DYayze8IZmrlK2aB4ii1isFJM0ywz2H2XW8LoIw/formResponse) com os dados para cadastrar a APyB como fornecedor.

**Comment by alynnefs** [comment]
Contrato enviado para assinatura

**Comment by tiidadavena** [comment]
A empresa enviou email questionando sobre o tutorial. Avisamos que o Form será enviado, mas foram listados os pontos necessários para a pessoa instrutora ir "adiantando" o conteúdo.

**Comment by tiidadavena** [comment]
Diego Samur pediu para enviarmos os dados do Form para ele localizar os dados para prosseguir com o processo de solicitação de pagamento.

Ainda faltam outras pessoas responsáveis para assinar o contrato.

**Comment by tiidadavena** [comment]
Diego enviou uma cópia do contrato de NDA para a gente analisar e enviar com os dados da APyB: https://docs.google.com/document/d/14i1-wqYfj7IIza61-GY_PRx7yY0gGZBT/edit?usp=sharing&ouid=105194890272054172164&rtpof=true&sd=true

**Comment by tiidadavena** [comment]
Tive uma reunião com Tiago, que é dev BR na Cornershop, e foram esclarecidas dúvidas sobre a duração do tutorial, como o mesmo deve ser feito e pediu a assinatura do NDA para avançar no contrato.

**Comment by tiidadavena** [comment]
Diego informou que acreditam que não conseguirão montar o tutorial a tempo do evento e, mesmo com o prazo estendido para até o final desta semana (01/10), acreditam que não darão conta e resolveram desistir do patrocínio:

"Hello, speaking with tiago we really prefer to pass and plan it out better and in advance for the next python 2022
best regards, let me know if anything :)"

**Comment by tiidadavena** [comment]
Devolutiva final para a Cornershop e transferida a a tag para Python Brasil 2022 e adicionando @julianyraiol como Analista pois já é uma empresa confirmada na edição do ano que vem:


"We understand the position to sponsor Python Brasil 2022 (aka Juliana Raiol) and thank you again for the interest and enthusiasm during the process and we'll forward your contacts to the organization of the 2022 edition of PYBR to advance some points.

We are sure of next year, with the return of the face-to-face edition, you will shine as sponsors and supporters! <3 

We apologize for the rush and deadlines, but we count on your presence in this year's edition!  Registration can be made through this link <3
​
"
