### ISSUE TITLE
Informar que haverá intérprete de libras em toda a programação

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#214]
### Campanha
--
  
### Peça/publicidade solicitada
1 cartão

### Detalhamento do uso
Informar amplamente nas redes sociais que toda a programação do evento estará acessível para falantes de LIBRAS.

### Data prevista para uso da arte
20 set.

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Para tradução: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit


![Cards](https://user-images.githubusercontent.com/45003095/132068095-df1b833d-fd62-4a65-ae87-df250065142b.png)

**Comment by deboraazevedo** [comment]
teremos mesmo interprete de lingua de sinais em espanhol? pra gente se organizar pra ver se faz dois posts ou um carrossel no agendamento da postagem

**Comment by cecivieira** [comment]
Ainda não foi fechado orçamento @deboraazevedo

**Comment by cecivieira** [comment]
Posts agendados
