### ISSUE TITLE
Arte para certificado

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#215]
### Campanha
--
  
### Peça/publicidade solicitada
1 certificado

### Detalhamento do uso
Essa arte será usada para gerar os certificados de forma automatizada, usando o que foi produzido na issue #119 

### Data prevista para uso da arte
18 outubro

### Quais informações devem aparecer na arte
A definir nos comentários

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [x] Outro *A5 paisagem*

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by alynnefs** [comment]
Eu tinha pensado nisso:

```
CERTIFICADO DE PARTICIPAÇÃO

Certificamos que <nome> participou do evento Python Brasil 2021 entre os dias 11 e 15 de outubro de 2021.

<espaço pra assinatura, se tiver>
Organização da Python Brasil 2021
```

tirei os dias de tutoriais, vamos fazer pros tutoriais também?

**Comment by cmdiasbr** [comment]
Certificado para edição: 
https://www.canva.com/design/DAEpFeuhdUE/cmuTDicxY7bEuLx4px1VdQ/edit

Lembrando que deve ser feito a otimização posteriormente usando esse template.

![CERTIFICADO DE PARTICIPAÇÃO](https://user-images.githubusercontent.com/45003095/132109171-529345e4-a9af-4184-9561-ea7113b1e6c1.png)

**Comment by cecivieira** [comment]
@cmdiasbr tô sem acesso a arte. Enviei uma solicitação

**Comment by cmdiasbr** [comment]
> @cmdiasbr tô sem acesso a arte. Enviei uma solicitação

liberei lá :)

**Comment by cecivieira** [comment]
@gabubellon versão em SVG do certificado:
https://drive.google.com/file/d/1Kf1gGWKUGC9RhL0LNivUg0DnCXExS8Ir/view?usp=sharing
