### ISSUE TITLE
Divulgação de keynote

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#217]
### Campanha
Keynote
  
### Peça/publicidade solicitada
1 cartão

### Detalhamento do uso
A arte será utilizada para divulgação das keynotes nas redes sociais.

### Data prevista para uso da arte
13 setembro

### Quais informações devem aparecer na arte
Lugar para foto da keynote e minibio

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Card para edição: https://www.canva.com/design/DAEpGurfQdI/-7qdqF3eojKV8R4l9gHrZA/edit

![Keynote - Card Principal](https://user-images.githubusercontent.com/45003095/132113437-ec2ea20d-5d53-4a97-a742-5ed59bb0ed74.png)

**Comment by cecivieira** [comment]
Aguardando movimentação da issue #218

**Comment by cecivieira** [comment]
@cmdiasbr Fizemos algumas modificações nas artes, dá uma olhadinha e vê o que tu acha
Colocamos 1 bonequinha diferente para cada pessoas

**Comment by deboraazevedo** [comment]
achei que ficou muito bonito uma bonequinha representando cada uma das pessoas <3

**Comment by cecivieira** [comment]
Agendadas postagens de todas as keynotes que enviaram dados suficientes

**Comment by alynnefs** [comment]
@cecivieira tem como depois mandar as informações da Gabi pra gente fazer o card dela? eu não consigo ver as respostas daquele form :/

**Comment by cecivieira** [comment]
@alynnefs a planilha já tá compartilhada com o grupo. Tenta entrar por esse link

https://docs.google.com/spreadsheets/d/15wtTZPwTCafFqTZv07U8vpcJ56eM0y2rIimqO-WISnY/edit?usp=drivesdk

**Yasodara Córdova**
Foto: https://drive.google.com/open?id=1jc9fBNlO21o4iE7i_jK3qVQcYmXTfTDf

Resumo
Yaso é Principal Privacy Researcher na Unico IDTech. Também é MC/MPA Candidate, Ford Foundation Mason Fellow do Ash Center for Democratic Governance and Innovation em Harvard. Yaso trabalhou no Banco Mundial, no setor de Governança, como fellow para engajamento cívico e de práticas ágeis. Tendo background em desenvolvimento de softwares, ela colaborou para a integração de tecnologia e inovação na infra estrutura de governança de países em desenvolvimento. Yaso também foi fellow e afiliada ao Berkman Klein Center e fellow da Digital Kennedy School, um projeto do Belfer Center, ambos na universidade de Harvard. Ela também foi advisor da fundação Cidadão Inteligente e CEO do Serenata de Amor, um projeto anti-corrupção que usa aprendizado de máquina para facilitar o controle social de gastos na Câmara dos Deputados do Brasil. Yaso foi também especialista em Web no World Wide Web Consortium, onde foi co-chair do grupo Dados na Web, entre outras posições e foi uma das fundadoras do Calango, o Hackerspace de Brasília.

**Comment by cecivieira** [comment]
Gabi Cavalcante

Foto:
https://drive.google.com/open?id=1FkfEvivNj1Y334clGM-ubdrfhpk1DFpn

Resumo:
Co-fundadora do PyLadies Brasil/Natal. Formada em Tecnologia da Informação (UFRN), sou desenvolvedora na Vinta, e estou sempre interessada em conversar sobre Python, Testes e Qualidade de Software.

**Comment by alynnefs** [comment]
@cecivieira muuuuito obrigada, eu não tinha achado pelo drive, geralmente eu vou pelo form e olho as respostas, mas nesse não rolou. Mas vou ver se consigo mexer nas artes hoje ainda

**Comment by alynnefs** [comment]
Fiz os cards da Gabi e da Yaso e já programei. Gabi pra segunda e Yaso pra quinta. Agradeço se alguém puder dar uma olhada antes das postagens 💙

**Comment by cecivieira** [comment]
@alynnefs estão ok as postagens agendadas

**Comment by cecivieira** [comment]
@alynnefs o que você acha de divulgar as keynotes hoje e amanhã? Assim, começariamos a divulgar as palestras na quarta

**Comment by alynnefs** [comment]
@cecivieira dá pra puxar a Gabi pra hoje, mas a Yaso tem que mudar uma coisa

**Comment by cecivieira** [comment]
@alynnefs tu pode fazer isso?
Precisa alterar o que el Yaso? Sobre o Calango hackerclub?

**Comment by alynnefs** [comment]
@cecivieira até posso, mas só depois da reunião, talveeeez na hora do almoço. Mas é isso do calango mesmo, só que tem que alterar imagem e texto

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/136446587-07be2e7f-8615-4c29-89e1-744ac763b4ef.png)
![image](https://user-images.githubusercontent.com/30605862/136446600-68890f3b-fa5c-4535-8f50-9d7f979f91a8.png)
![image](https://user-images.githubusercontent.com/30605862/136446607-071d648f-6da8-4c2b-ad65-bc6087a1a755.png)
![image](https://user-images.githubusercontent.com/30605862/136446621-0a80a44b-5cb8-4a5d-9830-34ec01f61b88.png)
![image](https://user-images.githubusercontent.com/30605862/136446632-4367cecd-e1ee-4534-bfe5-f339bdfbe158.png)
