### ISSUE TITLE
Solicitar informações das keynotes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#218]
### Descrição
Solicitar as seguintes informações das keynotes confirmadas:
- Foto
- microbio (até 200 caracteres)
- minibio 
- link para rede social que ela peseja divulgar

### Requisitos para a atividade ser considerada como concluída
- Receber informações das 5 keynotes 
- Comentar aqui as informações

**Comment by alynnefs** [comment]
@cecivieira @anadulce vcs conseguiram fechar o form?
Sem pressa, só pra saber mesmo

**Comment by cecivieira** [comment]
Vou revisar agora a tarde

**Comment by cecivieira** [comment]
Contatos realizados:

Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/7216
Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/7217
Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/7260
Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/7223
Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/7252
