### ISSUE TITLE
Responder formulários das submissões não revisadas

### ISSUE THREAD

**Issue by belaaiza** [pythonbrasil/pybr2021-org#219]
### Descrição
**palestras**
tivemos 406 revisões respondidas e 200 não respondidas
links dos forms não respondidos: https://docs.google.com/spreadsheets/d/1dGXXFPWapSlsqTi7-9Gvd4Sjh_6ujNcpEIZPBF_Kado/edit#gid=0

**tutoriais**
tivemos 83 revisões respondidas e 52 não respondidas
links dos forms não respondidos: https://docs.google.com/spreadsheets/d/1b-ZH_RPEccUHBetqj8N7EyMj6yxFGKWXGNQSetwYStc/edit#gid=0

as não respondidas nós mesmas vamos precisar responder, quem quiser ajudar é só clicar nos forms das planilhas acima e respondê-los, marquem de lilás a linha do form que vocês responderem

### Regras para resposta do formulário
Não revisar a mesma palestra duas vezes (pode acontecer, porque tem três cópias);
Não avaliar quando identificar a pessoa proponente;
Não pode participar quem submeteu atividades;

### Requisitos para a atividade ser considerada como concluída

- Ter todos os formulários respondidos

**Comment by jsbueno** [comment]
não é muito só pra quem está na org? pelo que ví no twitter, muita gente perdeu o prazo pq. não achou os e-mails. De repente vale a pena mais uma rodada (com um prazo menor, claro)

**Comment by cecivieira** [comment]
Informações vindas de @anadulce :

- Não revisar a mesma palestra duas vezes (pode acontecer, porque tem três cópias);
- Não avaliar quando identificar a pessoa proponente;
- Não pode participar quem submeteu atividades;

**Comment by anadulce** [comment]
Sobre o ponto 1, as palestras devem ser avaliadas três vezes, mas uma por cada pessoa diferente. Então foi isso que que dizer sobre não avaliar a mesma palestra duas vezes.

**Comment by cecivieira** [comment]
@anadulce então precisa de 600 avaliações?
Talvez seja mesmo uma voa ideia abrir para a comunidade no geral.

**Comment by alynnefs** [comment]
@cecivieira, são as 200 da planilha. As que não foram avaliadas estão com 3 links diferentes, as que foram avaliadas uma vez têm 3 links e por aí vai. Ainda assim são muitas avaliações

**Comment by cecivieira** [comment]
Atividade concluída.
Necessário envio de e-mail para pessoas selecionadas incluindo o formulário de coleta de informações #125

**Comment by alynnefs** [comment]
Ainda faltam os tutoriais
