### ISSUE TITLE
Parceria com Elleve

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#220]
### Descrição
Iniciar o processo de patrocínio com a Elleve

### Requisitos para a atividade ser considerada como concluída

Contrato assinado e pagamento recebido do patrocínio + Form recebido com o tutorial (caso haja)

Ticket #7263 - Elleve representada por Pedro Martins

**Comment by alynnefs** [comment]
@tiidadavena enviou o plano de patrocínio em inglês e português

**Comment by tiidadavena** [comment]
Email de resposta da empresa:

"Não seis e você entendeu bem, nós proporcionamos apoio financeiro aos alunos parcelando os cursos em até 24x e ao mesmo tempo antecipamos os recebíveis para a escola.
 
Faria sentido marcarmos um call na semana que vem para ver se funcionaria uma parceria?"

**Comment by tiidadavena** [comment]
@alynnefs segue proposta de devolutiva:

"Agradecemos o interesse em colaborar junto com a Python Brasil 2021! 
Entretanto, a APyB e o seu maior evento não visam fins lucrativos e apoiamos instituições e empresas com interesses alinhados com os valores da comunidade open source. Não realizamos parcerias para descontos e processos afins porque entendemos que o evento é voltado para produzir conteúdo gratuito e fomentar o conhecimento dos participantes."
