### ISSUE TITLE
Patrocínio com VanHack

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#221]
### Descrição
Iniciar o processo de patrocínio com a VanHack

### Requisitos para a atividade ser considerada como concluída

Contrato assinado e pagamento recebido do patrocínio + Form recebido com o tutorial (caso haja)

Ticket #7220 - VanHack representada por Julia

**Comment by alynnefs** [comment]
@cecivieira respondeu o e-mail perguntando o melhor horário para conversar

**Comment by tiidadavena** [comment]
Eles ainda não responderam. Posso enviar email para eles amanhã

**Comment by cecivieira** [comment]
Acho que podemos abstrair/deixar para lá, pois o e-mail que enviei foi o segundo.
Deza mandou e-mail fazendo a ponte, a pessoa da VanHack não respondeu, daí eu mandei um outro e-mail falando algo como "oi, estamos aqui. quer conversar?"

**Comment by tiidadavena** [comment]
> Acho que podemos abstrair/deixar para lá, pois o e-mail que enviei foi o segundo.
> Deza mandou e-mail fazendo a ponte, a pessoa da VanHack não respondeu, daí eu mandei um outro e-mail falando algo como "oi, estamos aqui. quer conversar?"

Bem observado, Ana!

**Comment by tiidadavena** [comment]
@alynnefs posso fechar a issue devido à ausência de resposta da VanHack?

**Comment by alynnefs** [comment]
Vou fechar, qualquer coisa a gente abre de novo
