### ISSUE TITLE
Divulgação de patrocinador - Buser

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#222]
### Campanha
Divulgação da Buser, que é patrocinador prata.
  
### Peça/publicidade solicitada
3 Cartões - 1 para lançar antes do evento, 1 durante e 1 depois (agradecimento)

### Detalhamento do uso
Arte para divulgação dos patrocinadores, acredito que um modelo só resolva para as 3 cotas

### Data prevista para uso da arte
15 de setembro de 2021
entre 11 e 17 de outubro de 2021
até 24 novembro de 2021

### Quais informações devem aparecer na arte
Cota de patrocínio: prata

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Os 3 cards editáveis estão aqui: https://www.canva.com/design/DAEpEvgaWm8/Hs6qN0WC8gUduY5hrnj0bQ/edit

![Patrocinadores - Cards](https://user-images.githubusercontent.com/45003095/132106248-c60a1eb5-0ff5-4661-a3ea-c2ff09ddac4c.png)

**Comment by alynnefs** [comment]
@cmdiasbr isso foi absurdamente rápido 😱
Foi tranquilo encontrar a logo? Eu ia mandar depois

**Comment by cmdiasbr** [comment]
Tirei o dia hoje pra fazer as artes pendentes 😅 eu fiquei com medo de errar as logos, então se puderem pelo menos colocar o link do site do patrocinador, eu me viro para achar a logo (para que eu não acabe errando o patrocinador)

**Comment by cecivieira** [comment]
Sugiro solicitar as informações da empresa patrocinadora, assim como foi feito com a JusBrasil.
O formulário utilizado foi esse:
https://forms.gle/HtsbnSnaEdB2C8XF7

@tiidadavena

**Comment by alynnefs** [comment]
@cecivieira, respondendo eu percebi que não enviei o formulário ainda. Mas a logo do site é essa mesma, posso editar se eles mandarem outra (:

**Comment by cecivieira** [comment]
Seria interessante mandar o formulário e só divulgar arte após a coleta dessa informação.

**Comment by cecivieira** [comment]
@tiidadavena tu mandou o formulário para a empresa? Se não, poderia mandar, por favor?

**Comment by tiidadavena** [comment]
> @tiidadavena tu mandou o formulário para a empresa? Se não, poderia mandar, por favor?

Enviando agora

**Comment by tiidadavena** [comment]
> > @tiidadavena tu mandou o formulário para a empresa? Se não, poderia mandar, por favor?
> 
> Enviando agora

Enviado

**Comment by deboraazevedo** [comment]
aguardando as próximas informações para agendar o post :)

**Comment by cecivieira** [comment]
@deboraazevedo se tu fizer, por favor atualiza a issue #227 
Essa daqui é só solicitando a arte.

**Comment by cecivieira** [comment]
logos informadas pela patrocinadora:
![image](https://user-images.githubusercontent.com/30605862/132887618-04d4ba37-c41e-48fc-89f7-2e8e61f3cf3c.png)
![image](https://user-images.githubusercontent.com/30605862/132887637-6715a820-8d06-41fc-b697-dca19ecf0808.png)

**Comment by cecivieira** [comment]
Imagens substituídas nas artes e postagens agendadas

**Comment by cecivieira** [comment]
https://www.instagram.com/p/CTphrJygPq9/
https://www.facebook.com/pythonbrasil/photos/a.582882565067606/4637506202938535/
https://www.linkedin.com/feed/update/urn:li:activity:6842140870343434240
https://twitter.com/pythonbrasil/status/1436376150343929906
