### ISSUE TITLE
Jusbrasil: Cumprimento de contrapartida do patrocínio ouro

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#226]
### Descrição
Cumprir compromissos contratuais do patrocínio ouro.

### Requisitos para a atividade ser considerada como concluída
(template #138)

**Ouro**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Exposição da marca durante toda a grade de palestra (background do StreamYard)
- [ ] Apresentação do vídeo institucional na abertura das Keynote
- [ ] Post nas redes sociais antes do evento
- [ ] Post nas redes sociais durante o evento
- [ ] Post nas redes sociais pós evento
- [ ] Post nas redes sociais com vídeo da patrocinadora
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord
- [ ] Exposição da marca em toda comunicação via e-mail para participantes e facilitadoras de atividades

**Comment by cecivieira** [comment]
**Ouro**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Exposição da marca durante toda a grade de palestra (background do StreamYard)
- [ ] Apresentação do vídeo institucional na abertura das Keynote
- [x] Post nas redes sociais antes do evento
- [x] Post nas redes sociais durante o evento (agendado)
- [x] Post nas redes sociais pós evento (agendado)
- [x] Post nas redes sociais com vídeo da patrocinadora (agendado)
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord
- [ ] Exposição da marca em toda comunicação via e-mail para participantes e facilitadoras de atividades

**Comment by cecivieira** [comment]
Vídeo:

Facebook: https://www.facebook.com/story.php?story_fbid=4675185352503953&id=328258703863328&scmts=scwspsdd

Twitter: https://twitter.com/pythonbrasil/status/1440648338148237322?s=19

LinkedIn: https://www.linkedin.com/posts/apyb_conhe%C3%A7a-um-pouco-mais-da-jusbrasil-patrocinadora-activity-6846414028634386432-ulLC


Instagram: Não realizado (vídeo enviado pela patrocinadora extrapola 15 segundos do tempo limite informado. Então, o vídeo não é suportado pela plataforma Instagram)

**Comment by cecivieira** [comment]
**Ouro**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Exposição da marca durante toda a grade de palestra (background do StreamYard)
- [ ] Apresentação do vídeo institucional na abertura das Keynote
- [x] Post nas redes sociais antes do evento
- [x] Post nas redes sociais durante o evento (agendado)
- [x] Post nas redes sociais pós evento (agendado)
- [x] Post nas redes sociais com vídeo da patrocinadora (agendado)
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord
- [x] Exposição da marca em toda comunicação via e-mail para participantes e facilitadoras de atividades

**Comment by alynnefs** [comment]
@cecivieira acho que não dava pra agendar, mas deu pra postar no instagram: https://www.instagram.com/tv/CUH5ptUA4FH/?utm_medium=share_sheet

**Comment by alynnefs** [comment]
**Ouro**
- [ ] Agradecimento no início de cada dia de evento
- [x] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Exposição da marca durante toda a grade de palestra (background do StreamYard)
- [ ] Apresentação do vídeo institucional na abertura das Keynote
- [x] Post nas redes sociais antes do evento
- [x] Post nas redes sociais durante o evento (agendado)
- [x] Post nas redes sociais pós evento (agendado)
- [x] Post nas redes sociais com vídeo da patrocinadora (agendado)
- [ ] Job fair
- [ ] Tutorial
- [x] Canal exclusivo no Discord
- [x] Exposição da marca em toda comunicação via e-mail para participantes e facilitadoras de atividades

**Comment by cecivieira** [comment]
**Ouro**
- [x] Agradecimento no início de cada dia de evento
- [x] Exposição da marca no site
- [x] Exposição da marca durante os intervalos das palestras
- [x] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [x] Exposição da marca durante toda a grade de palestra (background do StreamYard)
- [x] Apresentação do vídeo institucional na abertura das Keynote
- [x] Post nas redes sociais antes do evento
- [x] Post nas redes sociais durante o evento (agendado)
- [x] Post nas redes sociais pós evento (agendado)
- [x] Post nas redes sociais com vídeo da patrocinadora (agendado)
- [x] Job fair
- [x] Tutorial
- [x] Canal exclusivo no Discord
- [x] Exposição da marca em toda comunicação via e-mail para participantes e facilitadoras de atividades
