### ISSUE TITLE
Buser: Cumprimento de contrapartida do patrocínio prata

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#227]
### Descrição
Cumprir compromissos contratuais do patrocínio prata.

### Requisitos para a atividade ser considerada como concluída

(template #138)

**Prata**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Post nas redes sociais antes do evento
- [ ] Post nas redes sociais durante o evento
- [ ] Post nas redes sociais pós evento
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord

**Comment by cecivieira** [comment]
Aguardando confirmação das informações da issue #222

**Comment by cecivieira** [comment]
**Prata**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [x] Post nas redes sociais antes do evento
- [x] Post nas redes sociais durante o evento (agendada)
- [x] Post nas redes sociais pós evento (agendada)
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord

**Comment by tiidadavena** [comment]
Escala da Job Fair da Buser:
[Escala Job Fair Python Brasil 2021.xlsx](https://github.com/pythonbrasil/pybr2021-org/files/7314325/Escala.Job.Fair.Python.Brasil.2021.xlsx)

**Comment by tiidadavena** [comment]
@cecivieira vcs receberam o tutorial?

**Comment by tiidadavena** [comment]
Ticket 7619 no Freshdesk

**Comment by alynnefs** [comment]
> > @tiidadavena eu tinha mandado. Eles pediram ou é só pra registrar?
> > Submeteram tutorial sim (:
> 
> Eles perguntaram pq o tutorial deles não consta na grade

na grade tava só Job Fair, mas a Ceci tá fazendo 💙

**Comment by cecivieira** [comment]
**Prata**
- [x] Agradecimento no início de cada dia de evento
- [x] Exposição da marca no site
- [x] Exposição da marca durante os intervalos das palestras
- [x] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [x] Post nas redes sociais antes do evento
- [x] Post nas redes sociais durante o evento (agendada)
- [x] Post nas redes sociais pós evento (agendada)
- [x] Job fair
- [x] Tutorial
- [x] Canal exclusivo no Discord
