### ISSUE TITLE
Ebury: Cumprimento de contrapartida do patrocínio prata

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#228]
### Descrição
Cumprir compromissos contratuais do patrocínio prata.

### Requisitos para a atividade ser considerada como concluída

(template #138)

**Prata**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Post nas redes sociais antes do evento
- [ ] Post nas redes sociais durante o evento
- [ ] Post nas redes sociais pós evento
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord

**Comment by cecivieira** [comment]
@alynnefs esse dinehiro já caiu na conta?

**Comment by alynnefs** [comment]
@cecivieira vou gerar a nota daqui a pouco, criei a issue pra adiantar. Vou deixar como bloqueado

**Comment by cecivieira** [comment]
Contrato assinado #185

**Comment by cecivieira** [comment]
**Prata**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [x] Post nas redes sociais antes do evento (agendado)
- [x] Post nas redes sociais durante o evento (agendado)
- [x] Post nas redes sociais pós evento (agendado)
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord

**Comment by cecivieira** [comment]
**Prata**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [x] Post nas redes sociais antes do evento (agendada)
- [x] Post nas redes sociais durante o evento (agendada)
- [x] Post nas redes sociais pós evento (agendada)
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord

**Comment by cecivieira** [comment]
**Prata**
- [x] Agradecimento no início de cada dia de evento
- [x] Exposição da marca no site
- [x] Exposição da marca durante os intervalos das palestras
- [x] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [x] Post nas redes sociais antes do evento
- [x] Post nas redes sociais durante o evento (agendada)
- [x] Post nas redes sociais pós evento (agendada)
- [x] Job fair
- [x] Tutorial
- [x] Canal exclusivo no Discord
