### ISSUE TITLE
Sugerir e escolhar organização para receber doações

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#230]
### Descrição
* Elencar sugestões e escolher  as organizações para receber as doações do evento;
* Organizações ligadas a campanha da fome;

### Requisitos para a atividade ser considerada como concluída
* Ter uma lista de organizações e a escolhida para doações

**Comment by Flaviasv** [comment]
Sugestão:
https://acervo.temgentecomfome.com.br/

**Comment by cecivieira** [comment]
MTST - Cozinhas solidárias

https://apoia.se/cozinhasolidaria

**Comment by gabubellon** [comment]
https://www.acaodacidadania.org.br/

**Comment by gabubellon** [comment]
https://bancodealimentos.org.br/junte-se-a-causa/

**Comment by gabubellon** [comment]
http://br.stop-hunger.org/home.html

**Comment by gabubellon** [comment]
https://www.maesdafavela.com.br/

**Comment by tiidadavena** [comment]
Apoio muito a Tem gente com fome (Mantêm o site atualizado e sem meta financeira atingida) e a Mães da Favela (público-alvo altamente prejudicado pela pandemia).+

**Comment by gabubellon** [comment]
https://www.temgentecomfome.com.br/

**Comment by alynnefs** [comment]
Mães da Favela foi a ONG escolhida
