### ISSUE TITLE
Fazer bot para confirmar inscrição no Discord

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#232]
### Descrição
A ideia de @gabubellon foi atrelar o código de inscrição do EventBrite com a entrada da participante no servidor da PyBr2021.

### Requisitos para a atividade ser considerada como concluída

- Bot para discord que checa  a inscrição da participante no Eventbrite

**Comment by gabubellon** [comment]
@anadulce preciso de ajuda aqui pra ter acesso a API do eventbrite

**Comment by gabubellon** [comment]
https://www.eventbrite.com/platform/api#/reference/attendee/retrieve/list-attendees-by-event

**Comment by gabubellon** [comment]
Recuperar a listagem de pessoas é ok, usando o seguinte get

```
https://www.eventbriteapi.com/v3/events/<id_event>/attendees/?token=<Token>
```

**Comment by gabubellon** [comment]
Já envia pra uma planilha https://github.com/gabubellon/eventbrite-to-sheets

**Comment by cecivieira** [comment]
Talvez eu consiga ajudar @gabubellon 
É pra ler o último link que tu mandou aqui e seguir as instruções?

**Comment by gabubellon** [comment]
Convites para mesa de Educação não fomal enviados e 90% respondidos

**Comment by gabubellon** [comment]
Envia dados do eventbrite para o sheeets https://github.com/gabubellon/eventbrite-to-sheets

Criador de certificados com base em uma planilha https://github.com/gabubellon/certificates-google-sheets-generator

**Comment by alynnefs** [comment]
Esse bot é o mesmo que será usado na inscrição dos tutoriais? Se sim, essa issue pode estar relacionada #238
