### ISSUE TITLE
Arte com resumo do evento (divulgação com apoiador(a))

### ISSUE THREAD

**Issue by paulohenriquedsgn** [pythonbrasil/pybr2021-org#234]
### Campanha
Divulgação da Python Brasil 2021 pelos patrocinadores
  
### Peça/publicidade solicitada
Arte para publicação em redes sociais

### Detalhamento do uso
A arte será utilizada pelos apoiadores para divulgação do evento em suas redes sociais. É necessário que seja deixado um espaço para que o apoiador(a) insira a sua logo

### Data prevista para uso da arte
O mais breve possível

### Quais informações devem aparecer na arte
*Informe as informações que você imagina que deva conter na arte*

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by paulohenriquedsgn** [comment]
![AF19B6CF-AB22-497C-B1CC-AD7C058E8B09](https://user-images.githubusercontent.com/64554724/132880372-c09459d2-8387-4b87-855b-956d15265843.jpeg)


@cmdiasbr o pessoal da Todas as Letras pediu uma arte com um resumo do evento e um espaço para inserir a logo deles para poderem compartilhar a PyBr2021. Pode ser algo parecido com essa imagem em anexo, assim que você puder ver, por favor.

**Comment by cmdiasbr** [comment]
Card 17: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

![patrocinio](https://user-images.githubusercontent.com/45003095/132903699-eb3f9bd4-4fe5-4d40-beba-13965387021e.png)

**Comment by paulohenriquedsgn** [comment]
@cmdiasbr ficou ótima assim e o espaço pra colocar o apoio tá com fundo rosa e contrasta com a logo do Todas as Letras

**Comment by paulohenriquedsgn** [comment]
@cmdiasbr obrigado :)

**Comment by cecivieira** [comment]
@tiidadavena seguem imagem e texto sugerido para empresas fazerem a divulgação:
"Abertas as inscrições para a Python Brasil 2021!! 
O evento será online e gratuito. 
Além de se inscrever para a #PyBR2021 você também pode contribuir para combater à fome no Brasil.

Para mais informações acesse: https://2021.pythonbrasil.org.br/"

![image](https://user-images.githubusercontent.com/30605862/133175425-750c310c-dc34-47fb-85d1-a35c00b42a36.png)
![image](https://user-images.githubusercontent.com/30605862/133175439-8d9f63f6-e341-4cde-877c-ecf7931a505b.png)
![image](https://user-images.githubusercontent.com/30605862/133175451-2484aaee-35e1-4d56-9c97-e35209660469.png)

**Comment by alynnefs** [comment]
@cecivieira devemos mudar de "apoio" para "patrocinador" ou a ideia era deixar assim mesmo?

**Comment by cecivieira** [comment]
@alynnefs bem obervado. Vou fazer a alteração

**Comment by paulohenriquedsgn** [comment]
@alynnefs e @cecivieira no caso do Todas as Letras seria apenas para apoio mesmo. As demais podem utilizar patrocinador

**Comment by cecivieira** [comment]
@alynnefs imagens atualizadas

**Comment by tiidadavena** [comment]
@alynnefs @cecivieira as artes devem ser divulgadas para as empresas que ainda estão processo de patrocínio?
 
Para elas, já tinha enviado texto na semana passada, mas sem imagem.

Foram enviados os emails para os patrocinadores confirmados até a data de hoje: JusBrasil, Buser e Ebury

**Comment by cecivieira** [comment]
Como tem a logo das empresas, acho que seria interessante esperar o contrato assinado.

**Comment by cecivieira** [comment]
@tiidadavena arte para ser enviada à patrocinadora com a sugestão de legenda:

"Abertas as inscrições para a Python Brasil 2021!!
O evento será online e gratuito.
Além de se inscrever para a #PyBR2021 você também pode contribuir para combater à fome no Brasil.

Para mais informações acesse: https://2021.pythonbrasil.org.br/"


![image](https://user-images.githubusercontent.com/30605862/134042630-96a17daf-ccdb-4d64-866c-ef25484c060a.png)
