### ISSUE TITLE
Divulgação de patrocinador - Ebury

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#235]
### Campanha
Divulgação da Ebury, que é patrocinador prata.
  
### Peça/publicidade solicitada
3 Cartões - 1 para lançar antes do evento, 1 durante e 1 depois (agradecimento)

### Detalhamento do uso
Arte para divulgação dos patrocinadores, acredito que um modelo só resolva para as 3 cotas

### Data prevista para uso da arte
15 de setembro de 2021
entre 11 e 17 de outubro de 2021
até 24 novembro de 2021

### Quais informações devem aparecer na arte
Cota de patrocínio: prata

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by alynnefs** [comment]
acho que ainda não responderam o formulário com a logo

**Comment by cecivieira** [comment]
@alynnefs não responderam. Quando fizerem, coloco a logo aqui e substituo nas artes, caso já estejam prontas

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/133151691-8c58674e-31c0-4384-8e34-c2ecdcb4e9a5.png)

**Comment by cecivieira** [comment]
Link para logo marca no Drive:
https://drive.google.com/file/d/11ip3GOscURVEcUXCKtgoEwkBaP2dv4k6/view

**Comment by cmdiasbr** [comment]
Para edição: https://www.canva.com/design/DAEpEvgaWm8/Hs6qN0WC8gUduY5hrnj0bQ/edit

![Patrocinadores - Cards (1)](https://user-images.githubusercontent.com/45003095/133163793-7b798b4b-1b2e-45b2-9df1-ca01e42ca5d2.png)

**Comment by cecivieira** [comment]
@cmdiasbr A Ebury é uma empresa de soluções financeiras. Tu poderia deixar a propaganda mais aleatória? Duas delas remetem a logística, entrega de pacotes.

Guarda essas artes dos pacotes para usar na divulgação do Mercado Livre (estamos quase assinando o contrato).

*** Agendei essa que tá explicitada na issue para sair na quarta-feira.

**Comment by cmdiasbr** [comment]
atualizado @cecivieira

**Comment by cecivieira** [comment]
https://twitter.com/pythonbrasil/status/1438155926364688387
https://www.instagram.com/p/CT2LdypMN5Z/
