### ISSUE TITLE
Criar badge eFlag + Python Brasil

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#237]
### Campanha
sem campanha
  
### Peça/publicidade solicitada
- Criar logo/badge da eFlag, comunidade que organizará a CTF. A badge deve conter a logo deles e a nossa ou algo que informe a parceria.
- Card para divulgação do CTF

### Detalhamento do uso
A logo será adicionada na plataforma deles.
O card será usado para divulgar a competição nas redes sociais da Python Brasil.

### Data prevista para uso da arte
27 de setembro

### Quais informações devem aparecer na arte
Badge: as logos da eFlag e da Python Brasil ou algo equivalente que identifique os dois
Card:
- logo e data da competição: 16 e 17 de outubro
- "Mais informações em breve" 

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by alynnefs** [comment]
![eflag_logo](https://user-images.githubusercontent.com/17454743/133174630-4d9037cb-601e-4095-9762-093d6cc22a11.png)

[pasta com arquivo em svg e png](https://drive.google.com/drive/folders/1MmfAZvhtzR9Sb76cswKz5EE9susAcnAZ?usp=sharing). As cores podem ser alteradas

**Comment by fguisso** [comment]
Alguns exemplos de badges dos nossos eventos passados:
<img src="https://user-images.githubusercontent.com/5755568/133174895-49cd7e8c-2ade-4e9c-b6af-b8e21a89d1a3.png" width="250">
<img src="https://user-images.githubusercontent.com/5755568/133174902-01f66589-d3fe-4bf1-b1a4-08285971c984.png" width="250">
<img src="https://user-images.githubusercontent.com/5755568/133174908-0089edf4-06f4-4b3a-9a74-529935889e3d.png" width="250">

**Comment by cmdiasbr** [comment]
Card 21: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit
![Cards Gerais (1)](https://user-images.githubusercontent.com/45003095/133910783-1aef10bd-6196-4a78-a4f2-15742e62f3e4.png)

**Comment by cmdiasbr** [comment]
Badge:

![capture-flag-2021](https://user-images.githubusercontent.com/45003095/133910794-4c4d0f6c-7ea8-424b-aaf8-4514fd99ed20.png)

**Comment by cmdiasbr** [comment]
Badge png: 
https://drive.google.com/file/d/1eY4jkJAkMLk7BHUVIDQOm43MP_RWcO52/view?usp=sharing

![capture-flag-2021](https://user-images.githubusercontent.com/45003095/133910829-a4f1bae1-4256-4955-9a5a-f01f21dd45ea.png)

**Comment by fguisso** [comment]
Boa tarde pessoa, passei a arte aqui para o designer q fez a nossa logo e ele fez algumas alterações, então estou enviando aqui pra ver se podemos utilizar esta versão:

Card
![CAPTURE THE FLAG](https://user-images.githubusercontent.com/5755568/134369964-9c5ef953-0e65-4a6b-b7cc-bbd8f53956fb.png)

Badge
![CAPTURE THE FLAG2](https://user-images.githubusercontent.com/5755568/134370965-39170de4-8e22-4799-9535-9d24c9cdddb5.png)

**Comment by cecivieira** [comment]
@cmdiasbr tu poderia dá uma olhada e responder?

**Comment by cmdiasbr** [comment]
Ficaram ótimas, por mim pode ser @cecivieira @fguisso

**Comment by cmdiasbr** [comment]
@fguisso se possível, só aumentem as logos

**Comment by fguisso** [comment]
@cmdiasbr certo, vou pedir pra alterar, poderia me passar por favor a logo em alta qualidade, facilitaria pra aumentar sem perder a qualidade

**Comment by cmdiasbr** [comment]
@fguisso
![logo-python](https://user-images.githubusercontent.com/45003095/134381872-9bc637ec-1103-417f-961f-14299b567591.png)

**Comment by fguisso** [comment]
![pybr2021-eflag](https://user-images.githubusercontent.com/5755568/134414818-f5d29ef9-9efd-4a60-869b-94ecd4ffd328.png)
![CAPTURE THE FLAG (1)](https://user-images.githubusercontent.com/5755568/134414858-d34ea6f7-5df5-4857-a1d2-d0295c46e5a3.png)

Ta bom assim @cmdiasbr ?

**Comment by cmdiasbr** [comment]
Sim, está ótimo. Obrigada! @fguisso

**Comment by fguisso** [comment]
@cmdiasbr eu pedi pro pessoal nosso fazer mais uns dois cards pra divulgar em momentos diferentes, posso compartilhar aqui nesta mesma issue depois pra vc aprovar, ou precisa abrir outra?

**Comment by cmdiasbr** [comment]
> @cmdiasbr eu pedi pro pessoal nosso fazer mais uns dois cards pra divulgar em momentos diferentes, posso compartilhar aqui nesta mesma issue depois pra vc aprovar, ou precisa abrir outra?

Pode ser aqui mesmo. 🙂

**Comment by alynnefs** [comment]
@fguisso se não for pedir muito, nos outros cards pode ter bonecos de outro gênero e/ou de outra cor de pele? a gente tem umas imagens caso precisem
