### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#24]
[Repositório para o site](https://github.com/pythonbrasil/pybr2021-site)

**Comment by alynnefs** [comment]
task relacionada: #56

**Comment by alynnefs** [comment]
possível referência
https://github.com/pythonbrasil/pythonbrasil14-site

**Comment by rougeth** [comment]
Adicionei a Camila como assignee da issue, se não me falha a memória foi isso que conversamos na última reunião.

**Comment by cecivieira** [comment]
Primeira versão do site https://github.com/pythonbrasil/pybr2021-site/pull/4 com publicação em andamento
