### ISSUE TITLE
Definir horário de abertura de paletras relâmpago

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#242]
### Descrição
Verificar funcionamento do bot para inscrição de palestra relâmpago, definir regras e horário de abertura.

### Requisitos para a atividade ser considerada como concluída

- Regras explícitas
- Horário definido

**Comment by jsbueno** [comment]
Pessoal - só vi duas issues públicas sobre palestras relâmpago  - tenho uma sugestão importante, que tem a ver com as regras:
Na última Python brasil presencial, em 2019, as palestras relâmpago eram de 3 minutos, em vez dos tradicionais 5 minutos. (em 2020 eu não participei das sessões, não me lembro) - 3 minutos  é suficiente para falar que existe um projeto legal e o que ele faz, ou divulgar um evento, mas na prática inviabiliza qualquer palestra tecnica - seja com live coding, seja uma demonstração de slides com algum código.  E essas são as palestras mais legais. 


Então, se a org atual estiver trabalhando com "3 minutos", acho que seria legal uma opção de "5 minutos" - e  deixar o apresentador escolher quanto tempo precisa no ato de inscrição.

**Comment by deboraazevedo** [comment]
acredito que pra fins de organização, é melhor fechar 3 ou 5 minutos mesmo, ao invés de usar os dois tempos, pra ter um número provavel de palestras fechado para cada dia sem depender de quem escolhe 3 ou 5 minutos

**Comment by alynnefs** [comment]
Sobre o horário: eu tava considerando os horários que usaram pra pedir orçamento

![image](https://user-images.githubusercontent.com/17454743/133864749-df88dda4-cd25-4c31-9592-42d0369c86fd.png)

Sobre o bot: ele funcionou bem na Python Nordeste, vocês estão pensando em adicionar alguma regra?

**Comment by alynnefs** [comment]
iniciar as inscrições às 18:20, junto com o início da última palestra
