### ISSUE TITLE
Divulgação Palestra relâmpago

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#243]
### Campanha
nenhuma
  
### Peça/publicidade solicitada
1 cartão

### Detalhamento do uso
Divulgar que esse ano haverá palestras relâmpagos das 19h às 20h

### Data prevista para uso da arte
01 outubro 

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [x] Discord PyBr2021;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
Com a arte pronta, agendar disparos diários no canal geral do Discord com regras, indicando canal para inscrição e link do keynote.

**Comment by cecivieira** [comment]
Ver detalhes em #242 antes de escrever a legenda para as redes sociais

**Comment by cmdiasbr** [comment]
Card 20: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit
![relampago](https://user-images.githubusercontent.com/45003095/133910067-24306713-3da1-441b-8e84-0100da1b1efb.png)

**Comment by alynnefs** [comment]
pode postar?

**Comment by cecivieira** [comment]
Sim

**Comment by deboraazevedo** [comment]
postagens agendadas para 05/10, 07/10, 12/10
