### ISSUE TITLE
Criar roteiro para palestra de keynotes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#247]
### Descrição
Criar roteiro para rodas de conversas usando como base [o de palestra](https://github.com/pythonbrasil/pybr2021-org/blob/main/roteiros/palestra-transmissao-ao-vivo.md).
Requisito:
Cumprir requisitos para as patrocinadoras #138 

### Requisitos para a atividade ser considerada como concluída
- Roteiro
- Publicar no repositório (https://github.com/pythonbrasil/pybr2021-org/tree/main/roteiros)

**Comment by alynnefs** [comment]
passar os vídeos institucionais

**Comment by alynnefs** [comment]
[PR pra revisão](https://github.com/pythonbrasil/pybr2021-org/pull/277)
