### ISSUE TITLE
Divulgação de patrocinador - Carta

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#253]
### Campanha
Divulgação da Carta, que é patrocinadora ouro.
  
### Peça/publicidade solicitada
3 Cartões - 1 para lançar antes do evento, 1 durante e 1 depois (agradecimento)

### Detalhamento do uso
Arte para divulgação dos patrocinadores.

### Data prevista para uso da arte
27 de setembro de 2021
entre 11 e 17 de outubro de 2021
até 24 outubro de 2021

### Quais informações devem aparecer na arte
Cota de patrocínio: ouro
Ainda não temos a logo. Assim que enviarem postarei nos comentários

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by alynnefs** [comment]
Aguardando logo

**Comment by cmdiasbr** [comment]
@alynnefs o que isso tem de diferente desse? https://github.com/pythonbrasil/pybr2021-org/issues/241 

#241 Divulgação de patrocinador - LuizaLabs

**Comment by alynnefs** [comment]
@cmdiasbr esse é da Carta, esqueci de mudar na descrição depois de colar

**Comment by cecivieira** [comment]
logo da empresa:
![image](https://user-images.githubusercontent.com/30605862/134397483-37558173-3bc0-4b39-80ae-1d0e6fc905a4.png)

**Comment by alynnefs** [comment]
@cmdiasbr precisa de algo pras artes da Carta?

**Comment by cmdiasbr** [comment]
A partir do card 16: https://www.canva.com/design/DAEpEvgaWm8/Hs6qN0WC8gUduY5hrnj0bQ/edit
![HUE](https://user-images.githubusercontent.com/45003095/135956022-c359b357-0f90-49c8-96e4-4bd419dba7d9.png)

**Comment by cecivieira** [comment]
Postagens agendadas
