### ISSUE TITLE
Arte para informações sobre doações

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#254]
### Campanha
*Informar a comunidade sobre doações*
  
### Peça/publicidade solicitada
*Uma peça com foco na nossa campanha de doação contra fome*

### Detalhamento do uso
*Será utilizada para ser adicionado ao site e as redes sociais para informações sobre as doações*

### Data prevista para uso da arte
26/09

### Quais informações devem aparecer na arte
Uma arte para informar sobre a campanha
Pode ter o seguinte texto melhorado:
As doações vão pra ApyB e a organização junto a ApyB ira repassar a instituição
- O Event Brite cobra a taxa dele além da doação, fazendo com que o valor doado seja o que a pessoa colocou mesmo
- Estamos validando qual insituição e iremos informa ainda esse mês de setembo
- Iremos prestar contas de todos os valores doados pela compra de ingresso (editado)

### Quais formatos necessários
- [X] Quadrado
- [x] Retangular (instagram story)

### Locais para divulgação
- [X] Redes sociais (twitter, facebook e instagram);
- [X] E-mail;
- [X] Discord PyBr2020;
- [X] Grupos do Telegram;
- [X] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Tem logo da apyb? Vou fazer em 2 cards para não ficar poluído, e aí coloquem eles juntos em 1 post só. @gabubellon @cecivieira @alynnefs

**Comment by cecivieira** [comment]
@gabubellon já temos essa arte. O que tu acha de continuar utilizando-a nas redes sociais e nessa issue pedi uma página html para o site?

Vocês acham que precisa de uma nova arte? Ou seria suficiente na legenda dessa arte colocar o link para mais detalhes no site ou, até mesmo, inserí-los dentro da própria legenda?

![image](https://user-images.githubusercontent.com/30605862/134395038-eb0cd423-c858-4b98-aecc-26cc58b82ee9.png)

**Comment by cmdiasbr** [comment]
> @gabubellon já temos essa arte. O que tu acha de continuar utilizando-a nas redes sociais e nessa issue pedi uma página html para o site?
> 
> Vocês acham que precisa de uma nova arte? Ou seria suficiente na legenda dessa arte colocar o link para mais detalhes no site ou, até mesmo, inserí-los dentro da própria legenda?
> 
> ![image](https://user-images.githubusercontent.com/30605862/134395038-eb0cd423-c858-4b98-aecc-26cc58b82ee9.png)

@gabubellon @cecivieira @alynnefs precisa de uma nova arte?

**Comment by gabubellon** [comment]
> > @gabubellon já temos essa arte. O que tu acha de continuar utilizando-a nas redes sociais e nessa issue pedi uma página html para o site?
> > Vocês acham que precisa de uma nova arte? Ou seria suficiente na legenda dessa arte colocar o link para mais detalhes no site ou, até mesmo, inserí-los dentro da própria legenda?
> > ![image](https://user-images.githubusercontent.com/30605862/134395038-eb0cd423-c858-4b98-aecc-26cc58b82ee9.png)
> 
> @gabubellon @cecivieira @alynnefs precisa de uma nova arte?

@cmdiasbr  gera uma versão dela sem o texto por favor ?
É para a interprete de libras usar como fundo

**Comment by gabubellon** [comment]
@cmdiasbr Exatamente ❤️ 
Obrigado

**Comment by alynnefs** [comment]
Como as artes já foram feitas, vou fechar aqui (:
