### ISSUE TITLE
Divulgação de patrocinador - AmbevTech

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#256]
### Campanha
Divulgação da AmbevTech, que é patrocinadora bronze.
  
### Peça/publicidade solicitada
3 Cartões - 1 para lançar antes do evento, 1 durante e 1 depois (agradecimento)

### Detalhamento do uso
Arte para divulgação dos patrocinadores.

### Data prevista para uso da arte
01 de outubro de 2021
entre 11 e 17 de outubro de 2021
até 17 outubro de 2021*

* esqueci de sugerir que o fim do contrato fosse uma semana após o evento, mas vou perguntar se tem problema ser depois

### Quais informações devem aparecer na arte
Cota de patrocínio: bronze
Ainda não temos a logo. Assim que enviarem postarei nos comentários

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/134520194-16500a3c-6e84-4b20-a978-cff7e883bacb.png)

**Comment by cmdiasbr** [comment]
A partir do card 13 aqui https://www.canva.com/design/DAEpEvgaWm8/Hs6qN0WC8gUduY5hrnj0bQ/edit

![Patrocinadores - AMBEVTECH](https://user-images.githubusercontent.com/45003095/135949854-84082263-0644-42a3-8847-af6a3388c664.png)

**Comment by cmdiasbr** [comment]
Obs.: peguem as imagens direto do Canva, pois pode haver atualizações.

**Comment by cecivieira** [comment]
Postagens agendadas
