### ISSUE TITLE
Separar materiais de estudo para time de libras

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#259]
### Descrição
Separar materiais de referencias para equipe de libras

### Requisitos para a atividade ser considerada como concluída

Ter uma pasta no drive com materiais para a equipe de libras estudar o conteudo

- Verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/). Válido para atividades que dependem de imagem, como criação de artes e modificação do site.

**Comment by cecivieira** [comment]
@gabubellon nesse envio, acho que a gente falou que também mandaria os textos das submissões e os textos de confirmação das palestras

**Comment by alynnefs** [comment]
#260
#261
