### ISSUE TITLE
Criar texto para equipe de libras fazer video de propaganda

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#261]
### Descrição
Criar um texto para time de libras fazer um video de chamada para o evento traduzido em libras

### Requisitos para a atividade ser considerada como concluída

Ter um texto para a equipe de libras fazer um video para propagando do evento

**Comment by cecivieira** [comment]
Enviar junto com o texto, um background com identidade visual do evento

**Comment by deboraazevedo** [comment]
A Python Brasil é a maior conferência da linguagem de programação Python da América Latina. É um evento que este ano está acontecendo on-line, de 11 a 17 de outubro. O evento é gratuito, mas este ano estamos incentivando a doação no momento da inscrição para a ONG Mães da Favela, cujo objetivo é combate à fome.
Na Python Brasil são tratados os mais diversos assuntos do ecossistema Python, como carreira, comunidade, educação e assuntos técnicos também. Também teremos uma trilha de palestras em espanhol, para conhecermos o que está sendo feito nos países vizinhos. Teremos conteúdo para todos os  níveis de pública e todas as palestras serão acessíveis com Libras!

O evento é gratuito, se inscrevam e, se puder, doem!

Nos vemos na Python Brasil 2021!

**Comment by gabubellon** [comment]
@deboraazevedo Tá ótimo, mando amanhã pra equide de libras

**Comment by alynnefs** [comment]
posso fechar a issue ou tem algo pendente?
