### ISSUE TITLE
Solicitar arquivos das palestras para time de libras

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#262]
### Descrição
Solicitar que os palestrantes enviem seus slides ou textos de base para apoio do time de libras

### Requisitos para a atividade ser considerada como concluída
* Ter um pasta/formulario para os palestrantes **confirmados** enviarem material previo;
* Solicitar aos palestrantes que enviem informações **para os estudo de libras**;
* Validar os dados enviados
* Enviar os dados para time de libras
* Prazo até 6 de Outubro

**Comment by cecivieira** [comment]
Sugerimos o envio das submissões e resumo curto e longo enviados no formulário de confirmação de atividade
