### ISSUE TITLE
Gravar vídeo de abertura

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#265]
### Descrição
Separar o que cada pessoa vai falar e quem vai participar. Os pontos que lembro:
- Dar as boas vindas aos participantes; @alynnefs 
    - "Olá, eu sou Alynne e gostaria de desejar boas-vindas a todo mundo que já está participando da Python Brasil e pra quem ainda vai participar.""
- Falar o que é a Python Brasil e porque está sendo online @alynnefs 
    - A Python Brasil é um evento anual e, geralmente, ocorre de forma presencial. Entretanto, devido à pandemia, está acontecendo online mais uma vez. Todos os links que serão citados estão na descrição do vídeo.
- Sugerir que se inscrevam se ainda não estiverem inscritos; - @gabubellon 
  - Mostrar link do Eventbrite;
  - Falar sobre as doações e instituição escolhida;
  - "Olá, eu sou o Gabu. Caso você ainda não tenha feito a inscrição, você pode fazer pelo eventbrite. O evento é gratuito, mas este ano estamos incentivando a doação para a ONG Mães da Favela, cujo objetivo é combate à fome. Você pode fazer a doação no momento da inscrição ou durante o evento pelo pix da ONG(vai ter? Se tiver, mostra nessa hora)"

- Explicar que inscrição é necessária para entrar no Discord, pois a comunicação será por lá; - @Rougeth
  - avisar que teremos um checkin no discord superficialmente
  - mostrar e dizer bitly ou equivalente do discord e do vídeo explicando como funciona
  - "Oi, eu sou o Rougeth. A inscrição é necessária para entrar no Discord (mostrar link), já que toda a nossa comunicação será por lá. A inscrição também é necessária caso você deseje receber o certificado."
- Que tipos de atividades existem/onde encontrar tudo - @muriloviana 
  - "Olá, eu sou o Murilo. Serão sete dias de conteúdos, palestras, keynotes, e rodas de conversa de segunda a sexta, sprints e tutoriais no fim de semana. Veja a programação completa no nosso site https://2021.pythonbrasil.org.br/ (mostrar site)" 
- falar sobre as palestras - @anadulce
  - dias, horário de início e fim
  - falar os nomes das trilhas e o nível de cada uma
  - "Oi, eu sou a Ana Dulce. As palestras acontecerão de segunda a sexta. De tarde, o início será às 15h. Durante a noite, começará às 19h (confere se coloquei certo). Nesse ano, as trilhas receberão o nome de mulheres que foram importantes na história da tecnologia, mas que difilcilmente são lembradas.
      - Shirley Ann Jackson: palestras de nível iniciante
      - Marie Van Brittan Brown: palestras de nível intermediário
      - Timnit Gebru: palestras de nível avançado
      - Angelica Ross: palestras de nível não-técnico
      - Bonnie Prado Pinto: palestras em espanhol"
- trilha em espanhol - @cecivieira
  - Tradução simultânea
  - "Olá, eu sou a Ana Cecília. Este ano teremos novidade! Como Ana Dulce disse, teremos uma trilha em espanhol. O objetivo dela é nos aproximar de comunidades-irmãs da América Latina. No Discord tem um canal de voz com tradução simultânea para o português."
- Libras - @dandaramcsousa 
    - "Oi, eu sou a Dandara. Visando tornar mais acessível o conteúdo incrível desse ano, todo o evento terá intérpretes de LIBRAS. Caso você se inscreva para um tutorial e precisa que alguém interprete para você, mande uma mensagem para @organização no discord."
- falar sobre keynotes - @deboraazevedo 
  - O que é um keynote
  - horários de segunda a quinta e horário de sexta
  - dizer quais keynotes são em quais dias (?)
  - "Olá, eu sou a Débora. Os keynotes são as palestras mais esperadas do evento, já que os palestrantes são pessoas que fazem algum trabalho importante para a sociedade através da tecnologia. De segunda a sexta, acontecem a partir das 20:20 e na sexta, começa às 19:00."
- falar sobre tutoriais - @belaaiza 
  - que vai ser no discord
  - como vai funcionar as inscrições
  - que não vai ser gravado
  - que só pode se inscrever para um (seguimos com essa regra?)
  - "Oi, eu sou a Izabela. Os tutoriais acontecerão Discord, assim como toda a comunicação do evento. As inscrições também serão por lá e o conteúdo não será gravado. Para que mais pessoas possam participar dos tutoriais, cada pessoa só pode se inscrever em um. Alguns dos tuoriais são dos nossos patrocinadores, eles vão mostrar tecnologias usadas dentro das respectivas empresas."
- falar sobre sprints e certificados @GabrielRF
  - sprints
    - que vai ser no discord
    - como participar
    - "Olá, eu sou o Gabriel (sobrenome). Sprints são o momento em que a comunidade se une para colaborar em um projeto. Terão pessoas do projeto explicando como ele funciona e o que precisa ser feito, além de ajudar a resolver os problemas propostos. As Sprints também acontecerão no Discord."
  - certificados 
    - quem terá direito
    - quando serão enviados
    - " Todo mundo que se inscrever pelo Eventbrite e entrar no discord terá direito ao certificado. Ele serão enviados por e-mail após o envento. (confirmar informação)"

- falar sobre a mesa redonda - @Flaviasv
  - o que é;
  - onde participar;
  - "Oi, eu sou a Flávia. Mesas Redondas são o momento em que um grupo de pessoas conversa sobre como a tecnologia pode ajudar a sociedade. Elas sempre acontecem às 10h e os temas são:
    - Segunda: AfroPython, apresentando mais a comunidade
    - Terça: APyB, que é a Associação Python Brasil
    - Quarta: Dados abertos, com Gênero e número, Elas no congresso, Fiquem sabendo, Casa Fluminense (tira se alguém não tiver aceitado)
    - Quinta: aprendizagem não formal, com EducaTRANSforma, Quebradev e MSTS Tec
    - Sexta: Segurança da informação com Clara Nobre, Gabi Mobo, Christiane Santos e Marina Ciavatta"
- falar sobre o código de conduta - @julianyraiol 
  - onde encontrar
  - como agir caso ele seja infringido
  - "Oi, eu sou a Juliany. Todo o evento está sob o código de conduta, que pode ser encontrado no link https://python.org.br/cdc/ (mostrar link). É importante que todos leiam e cumpram o que está escrito lá. Caso seja vítima de algum descumprimento ou veja alguém infringido o código, temos esse guia de como agir (mostrar link) ou você pode entrar em contato com alguém que tenha as permissões de '@Código de conduta' no discord e essa pessoa vai te orientar sobre o que deve ser feito."
- Seguir nas redes sociais e usar a nossa hashtag para comentar o evento - @paulohenriquedsgn 
    - "Oi, eu sou o Paulo. Não esqueça de seguir o evento nas redes sociais, @PythonBrasil no instagram e Twitter, e usar a hashtag #PyBR2021. Todos os links estão na descrição do vídeo."
- falar sobre job fair - @apast 
  - como vai funcionar
  - "Olá, eu sou o Pastore. O Job Fair irá funcionar durante o dia inteiro, de segunda a sexta, no discord em um canal de voz chamado 'Job Fair'. Você pode encontrar os horários de cada empresa patrocinadora no nosso site. Cada empresa tem uma hora e meia por dia e esses horários mudam. Caso um horário não dê certo pra você, provavelmente em outro dia dará."
- agradecimentos - @tiidadavena e @Gabrieltggv 
  - patrocinadores - listar cada um, e enfatizar a cota
  - apoiadores - listar
  - pessoas que se disponibilizaram a compartilhar conteúdos no evento (palestrantes/ministrantes/mantenedores)
  - organizadores, que fizeram esse evento sair
  - participantes, porque sem eles, não teríamos porquê organizar o evento <3
  - "Oi, eu sou a Juliana. Gostaria de agradecer às empresas que estão patrocinando a Python Brasil esse ano. Apesar do evento ser gratuito para os participantes, existe um custo por trás e seria inviável sem o apoio dessas empresas. Os patrocinadores ouro são: Jusbrasil, LuizaLabs e Carta. Como patrocinadores prata, temos: Buser, Ebury e Mercado Livre. No patrocínio prata, temos a AmbevTech. Como apoiadores, temos Todas as Letras e Alura (grava esse fim sem a Alura, porque não tá fechado ainda)"
  - "Oi, eu sou o Gabriel (sobrenome). Também gostaria de agradecer a todas as pessoas que estão contribuindo com tempo e conteúdo, seja como palestrante, ministrante de tutorial ou mantenedores de projetos. Também agradecemos a todas as pessoas que submeteram atividades, mas que por limitação de tempo no evento, não foram selecionadas esse ano. Agradecemos também ao time de organização, por ter dedicado tempo e esforço para fazer o evento acontecer. E por último, mas não menos importante, agradecemos a todas as pessoas que estão participando. Sem vocês, nada disso faria sentido."

Por favor completem com o que esqueci <3

### Requisitos para a atividade ser considerada como concluída

- vídeos gravados. Previsão: 06/10

**Comment by alynnefs** [comment]
Não vou colocar como responsáveis porque o limite são 10 pessoas. Caso eu tenha esquecido alguém, me avisem

@rougeth
@apast
@deboraazevedo
@gabubellon
@dandaramcsousa
@anadulce
@belaaiza
@cecivieira
@Gabrieltggv
@muriloviana
@Flaviasv
@eloabe
@GabrielRF
@martinsvanessa
@cmdiasbr 
@paulohenriquedsgn
@julianyraiol (não sei se entra por ser do CDC)

**Comment by alynnefs** [comment]
Rodas de conversa
LIBRAS

**Comment by anadulce** [comment]
Agradecer apoiadores (listar)
Agradecer organizadores (geral)
Agradecer participantes

**Comment by anadulce** [comment]
Falar sobre inscrições se ainda não se inscreveu

**Comment by cmdiasbr** [comment]
Eu e a @martinsvanessa não gostaríamos de participar na gravação esse ano.

**Comment by alynnefs** [comment]
Links
inscrições: https://bit.ly/pybr2021
discord: não tem link geral ainda
site: https://2021.pythonbrasil.org.br/
CDC: https://python.org.br/cdc/
Guia de como agir em caso de infração: falta link da versão atualizada

**Comment by alynnefs** [comment]
Sobre os textos: é só uma sugestão, vocês podem personalizar como quiserem

**Comment by alynnefs** [comment]
[pasta pra colocar os vídeos](https://drive.google.com/drive/u/2/folders/1OiITvZ5vO4sWnHVyrsnrpskhCJfXl_6S)

**Comment by apast** [comment]
Oi!!

Eu consegui gravar, mas meu drive está cheio e não consigo fazer o upload.

Como será que posso fazer? Alguém tem uma sugestão de alternativa?

Obrigado!!!

**Comment by cecivieira** [comment]
@apast coloca nessa pasta:

https://drive.google.com/folderview?id=1ffzsWBV8HZUuxCEaYafJvmnm1KDKGUiX

**Comment by GabrielRF** [comment]
Falei dos certificados e do sprint.
Tem uma parte no meio que pode ser cortada. Precisei reler sobre os sprints.
Qualquer coisa me avisem que refaço. :) 
http://gofile.me/4aexz/ZgmbPWUE3

**Comment by alynnefs** [comment]
@apast me manda pelo telegram

**Comment by cecivieira** [comment]
@apast Também recebo pelo https://wetransfer.com/

**Comment by apast** [comment]
Consegui!!

Apaguei vários conteúdos, spams e afins!! Já estava quase entrando no plano pago!!

@cecivieira, obrigado!! Se nao desse, eu ia publicar nos endereços.

Obrigado pela ajuda!!

**Comment by apast** [comment]
@alynnefs !! Obrigado tb!! Deu certo!
