### ISSUE TITLE
Fluxo de edição e publicação dos vídeos

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#27]
Pessoas, queria iniciar a discussão sobre o processo de edição e publicação das palestras. Esse tópico acaba influenciando (e é influenciado - #12, #11, #10) as ferramentas e serviços que vamos usar. Para quem participou ano passado, me ajudem nos detalhes.

## Como funcionou na Python Brasil 2020
As palestras da Python Brasil 2020 foram publicadas no YouTube, usando o StreamYard. Criamos um stream por dia e por sala e ao final do evento, baixamos todos os arquivos e fizemos enviamos para um bucket S3 (conta da APyB). Um script foi criado para baixar os arquivos de forma automatizada do StreamYard.

Todo fluxo de edição e publicação das palestras da Python Brasil 2020 teve como ponto central uma planilha no Google Sheets. Nessa planilha, tínhamos informações sobre todas as palestras, como nome da pessoa palestrante, título da palestra, sala (virtual), data e horário, etc. Também incluímos na planilha, o tempo de início e fim de cada palestra, levando em consideração o stream no YouTube.

O processo de edição consistiu basicamente em:
1. Cortar os arquivos do StreamYard nos tempos corretos. Cada arquivo representava uma sala em um determinado dia e poderia conter múltiplas palestras.
2. Concatenar cada palestra com o arquivo de abertura. Foi necessário alterar o codec da abertura para facilitar a concatenação (processo não foi documentado).
3. Publicar as palestras no YouTube.

As primeiras palestras foram editadas em nossos computadores, mas a maioria foi feita em uma máquina virtual na AWS para agilizar o processo.

## O que mais deu trabalho
- Preencher a planilha, principalmente os dados para os cortes dos vídeos. Possível solução: dividir trabalho com os hosts, preenchendo quaisquer dados específicos da palestra logo após a palestra terminar.
- Transferência dos vídeos entre máquinas e hosts. StreamYard > Laptop > S3 > EC2 > Laptop > YouTube. Possível solução: Remover laptop do fluxo.
- Lidar com múltiplos arquivos da mesma sala/dia (*adicionado após comentário da @anadulce*)

## O que mais considerar para v2
- Avisos ou anúncios dados pelo host da palestra, relacionados ao evento e não a palestra em si, apareceram nas gravação. Particularmente não acho que seja um problema, mas talvez seja algo simples de resolver com um guia para a pessoa apresentando a palestrante, pendido para fazer uma leve pausa entre os avisos e a apresentação.
- Usar o Google Sheets ajudou muito na automação, mas uma vez com as fórmulas processadas e os dados prontos, foi difícil/lento usar a planilha em modo leitura.
- StreamYard não fornece uma API ou forma automatizada de baixas as palestras.
- Quase perdemos o prazo para download das palestras no StreamYard (1 semana).
- Nas últimas edições, eu estava demorando 1 hora para editar 7 vídeos (considerando todo o fluxo e uma máquina “parruda” no EC2 - c4.8xlarge).

**Comment by anadulce** [comment]
Acho que está muito completo!
A única consideração que consigo lembrar é que as salas do streamyard fecham após algum tempo sem utilização, isso acaba gerando dois vídeos relativo a uma trilha/dia e isso precisa ser tratado também.

**Comment by apast** [comment]
'

**Comment by apast** [comment]
Ótimos pontos para guiar a discussão e otimizarmos a próxima edição.

### Marcas de Início e Término de cada talk
O procedimento de verificação dos tempos dos vídeos no stream do YouTube é manual.

Os tempos são marcados em colunas específicas para `youtube_inicio` e `youtube_termino` na planilha de cada palestra.

No geral, os tempos 0'00'' são equivalentes entre YouTube e StreamYard. No momento da edição, alguns vídeos tiveram diferença de segundos em relação ao tempo 0'00'' do download do StreamYeard.

Sugestão é ter uma coluna para o início do stream do StreamYard (`streamyard_inicio`) para garantia destas excessões.

### Quem pode ajudar a preencher as planilhas de início e fim
No caso da PyBr2020, a verificação dos streams foi simples, no geral realizada por uma pessoa. O esforço é leve, mas será legal adicionar uma revisão por mais de uma pessoa.

### Download de vídeos e audios do StreamYard
O StreamYard mantém o backup das gravações por 15 dias após a transmissão.
Na edição de 2020, os download foram realizados nos últimos dias, correndo o risco de perdermos as gravações originais do StreamYard.
Executar o download ao encerramento de cada dia do evento, diretamente à infraestrutura em nuvem do evento.

O procedimento de extração e processamento dos vídeos possui boa parte automatizada e isto poderá ser melhorado na próxima edição, com algum pipeline completamente automatizado para download, processamento e publicação de todo o material relacionado aos vídeos:
- Durante o dia, os tempos das palestras podem ser atualizados automaticamente no site, com a fonte do stream live do youtube
- Após download e processamento do vídeo completo e Upload do vídeo para YouTube, outras ações podem ser automatizadas no pipeline
  - Atualização do site
  - Atualização do Wiki com as palestras
  - Atualizar qualquer outra midia relacionada, como Twitter, Discord, ...

**Comment by alynnefs** [comment]
Tentei quebrar essas issues, mas eu não estava na reunião #55. Posso considerar as atividades que estão no fim da ata?

**Comment by rougeth** [comment]
Eu criei as issues da outra reunião, e acho que podemos fechar essa também.
