### ISSUE TITLE
Thumbnail para lives no Youtube

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#271]
### Campanha
--
  
### Peça/publicidade solicitada
5 thumnail para youtube

### Detalhamento do uso
Serão usadas para o agendamento das lives para todo o evento.

### Data prevista para uso da arte
imediatamente

### Quais informações devem aparecer na arte
Cada thumbnail deve ter o fundo com a cor correspondente a cada atividade:

keynote e roda de conversa - #ffffff
trilha Shirley Ann Jackson - #476088 (azul escuro)
trilha Timnit Gebru - #ffc562 (amarelo)
trilha Marie Van Brittan Brown - #ff6d74 (rosa)
trilha Bonnie Prado Pinto - #4fddc3 (verde)
trilha Angelica Ross - #61a8e8 (azul)

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [x] Outro *(thumbnail youtube)*

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord PyBr2020;
- [ ] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
Sugestão é editar essa arte
![image](https://user-images.githubusercontent.com/30605862/136048078-ac25d6af-1a4d-4e11-8c26-bc2a7eda9744.png)

**Comment by cmdiasbr** [comment]
Thumbs prontas https://drive.google.com/drive/u/1/folders/1454eulvkOShuP5Jd9vrk9lpdxUROca-o

**Comment by cmdiasbr** [comment]
> @cmdiasbr a trilha de Angelica falta trocar o nome https://drive.google.com/file/d/1_O0YV7HSeraY71UfZGJsPxr-pqWAGDgE/view?usp=sharing
> 
> tem 2 imagens com nome de Bonnie

valeu por avisar, corrigido. :)

**Comment by cecivieira** [comment]
@GabrielRF thumbnails prontas =D
Vê se tu consegue acessar a pasta
