### ISSUE TITLE
Escrever mensagem para canal boas-vindas

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#275]
### Descrição
Escrever mensagem de boas vindas para as novas integrantes do Discord com as seguintes informações:
- regras palestra relâmpago #242 (ver regras)
- pronome
- foto
- tradução simultânea
- interprete de libras (adicionar que caso a pessoa se inscreva no tutorial e precisa de uma interprete, informe a uma das pessoas com o nome azul , que é da organizacao do evento)

### Requisitos para a atividade ser considerada como concluída

- Mensagem criada

**Comment by deboraazevedo** [comment]
Olá! Boas-vindas ao Discord da Python Brasil!

Estamos muito felizes em ter você aqui! Vai aqui algumas informações importantes para todas as participantes do evento:

Pedimos para vocês colocarem uma foto no perfil e o pronome de vocês no nome que é exibido no Discord.  Aqui tem o link de um vídeo de como fazer isso: 

As palestras relâmpago voltaram! São palestras de 5 minutos e podem ser sobre QUALQUER tema (desde que não fira o Código de Conduta (link)

niciar as inscrições às 18:20, junto com o início da última palestra
encerra com a última palestra, às 19:05
palestras com duração de 5 minutos
se inscrever no canal #quero-participar do discord do evento
o link do streamyard será enviado para o perfil das pessoas pelo bot
tempo de resposta para não perder a vaga: 3 minutos

Este ano teremos um trilha de palestras em espanhol, para saber o que as comunidades de países vizinhos estão produzindo Para tornar esse conteúdo mais acessível, contaremos com tradução simultânea do Espanhol para Portugues em todas as nossas palestras.

E falando em acessibilidade, nosso evento também conta com intérprete de Libras. As intérpretes estarão presentes em todas as palestras, e no caso de você se inscrever em um tutorial e precisar de uma interprete, informe a uma das pessoas com o nome azul @Organização, que é da organizacao do evento)

Esperamos que aproveitem bastante mais uma Python Brasil online!

**Comment by deboraazevedo** [comment]
Olá!

Estamos nos preparando para vivenciar mais uma Python Brasil online, muito felizes em ter vocês conosco, aqui no nosso Discord! Será o local onde vamos interagir, conversar, tomar aquela cerveja e ter mais uma experiência #PyBR.

Para dar as boas-vindas, vamos deixar aqui alguns recados importantes sobre o evento:

Pedimos que todas as pessoas do nosso servidor possa colocar uma foto e seus pronomes no seu usuário do Discord, para sabermos como nos dirigir a você. Um tutorial com passo a passo de como fazer isso está aqui (link)

Este ano, ters uma super novidade, que é nossa trilha de palestras em espanhol! Ela foi pensada para que pudéssemos conhecer o que os países vizinhos estão fazendo com Python. Para tornar este conteúdo mais acessível, as palestras dessa trilha contará com tradutoras, que farão a tradução simultânea do espanhol para o português.

E falando em acessibilidade, esse ano todo o nosso evento terá intérpretes de Libras! As instérpretes estarão em todas as palestras, e caso você se inscreva em algum tutorial e precise de interprete, por favor, informe a uma das pessoas com o nome azul @Organização, que é da organizacao do evento)
 
Além disso, as palestras relâmpago estão de volta! Essas são palestras de 5 minutos de duração e podem ser sobre QUALQUER tema (desde que nao fira o nosso Código de Conduta (link)). Para se inscrever, basta ir no canal #quero-participar do Discord do evento; as inscrições iniciam às 18:20, junto com o início da última palestra da tarde. O link do streamyard para fazer a transmissão da palestra será enviado para o perfil das pessoas pelo bot do Discord, e se liga: otempo de resposta para não perder a vaga é de 3 minutos.


Muitas informações né?! Pedimos que leiam tudo com calma, pois tudo foi pensado para que você tenha a melhor experiência no nosso evento. 

Esperamos que você tenha uma ótima Python Brasil!

**Comment by deboraazevedo** [comment]
tô procurando ainda, vou dar scroll nas mensagens do discord pra achar

**Comment by alynnefs** [comment]
Ainda precisam dessa issue ou posso fechar?
