### ISSUE TITLE
Escrever mensagem para canal regras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#276]
### Descrição
Escrever mensagem de boas vindas para as novas integrantes do Discord com as seguintes informações:
- checar inscricao para ter acesso ao conteúdo do servidor
- cdc
- regras inscrições tutoriais
- regras inscrições capture a flag

### Requisitos para a atividade ser considerada como concluída

- Mensagem criada

**Comment by deboraazevedo** [comment]
CANAL DE REGRAS DA PYTHON BRASIL

Pedimos atenção à essa mensagem, pois são regras importantes!

1) Para ter acesso integral à todas as informações do servidor, você precisa estar inscrito da Python Brasil. Caso você não esteja inscrito, não conseguirá acessar os canais do Discord onde interagiremos durante o evento. Então, para ter acesso a o servidores, faça a sua inscrição (aqui)[bit.ly/pybr2021].

2) Todo o nosso evento, mesmo online, segue um (Código de Conduta)[https://python.org.br/cdc/]. É importante que todas as pessoas leiam e fiquem atentas para fazer o ambiente do nosso evento um ambiente seguro e acolhedor.

3) Teremos tutoriais esse ano novamente! Eles estarão informados na programação. Pedimos que fiquem atentos aos nossos bots que serão por onde vocês se inscreveram nos tutoriais. Ao longo do evento, enviaremos as regras de participação, então fiquem ligados!

4) As inscrições para o Capture a flag acontecerão no canal #capture-a-flag! Caso queiram saber mais e se inscrever, cola no canal!
