### ISSUE TITLE
Texto para facilitadoras de sprint e tutorial

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#281]
### Descrição
Redigir texto para informar detalhes sobre como ocorrerão as sprints: plataforma, horário e link para discord

### Requisitos para a atividade ser considerada como concluída

- Texto redigido
- Email enviado para categoria SPRINT do mailchimp

**Comment by cecivieira** [comment]
Olá, *|NAME|*! 


A Python Brasil 2021 está chegando, e a sua presença é muito importante para o evento!

Sua sprint *|TITULO|* está planejada para ocorrer nos horários *|DATA|*, *|HORARIO|* no canal de voz exclusivo para sua atividade. Por isso, solicitamos que você entre no sevidor do evento através do link XXXXXXX .

Por favor, responda este e-mail declarando estar ciente sobre a data e horário da sua sprint.

A Python Brasil 2021 contará com interpretação em LIBRAS em todas as suas palestras, no entanto esse recurso só estará disponível para as sprints e tutoriais sob solicitação de uma participante que necessite dele.

Caso tenha alguma dúvida ou problema, não hesite em nos contatar respondendo a este e-mail.

Aguardaremos ansiosamente pela sua palestra na Python Brasil 2021!
 
Atenciosamente,
Comissão de Organização da Python Brasil 2021

**Comment by anadulce** [comment]
Olá, |NAME|!

A Python Brasil 2021 está chegando, e a sua presença é muito importante para o evento!

Sua sprint/tutorial |TITULO| está planejada para ocorrer nos horários |DATA|, |HORARIO| no canal de voz exclusivo para sua atividade. Por isso, solicitamos que você entre no servidor do evento através do link XXXXXXX . 

Sugerimos que entre em contato conosco pelo Discord em caso de dúvidas. Lá você também poderá ter contato direto e mais rápido com a Organização, basta marcar @organização no canal #ministrantes-pt-br que rapidamente alguma de nós responderá à tua pergunta, e também poderá acessar dúvidas já tiradas por demais ministrantes.

A Python Brasil 2021 contará com interpretação em LIBRAS em todas as suas palestras, no entanto esse recurso só estará disponível para as sprints e tutoriais sob solicitação de uma participante que necessite dele.

Hoje (09/10) às 18h30 teremos uma live para testar toda nossa infraestrutura e tudo mais o que fizer falta. Então, te convidamos a assisti-la e tirar as dúvidas que você já tenha.

Atenciosamente,
Organização da Python Brasil 2021

**Comment by cecivieira** [comment]
email enviado
