### ISSUE TITLE
Texto para envio de links de Streamyard e Discord para ministrantes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#282]
### Descrição
Escrever texto com detalhes de acesso para streamyard e youtube

### Requisitos para a atividade ser considerada como concluída

- texto escrito
- -email enviado para tag ministrantes-pt-es

**Comment by anadulce** [comment]
Olá, |NAME|! Tudo bem?

Falta pouco para a Python Brasil 2021! Esperamos que você esteja tão animada quanto nós pelo evento.

Te informamos que usaremos a plataforma StreamYard para fazer a live. Esperamos que toda a programação ocorra conforme horário planejado, por isso solicitamos que você acesse a plataforma 15 minutos antes da sua palestra usando esse link: |STREAMYARD|.

Pedimos que você assista esse pequeno tutorial sobre como navegar na plataforma e como nos comunicaremos com você durante sua palestra. Além disso, hoje (09/10) às 18h30 teremos uma live para testar toda nossa infraestrutura, roteiro de apresentação de palestra e tudo mais o que fizer falta. Te convidamos a assistí-la e tirar as dúvidas que você já tiver.

A transmissão das palestras será feita pelo Youtube. Fica de olho nas nossas redes sociais (@pythonbrasil) que já já o card de divulgação da tua palestra aparece por lá pra tu compartilhar com todo mundo; nele haverá o link para Youtube, data e horário da tua apresentação.

Toda a interação do evento ocorrerá no Discord, lá você também poderá ter contato direto e mais rápido com a Organização, basta marcar @organização no canal #ministrantes-pt-br que rapidamente alguma de nós responderá à tua pergunta. Para acessar o Discord, usa esse link exclusivo para as ministrantes de atividades. Te esperamos lá! Não deixa para fazer de última hora!

Resumo da sua participação
Palestra: |TITULO|
Dia: |DATA|
Horário: |HORARIO|
Trilha: |TRILHA|
Link para StreamYard: |STREAMYARD|

Atenciosamente,
Organização da Python Brasil 2021

**Comment by cecivieira** [comment]
(es)
¡Hola | NOMBRE |!
 
¡Falta poco para Python Brasil 2021! Esperamos que estés tan emocionado como nosotros con el evento.
 
Te informamos que usaremos la plataforma StreamYard para hacer la transmisión en vivo. Esperamos que toda la programación se lleve a cabo según lo programado, por lo que le pedimos que acceda a la plataforma 15 minutos antes de su charla mediante este enlace: | STREAMYARD |.
 
Le pedimos que vea este breve tutorial sobre cómo navegar por la plataforma y cómo nos comunicaremos contigo durante tu charla. Además, hoy (10/09) a las 6:30 pm tendremos un live para probar toda nuestra infraestructura, guión de presentación de conferencias y todo lo demás que se necesites. Te invitamos a verlo y hacer cualquier pregunta que puedas tener.
 
La transmisión de las conferencias se realizará a través de Youtube. Esta atento a nuestras redes sociales (@pythonbrasil) que ya aparece allí la peublicación de tu conferencia para que la compartas con todos; en él habrá un enlace a Youtube, fecha y hora de tu presentación.
 
Toda la interacción del evento se llevará a cabo en Discord, allí también podrás tener un contacto directo y más rápido con la Organización, solo revisa @ Organização en el canal Ponentes-es y uno de nosotros responderá rápidamente a su pregunta. Para acceder a Discord, use este enlace exclusivo para líderes de actividades. ¡Te esperamos allí! ¡No esperes hasta el último minuto!
 
Resumen de su participación
Conferencia: | TÍTULO |
Día: | FECHA |
Hora: | HORA |
< ?: | ?? | >
Enlace a StreamYard: | STREAMYARD |
 
Atentamente,
Organización Python Brasil 2021

**Comment by cecivieira** [comment]
@alynnefs esses detalhes técnicos estão no vídeo e na live de hoje, também nas rondas de teste de áudio e vídeo que faremos
