### ISSUE TITLE
Definir o tema para a arte do evento

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#29]
Brainstorming de possíveis temas para criação de logo, plano de patrocínio, site, etc

**Comment by cecivieira** [comment]
Registro da [reunião de 17 maio](#37 ):

-     definir cores para facilitar o reconhecimento nas redes sociais
-     votar na logo. Opções: neon, 4 elementos, algo que remeta ao Brasil (uma representação para cada região)

**Comment by cecivieira** [comment]
@jjoaosilva Achei esse site com vááŕias logos de Python pelo mundo. Achei que pode te ajudar como inspiração:
https://hugovk.github.io/python-logos/

**Comment by cecivieira** [comment]
Proposta de temas ([apresentação completa](https://drive.google.com/file/d/17aIRm1qEWfWKi6Ne0GBCbKKPMlIRyFzX/view?usp=sharing))

Tema 1
![image](https://user-images.githubusercontent.com/30605862/119351922-6d8cb480-bc77-11eb-8e08-1fa2e5dfe534.png)

Tema 2
![image](https://user-images.githubusercontent.com/30605862/119351951-75e4ef80-bc77-11eb-8b52-fafb4da1e273.png)

**Comment by cecivieira** [comment]
Tema 3:

![image](https://user-images.githubusercontent.com/30605862/119378907-2b726b80-bc95-11eb-81a1-677d8903c66b.png)

**Comment by cecivieira** [comment]
Votação para escolha da arte: 
https://forms.gle/Rp7tJ6dwkYDT7Emw8

**Comment by cecivieira** [comment]
Votação concluída. Tema escolhido:
![image](https://user-images.githubusercontent.com/30605862/119417704-d3eff200-bccc-11eb-9b80-58637066d2de.png)
