### ISSUE TITLE
Inscrições para o evento

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#3]
Mesmo que a ideia inicial do evento seja ser gratuito e aberto à comunidade, é importante termos uma plataforma de inscrições para que possamos ter números de participantes para gerar relatórios (potencial patrocínio da PSF) e apresentar resultados (pode ser interessante para as edições presenciais terem esses números, para fins de patrocínio).

Plataforma escolhida: Sympla, por motivos da geração de certificados do evento.

**Comment by alynnefs** [comment]
Precisamos da data (issue #2) para dar início às inscrições

**Comment by alynnefs** [comment]
task relacionada: #59

**Comment by alynnefs** [comment]
sugestão da @deboraazevedo 

![photo_2021-06-07_13-48-33](https://user-images.githubusercontent.com/17454743/121058736-13bbdc80-c797-11eb-8fc0-84b41922583d.jpg)

**Comment by cecivieira** [comment]
Inserir pergunta "Você aceita receber divulgação da organização da Python Brasil no seu e-mail?"

**Comment by cecivieira** [comment]
Atividade relacionada #85

**Comment by cecivieira** [comment]
Bloqueado pela #98 
É necessário escolher a plataforma a ser usada

**Comment by cecivieira** [comment]
Foi verificado que a plataforma usada no ano passado, EventBrite, atende as necessidades desse ano. Então, para simplificar a criação do formulário de inscrição desse ano, foi mantida a plataforma.

Os eventos estão sendo criados usando a issue #209
