### ISSUE TITLE
[Levantamento] Possiveis eventos que estejam previstos para as mesmas datas pre selecionadas

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#30]
## O que

* Opções: 11 a 17 de outubro / 01 a 07 novembro
* Buscar se existem eventos de médio e grande porte de tecnologia dentro do período acima.

## Referência
https://github.com/pythonbrasil/pybr2021-org/issues/28

**Comment by cecivieira** [comment]
Coda Br: 8 a 13 de novembro

**Comment by alynnefs** [comment]
- BrasilJS conf 21, 22 e 23 de outubro
- GopherCon Brasil 01 e 02 de outubro

**Comment by deboraazevedo** [comment]
Coda.Br 2021 ainda não tem info se vai acontecer
PyCon Latam (mencionada na reunião passada) 27-28 de agosto
Ruby Conf Brasil 29 e 30 de julho
SciPy 2021 12 a 18 de julho
QCon São Paulo está adiada para 2021 em data a ser definida

**Comment by alynnefs** [comment]
comentei sobre a escolha da data na issue original:

https://github.com/pythonbrasil/pybr2021-org/issues/2#issuecomment-845407756
