### ISSUE TITLE
Pagamento tradução simultânea

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#319]
### Descrição
Realizar pagamento para a empresa de tradução simultânea.

### Requisitos para a atividade ser considerada como concluída

- Nota fiscal enviada para ApyB
- Pagamento realizado

**Comment by mazulo** [comment]
@alynnefs sim, no pedido de pagamento você enviou o boleto e a NF. O pagamento já foi feito também, mas acho que esqueci de responder por email. Enviei agora junto com o link do comprovante.
