### ISSUE TITLE
Ler e divulgar os feedbacks da pybr2020

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#32]

**Comment by cecivieira** [comment]
@anadulce Os comentários estão compartilhados em algum lugar?

**Comment by rougeth** [comment]
Enviado no privado já que os campos abertos ainda não foram revisados.

**Comment by alynnefs** [comment]
Entre tantos elogios e comentários não tão necessários, separei alguns pontos.

Sobre palestras
- Palestras menores
- Opção de criar agenda própria, marcando as palestras que quer assistir
- Pesquisar palestras por palavra chave
- filtro por horário na página de palestras
- disponibilizar slide e/ou repositório do GitHub antes da palestra, mas no que implicaria?
- Descrição da palestra na programação do site
- Palestras com duração flexível. Problema: são muitas palestras para conseguir controlar isso e às vezes nem o palestrante sabe quanto tempo vai usar

Tutoriais
- É possível abrir mais vagas usando o discord? existe alguma forma de fazer upgrade, mesmo que pago, durante o evento?
- Como evitar desistências? Sugeriram uma taxa de inscrição simbólica com possibilidade de pedido de isenção. Entretanto, no tempo em que se pede isenção, é possível acabarem as vagas.
- Discutir a possibilidade de gravar tutoriais, deixando explícito na inscrição que vai ser gravado. Possíveis problemas: as pessoas podem evitar fazer perguntas por saberem que vai ser gravado; teria que ser gravado pelo ministrante ou precisaria de mais voluntários para isso, além de armazenamento, edição e disponibilização no youtube.
- Explicitar nível dos tutoriais, talvez apresentar uma lista de pré-requisito (isso foi apresentado, não?)
- Horário pré-definido para abertura das inscrições para tutoriais
- Lista de espera pra tutoriais

Para a plateia
- Tutorial de como usar o discord
- é necessário explicar o motivo da interação acontecer apenas pelo discord ou reforçamos mais ainda o link do servidor?
- Link do canal do youtube e do servidor do discord tanto na página de inscrição quanto no site e no e-mail de confirmação de inscrição
- Sugeriram debates depois dos Keynotes, mas isso já acontece no discord. Será que é necessário dizer que a ferramenta de streaming tem limitações ou apenas reforçamos o servidor do discord? 
- Lightning Talks
- Maratona de programação

Para os palestrantes
- Tutorial de como usar o streamyard. Temos o manual em PDF, mas será que é necessário um tutorial em vídeo?
- Incentivar palestrantes sobre a descrição de imagens do slide, não só a descrição de si mesmos

Para os ministrantes de tutoriais
- Dar prosseguimento no tutorial quando todos os alunos estiverem "na mesma página"

Para voluntários
- Chamar com antecedência
- Continuar com hosts e analisar a necessidade de treinamento
- Treinamento para infra

Sobre os dados pessoais
- Informar que o número do celular não é pra uso próprio, é pra evitar bots no servidor do discord. Informar também que não disponibilizamos e-mails e afins para os patrocinadores
- Seria interessante divulgar mais os dados que obtemos nas inscrições do ano passado. Por exemplo: mostrar a quantidade de mulheres inscritas e explicar que usamos os dados para trabalhar de forma mais assertiva, com o objetivo de trazer mais diversidade. Sem os números fica difícil descobrir os pontos de falha. Sugestão: postar o site do Gabu e o repositório de dados abertos nas redes sociais.
- "Oferecer a possibilidade de não ser gravado". A falta de autorização dos participantes foi um dos motivos para que os tutoriais não fossem gravados. Mas SE for uma possibilidade para esse ano, como gravar só um determinado grupo de pessoas em um canal de vídeo?

Sobre rodas de conversa e keynotes
- mais diversidade. Ano passado tivemos uma maioria feminina, o que por si só já foi incrível. Entretanto, acredito que conseguimos deixar ainda mais diverso. Ainda temos grupos sub-representados e temos que dar voz para eles também.

Opinião pessoal
- muitas pessoas pediram mais vagas nos tutoriais e ficaram chateadas por ter salas vazias. Isso foi falta de compromisso das pessoas por não aparecerem, mas como fazer para minimizar? E como fazer as pessoas entenderem que fizemos o possível para maximizar o número de alunos dentro do limite existente?
- teve muita gente pedindo não só mais tutoriais, mas também que ocorressem durante a semana. Como deixar claro que é feito por voluntários e que eles também trabalham?
- como melhorar o espírito de comunidade entre as pessoas que estão participando do evento pela primeira vez?
- como explicar de forma educada que diversidade não é sobre ideologia e sim uma necessidade?

**Comment by rougeth** [comment]
@alynnefs você viu algo nos campos abertos que precisam ser removidos antes de divulgarmos os dados?

**Comment by alynnefs** [comment]
Tem aquelas questões de reclamarem de diversidade e "ideologia". Também citaram algumas pessoas, mas foi elogiando

**Comment by gabubellon** [comment]
Tendo mais tempo esse ano podemos pensar em fazer um "aquecimento python brasil" ou algo do genero, uma live explicando como e porque as coisas são organizadas.
Acho que deixar explicito como é a organização (voluntários e com tempo limitado) pode ajudar a mostrar o porque alguns pontos não são feitos

**Comment by rougeth** [comment]
Por mais que não concordemos com os comentários, se eles não infringem o código de conduta, acho que não têm motivo para removê-los, não?

**Comment by anadulce** [comment]
Vocês acham que os comentários que criticam inclusão e diversidade não tem nenhum problema em constar nesses dados?

**Comment by rougeth** [comment]
Eu não vejo problema, mas também não vejo no que ajuda, como um todo, a divulgação das respostas de campo aberto. Elas valem para org do ano seguinte, mas no geral, não sei como esses dados poderiam ser usados para análise.

**Comment by alynnefs** [comment]
Tirar os campos abertos e divulgar o feedback

**Comment by rougeth** [comment]
@gabubellon campos abertos:
- Se escolheu alguma das opções acima, detalhe os motivos abaixo.
- Como podemos melhorar na próxima edição da Python Brasil?
- Você têm algum outro comentário sobre a Python Brasil 2020?

**Comment by gabubellon** [comment]
@rougeth dados separados sem os campos abertos https://github.com/pythonbrasil/dados/pull/5/
