### ISSUE TITLE
Realizar doação para Mães da Favela

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#320]
### Descrição
Viabilizar que todo o dinheiro arrecadado durante o evento (líquido R$14.337,20) seja doado para o projeto Mães da Favela.

### Requisitos para a atividade ser considerada como concluída

- Sacar dinheiro do EventBrite para ApyB
- Enviar dinheiro para Mães da Favela

**Comment by gabubellon** [comment]
@mazulo isso foi uma pergunta ? Como devemos proceceder ? A APyB faz essa ponto ou a organização precisa ?

**Comment by gabubellon** [comment]
@alynnefs @mazulo acho que precisamos mandar email para contato@maesdafavela.com.br

**Comment by cecivieira** [comment]
Gabu, tu poderia informar o valor exato de arrecadação no Evento Brite?
Além disso, proceder o resgate para a ApyB?

Assim que tu der o ok do resgate e informar o valor, entro em contato com a
ONG

**Comment by alynnefs** [comment]
Boleto solicitado [no ticket](https://pythonbrasil.freshdesk.com/a/tickets/7856)

**Comment by cecivieira** [comment]
@alynnefs a documentação (boleto e nota fiscal) foram recebidos por nós? Já conseguimos efetuar essa doação?
Pergunto para publicitar nas redes sociais

**Comment by alynnefs** [comment]
@cecivieira tô aguardando informações sobre a nota fiscal

**Comment by cecivieira** [comment]
@alynnefs aguardando a Mães da Favela responder com a Nota Fiscal?

**Comment by cecivieira** [comment]
Ticket: https://pythonbrasil.freshdesk.com/a/tickets/7894

@alynnefs posso seguir o contato com a Mães da Favela? Eu responderia o e-mail pedindo o telefone de Ivone e reforçando o pedido da Nota Fiscal.

**Comment by cecivieira** [comment]
E-mail lembrete emviado para Mães da Favela

**Comment by alynnefs** [comment]
@cecivieira desculpa, acho que o e-mail se perdeu no meio do spam e não tô com o freshdesk logado no pc do trabalho :(

Se conseguir seguir com isso, eu agradeço. Mas a gente ainda não recebeu o boleto, então podem não querer gerar a nota agora. Só seria bom confirmar se podem fazer, aí a gente pede os dois

**Comment by cecivieira** [comment]
@alynnefs vou pegar essa tarefa pra fazer.

Entrei em contato com a presidente da CUFA PE pelo whastapp e ela encaminhou a nossa demanda para a organização nacional. Em caso não tendo resposta da organização nacional  da CUFA até dia 15 dez. 2021, poderíamos proceder essa doação para o projeto Mães da Favela da CUFA PE?

**Comment by gabubellon** [comment]
@cecivieira  De Acordo

**Comment by alynnefs** [comment]
@cecivieira por mim tudo bem. Mas pergunta da NF 😅

**Comment by cecivieira** [comment]
@alynnefs emite nota fiscal sim

**Comment by cecivieira** [comment]
Devido a impossibilidade da organização CUFA nacional emitir nota fiscal, faremos a doação diretamente para o projeto Mães da Favela da CUFA PE.

Ticket do contato com a CUFA PE: https://pythonbrasil.freshdesk.com/a/tickets/7911

**Comment by cecivieira** [comment]
@alynnefs @gabubellon 
recebemos a nota fiscal da CUFA PE, nela constam os dados para pagamento. Encaminharei para @mazulo

**Comment by cecivieira** [comment]
Nota encaminhada para financeiro@python.org.br

**Comment by gabubellon** [comment]
@cecivieira podemos considerar esse feito certo ?

**Comment by cecivieira** [comment]
Doação realizada em 17 dez. 2021
