### ISSUE TITLE
Cotar Intérprete de Libras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#33]
Tabela orçamentária: https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing

Pasta para guardar orçamento: https://drive.google.com/drive/folders/1HhCzzJAsMxuMUo66wtm8xwaCdtpeXxtQ?usp=sharing

**Comment by cecivieira** [comment]
@gabubellon Qual a planilha onde tas juntando as informações relativas a contatos de fornecedoras e orçamentos?

**Comment by cecivieira** [comment]
Tabela orçamentária: https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing

**Comment by cecivieira** [comment]
@gabubellon @anadulce @alynnefs pensando nos eventos anteriores, quanto tempo de programação diária temos em cada trilha? Quantas trilhas simultânea existiram?

**Comment by anadulce** [comment]
2 horas de mesa redonda e 1:30h de keynote, que são atividades sem outras atividades paralelas.
E aproximadamente 4h de palestras distribuídas em 4 trilhas.

**Comment by alynnefs** [comment]
Entrei em contato com uma intérprete e ela fez algumas perguntas. Juntei as informações do ano passado e pedi ajuda da @anadulce pra revisar. Exemplo de mensagem para pedido de orçamento:

```
Datas: 11 a 15 de outubro ou 1 a 5 de novembro (ainda não definindo)

Horários:
- roda de conversa: das 10h às 12h

- palestras: 
De 15:00 às 15:45
Pausa de 5 minutos
De 15:50 às 16:35
Pausa de 5 minutos
De 16:40 às 17:25
Pausa de 55 minutos
De 18:20 às 19:05
Pausa de 5 minutos
De 19:10 às 19:55
Pausa de 5 minutos para o keynote

- keynote: das 20:00 às 21:30

Duração:

- 2 horas de roda de conversa
- 1:30h de keynote
- aproximadamente 4h de palestras

Opção 1: Keynote (1:30 por dia)
Opção 2: Keynote e mesa redonda (3:30 por dia)
Opção 3: tudo (7:30 por dia)

Tema/conteúdo?
Tecnologia, com foco em programação.

Ao vivo ou não?
Ao vivo

Vai ficar gravado?
Sim

Obs: esses foram os horários do ano passado, a título de referencial, pois temos a intenção de realizar o evento similarmente este ano. Entendemos que se mudarmos duração e horário, o valor do orçamento também mudará, mas um referencial nos basta. Se for possível, pode fazer orçamento para as 3 opções citadas? Vamos adequar o evento ao valor que arrecadarmos com os patrocínios.
```

**Comment by gabubellon** [comment]
Orçamento realizado Interprete: William Sestito contato: (47) 98907-6852 e adicionado a planilha

**Comment by cecivieira** [comment]
Solicitado orçamento para Greicy, intérprete da WiDS SP. Aguardando resposta

**Comment by cecivieira** [comment]
Recebi o orçamento.

Temos orçamento de 3 fornecedores. Vocês acham que dá para fechar essa issue?

**Comment by cecivieira** [comment]
A previsão orçamentária para essa atividade pode ser encontrada na planilha:
https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing
