### ISSUE TITLE
Participantes Tutorial

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#333]
- [x] Ter a lista e participantes de cada tutorial
- [x] Criar arte para participantes de tutorias com tempo espaço para o nome do tutorial
- [x] Coletar email e nome de cada participantes
- [x] Gerar certificados
- [ ] Enviar certificados
- [ ] Tratar excessões

**Comment by gabubellon** [comment]
@rougeth separei os user por tutorial aqui, precisamos enviar mensagens em privado pra eles
https://drive.google.com/file/d/15_Q1_QhREXx8p5lLnI76YoQ8W6So-zls/view?usp=sharing

@alynnefs vamos considerar qual regra ?
* role + inscrição ?
* Só role ?
* Raspar as mensagens da sala ???

**Comment by alynnefs** [comment]
Eu iria por role, só preciso criar pra sábado de manhã. Posso fazer daqui a pouco

**Comment by gabubellon** [comment]
@alynnefs @rougeth @anadulce @cecivieira

**Comment by gabubellon** [comment]
https://docs.google.com/forms/d/1SiOQmDFymP3to8wC2W3OuSxmqj4333DVRIZ0x6bPhvw/edit

**Comment by gabubellon** [comment]
Dados coletados em https://docs.google.com/spreadsheets/d/1Eqjb58VZm80Iben9fH0_YSp_w9FDt_Xbit8ZCqBTW1o/edit#gid=39661316

**Comment by gabubellon** [comment]
Certificados gerados em https://docs.google.com/spreadsheets/d/1Eqjb58VZm80Iben9fH0_YSp_w9FDt_Xbit8ZCqBTW1o/edit#gid=942311275

@anadulce consegue enviar ?

**Comment by alynnefs** [comment]
@anadulce deu certo o envio?

**Comment by cecivieira** [comment]
Não foram enviados esses certificados.
Aguardando acesso ao MailChimp

**Comment by cecivieira** [comment]
Pasta com certificados: https://drive.google.com/drive/u/0/folders/1TvTTgDP5ePAvKhY1VrM8wa7vfHVZNlMH

**Comment by cecivieira** [comment]
Certificados enviados
