### ISSUE TITLE
Ministrantes

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2021-org#334]
- [ ] Pegar info de ministrantes
- [ ] Criar arte de certificado de ministrantes
- [ ] Gerar certificado de ministranes
- [ ] Enviar certificados
- [ ] Tratar certificados

**Comment by cecivieira** [comment]
Ao enviar e-mail, informar que não será enviado o brinde .

**Comment by cecivieira** [comment]
Dados para geração de certificados:

https://docs.google.com/spreadsheets/d/1M-koe0XYuYyNpWBMBasT3ph19XhrdcQxRfNeTDoyvoA/edit?usp=sharing

**Comment by gabubellon** [comment]
> Dados para geração de certificados:
> 
> https://docs.google.com/spreadsheets/d/1M-koe0XYuYyNpWBMBasT3ph19XhrdcQxRfNeTDoyvoA/edit?usp=sharing

@cecivieira não entendi qual aba eu devo utilizar ? Tem abas com filtros aplicados, importante não ter esse filtro

Todavia o ambiente que gera os arquivos eu desliguei, vou precisar configurar tudo acho vai vai umas 2hs, não se consigo fazer hoje (24/01) ou essa semana.

Me chama no telegram se for melhor pra agilizar essa coisas

**Comment by cecivieira** [comment]
@gabubellon limpei a planilha e deixei apenas as 2 abas a serem consideradas. A aba "es_fonte_talks" são dados das palestras da trilha em espanhol, então seria interessante os certificados estarem nesse idioma também.

Já já coloco uma proposta de arte para os certificados aqui.

**Comment by cecivieira** [comment]
Vê se essas coordenadas fazem sentido (x,y):

Nome da ministrante: 401.273, 410,332
Texto do meio: 407.838, 370.793 
Título: 407.838, 318.793

Imagem base: https://drive.google.com/file/d/1wtvexywTrxVA6n9OzU2Z4AwQ907GaB41/view?usp=sharing

**Comment by cecivieira** [comment]
@pythonbrasil/apyb Tentei logar no MailChimp com o e-mail eventos@, mas informa que não existe mais conta associada a esse e-mail. Seria possível fornecer as credenciais para envio dos certificados?

![image](https://user-images.githubusercontent.com/30605862/150990417-780501a8-b994-47b9-a1b9-f784fd4a20a7.png)

**Comment by gabubellon** [comment]
@cecivieira @anadulce certificados gerados em https://docs.google.com/spreadsheets/d/1I6zQsbGgoqz_h8TOCWEp0iySZH9xgHLLy0NH9AVNoLI/edit#gid=939059366

**Comment by cecivieira** [comment]
Enviados

Noma pasta dos certificados: https://drive.google.com/drive/u/0/folders/1ehog6iX3Yz-BbDmiNMxBcZjo1zRR_uTg
