### ISSUE TITLE
Consolidar fluxo de caixa do evento

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#344]
### Descrição
Consolidar fluxo de caixa (entradas e despesas) realizadas durante o evento, bem como o saldo o deficit.

### Requisitos para a atividade ser considerada como concluída

- Fluxo de caixa aprovado por @alynnefs 
- Publicá-lo no site do evento

**Comment by cecivieira** [comment]
Fluxo de caixa:
https://docs.google.com/spreadsheets/d/1pz619Ma2K9mv6N2vdn1CdzzmHZ7yePuHN85CxKFZ0H0/edit#gid=228361764

Consolidação realizada conforme extratos bancários da APyB, fornecidos por @mazulo .
Aguardando aprovação de @alynnefs

**Comment by cecivieira** [comment]
Aguardando resposta da atual gestão da APyB sobre percentual de retenção: @mazulo 

Os 10% que fica para a APyB é sobre todo o patrocínio recebido? Ou sobre toda a movimentação de dinehiro realizada no evento?

**Comment by alynnefs** [comment]
@gabubellon @muriloviana podem verificar se os reembolsos de vcs estão corretos/atualizados?

**Comment by gabubellon** [comment]
Tudo certo os meus

**Comment by alynnefs** [comment]
aprovado 😃

**Comment by cecivieira** [comment]
Conforme informado por @mazulo , o estatuto da APyB prevê retenção de 10% em cima do valor do ingresso do evento. Como o evento PyBR2021 foi gratuito, logo não haverá nenhum tipo de retenção.

![image](https://user-images.githubusercontent.com/30605862/147747259-b93d42f9-197a-4711-ade4-2ded13d7add7.png)

**Comment by cecivieira** [comment]
Aberto pull request para publicação da prestação de contas no site:
https://github.com/pythonbrasil/pybr2021-site/pull/85
