### ISSUE TITLE
Criar onboarding para próxima organização

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#347]
### Descrição
Estruturar onboarding para a organização da PyBr2022 com objetivo de ser uma metodologia teste a ser reproduzida pela @pythonbrasil/apyb nas próximas organizações do evento.

Usar como base o [Manual do big kahuna da python brasil](manual.pythonbrasil.org.br.)

### Requisitos para a atividade ser considerada como concluída

- Estrutura do programa de onboarding
- Slides

**Comment by cecivieira** [comment]
# Onboarding para equipe organizadora da Python Brasil

- **Público alvo:** Big Kahuna e Equipe organizadora da próxima PyBr
- **Período de realização:** Entre 12 e 10 meses antes da realização do evento
- **Responsáveis:** APyB e membras da organização do evento anterior

## Estrutura
### 1. reunião
1. Boas vindas
2. Apresentar agenda
2. O que é Python Brasil desde uma perspectiva de gestão (projeto de código aberto com uma membra fixa: a Gestora de Projeto)
3. Apresentar possibilidade de pactuação com a APyB do modelo de organização:
    - Modelos existentes:  [Comunitário](https://manual-do-big-kahuna.readthedocs.io/en/latest/modelos/comunitario.html), [Misto](https://manual-do-big-kahuna.readthedocs.io/en/latest/modelos/misto.html) e [Profissional](https://manual-do-big-kahuna.readthedocs.io/en/latest/modelos/profissional.html)
4. Pré-evento (ordem cronológica de atividades):
    - Escolha e detalhamento de formato: presencial, online, híbrido; (aqui enfatizar que essa escolha deve fortemente levar em consideração a capacidade de trabalho da comunidade anfitriã do evento, seu engajamento na organização do evento, tempo disponível e possíveis ausências)
    - Desenvolvimento de identidade visual;
    - Levantamento de custo para viabilização; (criação de planilha que reuna todos os custos de infraestrutura e terceirização de serviços baseado em preços reais + 10%)
    - Criação do Plano de Patrocínio;
    - (opcional, caso a equipe já seja suficiente) Convidar novas voluntárias;
    - Formação de grupos de trabalho;
    - Planejar campanhas publicitárias (ex.: lançamento do evento, chamada para patrocinadoras, submissão de palestras, etc.);
    - Estabelecer grade horária do evento; (com isso será possível determinar quantidade de palestras, jobfairs, sorteiros, etc)
    - Planejar curadoria de conteúdo para o evento;
    - Pactuação contratual de fornecedores a partir da priorização de gastos e execução orçamentária (jamais pagar 100% do contrato adiantado).
5. Execução do evento
6. Pós-evento:
    - Execução orçamentária restante;
    - Emissão de certificados;
    - Abertura de dados anonimizados no repositório [dados](https://github.com/pythonbrasil/dados)
    - Exclusão permanente de dados pessoais de participantes;
    - Envio de relatório de impacto para patrocinadoras;
    - Atualização do [Manual da Big Kahuna](https://manual-do-big-kahuna.readthedocs.io/en/latest/);
    - Redação de Post mortem
7. Ferramentas úteis para gestão do projeto:
    - GitHub: gerenciamento de atividades e discussões;
    - Discord: comunicação online.
8. Conselhos finais
    - Comunicação:
        - Transparência como padrão;
        - Estabeleceder uma ótima comunicação assincrona;
        - Estimular o uso das ferramentas de comunicação e gerenciamento estabelecida pela equipe;
        - Estimular uma comunicação direta e sincera;
        - Haver coversa de entendimento que todas as pessoas estão andando no mesmo sentido, no entanto discordancias acontecerão, cobranças também e isso não quer dizer que é um problema pessoal. As insatisfações precisam ser expostas para que haja a possibilidade de entendimento e resolução;
    - Registrar todo o processo de execução da atividade na plataforma escolhida e estimular colaboração de todas nas que demandarem discussão. Um projeto de código aberto sem documentação não serve de muita coisa e dificulta muito a contribuição de outras pessoas.

**Comment by rougeth** [comment]
Considerando que o time tem dois anos para organizar a Python Brasil, acho que podemos dividir esse doc em duas partes:
1. Tudo que pode ser adiantado no primeiro ano, como desenvolvimento de identidade visual ou levantamento de custo para viabilização.
2. A passagem de bastão entre uma organização e a outra. Exemplos: detalhamento do que funcionou ou não, contatos dos patrocinadores, etc.

Dito isso, alguns pontos deixa de fazer sentido em uma reunião 12 meses antes do evento porque o time já deveria ter conhecimento deles. 

Agora sobre pontos específicos:

> Apresentar possibilidade de pactuação com a APyB do modelo de organização: 

Não acho que seja relevante falar especificamente sobre esses modelos (não sei em qual contexto eles foram escritos). Acho que a mensagem mais importante a passar é que a Big Kahuna tem autonomia para decidir como fazer o evento.

> (opcional, caso a equipe já seja suficiente) Convidar novas voluntárias;

Esse ponto é crítico, acho difícil uma big kahuna ter uma equipe já suficiente. Aqui cabe um livro sobre como gerenciar um time de voluntários e voluntárias.

Eu adicionaria um ponto para falar sobre o que pode ser reusado (talvez isso seja um subtópico em todos os tópicos, algo como "Como foi feito nos últimos anos" ou "Ferramentas usadas que funcionaram"). Queria algo que estimulasse o reuso de coisas feitas pela organização anterior.

Última coisa, pode trocar a url do manual do big kahuna para manual.pythonbrasil.org.br.

**Comment by cecivieira** [comment]
@rougeth troquei o link do manual da big kahuna. Obrigada!

Então, a proposta seria extender a proposta de onboarding para englobar acompanhamento? O 1. encontro seria dividido em 2, sendo o primeiro realizado entre 24 e 22 meses antes do evento e o segundo entre 12 e 10 meses?

**Comment by rougeth** [comment]
Sim. A org não pode (ou não deveria) começar a trabalhar apenas 1 anos antes do evento. A proposta da cidade sede é votada em assembleia dois anos antes da execução do evento, todo esse tempo precisa ser melhor aproveitado.

**Comment by gabubellon** [comment]
@cecivieira Primeirto, execelente iniciativa

Alguns desses pontos pode ser "estáticos" não, talvez serem sempre evoluidos, mas podemos pensar que alguns dessas cerimonias/contéudos possam criados (texto/videos) e usados de forma assincrona e atemporal
Podemos até ser usados por eventos que não a PythonBrasil.

Visto dessa forma penso que isso possa até ser um complemento do manual do Big Karuha. Sendo sempre o último tópico do para quem está fechando o evento e o primeiro pra quem está pegando o próximo

O que acha de conversar (call ) sobre  ?

**Comment by cecivieira** [comment]
@gabubellon aproveitamos pós reunião da PyBr22 para começar a mexer na estrutura. Rola pra tu uma reunião quarta-feira entre 8h30 e 9h30?

Modificações em curso: https://hackmd.io/@IAA8H7ZURCejO-4Zz31Dug/rkuWWzik5 (paramos no pós-evento)

**Comment by cecivieira** [comment]
Esta discussão foi transferida para o espaço de discussão da APyB:
https://github.com/apyb/comunidade/discussions/10
