### ISSUE TITLE
Cotar Ferramenta de Stream (StreamYard)

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#35]

**Comment by cecivieira** [comment]
US$20 (R$ 104.66, cotação 11 maio)

![image](https://user-images.githubusercontent.com/30605862/117839782-eb9d9400-b251-11eb-92f7-d8d6fe9e567c.png)

**Comment by cecivieira** [comment]
@rougeth vocês já tentaram baixar os vídeos pelo youtube?

![image](https://user-images.githubusercontent.com/30605862/117898804-2af0d280-b29c-11eb-9e6e-322073eceb73.png)

**Comment by rougeth** [comment]
Baixar do YouTube é uma opção sim, inclusive precisamos fazer para um dos streams que perdemos o arquivo (pybr2020). Mas, considerando que o YouTube processa e comprime os uploads, podemos ter melhor qualidade baixando direto do StramYard.

**Comment by cecivieira** [comment]
Os contatos das fornecedoras e orçamentos estão sendo reunidos [nessa tabela](https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing)
