### ISSUE TITLE
Cotar Custo Operacional

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#36]
- [X] Custos de download de edição de video
- [ ] Custo de possível ambiente 3D
- [x] Custo de ferramenta de Stream

**Comment by rougeth** [comment]
Itens relacionados a edição dos vídeos:

- Serviço para armazenamento temporário dos vídeos pré edição/publicação. Usamos AWS S3 ano passado. Usando a calculadora da AWS [1] com números bem maiores do que acho necessário, cheguei no valor de 3.01 USD.
  - 100 GB por mês de storage
  - 1k requisições de PUT, COPY, POST e LIST
  - 1k requisições de GET, SELECT
  - 1 TB por mês de dados retornados via S3 SELECT

- Máquina para edição dos vídeos. Usamos uma máquina virtual na AWS, C4.8xlarge de custo 1.591 USD/hora. Considerando o fluxo de edição de 2020, podemos considerar 3 horas por dia de evento.

1 - https://calculator.aws/#/createCalculator/S3

**Comment by gabubellon** [comment]
Podemos usar essa mesma máquina pra rodar o downloader dos videos, seja pelo stream yard ou qualquer outra ferramentar de stream que fomos utilizar, com esse mesmo custo

**Comment by rougeth** [comment]
Sobre o ambiente 3D, onde a ferramenta se encaixaria? Ela substituiria o Discord/StreamYard, ou só o Discord?

@gabubellon o https://gather.town usam o hubs.mozilla.com, é isso? Acho complicado se for apenas via marketplace, já que é fácil fazer deploy para produção mas nós que teremos que mantê-la na semana do evento.

**Comment by cecivieira** [comment]
@rougeth Acho que não substitui nada, é uma outra forma de navegar no evento: criando avatar e andando por um "joguinho" ([esse artigo](https://wegoout.com.br/no-ar-coquetel-molotov-mundo-3d-festival/) explica a ideia da aplicaçao no festival e [esse vídeo de 1min](https://youtu.be/U7ebl801sds) ilustra. 

Talvez possa servir como contrapartida para empresas patrocinadoras, colocar banner um banner ou criar um ambiente temático.

**Comment by gabubellon** [comment]
@rougeth  o o https://gather.town é uma ferramenta que vai ser usada em um evento de um colega, o hubs.mozilla.com é outra e que foi usado no evento que @cecivieira  citou

Sobre ter ou não ter essas ferramentas acho que é algo que precisamos entender se é viável tanto a custo como a engajamento das pessoas.

Já deixando minha opinião pessoal, eu acho legal, mas usaria muito pouco, mas tem sido uma opção de alguns eventos para tentar engajar as pessoas as interagirem

**Comment by rougeth** [comment]
Não sei qual ferramenta a Pycon US está usando, mas parece interessante: https://twitter.com/marlene_zw/status/1393241522024427520?s=21

**Comment by cecivieira** [comment]
Os contatos das fornecedoras e orçamentos estão sendo reunidos [nessa tabela](https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing)

**Comment by rougeth** [comment]
Não criaríamos concorrência com as outras ferramentas? Considerando que temos youtube/streamyard pra vídeo e discord para texto e áudio, o que fariam as pessoas irem para uma outra ferramenta? Concorrência é ruim para os patrocinadores (e acho que como experiência geral do evento mesmo), já que pra eles o alcance é o mais importante.

Se acabar sendo usado só por algumas pessoas (concordo com o @gabubellon, também acho que é o mais provável), acho que não vale a pena. Dito isso, podemos reavaliar as outras ferramentas também.

**Comment by jjoaosilva** [comment]
Ta gente, eu não sei se o que eu vou falar aqui vai ajudar ou vai ser ser só mais do mesmo ou se voces ja sabiam e tal. Eu tava dando uma olhada sobre os ambientes 3D e tal. Sobre o evento imersivo 3D, aquele ambiente foi criado, pelo que entendi, pelo grupo Rosabege que trabalha com essas paradas. Dai, pra gente ter orçamento de custo com algo parecido com isso (https://youtu.be/U7ebl801sds) a gente teria que entrar em contato com eles. 

Outra ferramenta falada com o gather. Dai, eu dei uma olhada nele, criei uma salinha la sem fazer login e tal mas ainda não consegui testar bem ele com mais pessoas e, sendo bem sincero, fiquei meio perdido no site deles pra ver bem com funciona. ele me pareceu ser legal tbm.

Dai lendo um pouco da thread dos custos tem uma observação lá a respeito da concorrência entre as plataformas e sobre se realmente ia valer a pena usar isso no evento. Eu nunca experimentei usar e nunca tinha visto na real, então pra mim a opinião que ficou foi a que eu conclui lendo a thread. De que esse ambiente seria mais um plus pra engajar mais mas não deveria ser algo principal pra repassar o conteúdo do evento.
[sugestão] Algo que poderia ser interessante, era liberar um desses locais, tipo no gather, pra galera interagir entre si em momentos de pausa ou em que o evento ficasse off. Se fosse pensar na ideia das cores ds trilhas/niveis, a glr poderia por as cores do avatar de acordo com o "nivel" pra glr poder trocar uma ideia e até ir atras de experiencias, não sei.

Dai, eu real fiquei meio perdido visualmente falando a respeito de usar o 3D, que é algo que eu manjo pouco. No canva eu consigo pegar pessoas e pelo que vi alguns objetos ou seres meio aleatórios... Nessa parte eu fiquei meio bugado

**Comment by gabubellon** [comment]
Custo de possível ambiente 3D será visto em outro momento se necessários
