### ISSUE TITLE
[Reunião] Geral: 17 maio 2021

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#37]
# Reunião Geral

- Data: 17 maio 2021  
- Participantes:
  - Ana Cecília Vieira (@cecivieira)
  - Alynne Ferreira (@alynnefs)
  - Ana Dulce (@anadulce)
  - José João (@jjoaosilva)
  - Izabela Cristina (@belaaiza)
  - Gisele Vanessa (@martinsvanessa)
  - Marco Rougeth (@rougeth)
  - Loyanne Repolho (@loyannec)
  - Gabu (@gabubellon)
  - Débora Azevedo (@deboraazevedo)

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Itens a serem debatidos

- [x] Definir tipos de cotas (exemplo: básica, por tipo de patrocinadores, por tipo de atividade/produto)
    - modificar o plano de patrocínio com os dados do ano passado
    - responder o email da JusBrasil
        - apresentar plano pronto até o final do mês
        - não confirmar exclusividade da cota
    - checklist de material que a empresa precisa mandar ao menos com um mês de antecedência e cobrar
    - treinamento do discord para as empresas patrocinadoras que vão ter canal de áudio, mas eles precisam definir o que vão fazer
    - ter alguém da organização para mediar as atividades da empresa, que devem ser mandadas com antecedência
    - quantidade de vezes que a gente divulga a empresa dependendo da cota de patrocínio
    - vídeo-propaganda da empresa (institucional)
    - diferenciar valor para logo "eternizada" e só ao vivo
    - sponsorship no instagram (outras redes sociais possuem?)
    - fazer relatório registrando links e alcance de postagens para garantir que entregamos o que foi acordado
    - programar postagem de divulgação do material de marketing do evento passado
    - cotas
        - ouro: 3
        - prata: 5
        - bronze: 10

- [ ] [Definir formato do evento](https://github.com/pythonbrasil/pybr2021-org/issues/6)
- [x] [Identidade visual: primeiros produtos](#29)
    - definir cores para facilitar o reconhecimento nas redes sociais
    - votar na logo. Opções: neon, 4 elementos, algo que remeta ao Brasil (uma representação para cada região)

### Ações para serem realizadas

Atividade| Responsável | Link útil| Observações|
 --| --| --|--|
 

cc @<GitHub team do grupo de trabalho responsável pela reunião>

**Comment by alynnefs** [comment]
Como temos um projeto no GitHub e a atualização das atividades pendentes pode acabar ficando desatualizada nas atas, optamos por acompanhar o andamento através das issues que estão em progresso.

**Comment by rougeth** [comment]
Para fins de registro, conversamos sobre a ferramenta hubilo.com, usada na PyCon US 2021, mas decidimos que não mudaremos as ferramentas usadas ano passado (Discord/StreamYard/Youtube).
