### ISSUE TITLE
Patrocínio da JusBrasil

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#40]

**Comment by loyannec** [comment]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêndice no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião com a JusBrasil

- Data: 12 maio 2021
- Participantes:
  - Loyanne Repolho (@loyannec)
  - Alyne Ferreira (@alynnefs)
  - Mario Sérgio (@sergiomarioq)
  - Patrick Mazulo (@mazulo)
  - Adriano Margarin (@adrianomargarin)

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil| Observações|
 --| --| --| --|

### Itens a serem debatidos

- [ ] Proposta para cota de patrocínio da parte da JusBrasil.
- [ ] Possibilidade de pagarmos por certos serviços que em 2020 foram realizados de forma voluntária e agora passar a ser remunerado como prestação de serviço com nota fiscal avulsa.
- [ ] A JusBrasil tem como expectativa ser patricinadora nas edições 2021, 2022 e 2023 da Python Brasil.

### Ações para serem realizadas

Atividade| Responsável | Link útil| Observações|
 --| --| --|--|
 Elaborar contrato para JusBrasil levando em consideração a possibilidade da mesma ser patrocinadora das próximas três edições da PyBr. --| --|--|
 Buscar por um plano B caso a próximas edições dos anos seguintes não ocorram por alguma eventualizade e eles fiquem com um "crédito" com a PyBr. --| --|--|
 Levar em consideração que o valor definido para os próximos anos será analisado e avaliado conforme a inflação que pode estar por vir. --| --|--|

**Comment by rougeth** [comment]
> Elaborar contrato para JusBrasil levando em consideração a possibilidade da mesma ser patrocinadora das próximas três edições da PyBr.

- Caso alguma das duas próximas edições não seja presencial, o patrocínio continua válido?
- Chegaram a discutir possíveis benefícios? Como distribuiremos isso entre as edições?

> Buscar por um plano B caso a próximas edições dos anos seguintes não ocorram por alguma eventualizade e eles fiquem com um "crédito" com a PyBr.

- Considerando que nem a edição online ocorra, certo?

> Levar em consideração que o valor definido para os próximos anos será analisado e avaliado conforme a inflação que pode estar por vir.

- O valor seria pago integralmente agora?
- Essa é uma observação para a primeira atividade, né? O que fizemos na primeira reunião, foi criar uma issue para cara atividade.

> Informar sobre o valor da proposta com o restante da organização.

*Marcando a issue da próxima reunião geral #37 (Caso uma reunião específica para isso não for necessária)*

**Comment by loyannec** [comment]
> Caso alguma das duas próximas edições não seja presencial, o patrocínio continua válido?
- Continua válido mas precisa ser descrito no contrato.
> Chegaram a discutir possíveis benefícios? Como distribuiremos isso entre as edições?
- Discutimos o que já havia sido feito e as novas idéias para a nova edição
> Considerando que nem a edição online ocorra, certo?
- Certo!
> O valor seria pago integralmente agora?
- O Mário pediu um tempo para conversar com o setor responsável da JusBrasil mas ele deu 99,9% de certeza, tanto que não precisaria do Plano de Patrocínio para agora mas é algo que podemos perguntar para ele num futuro próximo.
> Essa é uma observação para a primeira atividade, né? O que fizemos na primeira reunião, foi criar uma issue para cara atividade.
- Não entendi :)

**Comment by rougeth** [comment]
> Não entendi :)

Sorry 🙃 Cada item no `Ações para serem realizadas` vira uma issue no Github. Meu comentário sobre o terceiro item, é que ele parece ser uma observação a ser considerada na elaboração do contrato (primeiro item).

**Comment by cecivieira** [comment]
O que vocês acham de mudar o título dessa issue para "Patrocínio da JusBrasil"? Assim, o histórico da negociação fica em uma issue só.

**Comment by loyannec** [comment]
Criada [essa issue](https://github.com/pythonbrasil/pybr2021-org/issues/46) para o contrato com a JusBrasil

**Comment by cecivieira** [comment]
@alynnefs @loyannec O e-mail da JusBrasil foi respondido?

**Comment by alynnefs** [comment]
E-mail respondido hoje

**Comment by rougeth** [comment]
Issue criada para reunião com a JusBrasil. Fechando, já que as pendências foram concluídas.
