### ISSUE TITLE
Cotar Legenda para vídeos

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#41]

**Comment by cecivieira** [comment]
Os contatos das fornecedoras e orçamentos devem ser reunidos [nessa tabela](https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing)

**Comment by gabubellon** [comment]
A ideia é legendar pós eventos ? 
Em português inicialmente ?
Se sim, podemos pensar em uma automatização de extração de texto dos videos, junto a rotinas de quebra, e ai termos a necessidade de ter uma revisão disso. Pode ajudar a diminuir tempo e custo

**Comment by cecivieira** [comment]
A ideia é essa mesmo @gabubellon , legendar em português no pós evento

**Comment by gabubellon** [comment]
> A ideia é essa mesmo @gabubellon , legendar em português no pós evento

Legal, podemos testar a extração automática de texto com os videos de 2020 e já ganhar tempo e custo com isso então

**Comment by cecivieira** [comment]
https://webcaptioner.com/captioner

Pode ser uma solução para participantes que precisam de legenda para as lives.

**Comment by rougeth** [comment]
Legenda automática do YouTube não seria suficiente?

**Comment by cecivieira** [comment]
Faz um tempinho que não teso o caption automático do Youtube, mas se tá
funcionando de boa, acho que é sim suficiente.

**Comment by alynnefs** [comment]
Também faz tempo que não olho, mas em maio do ano passado só gerava a legenda em português depois de algumas horas e sempre tinha erro. Precisava ser corrigido manualmente

**Comment by cecivieira** [comment]
Tienes una invitación para el siguiente evento.

Título: Teste de infraestrutura com tradutoras de espanhol
Cuándo: lun 4 de oct de 2021 18:00 – 18:20 Hora estándar de Brasilia -  
Recife

Información para unirse: Unirse con Google Meet
https://meet.google.com/zih-dzpt-ycf?hs=224

Calendario:  
***@***.***
Quién:
     * ***@***.*** organizador
     * ***@***.***
     * ***@***.***
     * ***@***.***
     * ***@***.***

Detalles del evento:  
https://calendar.google.com/calendar/event?action=VIEW&eid=NWZpbWg1YzA1bDdlZTgwcDAydjc1bnE4a3AgcmVwbHkrYWhqcWVqdXg2bXdjamx2ZWU0N21iNm42MnpncXJldmJuaGhkanJsZGxtQHJlcGx5LmdpdGh1Yi5jb20&tok=MjAjY2VjaXZpZWlyYUBnbWFpbC5jb21mNzhhNjRjODgzOWZmM2RmNTFiYTg1NzFmZTM1MmVhNjhkNzAyMmVk&ctz=America%2FRecife&hl=es&es=0

Invitación de Google Calendar: https://calendar.google.com/calendar/

Recibes este mensaje de cortesía en la dirección  
***@***.*** de la  
cuenta porque eres uno de los participantes de este evento.

Si ya no quieres recibir más avisos sobre este evento, recházalo. Si lo  
prefieres, solicita una cuenta de Google en  
https://calendar.google.com/calendar/ y controla la configuración de las  
notificaciones de todo tu calendario.

Si reenvías esta invitación, los destinatarios podrían enviar una respuesta  
al organizador para que los añada a la lista de invitados, o invitar a  
otras personas independientemente del estado de su propia invitación, o  
cambiar tu respuesta de confirmación de asistencia. Más información en  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by cecivieira** [comment]
Devido s funcionalidade de close caption do YouTube, não será necessária  contratação de empresa para legendar os vídeos
