### ISSUE TITLE
Assembleia da APyB

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#42]
Precisamos definir junto a APyB, como será a assembleia, já que 2021 é ano de eleição.

**Comment by rougeth** [comment]
Boa! E bloqueada também pela definição das ferramentas que usaremos durante o evento #12, por exemplo, se for Discord, uma sala de voz seria suficiente?

**Comment by mazulo** [comment]
@filipecifali tivemos uma reunião há 1 ou 2 semanas atrás pra começarmos a falar sobre isso. Temos alguns pontos ainda a discutir/analisar, esse incluso. Aparentemente há a possibilidade de fazer isso sem muita complicação (como a dos certificados A3, que além de caros é [ou pode ser] uma burocracia tremenda). Esse mês ainda pretendo ter uma posição melhor sobre essa parte.

**Comment by alynnefs** [comment]
A Python Brasil 2021 acontecerá entre 11 e 17 de outubro (#2)

**Comment by alynnefs** [comment]
@mazulo alguma novidade? :D

**Comment by mazulo** [comment]
@alynnefs ainda não 😞  mas estarei entrando em contato essa semana com algumas partes que vão poder auxiliar a gente nessa questão. Até sexta eu espero ter novidades

**Comment by rougeth** [comment]
@mazulo em relação a infra, para vocês se organizarem, vamos usar as mesmas ferramentas do ano passado: Discord, StreamYard e YouTube.
