### ISSUE TITLE
Cotar custo para identidade visual

### ISSUE THREAD

**Issue by loyannec** [pythonbrasil/pybr2021-org#43]

**Comment by cecivieira** [comment]
Os contatos das fornecedoras e orçamentos devem ser reunidos [nessa tabela](https://docs.google.com/spreadsheets/d/12K8yT1vgYTmVhf7WRDQSVe8Qjf-SvpJ34XnV8pjNdGw/edit?usp=sharing)

**Comment by alynnefs** [comment]
Essa issue permanecerá em "to do" até fecharmos os patrocínios. O time de artes irá contar quanto tempo estão disponibilizando individualmente.

**Comment by cecivieira** [comment]
Acredito que a remuneração da equipe pode ser ponto de pauta para próximos eventos.
Para esse eu consideraria todo o trabalho como voluntário
