### ISSUE TITLE
Criar e divulgar formulário para voluntários

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#45]
### Descrição
Além de convidar hosts (#11), precisamos convidar gente para infraestrutura e para a organização propriamente dita.
Motivo: com isso obtemos mais ajuda, opiniões e representatividade, e também aumentamos o sentimento de pertencimento à comunidade

### Requisitos para a atividade ser considerada como concluída

- Formulário criado e revisado
- Formulário divulgado nas redes sociais

**Comment by alynnefs** [comment]
com o formato do evento definido (#6 ), podemos começar a pensar na melhor forma de abrir formulário para inscrição de voluntários

**Comment by deboraazevedo** [comment]
passando aqui só pra dizer que amo isso do sentimento de pertencimento estar mencionado aqui <3 logo mais virei c pitacos uteis :P

**Comment by cecivieira** [comment]
> A responsabilidade pela trilha é dividida entre nós? Como foi organizado isso nos anos anteriores?

Sugestão de organização de voluntariado:

- Identificar grupos (ex.: Anfitriã, Infraestrutura, CDC, Arte e Comunicação)
- Definir escopo dos grupos:
    **Anfitriã** - Dar suporte em vídeo a palestrante durante a live: no início apresentar a palestrante e palestra, durante a palestra selecionar perguntas a serem feitas, no final realizar as perguntas.
    **Infraestrutura** - Dar suporte no backstage da live: fazer transição de telas, colocar e retirar participantes da live, fazer teste de infraestrutura com palestrantes e anfitriãs. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
    **CDC** - Monitorar interação entre participantes do evento na plataforma Discord e assistir palestras. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
    **Arte** - Desenvolver artes para evento usando o manual de identidade visual estabelecido. 
    **Comunicação** - Desenvolver textos para postagem em redes sociais e canais de divulgação previamente mapeados. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
- Definir responsáveis por cada grupo;
- Definir canal de comunicação (sugestão Discord);
- Preparar treinamento para grupos, quando adequado;
- Realizar treinamento.

**Comment by cecivieira** [comment]
Criada issue #83 para estruturação do programa de voluntariado.

**Comment by alynnefs** [comment]
Fechado até que seja necessário chamar mais gente
