### ISSUE TITLE
Redigir contrato com a JusBrasil [PRIORIDADE]

### ISSUE THREAD

**Issue by loyannec** [pythonbrasil/pybr2021-org#46]

**Comment by loyannec** [comment]
Essa issue está conectada com [essa](https://github.com/pythonbrasil/pybr2021-org/issues/40)

**Comment by alynnefs** [comment]
@anadulce sabe onde tem exemplo de contrato de anos anteriores?

**Comment by alynnefs** [comment]
Link do contrato em andamento: https://docs.google.com/document/d/11nZMtCtC6L9i3hyRoRijDIOK3fallWEp_cOltvL5vro/edit?usp=sharing

Pergunta: como a edição é online, deixo a cidade que resido atualmente ou a cidade da sede da APYB?

**Comment by alynnefs** [comment]
plano de patrocínio e minuta do contrato enviados

**Comment by rougeth** [comment]
@alynnefs podemos fechar a issue ou vamos esperar a assinatura do lado deles?

**Comment by alynnefs** [comment]
Acho que pode fechar sim, porque já foi redigido

**Comment by cecivieira** [comment]
Adicionar cláusula sobre envio de atividade com antecedência (30 dias)

https://github.com/pythonbrasil/pybr2021-org/issues/37

**Comment by alynnefs** [comment]
"Enviar a proposta de atividade prática de 3 ou 6 horas, que pode ser relacionada ou não ao contexto da empresa, com no mínimo um mês de antecedência."

Essa cláusula faz sentido? Vocês acham que dá pra deixar mais descritivo?

**Comment by alynnefs** [comment]
como peguei as modificações sugeridas pela Jusbrasil e tinha formatação, o novo link é esse: https://drive.google.com/file/d/1Dnxc2HahB6073a1gDZNn31rGQJYE_TLt/view?usp=sharing

Podem desconsiderar o anterior

**Comment by tiidadavena** [comment]
> "Enviar a proposta de atividade prática de 3 ou 6 horas, que pode ser relacionada ou não ao contexto da empresa, com no mínimo um mês de antecedência."
> 
> Essa cláusula faz sentido? Vocês acham que dá pra deixar mais descritivo?

Alterei o texto (que ainda está em vermelho) para assegurar que o conteúdo das atividades práticas envolva Python: " Enviar a proposta de atividade prática (sprint ou tutorial) de 3 ou 6 horas, que pode ser relacionada ou não ao contexto da empresa, com no mínimo um mês de antecedência. Entretanto, o tema da proposta da atividade prática deve envolver o tema do evento, isto é, ter o uso essencial da linguagem de programação Python na atividade."

**Comment by alynnefs** [comment]
@tiidadavena eu deixei vermelho de propósito, pra encontrarem fácil o que foi modificado. Você tá no freshdesk? respondi ontem, mas enviei o link com permissão de comentário

**Comment by alynnefs** [comment]
Contrato enviado para assinatura

**Comment by alynnefs** [comment]
Falta enviar nota fiscal para a jusbrasil

**Comment by rougeth** [comment]
Como solicito a emissão de uma nota fiscal?
 - https://docs.google.com/document/d/1j0UwPbZrN1E8W3zdclzyIxaFPgztjLAATSdsPAizFX0/edit#heading=h.26bkul24yshu

**Comment by alynnefs** [comment]
[contrato assinado](https://drive.google.com/file/d/10QdBXp-VnNVrmflkn_NgoX20uKmiT9s3/view?usp=sharing)

**Comment by alynnefs** [comment]
Nota fiscal enviada

**Comment by cecivieira** [comment]
@tiidadavena por favor, solicita o preenchimento desse formulário para a JusBrasil. Seria interessante o preenchimento até 10 setembro.
https://forms.gle/6Qgf5CSn2WMZt7ZY6
