### ISSUE TITLE
Verificar se os benefícios foram cumpridos

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#48]
Reler o plano para ver se cumprimos todos os benefícios prometidos

- [ ] Jusbrasil
- [ ] Buser

**Comment by cecivieira** [comment]
Usar checklist definido em #138

**Comment by cecivieira** [comment]
#226 - JusBrasil
#227 - Buser

**Comment by alynnefs** [comment]
#228 - Ebury

**Comment by cecivieira** [comment]
Todas as contrapartidas para patrocinadoras foram cumpridas.
Acompanhamento:
#269 #255 #252 #240 #228 #227 #226 #
