### ISSUE TITLE
[Reunião] Geral: 24 maio 2021

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#49]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um arquivo no [Google Drive da organização da Python Brasil 2021](https://drive.google.com/drive/folders/18zvyKpV42k_n_8Sr4a7yo5KxyU_SFgen?usp=sharing) e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião Geral

- Data: 24 maio 2021  
- Participantes:
  - Ana Cecília Vieira (@cecivieira)
  - Camila Dias(@cmdiasbr)
  - Gislene Vanessa(@martinsvanessa)
  - Gabriel Bellon (@gabubellon)
  - Alynne Ferreira (@alynnefs)
  - Marco Rougeth (@rougeth) 
  - Dandara Sousa (@dandaramcsousa)
  - Ana Dulce (@anadulce)
  - Andre Pastore (@apast)

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das tarefas

- [x] Verificar [tarefas bloqueadas](https://github.com/pythonbrasil/pybr2021-org/projects/1?card_filter_query=label%3Abloqueado):
  - Está claro o que precisa ser feito para desbloquear a tarefa?
  - Há parte da tarefa que pode prosseguir de alguma forma?
- [x] Verificar [tarefas em andamento](https://github.com/pythonbrasil/pybr2021-org/projects/1)
  - A tarefa está associada a uma pessoa responsável?
  - Há algo bloqueando o avanço da tarefa que possa ser discutido?
- [x] Verificar [tarefas abertas](https://github.com/pythonbrasil/pybr2021-org/issues?q=is%3Aopen+is%3Aissue+-project%3Apythonbrasil%2Fpybr2021-org%2F1+) não associadas ao projeto no Github.

### Itens a serem debatidos

Descrição | Link da Tarefa | Tempo para discussão | Observação|
----------|--------|----------------------| --|
Ingressos virtuais | #59 | -- | Vamos discutir na Issue e saber se vale a pena|
Definir data do evento | #30 | -- | Acontecerá entre 11 e 17 de outubro de 2021|
Definir estrutura| #6 | -- |  Seg-Sex: 1 mesa redonda, 5 Trilhas (4pt/1 ling estrang.) e 1 Keynote por dia, Sab-Dom:Sprints e Tutoriais  |
Demo: usando Discord para Palestras Relâmpago| -- | 5-10min | --|
Escolha de tema para identidade visual (propostas) | #29  | --| modelo 3d |

### Ações para serem realizadas

Atividade| Responsável | Link útil| Observações|
 --| --| --|--|
Criar um site landing page para fixar as Datas e com form para lista de email | -- | #56 | --|
[Reunião] Fluxo de edição e publicação dos vídeos |@rougeth @gabubellon @apast | #55 | --|
Discussão sobre trilha em lingua estrangeira | -- | #57 | --|
Discussão sobre Ingresso Virtual | -- | #59 | --|
Desenvolver tema para identidade visual | -- | #58 | --|

cc @<GitHub team do grupo de trabalho responsável pela reunião>

**Comment by rougeth** [comment]
Tópico para discussão: Para fins de engajamento/marketing, poderíamos criar ingressos virtuais no estilo da conf Next.js - 
https://twitter.com/jaydson/status/1394973225449402368

**Comment by rougeth** [comment]
*Atualizei a descrição da issue com o novo template - https://github.com/pythonbrasil/pybr2021-org/blob/main/.github/ISSUE_TEMPLATE/reuniao.md*

**Comment by cecivieira** [comment]
Tópicos para discussão: 
* Definir data do evento (observar #30)
* Definir estrutura (observa #6)

**Comment by rougeth** [comment]
Tópicos para discussão:
- Demo (5-10min): usando Discord para Palestras Relâmpago

**Comment by cecivieira** [comment]
Tópicos para discussão:
- Escolha de tema para identidade visual ([apresentação dos temas](https://drive.google.com/file/d/17aIRm1qEWfWKi6Ne0GBCbKKPMlIRyFzX/view?usp=sharing)) #29
