### ISSUE TITLE
Criar treinamento em vídeo para infraestutura

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#53]
Seria interessante transformar [esse guia](https://docs.google.com/document/d/17IBjUlSI3VaioHAM2sIVumlJqWWD4ix5EcWwL2_XjHE/edit#heading=h.jrxthz9dynnf) em vídeo? Acredito que, pra algumas pessoas, assistir seja mais fácil de entender do que ler. Mesmo assim acho legal manter os dois, já que escrito é mais rápido para cosultas.

Estou com uma versão paga do StreamYard até dia 4 e tanto posso gravar quanto posso passar o código de validação caso alguém queira gravar.

**Comment by rougeth** [comment]
Talvez uma reunião com os hosts uma semana antes do evento resolva? Até pq até lá, o processo em si pode mudar, né?

**Comment by martinsvanessa** [comment]
Penso que posso ajudar nisso juntamente com a @cmdiasbr

**Comment by martinsvanessa** [comment]
Como @anadulce questionou, manteremos a mesma estrutura do ano passado? Se for, perfeito!

**Comment by alynnefs** [comment]
> Como @anadulce questionou, manteremos a mesma estrutura do ano passado? Se for, perfeito! Precisaríamos apenas repassar o roteiro com vocês antes :)

Gosto de manter a mesma estrutura. Só queria ver se é possível fazer a maratona de programação, se faz sentido e o que mudaria na infração

**Comment by anadulce** [comment]
Acho que temos que ter vídeos separados para as atividades. Podemos começar por palestras que é o que temos certeza que manteremos igual. O que vocês acham?
Aí um vídeo pra quem é infra e um vídeo para participantes de como interagir/participar?

**Comment by alynnefs** [comment]
> Talvez uma reunião com os hosts uma semana antes do evento resolva? Até pq até lá, o processo em si pode mudar, né?

Então, pra hosts deve resolver sim. Meu medo maior são os voluntários de infraestrutura, pq tem que saber controlar as telas. Independente de ter vídeo, seria bom treinar um tempo antes

**Comment by alynnefs** [comment]
[guia de infraestrutura do ano passado](https://docs.google.com/document/d/17IBjUlSI3VaioHAM2sIVumlJqWWD4ix5EcWwL2_XjHE/edit?usp=sharing)

**Comment by alynnefs** [comment]
#265

**Comment by alynnefs** [comment]
[Vídeos brutos](https://drive.google.com/drive/folders/1FQAPnhhUSF9RwbOtKJZZY0HMvwDvA-E8), falta editar

**Comment by cecivieira** [comment]
@gabubellon peguei o video de palestrante para editar. Tá desincronizado o áudio e vídeo no arquivo original. Não vou consegui ajeitar isso com o tempo e ferramenta que tenho. Não é muito, mas se você se incomodar e consegui fazer, me ocupo com outra coisa
