### ISSUE TITLE
Divulgar data do evento

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#54]
### Descrição
Divulgar nas redes sociais e lançar site com landpage informando data do evento (#2)

### Requisitos para a atividade ser considerada como concluída

- Arte para Instagram;
- Arte para Twitter;
- https://github.com/pythonbrasil/pybr2021-org/issues/56 - Landing page

**Comment by alynnefs** [comment]
Depende da #62

**Comment by rougeth** [comment]
- https://2021.pythonbrasil.org.br
- https://twitter.com/pythonbrasil/status/1407366362155073539
- https://www.instagram.com/p/CQbZ9G1tKuU/
