### ISSUE TITLE
Criar um site landing page para fixar as Datas 

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#56]
### Descrição
Com a finalidade de reservar a data do evento e evitar conflitos, criar uma landing page com informações básicas.

### Requisitos para a atividade ser considerada como concluída

- landing page no link https://2021.pythonbrasil.org.br/

**Comment by alynnefs** [comment]
copiei o título da ata, mas acredito que o "form para lista de email" entra em outra issue. Vou modificar e criar a outra.

**Comment by rougeth** [comment]
\o/ https://2021.pythonbrasil.org.br/
