### ISSUE TITLE
Discussão sobre trilha em lingua estrangeira

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#57]
### Descrição
Trilha que visa trazer mais palestrantes de outros países, com a intenção de aumentar o leque de possibilidades de conteúdos, além de estreitar laços com as comunidades de outros países

### Requisitos para a atividade ser considerada como concluída

- Cotar o valor da tradução simultânea (#34)
- Decidir as línguas que serão permitidas
- Ver a possibilidade de estender para toda a semana

**Comment by cecivieira** [comment]
Sugiro que seja uma trilha focada na América Latina (espanhol), visando fornecer espaço para que nossa comunidade conheça o que está sendo produzido pelos países vizinhos. É comum conhecermos o que está sendo produzido no "norte global", mas pouco temos acesso ao que está sendo produzido no nosso contexto.

Nesse sentido, a trilha seria a semana inteira, em espanhol e com palesttrantes residente em países da América Latina (cuja lingua oficial é espanhol).

**Comment by rougeth** [comment]
+1 pela sugestão da Ceci.

**Comment by alynnefs** [comment]
Podemos decidir por ter uma trilha em espanhol ou alguém tem alguma objeção?

**Comment by rougeth** [comment]
Bora!

**Comment by gabubellon** [comment]
Bora +1

**Comment by deboraazevedo** [comment]
zero objeçoes e  vámonossssss

**Comment by anadulce** [comment]
Boora <3

**Comment by alynnefs** [comment]
então feshow
