### ISSUE TITLE
Desenvolver tema

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#58]
### Descrição
Reunir sugestões para aperfeiçoar tema da identidade visual escolhida.
![image](https://user-images.githubusercontent.com/30605862/119417872-2af5c700-bccd-11eb-953f-2c4eddd55f4c.png)

### Requisitos para a atividade ser considerada como concluída

- Enviar sugestões até 28 maio 2021

**Comment by cmdiasbr** [comment]
![exemplo1](https://user-images.githubusercontent.com/45003095/119856889-74226280-bee9-11eb-8a9a-a7bd8c75db4c.png)

**Comment by cmdiasbr** [comment]
![exemplo1-1](https://user-images.githubusercontent.com/45003095/119857913-573a5f00-beea-11eb-9e4d-9cec5cafb3f2.png)

**Comment by cmdiasbr** [comment]
![ideia3](https://user-images.githubusercontent.com/45003095/120044033-6f41d980-bfe3-11eb-96a8-f4dae5c90f9c.png)

**Comment by alynnefs** [comment]
verificar acessibilidade das cores
https://www.toptal.com/designers/colorfilter/

**Comment by alynnefs** [comment]
A última logo foi a escolhida
