### ISSUE TITLE
Discussão sobre Ingresso Virtual

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#59]
### Descrição
Para fins de engajamento/marketing, poderíamos criar ingressos virtuais no estilo da conf Next.js -
https://twitter.com/jaydson/status/1394973225449402368

### Requisitos para a atividade ser considerada como concluída

- Criar a arte do ingresso virtual
- Gerar ingresso a partir de um formulário de inscrição

**Comment by gabubellon** [comment]
Mais um exemplo de ingresso virtual https://www.shiftfestival.cc/ingresso/23/gabu-bellon esse é customizavel nome e imagem

**Comment by gabubellon** [comment]
Sobre esse assunto, validei qual era a ferramenta utilizada em cheguei nesse cara:
https://github.com/vercel/virtual-event-starter-kit
Um demo por ser visto aqui : https://demo.vercel.events/

Pontos e opiniões:
* Essa opção utiliza Nextjs o que nos faz precisar ter conhecimento;
* Vamos precisar fazer algumas integrações para poder fazer sistema de login e/ou validação de ingressos;
* Pode ser uma opção de site para como todo;
* Adicionamos um grau de complexidade que possivelmente não sejam tão boas assim apenas para termos um ingresso online
* Acho que podemos ter uma solução similar  as não vejo isso com prioridade

**Comment by gabubellon** [comment]
Estou fechando essa issue e podemos voltar nela próximo a abertura das inscrições
