### ISSUE TITLE
Definir formato do evento

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#6]
Quais serão as atividades?
Como elas serão distribuídas?

**Comment by rougeth** [comment]
> vai ter maratona de programação? se sim, qual a duração? é só pra se divertir ou vai ter alguma premiação simbólica?

Eu nunca participei de uma maratona, mas me parece ser complexo o suficiente para ter uma equipe dedicada de organização. Talvez uma parceria com uma escola/universidade em que se responsabilizariam pela logística?

> vamos alterar duração das palestras?

+1 por manter

> vamos alterar o horário de alguma atividade?

Como temos mais tempo para organizar, vamos incluir palestras relâmpago? ⚡️

**Comment by cecivieira** [comment]
Gosto da ideia de manter a programação do ano passado com mesmos horários, além de incluir palestras relâmpago.

O que vocês acham de incluir uma trilha em espanhol (5 trilha)? A ideia é para aproximar a comunidade dos outros países da América do Sul. Eu não daria a mesma ideia em outro idioma, pois acho que já tem muito evento em inglês e outro idioma ficaria descontextualizado.

**Comment by rougeth** [comment]
> O que vocês acham de incluir uma trilha em espanhol (5 trilha)? 

Gosto **muito** da ideia. Uma trilha a mais aumenta consideravelmente o trabalho e precisaríamos ter mais pessoas falantes de espanhol na organização, mas sou total a favor.

**Comment by alynnefs** [comment]
Também gosto de ter uma quinta trilha, mas como o @rougeth falou, vamos precisar de gente que sabe espanhol. O que acham de abrir logo o formulário pra chamar voluntários e colocar esse ponto? Porque se a gente souber quantas pessoas tem pra ajudar, dá pra ver se colocamos a quinta trilha em um dia ou na semana inteira (se tiver palestrante também)

**Comment by cecivieira** [comment]
Poderíamos colocar 2 dias de trilha em espanhol, seriam 10 palestras. Assim, aumentaria médio a quantidade de trabalho.

Acho que deveríamos abrir para voluntáriado quando tivermos, data, estrutura da programação, identidade visual e plano de patrocínio (com a identidade visual do evento). Talvez essas informações sejam importantes para organizar as pessoas em grupos e definir atividades a serem desenvolvidas.

**Comment by alynnefs** [comment]
> Poderíamos colocar 2 dias de trilha em espanhol, seriam 10 palestras. Assim, aumentaria médio a quantidade de trabalho.
> 
> Acho que deveríamos abrir para voluntáriado quando tivermos, data, estrutura da programação, identidade visual e plano de patrocínio (com a identidade visual do evento). Talvez essas informações sejam importantes para organizar as pessoas em grupos e definir atividades a serem desenvolvidas.

Sim sim, meu "logo" é supondo que amanhã a gente já feche a maior parte e tenha o resto das coisas encaminhada

**Comment by gabubellon** [comment]
Dando meus pitacos
* Manter o mesmo que foi feito dem 2020 (como já comentado)
* Sobre 1 trilha para pessoas da America Latina
1. Convidar pessoas já conhecidas que tenhma até palestras prontas
3. Dependendo o volume, fazemos 1 trilha a mais ou adicionamos em horários dentro das trilhas.
4. É impresindivel ter alguém na organização que se sinta confortável em espanhol (e derivações ) pra fazer essas pontes, seja como host, seja ajudando em pontos de comunicação (temos essa pessoa hoje ?)

Algo interessante que surgiu no discord são os canais de [palco](https://support.discord.com/hc/en-us/articles/1500005513722-Stage-Channels-FAQ) em que pessoas moderam outras em conversas de audio, tendo um limite de 100 pessoas ao mesmo tempo.

Pergunta:
Nesse tópico vamos definir se as palestras seram ao vivo, gravadas ? Se vamos pedir que um palestrante sugira um host ? Se o host pode ficar se infra ao mesmo tempo ?

**Comment by cecivieira** [comment]
@gabubellon me sinto confortável para fazer essas pontes em espanhol.

Acho interessante convidar algumas pessoas para a trilha em espanhol, mas também acho importante mesclar com submissões. Para fins orçamentários, poderíamos considerar trilha para 2 dias em espanhol e se não rolar submissões suficientes, a gente toma a decisão de reduzir a quantidade de dias ou diluir nas outras trilhas.

Acho que poderíamos definir sobre palestras gravadas e ao vivo. Responder as outras perguntas poderiam ser requisitos opcionais para dar essa tarefa como concluida. Acho que pedir para que a palestrante sugira host é legal, mas acho complicado a host ficar na infraestrutura ao mesmo tempo, pois teria que treiná-la no streamyard e passar o prtocolo que a organização tá usando; talvez seja mais fácil destinar um grupo de voluntários para isso.

Resumão da estrutura sugerida até agora:

| Periodicidade | Atividades|
| ------------- |-------------|
| seg. a qua. | 10h-12h Mesa redonda <br /> 15h-17h Atividade de patrocinadoras no Discord <br /> 15h-19h55 4 trilhas simultâneas + 10min sessão de Q&A no palco Discord pós cada palestra <br /> 20h-21h30 Keynote |
|  qui. a sex. | 10h-12h Mesa redonda <br /> 15h-17h Atividade de patrocinadoras no Discord <br /> 15h-19h55 4 trilhas (pt-br) e 1 trilha (spa) simultâneas + 10min sessão de Q&A no palco Discord pós cada palestra <br /> 20h-21h30 Keynote |
| sab. a dom.  | 10h-18h Sprints e tutoriais simultâneos |

**Sugestões:**

- Permitir palestras gravadas, desde que enviadas com 1 mês de antecedência (para dar tempo editar) e a palestrante estar disponível para interação no horário e sessão de Q&A pós palestra. A escolha entre se a palestra será gravada ou não fica a cargo da palestrante no ato do preenchimento da submissão;
- Poderíamo substituir a última palestra de cada trilha por palestras relâmpagos.

**Comment by gabubellon** [comment]
+1 para subistituir as palestras do fim do dia por palestras relampagos. Podemos usar a mesma stream da keynote e usar como um ponto pra chamar o pessoal pra keynote. E podemos abrir pra palestra relampago durante o dia (a aqui abre um bom ponto de patrociono/brinde dos patrocinadores e dar livros pro pessoal das palestras relampagos)

Gosto da ideia de perguntar ao palestrante se ele quer ao vivo ou gravado, só temos que alinhar isso com custo x tempo

**Comment by rougeth** [comment]
> Se vamos pedir que um palestrante sugira um host ?
Não entendo o motivo da pessoa palestrante escolher host 🙃 alguém me explica? Na minha cabeça só atrapalha a org, já que não dá pra se organizar previamente.

> Poderíamos substituir a última palestra de cada trilha por palestras relâmpagos.
E juntá-las num stream só? Ou você pensou em ter palestras relâmpago concorrentes?

**Comment by deboraazevedo** [comment]
acredito que isso das palestras relâmpagos aconteceram no stream do keynote uma ótima ideia, mas aí nao sei se seria legal estar concorrendo com outras palestras, e sim tirar o último horário de cada dia pra ter as palestras relâmpagos.

gosto dos dois dias em espanhol, ou um só, como comentei na issue da tradução simultanea, como a pycon charlas da pycon us

sobre escolher host, acho que é algo pra deixar a pessoa palestrante se sentir mais confortável com quem vai apresentá-la pro pessoal que vai assistir, diminuir nervosismo etc, mas não vejo muito sentido isso se as palestras já forem pré-gravadas, por exemplo..

**Comment by cecivieira** [comment]
> Não entendo o motivo da pessoa palestrante escolher host upside_down_face alguém me explica? Na minha cabeça só atrapalha a org, já que não dá pra se organizar previamente.
Como espectadora, foi muito melhor assistir apresentações as quais a anfitriã era colega/amiga/admiradora da palestrante. A interação no começo e final foram mais fluidas e relaxadas. Entendo que isso pode atrapalhar a organização e gostei muito de como foi feito no ano passado. Talvez pedir para as voluntárias colocarem seus nomes em atividades com pessoas conhecidas, resolva.

> E juntá-las num stream só? Ou você pensou em ter palestras relâmpago concorrentes?
Gostei da ideia de Gabu, de fazer no stream da keynote.

**Comment by gabubellon** [comment]
Minha ideia é fazer as relâmpagos antes do keynote, e sem concorrencia (pensando em um tradução real x virtual) as palestras relampagos ajudavam a trazer o pessoal pra sala antes dos keynotes.

**Comment by alynnefs** [comment]
> Minha ideia é fazer as relâmpagos antes do keynote, e sem concorrencia (pensando em um tradução real x virtual) as palestras relampagos ajudavam a trazer o pessoal pra sala antes dos keynotes.

Na PyNE vai ser antes do keynote mesmo

**Comment by cecivieira** [comment]
Estrutura conversa durante a reunião #49 

| Periodicidade | Atividades|
| ------------- |-------------|
|  seg. a sex. | 10h-12h Mesa redonda <br /> 15h-17h Atividade de patrocinadoras no Discord <br /> 15h-19h55 4 trilhas (pt-br) e 1 trilha internacional (?a confirmar) <br /> 20h-21h30 Keynote |
| sab. a dom.  | 10h-18h Sprints e tutoriais simultâneos |
