### ISSUE TITLE
Definir logo

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#61]
### Descrição
Com base na identidade visual escolhida e nas ideias presentes na issue #58, precisamos criar a logo oficial e as cores, para que possam ser usadas nas artes de comunicação

### Requisitos para a atividade ser considerada como concluída

- Logo finalizada
- Hexadecimal das cores de fácil acesso

**Comment by cmdiasbr** [comment]
Ideias de logo: https://drive.google.com/drive/folders/1oXs9oP3qVveleqoVz2duvlwDMJwpETaw?usp=sharing

**Comment by alynnefs** [comment]
conforme conversado na issue #58, a [última ideia](https://github.com/pythonbrasil/pybr2021-org/issues/58#issuecomment-850688186) foi escolhida
