### ISSUE TITLE
Criar arte para divulgação da PyBR 2021

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#62]
### Descrição
Criar arte com a data do evento e demais informações necessárias

### Requisitos para a atividade ser considerada como concluída

- Arte criada
- Divulgação nas redes sociais

**Comment by cmdiasbr** [comment]
![divulgacao-2021-v2](https://user-images.githubusercontent.com/45003095/120554051-a9d6b800-c3cf-11eb-8cec-12e7e7a62d61.png)

**Comment by alynnefs** [comment]
arte pronta: https://drive.google.com/file/d/1Yxgqj30U1MpqWLkx0FhSqCjk6wyetHw3/view?usp=sharing
