### ISSUE TITLE
Criar arte para a divulgação das inscrições de participantes

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#63]
### Descrição
Criar arte para informar que as inscrições já iniciaram

### Requisitos para a atividade ser considerada como concluída

- Arte criada
- Divulgação nas redes sociais

**Comment by alynnefs** [comment]
issue relacionada: #3

**Comment by cmdiasbr** [comment]
![Cards](https://user-images.githubusercontent.com/45003095/126553109-3264cd64-dd7e-4af1-8dcf-1cd739321960.png)


Para tradução: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit
