### ISSUE TITLE
Criar arte de submissão de atividades

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#64]
### Descrição
Arte informativa sobre a submissão de palestras, tutoriais e sprints

### Requisitos para a atividade ser considerada como concluída

- Arte criada
- Divulgação nas redes sociais

**Comment by alynnefs** [comment]
Issues relacionadas: #14, #15 e #16

**Comment by cecivieira** [comment]
### Campanha
Chamada para atividades
  
### Peça/publicidade solicitada
Cartão para redes sociais

### Detalhamento do uso
Divulgar período de submissão de atividades entre 12 jun. a 12 ago.

### Data prevista para uso da arte
12 jun. 2021

### Quais informações devem aparecer na arte
--

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cmdiasbr** [comment]
Artes prontas https://www.canva.com/design/DAEjeGESl4Q/pVYqAhjwIfBzJxr1Z7LWBw/edit

**Comment by cecivieira** [comment]
Arte traduzida e agendada nas redes sociais.

@deboraazevedo falta agendar no telegram e demais

**Comment by cecivieira** [comment]
https://www.instagram.com/p/CRXcNzYjOmt/

https://twitter.com/pythonbrasil/status/1416038385706283020

https://twitter.com/pythonbrasil/status/1415686354973777925

https://twitter.com/pythonbrasil/status/1415686354906673155
