### ISSUE TITLE
Submissão de atividades - Encerramento

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#65]
### Descrição
Arte informativa sobre o fim do período de submissão de palestras, tutoriais e sprints

### Requisitos para a atividade ser considerada como concluída

- Arte criada
- Divulgação nas redes sociais

**Comment by alynnefs** [comment]
Issues relacionadas: #14, #15 e #16

**Comment by cecivieira** [comment]
### Campanha
Chamada para atividades
  
### Peça/publicidade solicitada
- Cartão informando que falta 1 semana para encerramento
- Cartão informando que falta 1 dia para encerramento

### Detalhamento do uso
As peças serão usadas para alertar sobre a aproximação da data limite para submeter atividades.

### Data prevista para uso da arte
05 ago. 2021 e 11 ago. 2021

### Quais informações devem aparecer na arte
Até 12 ago. 23h59 (UTF -3)

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] E-mail;
- [x] Discord PyBr2020;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by martinsvanessa** [comment]
![SUBMISSOES DE ATIVIDADES](https://user-images.githubusercontent.com/18190437/125217642-8db01b80-e297-11eb-85d4-92a190793e46.png)

**Comment by martinsvanessa** [comment]
https://www.canva.com/design/DAEjeGESl4Q/pVYqAhjwIfBzJxr1Z7LWBw/edit

**Comment by cecivieira** [comment]
@martinsvanessa Ficou massa!!! Obrigada!! Deixa a issue aberta, por favor, pra @deboraazevedo programar a publicação e registrar o link do post aqui também

**Comment by paulohenriquedsgn** [comment]
Pessoal boa noite. A submissão das palestras vai ser adiada? Poderiam nos confirmar isso?

**Comment by cecivieira** [comment]
@paulohenriquedsgn na ata da reunião passada #156 não define isso.
Inseri o ponto na pauta para a próxima reunião #182 . Só teremos resposta após 09 ago.

**Comment by paulohenriquedsgn** [comment]
Links dos posts

Instagram - https://www.instagram.com/p/CSb8t4HMDXL/?utm_source=ig_web_copy_link
Twitter - https://twitter.com/pythonbrasil/status/1425970642499870723?s=20
Facebook - https://www.facebook.com/pythonbrasil/photos/a.582882565067606/4544107765611713/
Linkedin - https://www.linkedin.com/posts/apyb_pybr2021-activity-6831192562359918592-hJ8L
