### ISSUE TITLE
Criar arte para apresentação de palestrantes

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#66]
### Descrição
Modelo que pode ser editado para substituir a foto e o título

### Requisitos para a atividade ser considerada como concluída

- Arte criada
- Link com permissão de edição divulgado com a organização

**Comment by cecivieira** [comment]
@alynnefs tô fechando essa issue para abrir uma para cada trilha. Fica mais fácil pra gente gestionar as publicações

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/135735424-29921d2e-587d-4696-8597-cec5d490ea68.png)

**Comment by cecivieira** [comment]
@gabubellon arte ajustada para palestrantes
