### ISSUE TITLE
Criar arte com contagem regressiva para o início do evento

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#67]
### Descrição
Sugestão: faltam X meses, faltam Y dias.

### Requisitos para a atividade ser considerada como concluída

- Arte criada
- Link com permissão de edição divulgado com a organização

**Comment by cmdiasbr** [comment]
Para tradução: https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

![Cards (1)](https://user-images.githubusercontent.com/45003095/127708698-22574b33-b7fa-4471-b642-adea1b2b8b35.png)

**Comment by paulohenriquedsgn** [comment]
@cecivieira as voluntárias poderiam traduzir essa arte? Estamos querendo programar a postagem para o dia 11/08 e precisaria da versão em espanhol para o carrossel e está faltando apenas isso, por favor.

**Comment by cecivieira** [comment]
@paulohenriquedsgn 
Feito

![image](https://user-images.githubusercontent.com/30605862/128508157-659459f1-6a0c-4473-a049-c84894ba14b5.png)

**Comment by cecivieira** [comment]
@deboraazevedo @paulohenriquedsgn Seria interessante postar essa arte no final de semana, se der.

**Comment by alynnefs** [comment]
dá pra modificar essa arte dizendo que falta um mês?

**Comment by cmdiasbr** [comment]
Só editar aqui @alynnefs https://www.canva.com/design/DAEjPWNunB0/yz3QY6JM1Huj4I6uZi3ZAA/edit

**Comment by cecivieira** [comment]
@alynnefsa versão em espanhol está nesse link:
https://www.canva.com/design/DAEloufMqdM/share/preview?token=OrE09zDsOky8usKp-wFSCA&role=EDITOR&utm_content=DAEloufMqdM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by alynnefs** [comment]
![Cards](https://user-images.githubusercontent.com/17454743/131593061-42e7f455-f140-4fb5-9284-24227f4d7490.png)

![es_propuestas_recuerdo](https://user-images.githubusercontent.com/17454743/131593145-72912cfb-c70b-4002-baa9-103a6b1c5251.png)

**Comment by cecivieira** [comment]
@paulohenriquedsgn @deboraazevedo programei essa arte para sair dia 11.

**Comment by cecivieira** [comment]
@paulohenriquedsgn @deboraazevedo programei essa arte para sair dia 11.

Como será um carrossel, a notificação será enviada para o celular de um de vocês. Caso isso não aconteça, por favor, informa

**Comment by deboraazevedo** [comment]
ok, coloquei um lembrete aqui no celular também para não esquecer

**Comment by cecivieira** [comment]
https://twitter.com/pythonbrasil/status/1436691453166694400
https://www.instagram.com/p/CTujzA1gSmy/

Agendado também para quando faltar 1 semana
