### ISSUE TITLE
Criar banner para as redes sociais

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#68]
### Descrição
Redes sociais que aceitam banner:
- facebook
- twitter

### Requisitos para a atividade ser considerada como concluída

- Banner substituído nas redes sociais

**Comment by cmdiasbr** [comment]
https://drive.google.com/drive/u/1/folders/1vijbP6a3Af0xOZrqsnIOLDAjUQ3guA0U

**Comment by alynnefs** [comment]
Vou fechar a issue. Quando a gente divulgar o evento, voltamos aqui <3

**Comment by cmdiasbr** [comment]
Atualizado https://drive.google.com/drive/u/1/folders/1vijbP6a3Af0xOZrqsnIOLDAjUQ3guA0U

**Comment by paulohenriquedsgn** [comment]
Todas as redes estão com as devidas capas (banners)
