### ISSUE TITLE
Decidir se iremos cobrar evento e doar a valores alguma para instituição

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#69]
### Descrição
Juntar opiniões sobre a possibilidade de cobrar ingressos.

### Requisitos para a atividade ser considerada como concluída

- Definir se vai ser cobrado ou não

**Comment by cecivieira** [comment]
Proposição:

Cobrar ingresso em valor muito baixo, entre R$2 e R$5, o qual seria totalmente convertido para doação a uma instituição que trabalhe com segurança alimentar (combate a fome).

No formulário de inscrição existiria um campo de isenção para que haja a possibilidade das pessoas declararem que não podem pagar pelo ingresso.

**Comment by alynnefs** [comment]
Ainda não fechamos as rodas de conversa, mas tenho alguns convidados em mente. Caso o evento seja cobrado, seria legal a doação ir para as instituições que eles participam, além das instituições de segurança alimentar

**Comment by anadulce** [comment]
Eu acho que seria melhor deixar como ingresso opcional do que um campo de isenção, tipo o que fizeram no evento da Vinta ano passado.
Pessoalmente, acho que é melhor não dificultar ou burocratizar o acesso, porque essa é possivelmente (e eu estou torcendo muito por isso) nossa última edição online de quarentena, e seria legal levar o evento ao maior número de pessoas possível. Se tornarmos o não-pagamento burocrático (com um campo específico de isenção) as pessoas poderão se sentir um pouco coagidas a solicitarem essa isenção.
Eu entendo que existe um ponto positivo além da reversão dessa verba às instituições favorecidas, porque mesmo que seja um preço simbólico, faz com que as pessoas sejam um pouquinho mais responsáveis pelo evento e participem porque pagaram, mas o apelo de um evento gratuito gera mais divulgações por parte da própria comunidade, ano passado tinha muita gente engajada em divulgar o evento porque era gratuito.
Acho que deveríamos manter o evento gratuito porque realmente não temos custos relevantes e vamos atingir mais pessoas.

**Comment by cecivieira** [comment]
Resultado da pesquisa aberta no Twitter por 3 dias:
![image](https://user-images.githubusercontent.com/30605862/124368232-9bc9c080-dc35-11eb-8a46-227abd7c0139.png)

**Comment by cecivieira** [comment]
O acesso a pesquisa postada no Instagram só é possível no período de vigencia do story (24h), ou seja, não sabemos o resultado

**Comment by cecivieira** [comment]
Vocês acham que é relevante refazer? Ou só o resultado do twitter (aonde temos mais que o dobro de seguidores) já vale?

**Comment by deboraazevedo** [comment]
> O acesso a pesquisa postada no Instagram só é possível no período de vigencia do story (24h), ou seja, não sabemos o resultado

Isso dá pra fazer sim, dá pra ver o story postado nos arquivos (tela do perfil > vai no botão superior direito de 3 listras > arquivo > arquivos de story. Você consegue ver os stories anteriores e se tu clica no story da enquete, aparecem as informações da porcentagem dos votos e quem votou

**Comment by cecivieira** [comment]
Que massa!

Consegui ver as porcentagens, mas não a quantidade votos:

**Comment by cecivieira** [comment]
Que massa!

Consegui ver as porcentagens, mas não a quantidade votos:
![image](https://user-images.githubusercontent.com/30605862/124387112-a32faf00-dcb3-11eb-993d-905ef1f38c7c.png)
![image](https://user-images.githubusercontent.com/30605862/124387114-a6c33600-dcb3-11eb-9cfe-1676bb742bf2.png)

------------
![image](https://user-images.githubusercontent.com/30605862/124387119-aaef5380-dcb3-11eb-902f-6999029b3813.png)
![image](https://user-images.githubusercontent.com/30605862/124387125-adea4400-dcb3-11eb-8a00-91a73c2581ce.png)

**Comment by cecivieira** [comment]
Que massa!

Consegui ver as porcentagens, mas não a quantidade votos:
![image](https://user-images.githubusercontent.com/30605862/124387235-1802e900-dcb4-11eb-957a-39e5bd762fbf.png)
![image](https://user-images.githubusercontent.com/30605862/124387240-1c2f0680-dcb4-11eb-86de-bdc69f36729d.png)


------------
![image](https://user-images.githubusercontent.com/30605862/124387253-281ac880-dcb4-11eb-80a5-906ad7a9307f.png)
![image](https://user-images.githubusercontent.com/30605862/124387257-2ea94000-dcb4-11eb-97ad-7aea471d463a.png)

**Comment by cecivieira** [comment]
Foi decidio na reunião #99 que a arrecadação financeira será através de doações voluntárias

```
Trecho da ata
    de acordo com as pesquisas, a porcentagem de pessoas que doariam voluntariamente diminui
    deixar claro que iremos escolher as instituições
    não iremos deixar o eventos fechado, mesmo tendo ingressos pagos
```


Formas:
- Ingressos gratuitos e com várias faixas de valor;
- Bot no Discord incentivando a doação através do qr code + pix;
- Incentivo para doação nos intervalos ou início entre palestras com qr code + pix
