### ISSUE TITLE
Anunciar Python Brasil online e Alynne como Big Kahuna

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#7]
Depende da APyB divulgar a mudança na lista dos associados

**Comment by rougeth** [comment]
Anúncio da APyB - https://twitter.com/apyb/status/1393209562099068930

**Comment by rougeth** [comment]
Anúncio no [@pythonbrasil](https://twitter.com/pythonbrasil): https://twitter.com/pythonbrasil/status/1393650540735864832
