### ISSUE TITLE
Checar processo de início e encerramento das lives no StreamYard/YouTube

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#73]
### Descrição
Em 2020, tivemos um problema em algumas trilhas/lives em que, por algum motivo que ainda não sabemos, o vídeo publicado no YouTube e o arquivo fonte baixado do StreamYard foram gerados com alguns segundos de diferença. Essa diferença tornou a edição mais trabalhosa, já que impediu que usássemos o vídeo no YouTube para buscar os tempos dos cortes de cada palestra.

A suspeita é que, por alguma diferença no uso do StreamYard acabou causando essa diferença. Então a proposta dessa tarefa é validar o processo que vamos usar nos dias do evento para iniciar um streaming, publicar no YouTube e encerrá-lo.

### Requisitos para a atividade ser considerada como concluída
- Fazer testes de lives no StreamYard e checar os tempos no vídeo do YouTube e no arquivo fonte baixado do StreamYard. 
- Criar um passo a passo de como será o processo de iniciar e finalizar as lives no StreamYard.

**Comment by gabubellon** [comment]
Para realizar esse teste precisamos de uma conta paga do stream yard

**Comment by cecivieira** [comment]
Fizemos uma live sábado passado com uma conta paga do StreamYard. Querem os arquivos do streamyard e youtube para fazer o teste?

**Comment by rougeth** [comment]
@cecivieira precisamos combinar antes de fazer o streaming. Um dos testes é saber em quanto tempo conseguimos ter o botão para download do vídeo.

O outro ponto talvez faça parte do manual do host/infra (ou pessoa que vá cuidar do streamyard).

**Comment by cecivieira** [comment]
Entendi.
Vi que @alynnefs disponibilizou a conta da PyNE para fazer isso.

**Comment by rougeth** [comment]
Acham que podemos seguir sem essa issue? Do ponto de vista da edição de vídeo, acho que podemos contornar qualquer problema conforme fiquemos ano passado. @cecivieira ainda estamos sem ninguém responsável pelo grupo de trabalho dos hosts/infra, né?

**Comment by cecivieira** [comment]
Ainda não temos ninguém responsável por hosts/infra.
Acho que podemos fechar a issue.
