### ISSUE TITLE
Automação da criação dos formulários de avaliação das submissões

### ISSUE THREAD

**Issue by belaaiza** [pythonbrasil/pybr2021-org#75]
### Descrição
No ano passado usamos um script da @anadulce para gerar uma planilha com as informações anôninmas das submissões e as pessoas avaliadoras alocadas. Com isso, usamos o Google App Scripts para ler a planilha, gerar os formulário com as informações, e gerar outra planilha com nome e e-mail da pessoa avaliadora, e os links dos formulários com as submissões que ela deveria avaliar.

O problema que tivemos foi que os scripts da Google App Scripts ficaram muito lentos, excedendo o limite de 5 minutos da Google para contas normais e 30 minutos para contas G Suite Business / Enterprise / Education, isso fazia com que o processamento fosse interrompido e daí a gente precisava de um esforço manual pra identificar onde parou e onde reiniciar.

Para este ano temos algumas opções:
1 - Podemos tentar otimizar o script para que ele execute de forma mais rápida, dentro do timeout
2 - Se a opção 1 não for possível, podemos identificar de forma automática onde o script parou (salvando o estado, ou algo do tipo) e reiniciar deste ponto também de forma automática usando os [triggers do ScriptService](https://developers.google.com/apps-script/reference/script).
3 - Não usar o Google App Scripts e gerar os formulários de outra forma

### Requisitos para a atividade ser considerada como concluída

- Código da automação pronto para ser executado em ambiente produtivo
- O código deve ter sido testado em uma massa com volume considerável 

Link para o script: https://script.google.com/d/1l3tO3hfyfonSwDBGKtrgkPxDDNFG3EygIuzSsSP4l8JFnkE1InSqLBOc/edit?usp=sharing

**Comment by gabubellon** [comment]
@belaaiza ou @anadulce  Acho que seria legal documentar caso ainda não tenha como e onde estão esses scripts, assim conseguimos compartilhar a informação e até testar e ajudar na solução.

Vi que o Google App Scripts tem api python https://developers.google.com/apps-script/api/quickstart/python . Talvez possamos pensar em algo mais robusto com isso

**Comment by belaaiza** [comment]
@gabubellon atualizei a issue com o link para o script, esta na pasta CFP > Avaliação do evento do ano passado. Nós conhecemos a API Python mas infelizmente ela é bem novinha ainda, só permite a execução remota do script, talvez seja mais fácil a captura das exceções com ela

**Comment by anadulce** [comment]
@belaaiza foi a grande responsável pelo sucesso das palestras ano passado, eu só gerei a distribuição, os scripts dela geraram os formulários de avaliação e agruparam as respostas, foi incrível!
Precisamos retomar essa task e ter um prazo para abertura/encerramento das submissões de atividades.
@belaaiza podemos marcar uma reunião para discutir especificamente esse tema?

**Comment by belaaiza** [comment]
@anadulce podemos sim, vou marcar na semana que vem pra eu preparar o material pra reunião esse fds

**Comment by rougeth** [comment]
@belaaiza essa reunião não aconteceu ainda né? @gabubellon tinha comentado de dar uma olhada se o Google está aceitando scripts Python.

**Comment by belaaiza** [comment]
@rougeth não rolou :( eu tô na zona rural e a internet aqui tá muito ruim pra fazer a call, mas a partir de amanhã vou  ter uma internet melhor, podemos marcar nesse fds ou no próximo, vou chamar lá no discord.

Sobre a google aceitar scripts Python, comentei ali em cima, tem uma API mas é bem básica, só permite a execução remota dos scripts

**Comment by cecivieira** [comment]
A issue #17 trata sobre o mesmo assunto, então fechei e tô trazendo a conversa para cá:

A conversa é sobre o uso da plataforma https://www.papercall.io/. @belaaiza Dá par anonimizar, mas não sei se tem como inserir um formulário de avaliação. Teria que testar a plataforma.

@anadulce  vai ficar off por uns dias por motivos pessoais. Acho que por conta do nosso tempo, podemos seguir o plano de usar o mesmo sistema do ano passado, caso não consigamos testar a plataforma essa semana para abrir a inscrições até 17/07.

Essa imagem é um exemplo de como tá sendo feita a votação na PyLatam:
![image](https://user-images.githubusercontent.com/30605862/125196446-5f4b2580-e230-11eb-9e7f-623aee856648.png)

**Comment by belaaiza** [comment]
Pessoal, nós usaremos a mesma versão do ano passado pro formulário de avaliação? https://docs.google.com/forms/d/16azYljbRqleVl0Mp-rTyZ_blXm2RTt2huIAi8tDXL4M/edit

@anadulce @gabubellon lembro que vcs estavam bem envolvidos com o algoritmo de ranqueamento ano passado, vocês gostaram de como ficou o form e o ranqueamento com base nessas perguntas depois?

**Comment by cecivieira** [comment]
Não entendi o que queremos saber com essa pergunta:
"Como você avalia esta atividade em relação à confiabilidade ao tema proposto?"

**Comment by belaaiza** [comment]
o pessoal pode me corrigir se eu  estiver errada mas acredito que seja o quão confiável as informações tragas sobre o tema estão corretas

**Comment by cecivieira** [comment]
Sugestão de texto para a pergunta:
Como você avalia a confiabilidade das informações apresentadas sobre o tema?

**Comment by belaaiza** [comment]
pessoal, como o script para geração dos forms de avaliação já está pronto vou fechar essa issue, beleza?

falei com a @anadulce que precisamos abrir issues para dois outros scripts:
1 - script de distribuição das avaliações (alocação de qual submissão vai ser avaliada por quem)
2 - script de ranqueamento bon base nas avaliações

**Comment by cecivieira** [comment]
@belaaiza tu poderia linkar as novas issues aqui?

**Comment by belaaiza** [comment]
1 - script de distribuição das avaliações (alocação de qual submissão vai ser avaliada por quem) #177 
2 - script de ranqueamento com base nas avaliações #178
