### ISSUE TITLE
Traduzir o plano de patrocínio para inglês

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#78]
### Descrição
Traduzir o plano de patrocínio para a língua inglesa, de forma que possamos enviar para empresas interessadas que não têm o português como língua oficial.

### Requisitos para a atividade ser considerada como concluída

- Versão em inglês finalizada
- Valores convertidos para dólar

**Comment by alynnefs** [comment]
Link do slide para ser modificado. No momento está em português, mas pode ser editado diretamente: https://drive.google.com/file/d/1I_U7rBW_SpE0fKVNtdfN42VBVYQDR_cZ/view?usp=sharing

**Comment by cecivieira** [comment]
Plano de patrocínio sendo traduzido por @jtemporal 

Plano em inglês:
https://drive.google.com/file/d/162aP16LwpYutmrnhgXypclHfO0UxnSLL/view?usp=sharing

**Comment by deboraazevedo** [comment]
posso revisar se preciso, mas pra traduzir nao.. essa semana eu tô com notas do bimestre dos alunos pra entregar, aí essa semana especifica eu não consigo me comprometer

**Comment by tiidadavena** [comment]
Posso traduzir, mas vou precisar de alguém revisar

**Comment by jtemporal** [comment]
@tiidadavena pode iniciar então! Minha vida virou de pernas pro ar e não consegui encostar nele mas essa semana eu consigo! A gnt divide a carga 😉 

@cecivieira confere pra dar acesso pra @tiidadavena por gentileza ^^

**Comment by cecivieira** [comment]
@tiidadavena Link para edição:
https://drive.google.com/file/d/162aP16LwpYutmrnhgXypclHfO0UxnSLL/view?usp=sharing

**Comment by tiidadavena** [comment]
Tradução feita + ajustes no layout, devo fazer alguns ajustes amanhã, mas fiquem à vontade pra dar feedbacks e outras observações.
Obrigada pela parceria, @jtemporal! <3

**Comment by tiidadavena** [comment]
Vi na tradução que só traduzi os valores para EN.
No caso, o valor convertido será exatamente o valor em reais ou terá algum tipo de reajuste (para cima ou pra baixo)?

**Comment by cecivieira** [comment]
@mazulo @rougeth qual o percentual de imposto sobre o valor recebido de empresas estrangueiras precisaremos recolher?

Talvez essa informação ajude a decidir se só usaremos o câmbio do dia ou incluir algo a mais.

**Comment by rougeth** [comment]
Em uma mensagem antiga da pybr2019 sobre recebimento de patrocínio em dólar:
```
- Spread é 1% do valor com limite de cobrança máxima de R$275,00 reais
- Bancos intermediários descontam de $30.00 a $100.00 USD;
- 4.5% de tributos pagos pela APyB;
- IOF;
- Cotação do Dólar
- O restante é margem para flutuação do dólar;
```

Receber patrocínio em dólares tem custos adicionais mesmo. @apast consegue ajudar a gente aqui, ele que definiu os valores em 2019 :)

**Comment by apast** [comment]
Pessoal, os valores descritor pelo @rougeth estão corretos. Utilizamos estes indicadores em 2019 e 2021, alinhado com APyB.

Nesta planilha, temos a base para o controle financeiro.

https://docs.google.com/spreadsheets/d/1ddYFSfrkOsH0LbP7O1a13IuZImvUXEGnfvpQiv3aISM/edit#gid=510557133

Na sheet: **Referencias**, tem os valores aproximados da cota de patrocínio em USD.

Tem o valor baseado na cotação do dolar no dia corrente, além da mínima e máxima do ano. Isto nos ajuda a estimar a flutuação da moeda no ano atual.

Já há colunas com o calculo de descontos (impostos, apyb, banco, taxas exterior).

Para o valor se aproximar do valor em Reais, considerando o valor líquido (após taxas e impostos):

Ouro: USD 10.500,00
Prata: USD 7.000,00
Bronze: USD 2.300,00

Podemos fazer uma chamada para exercitar as possibilidades e outros números.

**Comment by apast** [comment]
@alynnefs , editei/revisei uma parte neste arquivo aqui, na pasta de patrocínio:

https://docs.google.com/presentation/d/162aP16LwpYutmrnhgXypclHfO0UxnSLL/edit#slide=id.p1

Está correto?

Faltou traduzir as cotas. Coloquei valores, podemos discutir mais sobre.

@tiidadavena

**Comment by alynnefs** [comment]
> 
> Está correto?
> 


@apast, é esse mesmo (:

**Comment by rougeth** [comment]
Criei uma issue no manual da Python Brasil para, quem sabe um dia, termos isso documentado hahah☝️

**Comment by tiidadavena** [comment]
Sobre a logo, comentaram do título "Python Brasil" logo abaixo da ilustração ser traduzido para o inglês.

Para divulgação internacional, concordo que faz sentido uma logo com os dizeres "Python Brazil".

![image](https://user-images.githubusercontent.com/12106738/124772616-92c93f80-df12-11eb-8f2c-ede8e188950b.png)

**Comment by tiidadavena** [comment]
> @alynnefs , editei/revisei uma parte neste arquivo aqui, na pasta de patrocínio:
> 
> https://docs.google.com/presentation/d/162aP16LwpYutmrnhgXypclHfO0UxnSLL/edit#slide=id.p1
> 
> Está correto?
> 
> Faltou traduzir as cotas. Coloquei valores, podemos discutir mais sobre.
> 
> @tiidadavena

Opa, Pastore!

Podemos ver sim, se precisar falar mais, estou no Telegram como @julianabrlm

**Comment by jtemporal** [comment]
Gente eu não traduziria o nome do evento, isso pode confundir as pessoas ao procurarem pelo evento nas redes sociais pra saber nosso alcance, todas nossas redes e o site é pythonbrasil então eu diria pra manter tudo com s mesmo.

Fora isso eu acabei de passar por todo documento e arrumei umas questões de ingles pra melhorar a leitura, acho que agora ta pronto.

Eu também deixei todos os o lugares com o nome do evento com S, então se decidirem mudar pra Z precisa atualizar os demais títulos.

**Comment by cecivieira** [comment]
Vocês arrasaram @tiidadavena @camilafracaro @jtemporal !!
Inseri a versão do plano em inglês no site
https://github.com/pythonbrasil/pybr2021-site/pull/3
