### ISSUE TITLE
Escolha de keynotes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#81]
### Descrição
Escolher 5 keynotes para o evento.

### Requisitos para a atividade ser considerada como concluída

- Reunir sugestões
- Estabelecer critérios
- Realizar escolha

**Comment by cecivieira** [comment]
As sugestões devem ser realizadas nesse arquivo:

https://docs.google.com/spreadsheets/d/1qfc6b5w5IBYgCelThvSSeKcGcHncd3vaMAcx9ZXU_IA/edit?usp=sharing

**Comment by cecivieira** [comment]
Calendário 

Receber sugestão de keynote até 09 agosto.

**Comment by gabubellon** [comment]
Levando pra pauta #182

**Comment by alynnefs** [comment]
Keynotes escolhidos, vou começar a enviar os convites amanhã
