### ISSUE TITLE
Criar formulário para participar da lista de e-mail

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#82]
### Descrição
Como mencionado na reunião  #49, criar formulário simples para inserção de pessoas na lista de e-mail.

### Requisitos para a atividade ser considerada como concluída

*Por exemplo: "- Plano de patrocínio em PDF salvo no Drive da organização."*

- Formulário criado
- Formulário divulgado. Obs: a ideia inicial era colocar o link no site.

**Comment by cecivieira** [comment]
Que lista de e-mail? Para que tema?
Poderia descrever melhor? @alynnefs

**Comment by alynnefs** [comment]
Eu não lembro quem levantou esse ponto na reunião, mas o formulário era para adicionar pessoas interessadas na lista de e-mail. Acredito que tem uma lista nacional. Estava junto com a landing page (está como atividade na reunião #49 ), mas acho que isso não tem muito a ver com o evento em si.

**Comment by cecivieira** [comment]
Talvez faça sentido ter um campo de assinatura de newsletter do evento, mas vamos ter isso?
Acho que seria interessante esperar o GT de comunicação se estruturar

**Comment by alynnefs** [comment]
Acho que vale retomar a discussão mais pra frente mesmo. Não coloquei a issue no projeto PyBR 2021 por não saber no momento se a tarefa é nossa enquanto organização.

**Comment by rougeth** [comment]
@alynnefs foi mal, adicionei no projeto sem ler a issue. Mas acho que não tem problema deixar, pode ficar confuso ter issues que estão e que não estão no projeto.

**Comment by rougeth** [comment]
Lembrei do contexto: a ideia era coletar e-mails na landing page para usarmos na divulgação do evento quando o site ficar pronto. @cecivieira @deboraazevedo me parece interessante para o plano de comunicação, faz sentido?

**Comment by cecivieira** [comment]
@rougeth faz sentido sim.
Abri a issue #97 pra dá uma olhada em umas ferramentas e usá-las para coletar os e-mails. O que tu acha disso?

**Comment by cecivieira** [comment]
Issue duplicada. Ver #97
