### ISSUE TITLE
Estruturar programa de voluntariado

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#83]
### Descrição
Estruturar programa de voluntariado para evento. 

### Requisitos para a atividade ser considerada como concluída

- Estabelecer grupos de voluntariado;
- Estabelecer responsáveis por cada grupo

**Comment by cecivieira** [comment]
Sugestão de organização de voluntariado:

    

- Identificar grupos (ex.: Anfitriã, Infraestrutura, CDC, Arte e Comunicação)
- Definir escopo dos grupos:
    -  Anfitriã - Dar suporte em vídeo a palestrante durante a live: no início apresentar a palestrante e palestra, durante a palestra selecionar perguntas a serem feitas, no final realizar as perguntas.
    - Infraestrutura - Dar suporte no backstage da live: fazer transição de telas, colocar e retirar participantes da live, fazer teste de infraestrutura com palestrantes e anfitriãs. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
   - CDC - Monitorar interação entre participantes do evento na plataforma Discord e assistir palestras. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
    - Arte - Desenvolver artes para evento usando o manual de identidade visual estabelecido.
    - Comunicação - Desenvolver textos para postagem em redes sociais e canais de divulgação previamente mapeados. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
- Definir responsáveis por cada grupo;
- Definir canal de comunicação (sugestão Discord);
- Criar formulário para inscrição de voluntáriado com data para abertura e fechamento;
- Preparar treinamento para grupos, quando adequado;
- Realizar primeira reunião com grupos para informar sobre canal de comunicação, apresentar escopo com mais detalhe, apresentar responsáveis e definir datas para treinamentos.
- Realizar treinamento.

**Comment by cecivieira** [comment]
Definidos os seguintes grupos durante a reunião #77 :

- **Live** (Responsável: A DEFINIR)
    - **Anfitriã** - Dar suporte em vídeo a palestrante durante a live: no início apresentar a palestrante e palestra, durante a palestra selecionar perguntas a serem feitas, no final realizar as perguntas. 
    - **Infraestrutura** - Dar suporte no backstage da live: fazer transição de telas, colocar e retirar participantes da live, fazer teste de infraestrutura com palestrantes e anfitriãs. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
- **CDC** (Responsável: A DEFINIR)
    Monitorar interação entre participantes do evento na plataforma Discord e assistir palestras. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
- Comunicação (Responsável: A DEFINIR)
   Desenvolver textos para postagem em redes sociais e canais de divulgação previamente mapeados. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.

**Comment by alynnefs** [comment]
Disponibilidade dos voluntários: duas semanas antes e a semana do evento. Com exceção do time de comunicação, que entrará assim que possível.

**Comment by deboraazevedo** [comment]
eu fico como responsável pela comunicação :)

**Comment by cecivieira** [comment]
Pensando na trilha em espanhol, penso que podemos criar um grupo de voluntários nesse idioma com organizadoras das comunidades (Grupy, Pyladies etc) para ajudar na capilarização do evento nesses grupos, atrair propostas de palestras, anfitriãs para elas e ajudar na tradução de tudo.

Posso ficar a frente disso.

**Comment by cecivieira** [comment]
Resumo dos grupos:

- **Live** (Responsável: A DEFINIR)
    - **Anfitriã** - Dar suporte em vídeo a palestrante durante a live: no início apresentar a palestrante e palestra, durante a palestra selecionar perguntas a serem feitas, no final realizar as perguntas.
    - **Infraestrutura** - Dar suporte no backstage da live: fazer transição de telas, colocar e retirar participantes da live, fazer teste de infraestrutura com palestrantes e anfitriãs. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
- **CDC** (Responsável: A DEFINIR)
    Monitorar interação entre participantes do evento na plataforma Discord e assistir palestras. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
- **Comunicação** (Responsável: @deboraazevedo )
    Desenvolver textos para postagem em redes sociais e canais de divulgação previamente mapeados. Ter disponibilidade de 1 turno (manhã, tarde ou noite) durante o evento.
- **América Latina** (Responsável: @cecivieira )
    Disseminar evento em países latinoamericanos: tradução de conteúdo para espanhol, divulgação da PyBR nos eventos e comunidades locais, incentivar pessoas a submeter palestras. Além disso, ser anfitriã das palestras

**Comment by alynnefs** [comment]
Vou assumir a parte de CDC

**Comment by alynnefs** [comment]
Como o CDC vai ser um grupo diferente da organização, @julianyraiol assumiu o CDC.

Vou fechar a issue porque o voluntariado já está encaminhado (:
