### ISSUE TITLE
Criar templates de artes para mensagens nas redes sociais

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#84]
### Descrição
Para facilitar e permitir a divisão de tarefas do time de comunicação e artes, devemos criar templates de artes para mensagens nas redes sociais.

### Requisitos para a atividade ser considerada como concluída

- Verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/).
- Templates criados
- Templates separados por temas. Exemplo: divulgação de chamada de atividades, divulgação de palestrantes, etc

**Comment by cecivieira** [comment]
Aguardando cronograma do GT de Comunicação

**Comment by rougeth** [comment]
@cecivieira issue do cronograma é #93?

**Comment by cecivieira** [comment]
Sim @rougeth 
Vou fechar essa issue porque fica a cargo de @cmdiasbr @martinsvanessa como vão criar as artes. 
Após a finalização do cronograma da #93 , criaremos issues para cada arte (ou tipo de arte).
