### ISSUE TITLE
Criar pesquisa nas redes sociais para definir forma de cobrança (doação ou direta)

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#85]
### Descrição
Para definir se iremos cobrar ou não ingressos com o intuito de doar o dinheiro para alguma(s) instituição(ões), como mencionado na issue #69, precisamos criar uma pesquisa para ver o que é mais viável:
- cobrar por padrão e ter a opção de isenção ou
- criar diferentes opções de ingressos, com a opção gratuita e com diferentes valores para doação.

Possível problema: se as pesquisas forem separadas, pode ser que uma opção vença no instagram e outra no twitter. Sugestão: criar um formulário simples ou considerar valores absolutos, somando os resultados das duas redes sociais.

### Requisitos para a atividade ser considerada como concluída

- Pesquisa feita e divulgada
- Divulgar o resultado

**Comment by cecivieira** [comment]
@anadulce 

Sugestão para fazer pesquisa:

Sequência de stories no Instagram e twitter:

1 - A PyBR2021 deseja apoiar financeiramente instituições com trabalhos sociais. Por isso, queremos sua opinião sobre como deve ser realizada essa arrecadação (setinha pro lado com a palavra "enquete");

2 - Você estaria disposta a pagar um ingresso entre R$1 e R$5 para participar do evento? (Opções de resposta: Sim, Não)

3 - Caso o ingresso seja gratuito, você estaria disposta a fazer uma contribuição voluntária (R$)? (Opções de resposta: Sim, Não)

**Comment by cecivieira** [comment]
@rougeth com essas perguntas tu acha que coleta as informações necessária? (pensando no que tu imaginou quando deu a ideia na reunião)

**Comment by cecivieira** [comment]
@cmdiasbr @martinsvanessa 

Vocês poderiam colocar 1 bonequinha e a logo do evento lá no Canva, por favor?
Tamos precisando fazer a arte da pesquisa.

**Comment by anadulce** [comment]
https://www.canva.com/design/DAEir_bihFM/share/preview?token=pLKa9MMMkuxPjS-regHArQ&role=EDITOR&utm_content=DAEir_bihFM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by cecivieira** [comment]
@anadulce 
Passei a arte no https://www.toptal.com/designers/colorfilter/, plataforma sugerida na issue #58
Achei de boa.

Bora lançar!!!

Sequência de stories no Instagram, twitter e Telegram (existe grupo python brasil?):

1 - A PyBR2021 deseja apoiar financeiramente instituições com trabalhos sociais. Por isso, queremos sua opinião sobre como deve ser realizada essa arrecadação (setinha pro lado com a palavra "enquete");

2 - Você se sentiria confortável em pagar um ingresso entre R$1 e R$5 para participar do evento? (Opções de resposta: Sim, Não) [modificação realizada conforme sugestão de @anadulce ]

3 - Caso o ingresso seja gratuito, você estaria disposta a fazer uma contribuição voluntária (R$)? (Opções de resposta: Sim, Não)

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/123813999-b87b9680-d8cb-11eb-97e4-c940f23602e4.png)
![image](https://user-images.githubusercontent.com/30605862/123814021-bca7b400-d8cb-11eb-9d88-b70a8bbcb378.png)

**Comment by cecivieira** [comment]
Enquete realizada no twitter (3 dias) e instagram (1 dia)
https://twitter.com/pythonbrasil/status/1410003920693383172

**Comment by cecivieira** [comment]
Resultado no Twitter

![image](https://user-images.githubusercontent.com/30605862/124368228-7e94f200-dc35-11eb-96a9-62003de5db7b.png)
