### ISSUE TITLE
Automatizar criação das artes com fotos dos palestrantes

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#86]
### Descrição
Com a finalidade de ganhar tempo e evitar trabalho manual, devemos automatizar a criação de artes para divulgação de palestrantes usando o template definido

### Requisitos para a atividade ser considerada como concluída

*Por exemplo: "- Plano de patrocínio em PDF salvo no Drive da organização."*

- Verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/).
- Script criado

**Comment by cmdiasbr** [comment]
https://www.canva.com/design/DAEiwp_oRBM/share/preview?token=Vbbme5YA404cPCgNeOi_6g&role=EDITOR&utm_content=DAEiwp_oRBM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by rougeth** [comment]
@GabrielRF essa é outra issue que talvez a gente consiga resolver de forma parecida com a geração dos certificados

**Comment by GabrielRF** [comment]
> 
> 
> @GabrielRF essa é outra issue que talvez a gente consiga resolver de forma parecida com a geração dos certificados

Sim, faz sentido.

**Comment by JacksonOsvaldo** [comment]
Pessoal, precisamos desenvolver algo Web ou podemos utilizar algo local? Minha ideia seria trabalhar com o SVG do template e utilizar, adaptando/refatorando algumas coisas, essa solução aqui: https://github.com/davidhdz/generador-de-certificados. Esse script foi feito pra gerar certificados utilizando SVG. Só que podemos trabalhar com ele no nosso caso em questão. O que acham?

**Comment by JacksonOsvaldo** [comment]
Ah, gente, @deboraazevedo @cecivieira, teria como jogar o SVG aqui?

**Comment by paulohenriquedsgn** [comment]
@JacksonOsvaldo você já deu uma olhada no link que a Camila deixou? Vou deixar aqui e me diz se isso é suficiente

https://www.canva.com/design/DAEiwp_oRBM/share/preview?token=Vbbme5YA404cPCgNeOi_6g&role=EDITOR&utm_content=DAEiwp_oRBM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by GabrielRF** [comment]
#182

**Comment by GabrielRF** [comment]
https://github.com/GabrielRF/pybr2021-Arte-Palestrantes/

**Comment by alynnefs** [comment]
Vou fechar a issue. Se precisar de algum ajuste a gente reabre.
