### ISSUE TITLE
Pensar em logística para isenção de inscrição

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#87]
### Descrição
Caso o resultado da pesquisa #85 seja favorável à cobrança com opção de isenção, devemos decidir como se dará a cobrança dos ingressos.

### Requisitos para a atividade ser considerada como concluída

- Definir possíveis ferramentas utilizadas

**Comment by rougeth** [comment]
Acredito que bloqueada por #85, confirma @cecivieira?

**Comment by cecivieira** [comment]
Sim @rougeth 
Ela está bloqueada, aguardando dados da pesquisa #85

**Comment by cecivieira** [comment]
Conforme decidido na reuniao #99 , a arrecadação será feita por meio de doação
