### ISSUE TITLE
Atualizar Discord

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#88]
### Descrição
Atualizar Discord para iniciar utilização da organização.

### Requisitos para a atividade ser considerada como concluída

- Atualizar logo do Discord;
- Criar espaço da PYBR21-ORGANIZAÇÃO;
- Rever acessos do servidor;
- Dar privilégio necessário à organização atual.

**Comment by rougeth** [comment]
Precisamos definir se o evento será fechado ou não. Se for fechado, precisaremos criar um novo servidor no Discord.

Bloqueada por https://github.com/pythonbrasil/pybr2021-org/issues/85.

**Comment by cecivieira** [comment]
Além disso, precisaríamos pensar no que fazer com o arquivo do evento passado, como @gabubellon bem lembrou.

Acredito que assim como o site, poderíamos criar um outro servidor de Discord. Sugiro que o antigo seja bloqueado para novas instegrantese postagens, deixando apenas com permissão para publicação as pessoas que ficarão com a Comunicação do evento desse ano. Como lá tem muita gente, vai ser um canal interessante para divulgação.

**Comment by rougeth** [comment]
- Discord da Python Brasil 2020 em modo leitura, com exceção da @cecivieira e @deboraazevedo.
- Discord da Python Brasil 2021 criado e divulgado no grupo.
