### ISSUE TITLE
Plano de Patrocínio

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#9]
### Descrição
Elaborar plano de patrocínio para que possamos enviar às empresas interessadas.

### Requisitos para a atividade ser considerada como concluída

- Plano em português feito
- Plano em inglês feito

**Comment by rougeth** [comment]
Dados da Python Brasil 2020
- https://github.com/pythonbrasil/dados/blob/main/dados/python-brasil-2020/
- https://pybr2020opendata.herokuapp.com/

**Comment by alynnefs** [comment]
slide em português: https://drive.google.com/file/d/1xh54DHHs5ZxzLFUJS5EQXkh9Nijmirgb/view?usp=sharing

**Comment by alynnefs** [comment]
A versão final do plano pode ser encontrada no link postado anteriormente

**Comment by cecivieira** [comment]
Plano de patrocínio pt-br : https://2021.pythonbrasil.org.br/plano-patrocinio.pdf
