### ISSUE TITLE
Criar cronograma de principais atividades para orientar a organização

### ISSUE THREAD

**Issue by anadulce** [pythonbrasil/pybr2021-org#91]
Criar um cronograma para as atividades organizacionais da Python Brasil (abrir inscrições, submissão de atividades, etc).
Precisamos controlar melhor nosso tempo até o evento.

### Requisitos para a atividade ser considerada como concluída

Uma planilha onde estarão elencadas nossas principais atividades e qual nosso tempo limite para cumpri-las.

**Comment by cecivieira** [comment]
Acho que pode ser um novo projeto no Github, como o que temos atualmente. No entanto, apenas com atividades principais.
Acho que fica mais fácil a visualização e acompanhamento por todas.

**Comment by rougeth** [comment]
Outra opção é criar um label para essas atividades macro, como `macro`, `meta` ou `epic` (puxando pro scrum).

**Comment by cecivieira** [comment]
Gosto mais da ideia de Rougeth. Dá para utilizar filtro na visualização do projeto atual.

**Comment by rougeth** [comment]
Discutimos no Telegram sobre usar as milestones do Github. Referência: https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones.
