### ISSUE TITLE
Atualizar redirecionamento do site https://pythonbrasil.org.br/

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#92]
### Descrição
Redirecionar https://pythonbrasil.org.br/ para https://2021.pythonbrasil.org.br.
O redirecionamento existente aponta para o evento de 2019.

### Requisitos para a atividade ser considerada como concluída

- Site https://pythonbrasil.org.br/ apontar para https://2021.pythonbrasil.org.br.

**Comment by rougeth** [comment]
Eu tinha atualizado mais cedo (https://github.com/pythonbrasil/pythonbrasil.org.br/commit/190634487337ffd3b49cb20a3300bad16fe2eadd), mas não tinha conferido. Precisei corrigir um registro no DNS, agora ta certinho.
