### ISSUE TITLE
Planejar Comunicação do evento

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#93]
### Descrição
Planejamento estratégico da comunicação do evento. Pensar público-alvo desejado, estabelecer canais de divulgação e campanhas (chamada palestrantes, inscrições, palestras, keynotes, etc...). Após esse planejamento deve-se desenvolver um cronograma das campanhas.

### Requisitos para a atividade ser considerada como concluída
- Estabelecer público alvo;
- Estabelecer canais de divulgação;
- Definir campanhas;
- Criar cronograma para cada campanha com as publicações.

**Comment by cecivieira** [comment]
Cronograma de das campanhas com as publicações:
https://drive.google.com/file/d/189yl3QEeWEMs7qtKZah6SVQLO--Edsrg/view?usp=sharing

**Comment by cecivieira** [comment]
**Estabelecer público alvo;**
Integrantes das comunidades Python Brasil;
Integrantes das comunidades Python América Latina;
Profissionais da área de TI não envolvidos com comunidades;
Academia (principalmente, cursos não STEAM)

**Estabelecer canais de divulgação;**
Redes sociais (twitter, facebook e instagram);
E-mail;
Discord PyBr2020;
Grupos do Telegram;
Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

**Definir campanhas;**
Lançamento do evento (siga nas redes sociais)
Programa de voluntariado
Chamada para atividades
Inscrições para evento
Contagem regressiva para evento
Divulgação das atividades (sprint, palestras, tutoriais e keynotes)
Divulgação de patrocínio
Divulgar a doação a ONG beneficiária


**Criar cronograma para cada campanha com as publicações.**
https://drive.google.com/file/d/189yl3QEeWEMs7qtKZah6SVQLO--Edsrg/view?usp=sharing

**Comment by apast** [comment]
Slides para apresentação non-STEAM & STEAM

https://docs.google.com/presentation/d/14fGg356VprKfU-ZRGN_FXyXn_H1ZpD2Q/edit#slide=id.p1

Será legal adicionar mais informações e convite às pessoas de todas as áreas, citar áreas que já participaram e apresentaram
...
