### ISSUE TITLE
Arte para cabeçado do Formulários

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#95]
### Descrição
Criar arte para cabeçalho dos formulários de voluntariado e facilitadoras. Penso que podem ser iguais e só mudar o background.

### Requisitos para a atividade ser considerada como concluída
- Arte para formulário do programa de voluntariado;
- Arte para formulário de submissão de atividades #14

**Comment by cmdiasbr** [comment]
![google-docs](https://user-images.githubusercontent.com/45003095/123705991-0d70cb80-d83e-11eb-8232-56dbad92fe80.png)

**Comment by cmdiasbr** [comment]
![google-docs2](https://user-images.githubusercontent.com/45003095/123706080-33966b80-d83e-11eb-8095-a4f91b30e068.png)

**Comment by cmdiasbr** [comment]
![google-docs](https://user-images.githubusercontent.com/45003095/123778346-6294f780-d8a7-11eb-9044-ed6f2ce947ba.png)
![google-docs2](https://user-images.githubusercontent.com/45003095/123778357-64f75180-d8a7-11eb-971c-2b76af6aa3d0.png)

**Comment by cecivieira** [comment]
@cmdiasbr Ficou massa!!!
tu poderia trocar o background de um dos cabeçalhos? É só pra ter uma diferenciação a mais do que só o título

**Comment by cecivieira** [comment]
Se essa arte tiver no Canva ou Figma, posso ajuda com ela

**Comment by cmdiasbr** [comment]
![google-docs](https://user-images.githubusercontent.com/45003095/123802136-51f17b00-d8c1-11eb-90b6-72e65f4deb36.png)
![google-docs2](https://user-images.githubusercontent.com/45003095/123802141-5322a800-d8c1-11eb-9fdd-14c10f329a93.png)

**Comment by cecivieira** [comment]
Ficaram perfeitooossss!!!!
Obrigada!!!! @cmdiasbr

**Comment by martinsvanessa** [comment]
Valeu @cmdiasbr! :D
