### ISSUE TITLE
Titular trilhas

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#96]
### Descrição
Decidir sobre título a ser usado em cada trilha e caracterizá-la (que tipo de palestra ou tema será tratado nela?)

### Requisitos para a atividade ser considerada como concluída

- Definir título para as 5 trilhas
- Caracterizar as 5 trilhas

**Comment by alynnefs** [comment]
Sugestões:

- Dona Tota (Dona Tota e o menino mágico, brasileiro)
- Luminaris (situado em Buenos Aires)
- Pingu
- Ginger (A fuga das galinhas)
- Wallace
- Gromit

São personagens, filmes ou curtas-metragens no estilo stop motion, mas não sei se dá problema de direitos autorais

**Comment by alynnefs** [comment]
Independente dos nomes, as 5 trilhas são:

- Iniciante
- Intermediária
- Avançada
- Não técnica
- Estrangeira (espanhol)

**Comment by deboraazevedo** [comment]
Queremos dar nomes temáticos para  as trilhas? Mesmo que isso acabe não fazendo muita diferença na hroa de caracterizar cada uma delas, pode ser algo a pensar.

**Comment by anadulce** [comment]
Eu acho que se for para ter nome temático, deveria ser temático em relação à Python Brasil, não à identidade visual.
Gostei demais dos nomes do ano passado porque eles trouxeram atenção para algo relativo à linguagem (dava oportunidade para explicarmos o que é uma PEP, e isso foi bem legal), porém zero criatividade pra fazer algo semelhante :)

**Comment by jsbueno** [comment]
sobre nomes temáticos, já foram feitas edições homenageando Pythonistas e figuras da T.I. mundiais também - (na verdade, foram nomes de sala - mas no online "nome de sala" e "nome de trilha" tem mais ou menos o mesmo significado) - "Guido" , "Dorneles", "Jean", por exemplo. Nada impede reusar os nomes do ano passado também. 

Vou aproveitar que vim aqui e falar um pouco da estratégia de trilhas que usamos na edição de 2013: em vez de "intermediária ...avançada", foi uma preocupação com a diversidade de coisas que podem ser feitas em Python - naquele momento, a linguagem era mais focada em backend com django/etc"django", "frameworks web", "desktop", "python core", "multimidia", "data science / big data"" - com um mínimo de palestras por trilha.
 - hoje acho que o uso da linguagem está mais diverso que "naquela época" e não vejo tanta necessidade disso - mencionei mais por curiosidade mesmo.

**Comment by alynnefs** [comment]
Não precisa ser ligado ao tema mesmo, eu só sugeri porque achei as pessoas bem perdidas nas PEPs. Acho que colocar nomes relacionados à linguagem ou nome de personalidades são ideias boas também.

Gosto de separar por tecnologia, mas realmente "agora" tá mais diverso, não dá pra garantir que a gente vai ter o mínimo por trilha :/

**Comment by alynnefs** [comment]
Ideia que surgiu durante a Python Nordeste: titular as trilhas com nome de mulheres importantes para a computação que não são muito conhecidas

**Comment by cecivieira** [comment]
@alynnefs está decidio que as trilhas serão tituladas com nomes de mulheres importantes para a computação que não são muito conhecidas ?

Se sim, você precisa que as pessoas dê sugestões ou já 5 mulheres em mente?

**Comment by alynnefs** [comment]
@cecivieira, foi só uma sugestão mesmo, a gente não decidiu nada ainda

**Comment by cecivieira** [comment]
@alynnefs sugestão de big kahuna tem prioridade. XD
Você quer que as trilhas tenham nomes de mulheres? Essa era a pergunta original.

**Comment by cecivieira** [comment]
Foi decido que as trilhas serão tituladas com nomes de mulheres importantes para a computação que não são muito conhecidas.
@alynnefs apresentará nomes ou sugestões na reunião #212 para finalizar essa atividade.

**Comment by anadulce** [comment]
Acho que as trilhas precisam ter nomes um pouquinho intuitivos. Se as pessoas ficaram perdidas nas PEPs que tinham algum sentido, pode ser ainda mais caótico.

**Comment by cecivieira** [comment]
Ficou decidido na reunião #212 que as trilhas serão tituladas com nome de mulheres.
Aguardando escolha de @alynnefs

**Comment by tiidadavena** [comment]
Modelo de uso de nomes de trilhas com nomes de mulheres notáveis na tecnologia - Programaria Summit 2021:
https://www.programaria.org/programariasummit2021/brilha/

**Comment by alynnefs** [comment]
Com asterisco são os que tô pensando, mas podem sugerir mais também

Ada Locelace
Dorothy Vaughan*: estrelas além do tempo
Mary Jackson: engenheira
Margareth Hamilton
Grace Hopper
Marissa Mayer
Katherine Johnson*: responsável pelos cálculoes para que o astronauta John Glenn fosse colocado em órbita
Irmã Mary Kenneth Keller: primeira muher a ter um doutorado em computação nos EUA
Radia Periman: desenvolvedora do protocolo STP
Hedy Lamarr: inventou o salto de frequência
Angelica Ross*: mulher trans que deu início à missão de deixar o mercado de tecnologia mais inclusivo (TransTech Social Enterprises)
Marie Van Brittan Brown*: inventou um sistema de segurança doméstica por vídeo
Shirley Ann Jackson*: primeira mulher negra a receber um título de doutorado do MIT

**Comment by gabubellon** [comment]
Cassie Kozyrkov

**Comment by cecivieira** [comment]
- Shirley Ann Jackson: palestras de nível iniciante
- Marie Van Brittan Brown: palestras de nível intermediário
- Timnit Gebru: palestras de nível avançado
- Angelica Ross: palestras de nível não-técnico
- Bonnie Prado Pinto: palestras em espanhol
