### ISSUE TITLE
Avaliar e escolher ferramente de mailmarketing

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#97]
### Descrição
Avaliar ferramentas gratuitas, preferencialmente open source, para ser usada para divulgação de mailmarketing para inscritas no site. 

### Requisitos para a atividade ser considerada como concluída

- Avaliar ferramentas
- Escolher a que será usada

**Comment by cecivieira** [comment]
Sugestões:
https://mailchimp.com/
https://moosend.com/

**Comment by cecivieira** [comment]
Qual a nossa expectativa de inscrições nessa newsleatter?

**Mail Chimp:**
![image](https://user-images.githubusercontent.com/30605862/123882317-ed640980-d91c-11eb-87c5-9ea24538c542.png)

**Moosend:**
![image](https://user-images.githubusercontent.com/30605862/123882685-b0e4dd80-d91d-11eb-935e-388efe12afcc.png)

**Comment by rougeth** [comment]
Acho que plano free deve ser suficiente.

**Comment by deboraazevedo** [comment]
tem que ver isso do plano free ser suficiente no sentido de: ontem conversei com @cecivieira sobre colocarmos no form de inscrição um checkbox pra pessoa indicar se gostaria de receber informações sobre a conferencia numa newsletter.. se tiveremos um número parecido de inscrições como no ano passado (e queremos superar isso), 2k parece um número facilmente atingivel de pessoas inscritas na newsletter, o que traria a necessidade de assinar um plano.. outra coisa é a frequência da newsletter, pq no plano básico só poderiamos enviar 5 e-mails (pelo que entendi pls send help)

**Comment by cecivieira** [comment]
@deboraazevedo talvez 2k seja suficente, pensando que as pessoas não gostam de spam na caixa de e-mail. O limite é de 5 e-mails/mês. Tem mais detalhes aqui: https://mailchimp.com/help/about-mailchimp-pricing-plans/

![image](https://user-images.githubusercontent.com/30605862/123958461-79108100-d983-11eb-834b-06e576eeaa8a.png)

**Comment by deboraazevedo** [comment]
ahh, são 5 e-mails por mes :) tudo ótimo então, obrigada

**Comment by cecivieira** [comment]
A ferramenta escolhida foi Mail Chimp. Conforme acordado com @gtsalles , foi criada conta usando o e-mail eventos@python.org.br e compartilhada as credenciais com ele.
