### ISSUE TITLE
Criar planilha comparativa entre sympla e eventbrite

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#98]
### Descrição
Comparar as possibilidades das ferramentas, como:
- geração de certificado;
- geração de cupom de desconto, etc

### Requisitos para a atividade ser considerada como concluída

- Planilha criada

**Comment by tiidadavena** [comment]
Criei uma planilha comparando a Sympla e a Even3, faltando apenas a Doity no benchmarking:
[](https://docs.google.com/spreadsheets/d/1EbkeHAdMe8hjRZoAJDlrZ_4Q1VK3YMGAE8MMoR9nQIQ/edit?usp=sharing)

**Comment by alynnefs** [comment]
@tiidadavena, não tá aparecendo nenhuma planilha ou link :(

**Comment by tiidadavena** [comment]
Opa, veja se agora foi: https://docs.google.com/spreadsheets/d/1EbkeHAdMe8hjRZoAJDlrZ_4Q1VK3YMGAE8MMoR9nQIQ/edit?usp=sharing

**Comment by cecivieira** [comment]
Ficou decidido na reunião #141 que seria usada a plataforma Eventbrite
